-- P1: authoritative Need cancellation and Response withdrawal.
--
-- This migration also repairs two regressions exposed by the lifecycle guard:
-- internal deadline expiry and Agreement cancellation must set the lifecycle
-- token before changing needs.status. Finally, rpc_submit_response now stores
-- durable command results so a network retry cannot create a phantom version.

create table if not exists private.response_submit_commands (
  worker_account_id uuid not null,
  client_request_id text not null
    check (char_length(btrim(client_request_id)) between 8 and 200),
  request_hash text not null check (char_length(request_hash) = 64),
  response_id uuid not null,
  response_version integer not null check (response_version >= 1),
  result jsonb not null,
  created_at timestamptz not null default statement_timestamp(),
  primary key (worker_account_id, client_request_id),
  foreign key (response_id, response_version)
    references public.marketplace_response_versions(response_id, version)
    on delete cascade
);

alter table private.response_submit_commands enable row level security;
revoke all on table private.response_submit_commands from public, anon, authenticated;

comment on table private.response_submit_commands is
  'Durable idempotency ledger for rpc_submit_response. Same worker/key returns the exact first result; a different payload is rejected.';

create table if not exists private.response_withdraw_commands (
  worker_account_id uuid not null,
  client_request_id text not null
    check (char_length(btrim(client_request_id)) between 8 and 200),
  request_hash text not null check (char_length(request_hash) = 64),
  response_id uuid not null,
  response_version integer not null check (response_version >= 1),
  result jsonb not null,
  created_at timestamptz not null default statement_timestamp(),
  primary key (worker_account_id, client_request_id),
  foreign key (response_id, response_version)
    references public.marketplace_response_versions(response_id, version)
    on delete cascade
);

alter table private.response_withdraw_commands enable row level security;
revoke all on table private.response_withdraw_commands from public, anon, authenticated;

comment on table private.response_withdraw_commands is
  'Durable semantic-command receipt for owner-locked Application withdrawal retries.';

-- Clean never received the donor's private marketplace audit owner. Preserve
-- the useful capability without importing donor naming or public read paths.
-- Entity UUIDs intentionally have no foreign keys: lifecycle evidence must
-- survive a later account closure or the narrow deletion of an empty DRAFT.
create table if not exists private.marketplace_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid,
  event_type text not null check (char_length(btrim(event_type)) between 1 and 100),
  entity_type text not null check (entity_type in ('NEED','RESPONSE','AGREEMENT','SYSTEM')),
  entity_id uuid,
  entity_version integer check (entity_version is null or entity_version >= 1),
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default statement_timestamp()
);

create index if not exists marketplace_audit_entity_idx
  on private.marketplace_audit_log (entity_type, entity_id, created_at desc);
create index if not exists marketplace_audit_actor_idx
  on private.marketplace_audit_log (actor_user_id, created_at desc)
  where actor_user_id is not null;

alter table private.marketplace_audit_log enable row level security;
revoke all on table private.marketplace_audit_log from public, anon, authenticated;
revoke all on sequence private.marketplace_audit_log_id_seq from public, anon, authenticated;

create or replace function private.audit_marketplace(
  p_actor uuid,
  p_event_type text,
  p_entity_type text,
  p_entity_id uuid,
  p_entity_version integer default null,
  p_detail jsonb default '{}'::jsonb
) returns void language sql security definer set search_path to 'pg_catalog' as $$
  insert into private.marketplace_audit_log (
    actor_user_id, event_type, entity_type, entity_id, entity_version, detail
  ) values (
    p_actor, p_event_type, p_entity_type, p_entity_id, p_entity_version,
    coalesce(p_detail, '{}'::jsonb)
  );
$$;

revoke all on function private.audit_marketplace(uuid,text,text,uuid,integer,jsonb)
  from public, anon, authenticated;

comment on table private.marketplace_audit_log is
  'Private authoritative marketplace mutation evidence. No client role has table access; entity references deliberately survive entity deletion.';

create or replace function public.rpc_submit_response(
  p_need_id uuid,
  p_need_revision integer,
  p_worker_profile_id uuid,
  p_covered_slots integer,
  p_price_rsd integer,
  p_proposed_start_at timestamptz,
  p_proposed_end_at timestamptz,
  p_scope_note text,
  p_client_request_id text
) returns jsonb language plpgsql security definer set search_path to 'pg_catalog' as $$
declare
  u uuid := auth.uid();
  n public.needs;
  v_resp public.marketplace_responses;
  v_command private.response_submit_commands;
  v_match jsonb;
  v_content_hash text;
  v_request_hash text;
  v_result jsonb;
  v_version integer;
begin
  if u is null then raise exception using errcode='42501', message='AUTH_REQUIRED'; end if;
  if p_client_request_id is null
     or char_length(btrim(p_client_request_id)) not between 8 and 200 then
    raise exception using errcode='22023', message='INVALID_CLIENT_REQUEST_ID';
  end if;

  -- The command key is global per worker, not per Need. Serialize it before the
  -- first lookup so two concurrent retries aimed at different Needs cannot race
  -- into the unique constraint and surface a non-authoritative 23505.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(u::text || ':' || p_client_request_id, 7241)
  );

  v_request_hash := encode(sha256(convert_to(jsonb_build_object(
    'needId', p_need_id,
    'needRevision', p_need_revision,
    'workerProfileId', p_worker_profile_id,
    'coveredSlots', p_covered_slots,
    'priceRsd', p_price_rsd,
    'proposedStartAt', p_proposed_start_at,
    'proposedEndAt', p_proposed_end_at,
    'scopeNote', coalesce(p_scope_note, '')
  )::text, 'UTF8')), 'hex');

  -- Fast idempotent replay, including after the Need has closed or the deadline
  -- has passed. A retry replays the committed command; it is not a new command.
  select * into v_command
    from private.response_submit_commands c
   where c.worker_account_id = u
     and c.client_request_id = p_client_request_id;
  if found then
    if v_command.request_hash <> v_request_hash then
      raise exception using errcode='22023', message='IDEMPOTENCY_KEY_REUSED';
    end if;
    return v_command.result || jsonb_build_object('idempotentReplay', true);
  end if;

  if not exists (
    select 1 from public.app_profiles p
     where p.id = p_worker_profile_id
       and p.account_id = u
       and p.kind = 'WORKER'
  ) then
    raise exception using errcode='42501', message='PROFILE_NOT_OWNED_BY_ACCOUNT';
  end if;

  -- Shared lock order for submit/select/cancel/withdraw: Need first.
  select * into n from public.needs where id = p_need_id for update;
  if not found then raise exception using errcode='P0002', message='NEED_NOT_FOUND'; end if;

  -- A concurrent first execution may have committed while this call waited for
  -- the Need lock. Recheck the ledger before creating a version.
  select * into v_command
    from private.response_submit_commands c
   where c.worker_account_id = u
     and c.client_request_id = p_client_request_id
   for update;
  if found then
    if v_command.request_hash <> v_request_hash then
      raise exception using errcode='22023', message='IDEMPOTENCY_KEY_REUSED';
    end if;
    return v_command.result || jsonb_build_object('idempotentReplay', true);
  end if;

  if n.status not in ('PUBLISHED','SELECTION') then
    raise exception using errcode='22023', message='NEED_NOT_OPEN';
  end if;
  if n.requester_account_id = u then
    raise exception using errcode='42501', message='OWN_NEED';
  end if;
  if n.response_deadline is not null
     and n.response_deadline <= statement_timestamp() then
    raise exception using errcode='22023', message='RESPONSE_WINDOW_EXPIRED';
  end if;
  if n.revision is distinct from p_need_revision then
    raise exception using errcode='P0001', message='STALE_REVIEW_REQUIRED';
  end if;
  if p_covered_slots is null
     or p_covered_slots < 1
     or p_covered_slots > n.required_slots then
    raise exception using errcode='22023', message='INVALID_COVERED_SLOTS';
  end if;
  if p_price_rsd is null or p_price_rsd <= 0 then
    raise exception using errcode='22023', message='INVALID_PRICE';
  end if;

  if exists (
    select 1 from public.marketplace_responses r
     where r.need_id = p_need_id
       and r.worker_account_id = u
       and (
         r.status = 'SELECTED'
         or exists (
           select 1 from public.agreements a
            where a.selected_response_id = r.id
              and a.status in ('CONFIRMED','SUPERSEDED','COMPLETED')
         )
       )
  ) then
    raise exception using errcode='P0001', message='RESPONSE_ALREADY_SELECTED';
  end if;

  v_match := private.match_detail(p_need_id, p_worker_profile_id);
  if not coalesce((v_match->>'responseAllowed')::boolean, false) then
    raise exception using errcode='P0001', message='WORKER_NOT_ELIGIBLE',
      detail = coalesce((v_match->'hardBlockers')::text, '[]');
  end if;

  select * into v_resp
    from public.marketplace_responses r
   where r.need_id = p_need_id
     and r.worker_account_id = u
     and r.status in ('DRAFT','SUBMITTED','DELIVERED','VIEWED','SHORTLISTED')
   order by r.created_at desc
   limit 1
   for update;

  v_content_hash := encode(sha256(convert_to(
    p_price_rsd::text || '|' || p_covered_slots::text || '|' ||
    coalesce(p_proposed_start_at::text, '') || '|' ||
    coalesce(p_proposed_end_at::text, '') || '|' ||
    coalesce(btrim(p_scope_note), '') || '|' || n.revision::text,
    'UTF8')), 'hex');

  if v_resp.id is null then
    insert into public.marketplace_responses (
      need_id, worker_account_id, worker_profile_id, response_kind, status,
      submitted_against_need_revision, current_version, covered_slots,
      price_rsd, proposed_start_at, proposed_end_at, scope_note, submitted_at
    ) values (
      p_need_id, u, p_worker_profile_id, 'OFFER', 'SUBMITTED', n.revision, 1,
      p_covered_slots, p_price_rsd, p_proposed_start_at, p_proposed_end_at,
      coalesce(p_scope_note, ''), statement_timestamp()
    ) returning * into v_resp;
    v_version := 1;
  else
    v_version := v_resp.current_version + 1;
    update public.marketplace_responses
       set current_version = v_version,
           status = 'SUBMITTED',
           submitted_against_need_revision = n.revision,
           covered_slots = p_covered_slots,
           price_rsd = p_price_rsd,
           proposed_start_at = p_proposed_start_at,
           proposed_end_at = p_proposed_end_at,
           scope_note = coalesce(p_scope_note, ''),
           submitted_at = statement_timestamp(),
           withdrawn_at = null
     where id = v_resp.id
     returning * into v_resp;
  end if;

  insert into public.marketplace_response_versions (
    response_id, version, need_revision, covered_slots, price_rsd,
    proposed_start_at, proposed_end_at, scope_note, content_hash
  ) values (
    v_resp.id, v_version, n.revision, p_covered_slots, p_price_rsd,
    p_proposed_start_at, p_proposed_end_at, coalesce(p_scope_note, ''),
    v_content_hash
  );

  update public.opportunity_deliveries
     set status = 'RESPONDED', responded_at = statement_timestamp()
   where need_id = p_need_id
     and need_revision = n.revision
     and worker_account_id = u
     and status in ('READY','SEEN');

  v_result := jsonb_build_object(
    'responseId', v_resp.id,
    'version', v_version,
    'needRevision', n.revision,
    'contentHash', v_content_hash,
    'status', v_resp.status,
    'authoritative', true,
    'idempotentReplay', false
  );

  insert into private.response_submit_commands (
    worker_account_id, client_request_id, request_hash,
    response_id, response_version, result
  ) values (
    u, p_client_request_id, v_request_hash,
    v_resp.id, v_version, v_result
  );

  return v_result;
end;
$$;

revoke all on function public.rpc_submit_response(
  uuid,integer,uuid,integer,integer,timestamptz,timestamptz,text,text
) from public, anon, authenticated;
grant execute on function public.rpc_submit_response(
  uuid,integer,uuid,integer,integer,timestamptz,timestamptz,text,text
) to authenticated;

comment on function public.rpc_submit_response(
  uuid,integer,uuid,integer,integer,timestamptz,timestamptz,text,text
) is 'Atomic and durably idempotent Response + ResponseVersion submission. Need is locked first and the same worker/clientRequestId can never create a second version.';

create or replace function public.rpc_cancel_need(
  p_need_id uuid,
  p_need_revision integer,
  p_reason text default ''
) returns jsonb language plpgsql security definer set search_path to 'pg_catalog' as $$
declare
  u uuid := auth.uid();
  n public.needs;
  affected_responses integer := 0;
  w record;
begin
  if u is null then raise exception using errcode='42501', message='AUTH_REQUIRED'; end if;

  -- Same lock as selection, dispatch and submission. Whichever transaction owns
  -- this row determines the canonical outcome of a race.
  select * into n from public.needs where id = p_need_id for update;
  if not found then raise exception using errcode='P0002', message='NEED_NOT_FOUND'; end if;
  if n.requester_account_id <> u then
    raise exception using errcode='42501', message='FORBIDDEN';
  end if;

  if n.status = 'CANCELLED' then
    return jsonb_build_object(
      'needId', n.id,
      'status', n.status,
      'revision', n.revision,
      'affectedResponses', 0,
      'idempotentReplay', true,
      'authoritative', true
    );
  end if;

  if n.revision is distinct from p_need_revision then
    raise exception using errcode='P0001', message='STALE_REVIEW_REQUIRED';
  end if;

  -- Once a seat is selected, cancellation belongs to the Agreement lifecycle.
  -- Historical CANCELLED Agreements do not keep the remaining Need hostage.
  if exists (
       select 1 from public.need_selections s
        where s.need_id = n.id and s.status = 'SELECTED'
     )
     or exists (
       select 1 from public.agreements a
        where a.need_id = n.id
          and a.status in ('CONFIRMED','SUPERSEDED','COMPLETED')
     )
     or exists (
       select 1 from public.marketplace_responses r
        where r.need_id = n.id and r.status = 'SELECTED'
     ) then
    raise exception using errcode='P0001',
      message='NEED_CANCELLATION_REQUIRES_AGREEMENT_FLOW';
  end if;

  if n.status not in ('DRAFT','PUBLISHED','SELECTION') then
    raise exception using errcode='22023', message='NEED_NOT_CANCELLABLE';
  end if;

  -- Stop every pending side effect before emitting the terminal event.
  update public.notification_deliveries d
     set state = 'EXPIRED'
    from public.user_activity_events e
   where d.event_id = e.id
     and d.state in ('CREATED','QUEUED','FAILED_RETRYABLE')
     and (
       (e.entity_type = 'NEED' and e.entity_id = n.id)
       or (e.entity_type = 'RESPONSE' and exists (
         select 1 from public.marketplace_responses r
          where r.id = e.entity_id and r.need_id = n.id
       ))
       or (e.entity_type = 'AGREEMENT' and exists (
         select 1 from public.agreements a
          where a.id = e.entity_id and a.need_id = n.id
       ))
     );

  update public.dispatch_rounds
     set status = 'STOPPED', stop_reason = 'NEED_CANCELLED'
   where need_id = n.id and status in ('PLANNED','SENT');

  update public.opportunity_deliveries
     set status = 'EXPIRED'
   where need_id = n.id and status in ('READY','SEEN');

  delete from private.dispatch_schedule where need_id = n.id;

  update public.access_grants g
     set status = 'REVOKED',
         revoked_at = coalesce(g.revoked_at, statement_timestamp())
   where g.status = 'GRANTED'
     and exists (
       select 1 from public.agreements a
        where a.id = g.agreement_id and a.need_id = n.id
     );

  perform set_config('uskoci.need_lifecycle', 'CANCEL_NEED', true);
  update public.needs
     set status = 'CANCELLED', urgent = false
   where id = n.id;

  -- Versions are never deleted or rewritten. Only the live Response outcome
  -- changes, and each affected worker receives an independently deduped event.
  for w in
    update public.marketplace_responses r
       set status = 'EXPIRED', selected_at = null
     where r.need_id = n.id
       and r.status in ('DRAFT','SUBMITTED','DELIVERED','VIEWED','SHORTLISTED','STALE')
     returning r.id, r.worker_account_id, r.current_version
  loop
    affected_responses := affected_responses + 1;
    perform private.emit_event(
      w.worker_account_id,
      'WORKER',
      'NEED_CANCELLED',
      'NEED',
      n.id,
      n.revision,
      'Potreba je otkazana',
      'Narucilac je otkazao Potrebu za koju ste poslali prijavu.',
      'need-cancelled:' || n.id::text || ':' || n.revision::text || ':worker:' || w.worker_account_id::text,
      'NORMAL',
      jsonb_build_object(
        'reason', 'REQUESTER_CANCELLED',
        'reasonProvided', char_length(btrim(coalesce(p_reason, ''))) > 0
      ),
      null
    );
  end loop;

  perform private.audit_marketplace(
    u,
    'NEED_CANCELLED',
    'NEED',
    n.id,
    n.revision,
    jsonb_build_object('reason', left(btrim(coalesce(p_reason, '')), 500))
  );

  return jsonb_build_object(
    'needId', n.id,
    'status', 'CANCELLED',
    'revision', n.revision,
    'affectedResponses', affected_responses,
    'idempotentReplay', false,
    'authoritative', true
  );
end;
$$;

revoke all on function public.rpc_cancel_need(uuid,integer,text)
  from public, anon, authenticated;
grant execute on function public.rpc_cancel_need(uuid,integer,text) to authenticated;

comment on function public.rpc_cancel_need(uuid,integer,text) is
  'Authoritative idempotent DRAFT/PUBLISHED/SELECTION cancellation. Need lock serializes selection/cron races; selected seats must use Agreement cancellation; versions and private history are preserved.';

-- Deleting an unpublished empty DRAFT and cancelling a lifecycle entity are
-- distinct product actions. Direct DELETE remains closed; this narrow path can
-- remove only a draft that has no marketplace/audit history and no storage
-- references. Sensitive draft-only construction data follows the Need FK.
create or replace function public.rpc_delete_draft_need(
  p_need_id uuid,
  p_need_revision integer,
  p_reason text default ''
) returns jsonb language plpgsql security definer set search_path to 'pg_catalog' as $$
declare
  u uuid := auth.uid();
  n public.needs;
begin
  if u is null then raise exception using errcode='42501', message='AUTH_REQUIRED'; end if;

  select * into n
    from public.needs x
   where x.id = p_need_id
   for update;

  if not found then
    if exists (
      select 1
        from private.marketplace_audit_log a
       where a.actor_user_id = u
         and a.event_type = 'NEED_DRAFT_DELETED'
         and a.entity_type = 'NEED'
         and a.entity_id = p_need_id
         and a.entity_version = p_need_revision
    ) then
      return jsonb_build_object(
        'needId', p_need_id,
        'revision', p_need_revision,
        'deleted', true,
        'idempotentReplay', true,
        'authoritative', true
      );
    end if;
    raise exception using errcode='P0002', message='NEED_NOT_FOUND';
  end if;

  if n.requester_account_id <> u then
    raise exception using errcode='42501', message='FORBIDDEN';
  end if;
  if n.revision is distinct from p_need_revision then
    raise exception using errcode='P0001', message='STALE_REVIEW_REQUIRED';
  end if;
  if n.status <> 'DRAFT' or n.published_at is not null then
    raise exception using errcode='22023', message='NEED_NOT_DELETABLE_DRAFT';
  end if;
  if cardinality(n.public_photo_paths) > 0 then
    raise exception using errcode='55000', message='DRAFT_MEDIA_CLEANUP_REQUIRED';
  end if;

  if exists (select 1 from public.marketplace_responses r where r.need_id = n.id)
     or exists (select 1 from public.need_selections s where s.need_id = n.id)
     or exists (select 1 from public.agreements a where a.need_id = n.id)
     or exists (select 1 from public.dispatch_rounds d where d.need_id = n.id)
     or exists (select 1 from public.opportunity_deliveries o where o.need_id = n.id)
     or exists (select 1 from private.dispatch_schedule q where q.need_id = n.id)
     or exists (
       select 1 from public.user_activity_events e
        where e.entity_type = 'NEED' and e.entity_id = n.id
     ) then
    raise exception using errcode='55000', message='DRAFT_HAS_AUTHORITATIVE_HISTORY';
  end if;

  delete from public.needs x where x.id = n.id;

  perform private.audit_marketplace(
    u,
    'NEED_DRAFT_DELETED',
    'NEED',
    n.id,
    n.revision,
    jsonb_build_object('reason', left(btrim(coalesce(p_reason, '')), 500))
  );

  return jsonb_build_object(
    'needId', n.id,
    'revision', n.revision,
    'deleted', true,
    'idempotentReplay', false,
    'authoritative', true
  );
end;
$$;

revoke all on function public.rpc_delete_draft_need(uuid,integer,text)
  from public, anon, authenticated;
grant execute on function public.rpc_delete_draft_need(uuid,integer,text)
  to authenticated;

comment on function public.rpc_delete_draft_need(uuid,integer,text) is
  'Narrow idempotent deletion for an unpublished zero-history, zero-media DRAFT. Published lifecycle records use rpc_cancel_need and remain historical.';

create or replace function public.rpc_withdraw_response(
  p_response_id uuid,
  p_need_revision integer,
  p_response_version integer,
  p_client_request_id text,
  p_reason text default null
) returns jsonb language plpgsql security definer set search_path to 'pg_catalog' as $$
declare
  u uuid := auth.uid();
  v_need_id uuid;
  n public.needs;
  r public.marketplace_responses;
  v_command private.response_withdraw_commands;
  v_request_hash text;
  v_result jsonb;
  old_status text;
begin
  if u is null then raise exception using errcode='42501', message='AUTH_REQUIRED'; end if;
  if p_client_request_id is null
     or char_length(btrim(p_client_request_id)) not between 8 and 200 then
    raise exception using errcode='22023', message='INVALID_CLIENT_REQUEST_ID';
  end if;

  v_request_hash := encode(sha256(convert_to(jsonb_build_object(
    'responseId', p_response_id,
    'needRevision', p_need_revision,
    'responseVersion', p_response_version,
    'reason', btrim(coalesce(p_reason, ''))
  )::text, 'UTF8')), 'hex');

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(u::text || ':' || p_client_request_id, 7242)
  );

  select * into v_command
    from private.response_withdraw_commands c
   where c.worker_account_id = u
     and c.client_request_id = p_client_request_id;
  if found then
    if v_command.request_hash <> v_request_hash then
      raise exception using errcode='22023', message='IDEMPOTENCY_KEY_REUSED';
    end if;
    return v_command.result || jsonb_build_object('idempotentReplay', true);
  end if;

  -- Discover the parent without locking, then take locks in canonical order:
  -- Need -> Response. Selection and submission use the same order.
  select x.need_id into v_need_id
    from public.marketplace_responses x
   where x.id = p_response_id;
  if not found then raise exception using errcode='P0002', message='RESPONSE_NOT_FOUND'; end if;

  select * into n from public.needs where id = v_need_id for update;
  if not found then raise exception using errcode='P0002', message='NEED_NOT_FOUND'; end if;

  select * into r from public.marketplace_responses x
   where x.id = p_response_id for update;
  if not found then raise exception using errcode='P0002', message='RESPONSE_NOT_FOUND'; end if;
  if r.need_id <> n.id then
    raise exception using errcode='P0001', message='RESPONSE_NEED_MISMATCH';
  end if;
  if r.worker_account_id <> u then
    raise exception using errcode='42501', message='FORBIDDEN';
  end if;
  if not exists (
    select 1 from public.app_profiles p
     where p.id = r.worker_profile_id
       and p.account_id = u
       and p.kind = 'WORKER'
  ) then
    raise exception using errcode='42501', message='PROFILE_NOT_OWNED_BY_ACCOUNT';
  end if;

  if r.status = 'WITHDRAWN' then
    return jsonb_build_object(
      'responseId', r.id,
      'needId', n.id,
      'needRevision', n.revision,
      'submittedNeedRevision', r.submitted_against_need_revision,
      'version', r.current_version,
      'status', r.status,
      'withdrawnAt', r.withdrawn_at,
      'idempotentReplay', true,
      'authoritative', true
    );
  end if;

  if r.current_version is distinct from p_response_version then
    raise exception using errcode='P0001', message='STALE_REVIEW_REQUIRED';
  end if;

  if not exists (
    select 1
      from public.marketplace_response_versions v
     where v.response_id = r.id
       and v.version = r.current_version
       and v.need_revision = r.submitted_against_need_revision
  ) then
    raise exception using errcode='P0002', message='RESPONSE_VERSION_NOT_FOUND';
  end if;

  -- C12.12: every withdrawal decision binds the latest Need revision reviewed
  -- by the Worker. A live Application must also have been submitted against it;
  -- a STALE Application deliberately retains its older immutable binding.
  if n.revision is distinct from p_need_revision
     or (r.status <> 'STALE'
         and r.submitted_against_need_revision is distinct from p_need_revision) then
    raise exception using errcode='P0001', message='STALE_REVIEW_REQUIRED';
  end if;

  if r.status = 'SELECTED'
     or exists (
       select 1 from public.agreements a
        where a.selected_response_id = r.id
          and a.status in ('CONFIRMED','SUPERSEDED','COMPLETED')
     ) then
    raise exception using errcode='P0001', message='RESPONSE_ALREADY_SELECTED';
  end if;

  if r.status not in ('DRAFT','SUBMITTED','DELIVERED','VIEWED','SHORTLISTED','STALE') then
    raise exception using errcode='22023', message='RESPONSE_NOT_WITHDRAWABLE';
  end if;

  old_status := r.status;

  update public.notification_deliveries d
     set state = 'EXPIRED'
    from public.user_activity_events e
   where d.event_id = e.id
     and e.entity_type = 'RESPONSE'
     and e.entity_id = r.id
     and d.state in ('CREATED','QUEUED','FAILED_RETRYABLE');

  update public.marketplace_responses
     set status = 'WITHDRAWN',
         withdrawn_at = statement_timestamp(),
         selected_at = null
   where id = r.id
   returning * into r;

  -- A DRAFT was never visible to the requester, so withdrawing it emits no
  -- cross-party event. Submitted history remains visible and versioned.
  if old_status <> 'DRAFT' then
    perform private.emit_event(
      n.requester_account_id,
      'REQUESTER',
      'RESPONSE_WITHDRAWN',
      'RESPONSE',
      r.id,
      r.current_version,
      'Prijava je povucena',
      'Uskocer je povukao prijavu za Vasu Potrebu.',
      'response-withdrawn:' || r.id::text || ':' || r.current_version::text,
      'NORMAL',
      jsonb_build_object('needId', n.id, 'needRevision', n.revision),
      null
    );
  end if;

  -- Withdrawal can reopen capacity. Wake dispatch only while the Need can still
  -- accept a replacement; an elapsed deadline must never schedule new work.
  if n.status in ('PUBLISHED','SELECTION')
     and (n.response_deadline is null
          or n.response_deadline > statement_timestamp())
     and public.fn_need_covered_slots(n.id) < n.required_slots then
    perform private.enqueue_dispatch(n.id, statement_timestamp());
  end if;

  perform private.audit_marketplace(
    u,
    'RESPONSE_WITHDRAWN',
    'RESPONSE',
    r.id,
    r.current_version,
    jsonb_build_object(
      'needId', n.id,
      'needRevision', n.revision,
      'submittedNeedRevision', r.submitted_against_need_revision,
      'clientRequestId', p_client_request_id,
      'reason', left(btrim(coalesce(p_reason, '')), 300)
    )
  );

  v_result := jsonb_build_object(
    'responseId', r.id,
    'needId', n.id,
    'needRevision', n.revision,
    'submittedNeedRevision', r.submitted_against_need_revision,
    'version', r.current_version,
    'status', r.status,
    'withdrawnAt', r.withdrawn_at,
    'idempotentReplay', false,
    'authoritative', true
  );

  insert into private.response_withdraw_commands (
    worker_account_id, client_request_id, request_hash,
    response_id, response_version, result
  ) values (
    u, p_client_request_id, v_request_hash,
    r.id, r.current_version, v_result
  );

  return v_result;
end;
$$;

revoke all on function public.rpc_withdraw_response(uuid,integer,integer,text,text)
  from public, anon, authenticated;
grant execute on function public.rpc_withdraw_response(uuid,integer,integer,text,text) to authenticated;

comment on function public.rpc_withdraw_response(uuid,integer,integer,text,text) is
  'Authoritative durably idempotent withdrawal. Need then Response locking serializes selection races; selected Responses require Agreement flow; C12.12 stale withdrawal binds the latest reviewed Need while submitted versions remain immutable.';

-- The temporary broad UPDATE path existed only because withdrawal was absent.
-- RPCs now own every Response mutation.
drop policy if exists responses_worker_update on public.marketplace_responses;
revoke insert, update, delete on public.marketplace_responses from anon, authenticated;
revoke insert, update, delete on public.marketplace_response_versions from anon, authenticated;

-- A requester still needs direct DRAFT creation/editing, but never destructive
-- DELETE. Splitting the old ALL policy preserves that boundary and prevents
-- cascading deletion of Response/ResponseVersion history.
drop policy if exists needs_owner_all on public.needs;
drop policy if exists needs_owner_select on public.needs;
drop policy if exists needs_owner_insert on public.needs;
drop policy if exists needs_owner_update on public.needs;
create policy needs_owner_select on public.needs
  for select to authenticated
  using (requester_account_id = auth.uid());
create policy needs_owner_insert on public.needs
  for insert to authenticated
  with check (requester_account_id = auth.uid() and status = 'DRAFT');
create policy needs_owner_update on public.needs
  for update to authenticated
  using (
    requester_account_id = auth.uid()
    and status in ('DRAFT','PUBLISHED','SELECTION')
  )
  with check (
    requester_account_id = auth.uid()
    and status in ('DRAFT','PUBLISHED','SELECTION')
  );
revoke insert, update, delete on public.needs from anon;
revoke delete on public.needs from anon, authenticated;

-- Need revision/cancellation events are part of the response lifecycle from a
-- worker's perspective and must honor responses_enabled, not account_enabled.
create or replace function private.category_of_event(p_event_type text)
returns text language sql immutable set search_path to 'pg_catalog' as $$
  select case
    when p_event_type = 'OPPORTUNITY_AVAILABLE' then 'opportunities'
    when p_event_type like 'RESPONSE\_%'
      or p_event_type in ('NEED_REVISED','NEED_CANCELLED') then 'responses'
    when p_event_type like 'AGREEMENT\_%'
      or p_event_type in ('MESSAGE_RECEIVED','PRIVATE_ACCESS_GRANTED','REVIEW_RECEIVED') then 'dogovor'
    when p_event_type in ('EXECUTION_STATE_CHANGED','COMPLETION_REQUIRED') then 'execution'
    when p_event_type = 'RECOVERY_OPENED' then 'recovery'
    else 'account'
  end;
$$;

revoke all on function private.category_of_event(text)
  from public, anon, authenticated;

-- Preserve Claude's ownership/revision guard and close its remaining terminal
-- mutation hole: CANCELLED/EXPIRED/COMPLETED/ARCHIVED truth is immutable.
create or replace function private.guard_need_write()
returns trigger language plpgsql security definer set search_path to 'pg_catalog' as $$
declare
  token text := current_setting('uskoci.need_lifecycle', true);
  material boolean;
begin
  if not exists (
    select 1 from public.app_profiles p
     where p.id = new.requester_profile_id
       and p.account_id = new.requester_account_id
       and p.kind = 'REQUESTER'
  ) then
    raise exception using errcode='42501', message='PROFILE_NOT_OWNED_BY_ACCOUNT';
  end if;

  if tg_op = 'INSERT' then
    if new.status <> 'DRAFT'
       and not (new.status = 'PUBLISHED' and token = 'PUBLISH') then
      raise exception using errcode='22023', message='NEED_MUST_START_AS_DRAFT';
    end if;
    return new;
  end if;

  -- Terminal domain truth is immutable. The only tolerated housekeeping change
  -- is urgent=true -> false (plus the normal updated_at trigger), so expiry of
  -- an old urgency projection can never wedge the marketplace cron.
  if old.status in ('COMPLETED','CANCELLED','EXPIRED','ARCHIVED')
     and (
       (to_jsonb(new) - array['urgent','updated_at'])
         is distinct from
       (to_jsonb(old) - array['urgent','updated_at'])
       or (not coalesce(old.urgent, false) and coalesce(new.urgent, false))
     ) then
    raise exception using errcode='22023', message='NEED_TERMINAL_IMMUTABLE';
  end if;

  if new.requester_account_id <> old.requester_account_id then
    raise exception using errcode='42501', message='NEED_OWNER_IMMUTABLE';
  end if;

  if new.status is distinct from old.status then
    if not (
         (token = 'PUBLISH'
          and old.status = 'DRAFT' and new.status = 'PUBLISHED')
      or (token = 'SELECT'
          and old.status in ('PUBLISHED','SELECTION')
          and new.status in ('SELECTION','ACTIVE'))
      or (token = 'CANCEL_NEED'
          and old.status in ('DRAFT','PUBLISHED','SELECTION')
          and new.status = 'CANCELLED')
      or (token = 'CANCEL_AGREEMENT'
          and old.status in ('ACTIVE','SELECTION')
          and new.status = 'SELECTION')
      or (token = 'EXPIRE'
          and old.status in ('PUBLISHED','SELECTION')
          and new.status = 'EXPIRED')
    ) then
      raise exception using errcode='22023', message='NEED_STATUS_TRANSITION_REQUIRES_RPC';
    end if;
  end if;

  material :=
       new.title is distinct from old.title
    or new.description is distinct from old.description
    or new.category is distinct from old.category
    or new.required_slots is distinct from old.required_slots
    or new.mode is distinct from old.mode
    or new.requester_price_rsd is distinct from old.requester_price_rsd
    or new.required_skills is distinct from old.required_skills
    or new.required_tools is distinct from old.required_tools
    or new.required_vehicles is distinct from old.required_vehicles
    or new.required_licenses is distinct from old.required_licenses
    or new.minimum_experience_years is distinct from old.minimum_experience_years
    or new.verified_identity_required is distinct from old.verified_identity_required
    or new.schedule_kind is distinct from old.schedule_kind
    or new.starts_at is distinct from old.starts_at
    or new.ends_at is distinct from old.ends_at
    or new.execution_location_mode is distinct from old.execution_location_mode
    or new.approximate_lat is distinct from old.approximate_lat
    or new.approximate_lng is distinct from old.approximate_lng;

  if material then
    if old.status in ('PUBLISHED','SELECTION') then
      new.revision := old.revision + 1;
    end if;
  elsif new.revision is distinct from old.revision then
    raise exception using errcode='22023', message='REVISION_BUMP_WITHOUT_MATERIAL_CHANGE';
  end if;

  return new;
end;
$$;

revoke all on function private.guard_need_write()
  from public, anon, authenticated;

-- Repair cron deadline expiry after needs_guard_write made status transitions
-- token-gated. The rest of the previously proven lifecycle remains unchanged.
create or replace function private.expire_lifecycle(
  p_at timestamptz default statement_timestamp()
) returns jsonb language plpgsql security definer set search_path to 'pg_catalog' as $$
declare
  d integer := 0;
  rr integer := 0;
  av integer := 0;
  ur integer := 0;
  ne integer := 0;
  re integer := 0;
  nd integer := 0;
  dq integer := 0;
  changed integer := 0;
begin
  perform set_config('uskoci.need_lifecycle', 'EXPIRE', true);

  with expired_needs as (
    update public.needs x
       set status = 'EXPIRED', urgent = false
     where x.status in ('PUBLISHED','SELECTION')
       and x.response_deadline is not null
       and x.response_deadline <= p_at
       and not exists (
         select 1 from public.need_selections s
          where s.need_id = x.id and s.status = 'SELECTED'
    )
    returning x.id, x.revision
  ), expired_responses as (
    update public.marketplace_responses r
       set status = 'EXPIRED', selected_at = null
      from expired_needs i
     where r.need_id = i.id
       and r.status in ('DRAFT','SUBMITTED','DELIVERED','VIEWED','SHORTLISTED','STALE')
    returning r.id
  ), expired_notifications as (
    update public.notification_deliveries d
       set state = 'EXPIRED'
      from public.user_activity_events e
     where d.event_id = e.id
       and d.state in ('CREATED','QUEUED','FAILED_RETRYABLE')
       and (
         (e.entity_type = 'NEED' and exists (
           select 1 from expired_needs i where i.id = e.entity_id
         ))
         or (e.entity_type = 'RESPONSE' and exists (
           select 1
             from public.marketplace_responses r
             join expired_needs i on i.id = r.need_id
            where r.id = e.entity_id
         ))
       )
    returning d.id
  ), stopped_rounds as (
    update public.dispatch_rounds r
       set status = 'STOPPED', stop_reason = 'NEED_EXPIRED'
      from expired_needs i
     where r.need_id = i.id and r.status in ('PLANNED','SENT')
    returning r.need_id
  ), expired_opportunities as (
    update public.opportunity_deliveries o set status = 'EXPIRED'
      from expired_needs i
     where o.need_id = i.id and o.status in ('READY','SEEN')
    returning o.need_id
  ), dequeued as (
    delete from private.dispatch_schedule s
     using expired_needs i where s.need_id = i.id
    returning s.need_id
  )
  select
    (select count(*)::integer from expired_needs),
    (select count(*)::integer from expired_responses),
    (select count(*)::integer from expired_notifications),
    (select count(*)::integer from stopped_rounds),
    (select count(*)::integer from expired_opportunities),
    (select count(*)::integer from dequeued)
  into ne, re, nd, rr, d, dq;

  update public.opportunity_deliveries
     set status = 'EXPIRED'
   where status in ('READY','SEEN')
     and expires_at is not null and expires_at <= p_at;
  get diagnostics changed = row_count;
  d := d + changed;

  update public.dispatch_rounds
     set status = 'EXPIRED'
   where status = 'SENT'
     and deadline_at is not null and deadline_at <= p_at;
  get diagnostics changed = row_count;
  rr := rr + changed;

  update public.app_profiles
     set available_now = false
   where available_now = true
     and available_now_expires_at is not null
     and available_now_expires_at <= p_at;
  get diagnostics av = row_count;

  ur := private.expire_urgent(p_at);

  return jsonb_build_object(
    'needsExpired', ne,
    'responsesExpired', re,
    'notificationsExpired', nd,
    'schedulesDequeued', dq,
    'deliveriesExpired', d,
    'roundsExpired', rr,
    'availabilityExpired', av,
    'urgencyExpired', ur
  );
end;
$$;

revoke all on function private.expire_lifecycle(timestamptz)
  from public, anon, authenticated;

-- Repair Agreement cancellation for the same lifecycle-token regression while
-- preserving the already proven privacy, ghost-notification and replacement work.
create or replace function public.rpc_cancel_agreement(
  p_agreement_id uuid,
  p_reason text
) returns void language plpgsql security definer set search_path to 'pg_catalog' as $$
declare
  uid uuid := auth.uid();
  v_need_id uuid;
  v_agr public.agreements%rowtype;
  v_covered integer;
  v_need public.needs%rowtype;
begin
  if uid is null then raise exception 'AUTH_REQUIRED' using errcode = '28000'; end if;
  if coalesce(btrim(p_reason), '') = '' then
    raise exception 'REASON_REQUIRED' using errcode = 'P0001';
  end if;

  -- Discover without locking, authorize, then use the canonical lock order
  -- Need -> Agreement -> Response shared with selection/cancel/withdraw.
  select a.need_id into v_need_id
    from public.agreements a
   where a.id = p_agreement_id;
  if not found then raise exception 'AGREEMENT_NOT_FOUND' using errcode = 'P0002'; end if;
  if not public.fn_is_party(p_agreement_id, uid) then
    raise exception 'NOT_PARTY' using errcode = '42501';
  end if;

  select * into v_need
    from public.needs n
   where n.id = v_need_id
   for update;
  if not found then raise exception 'NEED_NOT_FOUND' using errcode = 'P0002'; end if;

  select * into v_agr from public.agreements
   where id = p_agreement_id for update;
  if not found then raise exception 'AGREEMENT_NOT_FOUND' using errcode = 'P0002'; end if;
  if v_agr.need_id is distinct from v_need.id then
    raise exception 'AGREEMENT_NEED_MISMATCH' using errcode = 'P0001';
  end if;
  if not public.fn_is_party(p_agreement_id, uid) then
    raise exception 'NOT_PARTY' using errcode = '42501';
  end if;
  if v_agr.status = 'CANCELLED' then return; end if;
  if v_agr.status = 'COMPLETED' then
    raise exception 'ALREADY_COMPLETED' using errcode = 'P0001';
  end if;

  update public.agreements set status = 'CANCELLED' where id = p_agreement_id;
  update public.agreement_execution set state = 'CANCELLED'
   where agreement_id = p_agreement_id;
  update public.need_selections set status = 'CANCELLED'
   where id = v_agr.selection_id;
  update public.marketplace_responses
     set status = 'NOT_SELECTED', selected_at = null
   where id = v_agr.selected_response_id;
  update public.access_grants
     set status = 'REVOKED',
         revoked_at = coalesce(revoked_at, statement_timestamp())
   where agreement_id = p_agreement_id and status = 'GRANTED';
  update public.notification_deliveries d
     set state = 'EXPIRED'
    from public.user_activity_events e
   where d.event_id = e.id
     and e.entity_type = 'AGREEMENT'
     and e.entity_id = p_agreement_id
     and d.state in ('CREATED','QUEUED','FAILED_RETRYABLE');

  v_covered := public.fn_need_covered_slots(v_agr.need_id);

  if v_covered < v_need.required_slots
     and v_need.status in ('ACTIVE','SELECTION') then
    perform set_config('uskoci.need_lifecycle', 'CANCEL_AGREEMENT', true);
    update public.needs set status = 'SELECTION' where id = v_need.id;
    perform private.enqueue_dispatch(v_need.id, statement_timestamp());
  end if;
end;
$$;

revoke all on function public.rpc_cancel_agreement(uuid,text)
  from public, anon, authenticated;
grant execute on function public.rpc_cancel_agreement(uuid,text) to authenticated;

comment on function public.rpc_cancel_agreement(uuid,text) is
  'M06 unilateral Agreement cancellation. Revokes grants, expires pending Agreement notifications, releases only its seat and explicitly wakes replacement dispatch. Lifecycle token repaired after guard_need_write.';
