#!/usr/bin/env python3
"""B24 generator: turns b24_inventory.tsv (every live DEV function whose body raises SQLSTATE 40001, read from pg_proc on 2026-09-30) into

  supabase/candidates/b24_nonretried_conflicts_part1.sql           54 functions outside the certified closure source (certificate-neutral)
  supabase/candidates/b24_nonretried_conflicts_part2_certified.sql 14 functions inside it (moves the digest and re-binds the certificate, pkg032b pattern)
  supabase/candidates/b24_nonretried_conflicts_part1_revert.sql    exact inverse of part 1
  supabase/candidates/b24_nonretried_conflicts_part2_revert.sql    exact inverse of part 2, re-binding back
  docs/implementation/product-v1-closure-20260926/finalization-20260927/b24/B24_SITE_CLASSIFICATION.md

`--check` regenerates in memory and fails if a committed file differs, so the candidates can never drift from the inventory. Nothing here touches a database."""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..', '..'))
CAND = os.path.join(REPO, 'supabase', 'candidates')
DOCS = os.path.join(REPO, 'docs', 'implementation', 'product-v1-closure-20260926', 'finalization-20260927', 'b24')

# The certified closure digest on canonical DEV before this change (read from private.retention_ai_source_ready() on 2026-09-30).
CERTIFIED_BEFORE = '86ba37518263930961e254be85569db75257da53d4725c8c186c632dc11de41b'

CLASS_TEXT = {
    'D1': 'stale revision/version supplied by the caller',
    'D2': 'stale server-issued token (attempt, lease, generation) or expired review',
    'D3': 'idempotency / command conflict (same key, different content)',
    'D4': 'content digest, policy or context binding changed',
    'D5': 'concurrent write detected after the fact (update matched no row, insert lost, target vanished)',
    'D6': 'storage outcome unconfirmed or inconsistent for the settlement call',
    'D7': 'business-state conflict (already open)',
}


def load():
    rows = []
    lines = open(os.path.join(HERE, 'b24_inventory.tsv'), encoding='utf-8').read().splitlines()
    for line in lines[1:]:
        fn, part, exposure, md5, sites, msgs = line.split('\t')
        items = []
        for chunk in msgs.split(';'):
            m, c, n = chunk.split(':')
            items.append((m, c, int(n)))
        assert sum(n for _, _, n in items) == int(sites), fn
        rows.append({'fn': fn, 'part': int(part), 'exposure': exposure, 'md5': md5, 'sites': int(sites), 'items': items})
    return rows


def values_list(rows):
    return ',\n'.join(f"  ('{r['fn']}', {r['sites']}, '{r['md5']}')" for r in rows)


def names_list(rows):
    return ', '.join(f"'{r['fn']}'" for r in rows)


ATTRS_FN = """create function pg_temp.b24_attrs(p_oid oid) returns text language sql stable as $f$
  select md5(concat_ws('|', p.proowner::text, coalesce(p.proacl::text, ''), p.prosecdef::text, p.proisstrict::text, p.provolatile::text,
    p.proleakproof::text, p.proparallel::text, p.prolang::text, p.procost::text, p.prorows::text, p.prorettype::text, p.proargtypes::text,
    coalesce(p.proargnames::text, ''), coalesce(p.proargmodes::text, ''), coalesce(p.proallargtypes::text, ''), coalesce(p.proconfig::text, ''),
    p.prokind::text, coalesce(obj_description(p.oid, 'pg_proc'), '')))
  from pg_proc p where p.oid = p_oid
$f$;
"""


def header(title, rows, extra):
    sites = sum(r['sites'] for r in rows)
    return f"""-- {title}
-- GENERATED by supabase/proofs/b24/build_b24_candidates.py from supabase/proofs/b24/b24_inventory.tsv - do not edit by hand (`--check` fails on any difference).
-- STATUS: CANDIDATE, NOT APPLIED. Applying it to canonical DEV needs the owner's separate "primeni" (owner decision 2026-09-30).
--
-- Registry blocker B24 (docs/implementation/product-v1-closure-20260926/finalization-20260927/ROUND_74_P6_PHYSICAL_HONOR_CANDIDATE.md): PostgREST 14 re-executes,
-- without end and after the client has gone, any request whose function raises SQLSTATE 40001 (proof run 36745783626; Supabase documents the same defect: PostgREST 14
-- affected, 16 fixed, use a custom or P0001 code instead). Every one of the {sum(r['sites'] for r in rows)} sites below is a DETERMINISTIC business conflict (a stale revision, token, digest or
-- idempotency mismatch, classified one by one in docs/.../b24/B24_SITE_CLASSIFICATION.md): a retry of the same call can never succeed, so the retry is pure harm.
-- None is an engine-raised serialization failure (those come from Postgres itself, are not in any function body, and are not touched).
--
-- What this changes: in {len(rows)} functions the code of each such raise becomes PT409 (PostgREST answers HTTP 409 at once, with the same message), and nothing else:
-- same message, same arguments, same security, same grants, same comment. {extra}
"""


def part1(rows):
    p1 = [r for r in rows if r['part'] == 1]
    p2 = [r for r in rows if r['part'] == 2]
    sites = sum(r['sites'] for r in p1)
    extra = f"""None of these functions is among the 76 that `private.closure_source_digest_v5()` hashes, so the certified digest must NOT move:
-- the candidate asserts that before and after, and refuses to run twice. Part 2 covers the {len(p2)} certified functions and re-binds the certificate.
--
-- Guards: every target exists exactly once, carries exactly the pinned number of quoted '40001' and no 'PT409' yet; in strict mode (the default) its body md5 equals the pre-image
-- read from canonical DEV on 2026-09-30; afterwards its body with PT409 turned back into 40001 is byte-for-byte the old body, it has no 40001 left, its owner/ACL/security/config/comment
-- tuple is unchanged, and the only functions still raising 40001 are the certified ones of part 2. A disposable proof database that does not carry the DEV pre-image runs it with
-- `set b24.preimage = 'relaxed'` (the md5 pins and the closed list of names are skipped; every structural check stays)."""
    body = f"""begin;
set local lock_timeout = '5s';
set local statement_timeout = '180s';
set local search_path = pg_catalog;

create temporary table b24_targets(fn text primary key, sites integer not null, pre_md5 text not null) on commit drop;
insert into b24_targets(fn, sites, pre_md5) values
{values_list(p1)};

create temporary table b24_before(fn text primary key, fn_oid oid not null, pre_src text not null, attrs_md5 text not null) on commit drop;
create temporary table b24_cert(certified text not null) on commit drop;
{ATTRS_FN}
do $pre$
declare
  r record; v_oid oid; v_src text; v_n integer; v_certified text;
  v_strict boolean := coalesce(nullif(current_setting('b24.preimage', true), ''), 'strict') <> 'relaxed';
begin
  if (select count(*) from b24_targets) <> {len(p1)} or (select sum(sites) from b24_targets) <> {sites} then
    raise exception 'B24_TARGET_TABLE_INVALID' using errcode = '55000';
  end if;
  v_certified := private.closure_source_digest_v5();
  if v_certified is distinct from (select sha256 from private.closure_source_v5 where singleton)
     or v_certified is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
     or not private.retention_ai_source_ready() then
    raise exception 'B24_CERTIFICATE_NOT_READY' using errcode = '55000';
  end if;
  insert into b24_cert(certified) values (v_certified);
  if v_strict and exists (
       select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
        where p.prosrc like '%40001%' and n.nspname || '.' || p.proname not in ({names_list(rows)})) then
    raise exception 'B24_UNCLASSIFIED_40001_SITE' using errcode = '55000';
  end if;
  for r in select * from b24_targets order by fn loop
    select count(*) into v_n from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname || '.' || p.proname = r.fn;
    if v_n <> 1 then raise exception 'B24_FUNCTION_NOT_UNIQUE: % (% found)', r.fn, v_n using errcode = '55000'; end if;
    select p.oid, p.prosrc into v_oid, v_src from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname || '.' || p.proname = r.fn;
    if position('PT409' in v_src) > 0 then raise exception 'B24_ALREADY_APPLIED: %', r.fn using errcode = '55000'; end if;
    v_n := (length(v_src) - length(replace(v_src, '''40001''', ''))) / 7;
    if v_n <> r.sites or position('40001' in replace(v_src, '''40001''', '')) > 0 then
      raise exception 'B24_SITE_COUNT_DRIFT: % expected % quoted sites, found %', r.fn, r.sites, v_n using errcode = '55000';
    end if;
    if v_strict and md5(v_src) is distinct from r.pre_md5 then raise exception 'B24_PREIMAGE_DRIFT: %', r.fn using errcode = '55000'; end if;
    insert into b24_before(fn, fn_oid, pre_src, attrs_md5) values (r.fn, v_oid, v_src, pg_temp.b24_attrs(v_oid));
  end loop;
end
$pre$;

do $convert$
declare r record; v_def text; v_new text;
begin
  for r in select fn, fn_oid from b24_before order by fn loop
    v_def := pg_get_functiondef(r.fn_oid);
    v_new := replace(v_def, '''40001''', '''PT409''');
    if v_new = v_def then raise exception 'B24_NOTHING_TO_CONVERT: %', r.fn; end if;
    execute v_new;
  end loop;
end
$convert$;

do $post$
declare r record; v_src text; v_n integer; v_certified text;
  v_strict boolean := coalesce(nullif(current_setting('b24.preimage', true), ''), 'strict') <> 'relaxed';
begin
  for r in select t.fn, t.sites, b.fn_oid, b.pre_src, b.attrs_md5 from b24_targets t join b24_before b using (fn) order by t.fn loop
    select prosrc into strict v_src from pg_proc where oid = r.fn_oid;
    if position('40001' in v_src) > 0 then raise exception 'B24_40001_LEFT: %', r.fn; end if;
    v_n := (length(v_src) - length(replace(v_src, '''PT409''', ''))) / 7;
    if v_n <> r.sites then raise exception 'B24_SITE_COUNT_AFTER: % expected %, found %', r.fn, r.sites, v_n; end if;
    if replace(v_src, '''PT409''', '''40001''') is distinct from r.pre_src then raise exception 'B24_CHANGE_BEYOND_THE_CODE: %', r.fn; end if;
    if pg_temp.b24_attrs(r.fn_oid) is distinct from r.attrs_md5 then raise exception 'B24_ATTRIBUTES_CHANGED: %', r.fn; end if;
  end loop;
  select certified into strict v_certified from b24_cert;
  if private.closure_source_digest_v5() is distinct from v_certified
     or v_certified is distinct from (select sha256 from private.closure_source_v5 where singleton)
     or v_certified is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
     or not private.retention_ai_source_ready() then
    raise exception 'B24_CERTIFICATE_MOVED' using errcode = '55000';
  end if;
  if v_strict and exists (
       select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
        where p.prosrc like '%40001%' and n.nspname || '.' || p.proname not in ({names_list(p2)})) then
    raise exception 'B24_OTHER_40001_SITES_REMAIN' using errcode = '55000';
  end if;
end
$post$;

drop function pg_temp.b24_attrs(oid);
commit;
"""
    return header('B24 candidate, part 1 of 2: non-retried conflict codes in the functions OUTSIDE the certified closure source', p1, extra) + body


def part1_revert(rows):
    p1 = [r for r in rows if r['part'] == 1]
    sites = sum(r['sites'] for r in p1)
    extra = f"""Reverting re-introduces the endless PostgREST retry, so it exists only as the rollback the apply discipline asks for.
--
-- Guards: every target carries exactly the pinned number of quoted 'PT409' and no 40001; afterwards its body with 40001 turned back into PT409 is byte-for-byte the converted body,
-- the attributes tuple is unchanged and the certified digest did not move."""
    body = f"""begin;
set local lock_timeout = '5s';
set local statement_timeout = '180s';
set local search_path = pg_catalog;

create temporary table b24_targets(fn text primary key, sites integer not null, pre_md5 text not null) on commit drop;
insert into b24_targets(fn, sites, pre_md5) values
{values_list(p1)};

create temporary table b24_before(fn text primary key, fn_oid oid not null, pre_src text not null, attrs_md5 text not null) on commit drop;
create temporary table b24_cert(certified text not null) on commit drop;
{ATTRS_FN}
do $pre$
declare r record; v_oid oid; v_src text; v_n integer; v_certified text;
begin
  if (select count(*) from b24_targets) <> {len(p1)} or (select sum(sites) from b24_targets) <> {sites} then
    raise exception 'B24_TARGET_TABLE_INVALID' using errcode = '55000';
  end if;
  v_certified := private.closure_source_digest_v5();
  if v_certified is distinct from (select sha256 from private.closure_source_v5 where singleton)
     or v_certified is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
     or not private.retention_ai_source_ready() then
    raise exception 'B24_CERTIFICATE_NOT_READY' using errcode = '55000';
  end if;
  insert into b24_cert(certified) values (v_certified);
  for r in select * from b24_targets order by fn loop
    select count(*) into v_n from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname || '.' || p.proname = r.fn;
    if v_n <> 1 then raise exception 'B24_FUNCTION_NOT_UNIQUE: % (% found)', r.fn, v_n using errcode = '55000'; end if;
    select p.oid, p.prosrc into v_oid, v_src from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname || '.' || p.proname = r.fn;
    if position('40001' in v_src) > 0 then raise exception 'B24_NOT_APPLIED: %', r.fn using errcode = '55000'; end if;
    v_n := (length(v_src) - length(replace(v_src, '''PT409''', ''))) / 7;
    if v_n <> r.sites then raise exception 'B24_SITE_COUNT_DRIFT: % expected % quoted PT409 sites, found %', r.fn, r.sites, v_n using errcode = '55000'; end if;
    insert into b24_before(fn, fn_oid, pre_src, attrs_md5) values (r.fn, v_oid, v_src, pg_temp.b24_attrs(v_oid));
  end loop;
end
$pre$;

do $convert$
declare r record; v_def text; v_new text;
begin
  for r in select fn, fn_oid from b24_before order by fn loop
    v_def := pg_get_functiondef(r.fn_oid);
    v_new := replace(v_def, '''PT409''', '''40001''');
    if v_new = v_def then raise exception 'B24_NOTHING_TO_REVERT: %', r.fn; end if;
    execute v_new;
  end loop;
end
$convert$;

do $post$
declare r record; v_src text; v_n integer; v_certified text;
begin
  for r in select t.fn, t.sites, b.fn_oid, b.pre_src, b.attrs_md5 from b24_targets t join b24_before b using (fn) order by t.fn loop
    select prosrc into strict v_src from pg_proc where oid = r.fn_oid;
    if position('PT409' in v_src) > 0 then raise exception 'B24_PT409_LEFT: %', r.fn; end if;
    v_n := (length(v_src) - length(replace(v_src, '''40001''', ''))) / 7;
    if v_n <> r.sites then raise exception 'B24_SITE_COUNT_AFTER: % expected %, found %', r.fn, r.sites, v_n; end if;
    if replace(v_src, '''40001''', '''PT409''') is distinct from r.pre_src then raise exception 'B24_CHANGE_BEYOND_THE_CODE: %', r.fn; end if;
    if pg_temp.b24_attrs(r.fn_oid) is distinct from r.attrs_md5 then raise exception 'B24_ATTRIBUTES_CHANGED: %', r.fn; end if;
  end loop;
  select certified into strict v_certified from b24_cert;
  if private.closure_source_digest_v5() is distinct from v_certified or not private.retention_ai_source_ready() then
    raise exception 'B24_CERTIFICATE_MOVED' using errcode = '55000';
  end if;
end
$post$;

drop function pg_temp.b24_attrs(oid);
commit;
"""
    return header('B24 revert of part 1: the exact inverse (PT409 back to 40001)', p1, extra) + body


def part2_common_tables(p2, prefix):
    return f"""create temporary table {prefix}_targets(fn text primary key, sites integer not null, pre_md5 text not null) on commit drop;
insert into {prefix}_targets(fn, sites, pre_md5) values
{values_list(p2)};

create temporary table {prefix}_before(fn text primary key, fn_oid oid not null, pre_src text not null, pre_def text not null, attrs_md5 text not null) on commit drop;
create temporary table {prefix}_state(certified text not null, ready_masked text not null, moved text) on commit drop;
{ATTRS_FN}"""


def part2(rows):
    p2 = [r for r in rows if r['part'] == 2]
    sites = sum(r['sites'] for r in p2)
    extra = f"""These {len(p2)} functions ARE among the 76 that `private.closure_source_digest_v5()` hashes (md5 of each body), so changing them moves the digest and the certificate has
-- to be bound to the new value in its three places: private.closure_source_v5, private.closure_erasure_source_v5 and the constant inside private.retention_ai_source_ready()
-- (the $rebind$ pattern of PKG-023f / PKG-032b; a re-bind is a privacy certification of the erasure program, which is why this is its own candidate and its own approval).
--
-- What makes the re-binding honest (pkg032b): before, live = certified in all three places, the source is ready and no account closure is executing (strict mode also pins the
-- certified value {CERTIFIED_BEFORE[:12]}...); the new digest differs from the old one, and restoring the OLD definitions of these {len(p2)} functions inside this transaction gives the old
-- value back, so the {len(p2)} bodies are the only thing the new value reflects; after, the three places hold the new live value, the readiness function changed only by its
-- constant, the source is ready, the erasure binding carries the new value, and every body is the old one with PT409 turned back into 40001. The erasure program (redaction
-- relations and patch) is not touched. Run part 1 first or after: they are independent."""
    body = f"""begin;
set local lock_timeout = '5s';
set local statement_timeout = '180s';
set local search_path = pg_catalog;

{part2_common_tables(p2, 'b24p2')}
do $pre$
declare
  r record; v_oid oid; v_src text; v_n integer; v_certified text; v_ready_def text;
  v_strict boolean := coalesce(nullif(current_setting('b24.preimage', true), ''), 'strict') <> 'relaxed';
begin
  if (select count(*) from b24p2_targets) <> {len(p2)} or (select sum(sites) from b24p2_targets) <> {sites} then
    raise exception 'B24P2_TARGET_TABLE_INVALID' using errcode = '55000';
  end if;
  select sha256 into strict v_certified from private.closure_source_v5 where singleton;
  if v_certified is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton) then
    raise exception 'B24P2_CERTIFIED_VALUES_DISAGREE' using errcode = '55000';
  end if;
  v_ready_def := pg_get_functiondef('private.retention_ai_source_ready()'::regprocedure);
  if (length(v_ready_def) - length(replace(v_ready_def, v_certified, ''))) <> length(v_certified)
     or (select count(*) from regexp_matches(v_ready_def, '[0-9a-f]{{64}}', 'g')) <> 1 then
    raise exception 'B24P2_READY_BINDING_INVALID' using errcode = '55000';
  end if;
  if private.closure_source_digest_v5() is distinct from v_certified or not private.retention_ai_source_ready() then
    raise exception 'B24P2_CLOSURE_SOURCE_NOT_READY' using errcode = '55000';
  end if;
  if exists (select 1 from private.closure_executions_v5 where state = 'EXECUTING') then
    raise exception 'B24P2_CLOSURE_IN_FLIGHT' using errcode = '55000';
  end if;
  if v_strict and v_certified is distinct from '{CERTIFIED_BEFORE}' then
    raise exception 'B24P2_PREDECESSOR_DRIFT: the certified value is %', v_certified using errcode = '55000';
  end if;
  insert into b24p2_state(certified, ready_masked) values (v_certified,
    (select md5(regexp_replace(prosrc, '[0-9a-f]{{64}}', '<CERTIFIED>', 'g')) from pg_proc where oid = 'private.retention_ai_source_ready()'::regprocedure));
  for r in select * from b24p2_targets order by fn loop
    select count(*) into v_n from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname || '.' || p.proname = r.fn;
    if v_n <> 1 then raise exception 'B24P2_FUNCTION_NOT_UNIQUE: % (% found)', r.fn, v_n using errcode = '55000'; end if;
    select p.oid, p.prosrc into v_oid, v_src from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname || '.' || p.proname = r.fn;
    if position('PT409' in v_src) > 0 then raise exception 'B24P2_ALREADY_APPLIED: %', r.fn using errcode = '55000'; end if;
    v_n := (length(v_src) - length(replace(v_src, '''40001''', ''))) / 7;
    if v_n <> r.sites or position('40001' in replace(v_src, '''40001''', '')) > 0 then
      raise exception 'B24P2_SITE_COUNT_DRIFT: % expected % quoted sites, found %', r.fn, r.sites, v_n using errcode = '55000';
    end if;
    if v_strict and md5(v_src) is distinct from r.pre_md5 then raise exception 'B24P2_PREIMAGE_DRIFT: %', r.fn using errcode = '55000'; end if;
    insert into b24p2_before(fn, fn_oid, pre_src, pre_def, attrs_md5) values (r.fn, v_oid, v_src, pg_get_functiondef(v_oid), pg_temp.b24_attrs(v_oid));
  end loop;
end
$pre$;

-- a. The conversion.
do $convert$
declare r record; v_new text;
begin
  for r in select fn, pre_def from b24p2_before order by fn loop
    v_new := replace(r.pre_def, '''40001''', '''PT409''');
    if v_new = r.pre_def then raise exception 'B24P2_NOTHING_TO_CONVERT: %', r.fn; end if;
    execute v_new;
  end loop;
end
$convert$;

-- b. The new digest reflects these functions and only these: with the old definitions back it is the old certified value again.
do $isolate$
declare r record; v_old text; v_new text; v_back text; v_again text; v_src text;
begin
  select certified into strict v_old from b24p2_state;
  v_new := private.closure_source_digest_v5();
  if v_new is null then raise exception 'B24P2_SOURCE_DIGEST_UNAVAILABLE'; end if;
  if v_new = v_old then raise exception 'B24P2_CHANGE_NOT_IN_THE_DIGEST'; end if;
  for r in select fn, fn_oid, pre_src, pre_def from b24p2_before order by fn loop
    execute r.pre_def;
    select prosrc into strict v_src from pg_proc where oid = r.fn_oid;
    if v_src is distinct from r.pre_src then raise exception 'B24P2_RESTORE_IS_NOT_THE_OLD_BODY: %', r.fn; end if;
  end loop;
  v_back := private.closure_source_digest_v5();
  if v_back is distinct from v_old then
    raise exception 'B24P2_UNREVIEWED_CHANGE: with the old bodies the digest is %, the certified value is %', v_back, v_old;
  end if;
  for r in select fn, pre_def from b24p2_before order by fn loop
    execute replace(r.pre_def, '''40001''', '''PT409''');
  end loop;
  v_again := private.closure_source_digest_v5();
  if v_again is distinct from v_new then raise exception 'B24P2_DIGEST_NOT_STABLE'; end if;
  update b24p2_state set moved = v_new;
end
$isolate$;

-- c. The certified value, in its three places, for the state this transaction now holds.
do $rebind$
declare v_old text; v_new text; v_def text;
begin
  select certified, moved into strict v_old, v_new from b24p2_state;
  if v_new is distinct from private.closure_source_digest_v5() then raise exception 'B24P2_DIGEST_NOT_STABLE'; end if;
  v_def := pg_get_functiondef('private.retention_ai_source_ready()'::regprocedure);
  update private.closure_source_v5 set sha256 = v_new where singleton and sha256 = v_old;
  if not found then raise exception 'B24P2_CERTIFIED_VALUES_DISAGREE'; end if;
  update private.closure_erasure_source_v5 set sha256 = v_new where singleton and sha256 = v_old;
  if not found then raise exception 'B24P2_CERTIFIED_VALUES_DISAGREE'; end if;
  execute replace(v_def, v_old, v_new);
end
$rebind$;

do $post$
declare r record; v_old text; v_live text; v_ready text; v_src text; v_n integer; s record;
begin
  select * into strict s from b24p2_state;
  v_old := s.certified;
  v_live := private.closure_source_digest_v5();
  select prosrc into strict v_ready from pg_proc where oid = 'private.retention_ai_source_ready()'::regprocedure;
  if (select sha256 from private.closure_source_v5 where singleton) is distinct from v_live
     or (select sha256 from private.closure_erasure_source_v5 where singleton) is distinct from v_live
     or position(v_old in v_ready) > 0
     or (length(v_ready) - length(replace(v_ready, v_live, ''))) <> length(v_live) then
    raise exception 'B24P2_REBIND_INCOMPLETE';
  end if;
  if md5(regexp_replace(v_ready, '[0-9a-f]{{64}}', '<CERTIFIED>', 'g')) is distinct from s.ready_masked then
    raise exception 'B24P2_READINESS_FUNCTION_CHANGED_BEYOND_THE_CONSTANT';
  end if;
  if private.retention_ai_source_ready() is distinct from true then raise exception 'B24P2_SOURCE_NOT_READY'; end if;
  if private.closure_erasure_binding_v5() is null or private.closure_erasure_binding_v5()->>'sourceSha256' is distinct from v_live then
    raise exception 'B24P2_ERASURE_BINDING_NOT_READY';
  end if;
  for r in select t.fn, t.sites, b.fn_oid, b.pre_src, b.attrs_md5 from b24p2_targets t join b24p2_before b using (fn) order by t.fn loop
    select prosrc into strict v_src from pg_proc where oid = r.fn_oid;
    if position('40001' in v_src) > 0 then raise exception 'B24P2_40001_LEFT: %', r.fn; end if;
    v_n := (length(v_src) - length(replace(v_src, '''PT409''', ''))) / 7;
    if v_n <> r.sites then raise exception 'B24P2_SITE_COUNT_AFTER: % expected %, found %', r.fn, r.sites, v_n; end if;
    if replace(v_src, '''PT409''', '''40001''') is distinct from r.pre_src then raise exception 'B24P2_CHANGE_BEYOND_THE_CODE: %', r.fn; end if;
    if pg_temp.b24_attrs(r.fn_oid) is distinct from r.attrs_md5 then raise exception 'B24P2_ATTRIBUTES_CHANGED: %', r.fn; end if;
  end loop;
  if has_function_privilege('anon', 'private.retention_ai_source_ready()', 'EXECUTE')
     or has_function_privilege('authenticated', 'private.retention_ai_source_ready()', 'EXECUTE') then
    raise exception 'B24P2_GRANTS_NOT_EXACT';
  end if;
end
$post$;

drop function pg_temp.b24_attrs(oid);
commit;
"""
    return header('B24 candidate, part 2 of 2: non-retried conflict codes in the functions INSIDE the certified closure source, with the re-binding of the certificate', p2, extra) + body


def part2_revert(rows):
    p2 = [r for r in rows if r['part'] == 2]
    sites = sum(r['sites'] for r in p2)
    extra = f"""Reverting re-introduces the endless PostgREST retry for these functions, so it exists only as the rollback the apply discipline asks for. The digest after the revert must
-- again be the value before part 2 (strict mode pins {CERTIFIED_BEFORE[:12]}...); it is re-bound to whatever the live digest is, then asserted equal to that pin."""
    body = f"""begin;
set local lock_timeout = '5s';
set local statement_timeout = '180s';
set local search_path = pg_catalog;

{part2_common_tables(p2, 'b24p2')}
do $pre$
declare
  r record; v_oid oid; v_src text; v_n integer; v_certified text; v_ready_def text;
begin
  if (select count(*) from b24p2_targets) <> {len(p2)} or (select sum(sites) from b24p2_targets) <> {sites} then
    raise exception 'B24P2R_TARGET_TABLE_INVALID' using errcode = '55000';
  end if;
  select sha256 into strict v_certified from private.closure_source_v5 where singleton;
  if v_certified is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton) then
    raise exception 'B24P2R_CERTIFIED_VALUES_DISAGREE' using errcode = '55000';
  end if;
  v_ready_def := pg_get_functiondef('private.retention_ai_source_ready()'::regprocedure);
  if (length(v_ready_def) - length(replace(v_ready_def, v_certified, ''))) <> length(v_certified)
     or (select count(*) from regexp_matches(v_ready_def, '[0-9a-f]{{64}}', 'g')) <> 1 then
    raise exception 'B24P2R_READY_BINDING_INVALID' using errcode = '55000';
  end if;
  if private.closure_source_digest_v5() is distinct from v_certified or not private.retention_ai_source_ready() then
    raise exception 'B24P2R_CLOSURE_SOURCE_NOT_READY' using errcode = '55000';
  end if;
  if exists (select 1 from private.closure_executions_v5 where state = 'EXECUTING') then
    raise exception 'B24P2R_CLOSURE_IN_FLIGHT' using errcode = '55000';
  end if;
  insert into b24p2_state(certified, ready_masked) values (v_certified,
    (select md5(regexp_replace(prosrc, '[0-9a-f]{{64}}', '<CERTIFIED>', 'g')) from pg_proc where oid = 'private.retention_ai_source_ready()'::regprocedure));
  for r in select * from b24p2_targets order by fn loop
    select count(*) into v_n from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname || '.' || p.proname = r.fn;
    if v_n <> 1 then raise exception 'B24P2R_FUNCTION_NOT_UNIQUE: % (% found)', r.fn, v_n using errcode = '55000'; end if;
    select p.oid, p.prosrc into v_oid, v_src from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname || '.' || p.proname = r.fn;
    if position('40001' in v_src) > 0 then raise exception 'B24P2R_NOT_APPLIED: %', r.fn using errcode = '55000'; end if;
    v_n := (length(v_src) - length(replace(v_src, '''PT409''', ''))) / 7;
    if v_n <> r.sites then raise exception 'B24P2R_SITE_COUNT_DRIFT: % expected % quoted PT409 sites, found %', r.fn, r.sites, v_n using errcode = '55000'; end if;
    insert into b24p2_before(fn, fn_oid, pre_src, pre_def, attrs_md5) values (r.fn, v_oid, v_src, pg_get_functiondef(v_oid), pg_temp.b24_attrs(v_oid));
  end loop;
end
$pre$;

do $convert$
declare r record; v_new text;
begin
  for r in select fn, pre_def from b24p2_before order by fn loop
    v_new := replace(r.pre_def, '''PT409''', '''40001''');
    if v_new = r.pre_def then raise exception 'B24P2R_NOTHING_TO_REVERT: %', r.fn; end if;
    execute v_new;
  end loop;
end
$convert$;

do $isolate$
declare r record; v_old text; v_new text; v_back text; v_src text;
begin
  select certified into strict v_old from b24p2_state;
  v_new := private.closure_source_digest_v5();
  if v_new is null or v_new = v_old then raise exception 'B24P2R_CHANGE_NOT_IN_THE_DIGEST'; end if;
  for r in select fn, fn_oid, pre_src, pre_def from b24p2_before order by fn loop
    execute r.pre_def;
  end loop;
  v_back := private.closure_source_digest_v5();
  if v_back is distinct from v_old then raise exception 'B24P2R_UNREVIEWED_CHANGE'; end if;
  for r in select fn, pre_def from b24p2_before order by fn loop
    execute replace(r.pre_def, '''PT409''', '''40001''');
  end loop;
  if private.closure_source_digest_v5() is distinct from v_new then raise exception 'B24P2R_DIGEST_NOT_STABLE'; end if;
  update b24p2_state set moved = v_new;
end
$isolate$;

do $rebind$
declare v_old text; v_new text; v_def text;
begin
  select certified, moved into strict v_old, v_new from b24p2_state;
  if v_new is distinct from private.closure_source_digest_v5() then raise exception 'B24P2R_DIGEST_NOT_STABLE'; end if;
  v_def := pg_get_functiondef('private.retention_ai_source_ready()'::regprocedure);
  update private.closure_source_v5 set sha256 = v_new where singleton and sha256 = v_old;
  if not found then raise exception 'B24P2R_CERTIFIED_VALUES_DISAGREE'; end if;
  update private.closure_erasure_source_v5 set sha256 = v_new where singleton and sha256 = v_old;
  if not found then raise exception 'B24P2R_CERTIFIED_VALUES_DISAGREE'; end if;
  execute replace(v_def, v_old, v_new);
end
$rebind$;

do $post$
declare r record; v_old text; v_live text; v_ready text; v_src text; v_n integer; s record;
  v_strict boolean := coalesce(nullif(current_setting('b24.preimage', true), ''), 'strict') <> 'relaxed';
begin
  select * into strict s from b24p2_state;
  v_old := s.certified;
  v_live := private.closure_source_digest_v5();
  select prosrc into strict v_ready from pg_proc where oid = 'private.retention_ai_source_ready()'::regprocedure;
  if (select sha256 from private.closure_source_v5 where singleton) is distinct from v_live
     or (select sha256 from private.closure_erasure_source_v5 where singleton) is distinct from v_live
     or position(v_old in v_ready) > 0
     or (length(v_ready) - length(replace(v_ready, v_live, ''))) <> length(v_live) then
    raise exception 'B24P2R_REBIND_INCOMPLETE';
  end if;
  if md5(regexp_replace(v_ready, '[0-9a-f]{{64}}', '<CERTIFIED>', 'g')) is distinct from s.ready_masked then
    raise exception 'B24P2R_READINESS_FUNCTION_CHANGED_BEYOND_THE_CONSTANT';
  end if;
  if v_strict and v_live is distinct from '{CERTIFIED_BEFORE}' then
    raise exception 'B24P2R_NOT_BACK_TO_THE_PRE_B24_CERTIFICATE: %', v_live;
  end if;
  if private.retention_ai_source_ready() is distinct from true then raise exception 'B24P2R_SOURCE_NOT_READY'; end if;
  if private.closure_erasure_binding_v5() is null or private.closure_erasure_binding_v5()->>'sourceSha256' is distinct from v_live then
    raise exception 'B24P2R_ERASURE_BINDING_NOT_READY';
  end if;
  for r in select t.fn, t.sites, b.fn_oid, b.pre_src, b.attrs_md5 from b24p2_targets t join b24p2_before b using (fn) order by t.fn loop
    select prosrc into strict v_src from pg_proc where oid = r.fn_oid;
    if position('PT409' in v_src) > 0 then raise exception 'B24P2R_PT409_LEFT: %', r.fn; end if;
    v_n := (length(v_src) - length(replace(v_src, '''40001''', ''))) / 7;
    if v_n <> r.sites then raise exception 'B24P2R_SITE_COUNT_AFTER: % expected %, found %', r.fn, r.sites, v_n; end if;
    if replace(v_src, '''40001''', '''PT409''') is distinct from r.pre_src then raise exception 'B24P2R_CHANGE_BEYOND_THE_CODE: %', r.fn; end if;
    if pg_temp.b24_attrs(r.fn_oid) is distinct from r.attrs_md5 then raise exception 'B24P2R_ATTRIBUTES_CHANGED: %', r.fn; end if;
  end loop;
end
$post$;

drop function pg_temp.b24_attrs(oid);
commit;
"""
    return header('B24 revert of part 2: the exact inverse, re-binding the certificate back', p2, extra) + body


def classification_md(rows):
    n_fn = len(rows)
    n_sites = sum(r['sites'] for r in rows)
    p1 = [r for r in rows if r['part'] == 1]
    p2 = [r for r in rows if r['part'] == 2]
    exp = lambda e: [r for r in rows if r['exposure'] == e]
    counts = {}
    for r in rows:
        for _, c, n in r['items']:
            counts[c] = counts.get(c, 0) + n
    out = []
    out.append('# B24 — every site that raises SQLSTATE 40001 on canonical DEV, classified (2026-09-30)\n')
    out.append('GENERATED by `supabase/proofs/b24/build_b24_candidates.py` from `supabase/proofs/b24/b24_inventory.tsv`; do not edit by hand. Source: a read-only query of `pg_proc.prosrc` on canonical DEV (ledger 212, nothing was written).\n')
    out.append('## What was counted\n')
    out.append(f'- **{n_fn} deployed functions contain {n_sites} raise sites** with the code 40001 (every site is `raise exception … using errcode = \'40001\'`; no function names `serialization_failure`, none handles the code, none uses 40P01). The repository text shows 134 such lines in 33 migrations because it also carries superseded definitions and runtime-patched bodies; the deployed bodies are what matters.')
    out.append(f'- **Exposure:** {len(exp("A")) + len(exp("A+S"))} functions are executable by `authenticated` (any signed-in person reaches them through PostgREST), {len(exp("S"))} by `service_role` only (Edge workers), {len(exp("I"))} have no direct grant (private helpers called by the others, or revoked). `anon` executes none.')
    out.append(f'- **Certificate:** {len(p2)} of the {n_fn} ({sum(r["sites"] for r in p2)} sites) are among the 76 functions hashed by `private.closure_source_digest_v5()` and form part 2 (moves the digest, needs the re-binding); {len(p1)} ({sum(r["sites"] for r in p1)} sites) are outside it and form part 1 (certificate-neutral).\n')
    out.append('## Classes (all deterministic: a retry of the same call can never succeed)\n')
    out.append('| Class | Meaning | Sites | Decision |')
    out.append('| --- | --- | ---: | --- |')
    for c in sorted(CLASS_TEXT):
        out.append(f'| {c} | {CLASS_TEXT[c]} | {counts.get(c, 0)} | PT409 |')
    out.append(f'| | **total** | **{n_sites}** | |\n')
    out.append('**No site is kept on 40001.** The owner\'s rule is to keep 40001 only where it stands for a real serialization/retry case. A real one is raised by Postgres itself (for example `could not serialize access`), never by a function body, and those are not touched. '
               'Every site here compares something the caller or a worker supplied (an expected revision, an attempt/lease/generation token, a displayed digest, an idempotency key) with the stored state, or reports that a write found nothing to write; '
               'repeating the same call re-runs the same comparison against state that has already moved on, and raises the same code again (for D5 the repeat reaches the D1/D2 check first). D6 (`MEDIA_STORAGE_UNCONFIRMED`, 4 sites) is the closest to "try again later", '
               'but the caller that may try later is the Edge media worker, and it must do so with its own delay: an immediate unbounded retry inside PostgREST is exactly the defect.\n')
    out.append('## Functions\n')
    out.append('Exposure: A authenticated, S service_role, I none (internal). Part 1 = outside the certified digest, part 2 = inside it.\n')
    out.append('| Part | Function | Exp. | Sites | Messages (class × sites) |')
    out.append('| ---: | --- | :---: | ---: | --- |')
    for r in sorted(rows, key=lambda r: (r['part'], r['fn'])):
        msgs = '; '.join(f'`{m}` ({c}' + (f' ×{n}' if n > 1 else '') + ')' for m, c, n in r['items'])
        out.append(f"| {r['part']} | `{r['fn']}` | {r['exposure']} | {r['sites']} | {msgs} |")
    out.append('')
    return '\n'.join(out) + '\n'


def outputs():
    rows = load()
    return {
        os.path.join(CAND, 'b24_nonretried_conflicts_part1.sql'): part1(rows),
        os.path.join(CAND, 'b24_nonretried_conflicts_part2_certified.sql'): part2(rows),
        os.path.join(CAND, 'b24_nonretried_conflicts_part1_revert.sql'): part1_revert(rows),
        os.path.join(CAND, 'b24_nonretried_conflicts_part2_revert.sql'): part2_revert(rows),
        os.path.join(DOCS, 'B24_SITE_CLASSIFICATION.md'): classification_md(rows),
    }


def main():
    outs = outputs()
    if '--check' in sys.argv:
        bad = 0
        for path, text in outs.items():
            disk = open(path, encoding='utf-8', newline='').read().replace('\r\n', '\n') if os.path.exists(path) else None
            if disk != text:
                print('DIFFERS', os.path.relpath(path, REPO))
                bad += 1
        print('B24 candidates match the inventory' if not bad else f'{bad} file(s) differ')
        sys.exit(1 if bad else 0)
    os.makedirs(DOCS, exist_ok=True)
    for path, text in outs.items():
        open(path, 'w', encoding='utf-8', newline='\n').write(text)
        print('wrote', os.path.relpath(path, REPO), len(text), 'bytes')


if __name__ == '__main__':
    main()
