-- Chat voice B1 DEV application candidate. NOT APPLIED. It needs the owner's explicit "primeni" AND his approval of the closure-certificate re-bind (a privacy certification of the erasure program).
-- GENERATED by supabase/proofs/chat/build_voice_b1_dev_application.py from chat_voice_b1a_feature_chain.sql and chat_voice_b1b_closure_integration.sql: do not edit by hand (`--check` fails on any difference).
-- One atomic DO statement: exact DEV predecessor pins (complete metadata and LF-normalised bodies), the EXACT proved B1-a and B1-b install fragments, the three-place re-bind computed inside the same
-- transaction, and an exact delta accounting (every old function is unchanged except the rewritten ones, exactly the reviewed new functions exist, every catalog surface is unchanged except the reviewed additions).
-- The Edge functions uskoci-account-closure-worker (the agreement-voice decoder) and uskoci-media (the voice operations) must already be deployed: until then an account whose closure meets a voice object waits, it never loses data.
do $voice_b1_application$
declare
  pin record; prior record; actual jsonb; before_surface jsonb; after_surface jsonb; expected_datasets jsonb; before_buckets jsonb; before_storage_policies jsonb;
  old_source text; new_source text; definition text; source_row jsonb; erasure_row jsonb; affected integer; rewritten oid[]; fresh oid[]; diff_keys text;
  surface_query text := $surface_query$
    select jsonb_build_object(
      'relations',(select jsonb_agg(jsonb_build_array(c.oid,c.relname,c.relnamespace,c.relowner,c.relkind,c.relacl,
        c.relrowsecurity,c.relforcerowsecurity,c.relreplident,c.relispartition,c.reloptions) order by c.oid)
        from pg_class c join pg_namespace n on n.oid=c.relnamespace
        where n.nspname in('public','private','rls_private') and c.relkind in('r','p')
          and c.oid is distinct from to_regclass('private.agreement_voice_uploads_v1')),
      'columns',(select jsonb_agg(to_jsonb(a) order by a.attrelid,a.attnum)
        from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace
        where n.nspname in('public','private','rls_private') and c.relkind in('r','p')
          and a.attnum>0 and not a.attisdropped and c.oid is distinct from to_regclass('private.agreement_voice_uploads_v1')
          and not(c.oid='public.agreement_messages'::regclass and a.attname='voice_asset_id')),
      'constraints',(select jsonb_agg(to_jsonb(x) order by x.oid)
        from pg_constraint x join pg_class c on c.oid=x.conrelid join pg_namespace n on n.oid=c.relnamespace
        where n.nspname in('public','private','rls_private') and c.oid is distinct from to_regclass('private.agreement_voice_uploads_v1')
          and not(x.conrelid='public.agreement_messages'::regclass and x.conname in('agreement_messages_body_photo_check','agreement_messages_body_media_check'))
          and not(x.conrelid='private.closure_actions_v5'::regclass and x.conname='closure_action_shape146')
          and not(x.conrelid='public.agreement_messages'::regclass and x.conname='agreement_voice_link_guard_v1' and x.contype='t')),
      'triggers',(select jsonb_agg(to_jsonb(t) order by t.oid)
        from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace
        where (n.nspname in('public','private','rls_private') or c.oid='storage.objects'::regclass) and not t.tgisinternal
          and t.tgname not in('agreement_voice_message_guard_v1','agreement_voice_link_guard_v1','agreement_voice_asset_guard_v1','agreement_voice_storage_guard_v1')),
      'policies',(select jsonb_agg(to_jsonb(p) order by schemaname,tablename,policyname) from pg_policies p
        where schemaname in('public','private','rls_private') or (schemaname='storage' and tablename='objects' and policyname is distinct from 'agreement_voice_no_client_v1')),
      'indexes',(select jsonb_agg(to_jsonb(i) order by schemaname,indexname) from pg_indexes i
        where schemaname in('public','private','rls_private') and tablename is distinct from 'agreement_voice_uploads_v1'),
      'buckets',(select jsonb_agg(to_jsonb(b) order by b.id) from storage.buckets b where b.id is distinct from 'agreement-voice')
    )
  $surface_query$;
begin
  perform set_config('lock_timeout','5s',true);
  perform set_config('statement_timeout','120s',true);
  perform set_config('search_path','pg_catalog',true);
  if current_user<>'postgres' then raise exception 'VOICE_B1_APPLICATION_OWNER_REQUIRED' using errcode='55000';end if;
  -- Hold closure writes until this atomic change commits: a check without this lock could admit a closure between the check and the certificate replacement.
  lock table private.closure_executions_v5 in share mode;
  lock table private.closure_source_v5,private.closure_erasure_source_v5,private.closure_dataset_catalog_v5 in share row exclusive mode;
  if exists(select 1 from private.closure_executions_v5 where state='EXECUTING') then
    raise exception 'VOICE_B1_APPLICATION_CLOSURE_IN_FLIGHT' using errcode='55000';end if;
  if (select count(*) from private.closure_source_v5)<>1 or (select count(*) from private.closure_erasure_source_v5)<>1 then
    raise exception 'VOICE_B1_APPLICATION_CERTIFICATE_CARDINALITY' using errcode='55000';end if;
  if to_regclass('private.agreement_voice_uploads_v1') is not null or to_regprocedure('private.agreement_voice_surface_v1()') is not null
     or to_regprocedure('public.rpc_send_agreement_voice_message_v1(uuid,uuid,integer,text,uuid)') is not null
     or exists(select 1 from storage.buckets where id='agreement-voice') then
    raise exception 'VOICE_B1_APPLICATION_ALREADY_PRESENT' using errcode='55000';end if;
  -- Exact DEV predecessor metadata: every function this change rewrites, replaces, calls or re-binds.
  for pin in select * from (values
    ('private.closure_redaction_relations_v5()','30967acfddf4a189e7d97f1230ce286b'),
    ('private.closure_redaction_scope_v5(text)','1d9ea6d4b770cb0da939e87b2218e1eb'),
    ('private.closure_redaction_patch_v5(text,jsonb,uuid,uuid)','6f2f71c85685d1c34f07c6b7eb8efc64'),
    ('private.closure_blockers_v5(uuid)','272d5ea792598448e86b127f4dc37c3c'),
    ('public.rpc_start_account_closure_execution(uuid,uuid,integer,uuid,text)','77bb6868db8bfcc02d56137e22c04dab'),
    ('private.support_reference_v5(uuid,jsonb)','1433a1360c044dc3a6d984af95c89668'),
    ('private.data_export_snapshot(uuid,uuid,jsonb,timestamptz)','3965d2c8b12ff99d3c9dc928912890f1'),
    ('private.data_export_dataset_catalog()','206096870b0fd5eae1cb2780db2e6601'),
    ('private.data_export_policy_binding()','a9596e2741a92a607cfd4cee0896604a'),
    ('private.closure_source_digest_v5()','7ade1ea4e26aa1f5a7fb8a84553b89d4'),
    ('private.closure_erasure_program_digest_v5()','3b5059bc329407eface02b5b631d709d'),
    ('public.rpc_read_agreement_messages_page_v1(uuid,uuid,integer,timestamptz,uuid)','f36e7c48b979dcfe4e166bc7580daee5'),
    ('public.rpc_read_agreement_message_window_v1(uuid,uuid,uuid,integer,integer)','1c834a8394d65bc5faf14bc329af915f'),
    ('private.retention_ai_source_ready()','60d41c1d50dbaedd8cbcd7a580fc21d2'),
    ('private.closure_erasure_binding_v5()','5b8021c77f85c119e95a41bbac2da3b1'),
    ('private.support_auth_v5(uuid)','9437ac188420363cf6e3d13f7b4b4668'),
    ('private.push_session_valid(uuid,uuid)','b69a146d12476af01fc7f89b1228f537'),
    ('private.closure_assert_open(uuid,uuid)','7b0a4e1be3205b5de509ddfc726e406a'),
    ('private.closure_account_restricted(uuid)','814dfd0286240ae2eec5a2d2a56bbe51'),
    ('private.closure_account_key(uuid)','20307d6e0d35a0c76b8e04fc12ded583'),
    -- (The two functions with a composite argument type are pinned by body only: their metadata carries a per-database type OID and cannot be portable.)
    ('private.closure_redaction_allowed_v5(oid,text,jsonb,jsonb)','e4245b6db4ef8b0d4ee8846e684f511a'),
    ('private.safety_assert_pair(uuid,uuid)','ed421d927417faba0e160fb67cde193a'),
    ('private.media_evidence_key_v5(uuid)','07aad1936c6a61aa75c8c227e4d17e93'),
    ('private.emit_event(uuid,text,text,text,uuid,integer,text,text,text,text,jsonb,timestamptz)','f42a9a9adeed0279cd446cae160746c6'),
    ('public.rpc_read_agreement_photo_messages_v5(uuid,uuid,uuid[])','0729ed9c8423d4d9db4da5b8e9d22a4c')
  ) p(signature,metadata_md5) loop
    if (select md5(((to_jsonb(p)-'oid'-'pronamespace'-'proowner'-'prolang'-'proacl'-'prosrc')
        ||jsonb_build_object('namespace',n.nspname,'owner',pg_get_userbyid(p.proowner),
          'language',l.lanname,'acl',p.proacl::text))::text)
      from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang
      where p.oid=to_regprocedure(pin.signature)) is distinct from pin.metadata_md5 then
      raise exception 'VOICE_B1_APPLICATION_METADATA_DRIFT: %',pin.signature using errcode='55000';end if;
  end loop;
  -- Exact DEV predecessor BODIES (LF-normalised). Strict: the DEV bodies of the two functions that B24 part 2 rewrote are pinned, never their pre-B24 text.
  for pin in select * from (values
    ('private.closure_redaction_relations_v5()','c6d687219096c03371560cabb961cb0e'),
    ('private.closure_redaction_scope_v5(text)','3197a4c47582823d4474027bc49b4f84'),
    ('private.closure_redaction_patch_v5(text,jsonb,uuid,uuid)','0779e304e719774679d8ffb2d7c67fd9'),
    ('private.closure_blockers_v5(uuid)','dc78d910fde458c18e25c732888fa93a'),
    ('public.rpc_start_account_closure_execution(uuid,uuid,integer,uuid,text)','4e24973f86127de890d4cb77ab1b6e14'),
    ('private.support_reference_v5(uuid,jsonb)','907b383f500a91d3cf436448b1146295'),
    ('private.data_export_snapshot(uuid,uuid,jsonb,timestamptz)','b3c4b64a4c3afc98bd7a9aa12314bea5'),
    ('private.data_export_dataset_catalog()','c3d3a109d8e765ae1ad78910c320248d'),
    ('private.data_export_policy_binding()','2dbe3d1f343c37c5b3d722c97d9bcb70'),
    ('private.closure_source_digest_v5()','d67d37e2ebc5d9f85448693c0772f663'),
    ('private.closure_erasure_program_digest_v5()','3ec8d244730415d3a047312366672375'),
    ('public.rpc_read_agreement_messages_page_v1(uuid,uuid,integer,timestamptz,uuid)','912f1c7e4df9c8c933351f45bd1fa1c5'),
    ('public.rpc_read_agreement_message_window_v1(uuid,uuid,uuid,integer,integer)','9ae403a4c1ba9130e18cdd5b3dd831f6'),
    ('private.closure_erasure_binding_v5()','d6d7e7f6f108fff45a4df5126949fa04'),
    ('private.support_auth_v5(uuid)','66773994698c60b9fab919f2a9fda93a'),
    ('private.push_session_valid(uuid,uuid)','3454eb7040f3dab3cb0c35b512b46859'),
    ('private.closure_assert_open(uuid,uuid)','dc9bc4c718593850da4fdb49e612dbd2'),
    ('private.closure_account_restricted(uuid)','f4999250c315e0253374d4611291c7ad'),
    ('private.closure_account_key(uuid)','2dde6ad2462255b188e4f03ffe88edcd'),
    ('private.closure_assert_current_v5(private.closure_executions_v5)','3833e3df6eb404a5287d8a2d960dec1c'),
    ('private.closure_erasure_assert_current_v5(private.closure_executions_v5)','be536bbccba9600ecc5c34f4a4d747de'),
    ('private.closure_redaction_allowed_v5(oid,text,jsonb,jsonb)','7fabcc71502e065e638364fc3d58b761'),
    ('private.safety_assert_pair(uuid,uuid)','211a423b263bbbebdcf5e04f3c0e1bf3'),
    ('private.media_evidence_key_v5(uuid)','e5cba7665e684dab03a61cc6640e158c'),
    ('private.emit_event(uuid,text,text,text,uuid,integer,text,text,text,text,jsonb,timestamptz)','67413effbbb3fa227397d355e0d4edfb'),
    ('public.rpc_read_agreement_photo_messages_v5(uuid,uuid,uuid[])','9c5a0868e9507b23b600863f4508a5a5')
  ) p(signature,body_md5) loop
    if (select md5(replace(prosrc,E'\r\n',E'\n')) from pg_proc where oid=to_regprocedure(pin.signature)) is distinct from pin.body_md5 then
      raise exception 'VOICE_B1_APPLICATION_BODY_DRIFT: %',pin.signature using errcode='55000';end if;
  end loop;
  -- Certificate and readiness: certified in all three places, equal to the live digest, ready, bound. (The readiness source is pinned after replacing only its one certified literal.)
  select to_jsonb(c),sha256 into source_row,old_source from private.closure_source_v5 c where singleton;
  select to_jsonb(c) into erasure_row from private.closure_erasure_source_v5 c where singleton;
  select pg_get_functiondef(p.oid) into definition from pg_proc p where oid='private.retention_ai_source_ready()'::regprocedure;
  if old_source is null or old_source is distinct from private.closure_source_digest_v5() or old_source is distinct from erasure_row->>'sha256'
     or private.retention_ai_source_ready() is distinct from true or private.closure_erasure_binding_v5()->>'sourceSha256' is distinct from old_source then
    raise exception 'VOICE_B1_APPLICATION_CLOSURE_PREDECESSOR_NOT_READY' using errcode='55000';end if;
  if not exists(select 1 from pg_proc where oid='private.retention_ai_source_ready()'::regprocedure
      and (length(prosrc)-length(replace(prosrc,old_source,'')))=length(old_source)
      and md5(replace(replace(prosrc,E'\r\n',E'\n'),old_source,'__CERTIFIED_SOURCE__'))='bc85a1a744869abb6441e647b18b2195') then
    raise exception 'VOICE_B1_APPLICATION_READINESS_PREDECESSOR_DRIFT' using errcode='55000';end if;
  if (length(definition)-length(replace(definition,old_source,'')))<>length(old_source)
     or (select count(*) from regexp_matches(definition,'[0-9a-f]{64}','g'))<>1 then
    raise exception 'VOICE_B1_APPLICATION_READINESS_LITERAL_DRIFT' using errcode='55000';end if;
  execute surface_query into before_surface;
  create temporary table voice_b1_application_functions on commit drop as
    select p.oid,p.oid::regprocedure::text signature,to_jsonb(p) metadata
    from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    where n.nspname in('public','private','rls_private');
  select jsonb_agg(case when c.data_class='MEDIA_OBJECTS' then
    jsonb_set(to_jsonb(c),'{relations}',to_jsonb(c.relations||array['private.agreement_voice_uploads_v1']))
    else to_jsonb(c) end order by data_class) into expected_datasets from private.closure_dataset_catalog_v5 c;
  select jsonb_agg(to_jsonb(b) order by b.id) into before_buckets from storage.buckets b;
  select jsonb_agg(to_jsonb(p) order by policyname) into before_storage_policies from pg_policies p where schemaname='storage' and tablename='objects';
  rewritten:=array[to_regprocedure('private.closure_redaction_relations_v5()'),to_regprocedure('private.closure_redaction_scope_v5(text)'),
    to_regprocedure('private.closure_redaction_patch_v5(text,jsonb,uuid,uuid)'),to_regprocedure('private.closure_blockers_v5(uuid)'),
    to_regprocedure('public.rpc_start_account_closure_execution(uuid,uuid,integer,uuid,text)'),to_regprocedure('private.support_reference_v5(uuid,jsonb)'),
    to_regprocedure('private.data_export_snapshot(uuid,uuid,jsonb,timestamptz)'),to_regprocedure('private.data_export_dataset_catalog()'),
    to_regprocedure('private.data_export_policy_binding()'),to_regprocedure('private.closure_source_digest_v5()'),to_regprocedure('private.closure_erasure_program_digest_v5()'),
    to_regprocedure('public.rpc_read_agreement_messages_page_v1(uuid,uuid,integer,timestamptz,uuid)'),to_regprocedure('public.rpc_read_agreement_message_window_v1(uuid,uuid,uuid,integer,integer)')]::oid[];
  if cardinality(rewritten)<>13 or array_position(rewritten,null) is not null then raise exception 'VOICE_B1_APPLICATION_REWRITTEN_ROSTER' using errcode='55000';end if;

  -- BEGIN EXACT PROVED INSTALL FRAGMENTS (the BEGIN and COMMIT of each file are the only text not embedded).
  execute $voice_b1a_install$
set local lock_timeout = '5s';
set local statement_timeout = '60s';
set local search_path = pg_catalog;

create temporary table voice_b1a_before(digest text, ready boolean) on commit drop;
do $pre$
declare pin record; s text;
begin
  if to_regclass('private.agreement_voice_uploads_v1') is not null
     or exists(select 1 from pg_attribute where attrelid = 'public.agreement_messages'::regclass and attname = 'voice_asset_id' and not attisdropped)
     or to_regprocedure('public.rpc_send_agreement_voice_message_v1(uuid,uuid,integer,text,uuid)') is not null
     or to_regprocedure('public.rpc_read_agreement_messages_page_v2(uuid,uuid,integer,timestamptz,uuid)') is not null
     or exists(select 1 from storage.buckets where id = 'agreement-voice') then
    raise exception 'VOICE_B1A_ALREADY_APPLIED' using errcode = '55000';
  end if;
  for pin in select * from (values
    ('public.rpc_read_agreement_messages_page_v1(uuid,uuid,integer,timestamptz,uuid)', '912f1c7e4df9c8c933351f45bd1fa1c5'),
    ('public.rpc_read_agreement_message_window_v1(uuid,uuid,uuid,integer,integer)', '9ae403a4c1ba9130e18cdd5b3dd831f6')
  ) p(signature, body_md5) loop
    if (select md5(replace(prosrc, E'\r\n', E'\n')) from pg_proc where oid = to_regprocedure(pin.signature)) is distinct from pin.body_md5 then
      raise exception 'VOICE_B1A_PREDECESSOR_DRIFT: %', pin.signature using errcode = '55000';
    end if;
  end loop;
  -- Functions and tables this file only calls or reads must exist (their bodies are not patched here).
  for pin in select * from (values
    ('private.support_auth_v5(uuid)'), ('private.closure_assert_open(uuid,uuid)'), ('private.safety_assert_pair(uuid,uuid)'),
    ('private.push_session_valid(uuid,uuid)'), ('private.media_evidence_key_v5(uuid)'), ('private.closure_account_key(uuid)'),
    ('private.closure_assert_current_v5(private.closure_executions_v5)'), ('public.rpc_read_agreement_photo_messages_v5(uuid,uuid,uuid[])'),
    ('private.closure_redaction_allowed_v5(oid,text,jsonb,jsonb)')
  ) p(signature) loop
    if to_regprocedure(pin.signature) is null then raise exception 'VOICE_B1A_PREDECESSOR_MISSING: %', pin.signature using errcode = '55000'; end if;
  end loop;
  if to_regclass('private.closure_actions_v5') is null or to_regclass('private.retention_holds') is null
     or not exists(select 1 from storage.buckets where id = 'profile-media' and public = false) then
    raise exception 'VOICE_B1A_PREDECESSOR_MISSING: tables or bucket' using errcode = '55000';
  end if;
  if not exists(select 1 from pg_constraint where conrelid = 'public.agreement_messages'::regclass and conname = 'agreement_messages_body_photo_check') then
    raise exception 'VOICE_B1A_PREDECESSOR_DRIFT: agreement_messages_body_photo_check' using errcode = '55000';
  end if;
  s := private.closure_source_digest_v5();
  insert into voice_b1a_before values (s, private.retention_ai_source_ready());
end
$pre$;

-- 1. The private upload lifecycle: a clone of the photo table with audio columns. No foreign key, no client privilege, forced RLS.
create table private.agreement_voice_uploads_v1(
  id uuid primary key default gen_random_uuid(),
  account_id uuid not null,
  agreement_id uuid not null,
  agreement_version integer not null check(agreement_version > 0),
  client_request_id uuid not null,
  attempt_id uuid not null default gen_random_uuid(),
  state text not null check(state in ('PROCESSING','STAGED','READY','FAILED','CANCELLED')),
  input_sha256 text check(input_sha256 ~ '^[a-f0-9]{64}$'),
  input_bytes integer check(input_bytes between 1 and 4194304),
  input_type text check(input_type = 'audio/mp4'),
  admitted_at timestamptz,
  created_at timestamptz not null default clock_timestamp(),
  cancelled_at timestamptz,
  validated_sha256 text check(validated_sha256 ~ '^[a-f0-9]{64}$'),
  storage_path text unique,
  byte_size integer check(byte_size between 1 and 4194304),
  duration_ms integer check(duration_ms between 300 and 300000),
  dispatch_state text not null default 'NOT_DISPATCHED' check(dispatch_state in ('NOT_DISPATCHED','DISPATCHING','SETTLED')),
  dispatch_outcome text check(dispatch_outcome in ('STORED','REJECTED')),
  attached_message_id uuid,
  unique(account_id, client_request_id),
  check((input_sha256 is null and input_bytes is null and input_type is null and admitted_at is null and state = 'CANCELLED')
    or (input_sha256 is not null and input_bytes is not null and input_type is not null and admitted_at is not null)),
  check((storage_path is null and validated_sha256 is null and byte_size is null and duration_ms is null)
    or (storage_path is not null and storage_path = account_id::text || '/agreement-voice-v1/' || id::text || '/' || validated_sha256 || '.m4a'
        and validated_sha256 is not null and byte_size is not null and duration_ms is not null)),
  check((dispatch_state = 'SETTLED') = (dispatch_outcome is not null)),
  check(dispatch_state = 'NOT_DISPATCHED' or storage_path is not null),
  check(state not in ('STAGED','READY') or storage_path is not null),
  check(state <> 'READY' or (dispatch_state = 'SETTLED' and dispatch_outcome = 'STORED')),
  check((state = 'CANCELLED') = (cancelled_at is not null)),
  check(attached_message_id is null or state = 'READY')
);
create index agreement_voice_owner_v1 on private.agreement_voice_uploads_v1(account_id, agreement_id, created_at desc);
create index agreement_voice_rate_v1 on private.agreement_voice_uploads_v1(account_id, admitted_at) where admitted_at is not null;
alter table private.agreement_voice_uploads_v1 enable row level security;
alter table private.agreement_voice_uploads_v1 force row level security;
revoke all on private.agreement_voice_uploads_v1 from public, anon, authenticated, service_role;

-- 2. The message binding: one nullable voice asset, exclusive with a body and with photos.
alter table public.agreement_messages add column voice_asset_id uuid;
alter table public.agreement_messages drop constraint agreement_messages_body_photo_check;
alter table public.agreement_messages add constraint agreement_messages_body_media_check check(
  char_length(btrim(body)) <= 2000 and cardinality(photo_asset_ids) between 0 and 6
  and ((voice_asset_id is null and (char_length(btrim(body)) >= 1 or cardinality(photo_asset_ids) >= 1))
    or (voice_asset_id is not null and btrim(body) = '' and cardinality(photo_asset_ids) = 0)));

-- 3. The private bucket: no client policy of any kind (a restrictive policy keeps it so whatever permissive policy exists or is added).
insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('agreement-voice', 'agreement-voice', false, 4194304, array['audio/mp4']);
create policy agreement_voice_no_client_v1 on storage.objects as restrictive for all to authenticated
  using(bucket_id <> 'agreement-voice') with check(bucket_id <> 'agreement-voice');

create function private.agreement_voice_key_v1(a uuid) returns bigint language sql immutable strict set search_path = pg_catalog as $f$
  select hashtextextended('uskoci:agreement-voice:' || a::text, 1);$f$;
-- Participant gate. A POSITIVE membership test: the photo gate uses NOT IN, which passes when a participant is NULL.
create function private.agreement_voice_context_v1(a uuid, g uuid, v integer, writing boolean) returns public.agreements
  language plpgsql security definer set search_path = pg_catalog as $f$
declare ag public.agreements;
begin
  select * into ag from public.agreements where id = g;
  if not found or (a is distinct from ag.requester_account_id and a is distinct from ag.worker_account_id) then
    raise exception 'MEDIA_NOT_FOUND' using errcode = '42501';
  end if;
  if writing then
    perform private.closure_assert_open(ag.requester_account_id, ag.worker_account_id);
    perform pg_advisory_xact_lock(private.agreement_voice_key_v1(a));
    select * into ag from public.agreements where id = g for share;
    perform private.safety_assert_pair(ag.requester_account_id, ag.worker_account_id);
    if ag.status not in ('CONFIRMED','SUPERSEDED') then raise exception 'MEDIA_NOT_EDITABLE' using errcode = '42501'; end if;
    if v is null or v <> ag.current_version then raise exception 'MEDIA_VERSION_CONFLICT' using errcode = 'PT409'; end if;
    if not exists(select 1 from public.agreement_versions where agreement_id = g and version = v and status in ('CONFIRMED','SUPERSEDED')) then
      raise exception 'MEDIA_NOT_EDITABLE' using errcode = '42501';
    end if;
  end if;
  return ag;
end $f$;

create function private.agreement_voice_document_v1(a private.agreement_voice_uploads_v1) returns jsonb language sql stable set search_path = pg_catalog as $f$
  select jsonb_build_object('accountId', a.account_id, 'agreementId', a.agreement_id, 'agreementVersion', a.agreement_version, 'clientRequestId', a.client_request_id,
    'assetId', a.id, 'state', a.state, 'attachedMessageId', a.attached_message_id,
    'voice', case when a.state = 'READY' then jsonb_build_object('assetId', a.id, 'durationMs', a.duration_ms, 'byteSize', a.byte_size, 'contentType', 'audio/mp4') else null end,
    'authoritative', true);$f$;
create function private.agreement_voice_transfer_v1(a private.agreement_voice_uploads_v1) returns jsonb language sql stable set search_path = pg_catalog as $f$
  select jsonb_build_object('receipt', private.agreement_voice_document_v1(a), 'attemptId', a.attempt_id, 'path', a.storage_path, 'sha256', a.validated_sha256,
    'byteSize', a.byte_size, 'durationMs', a.duration_ms, 'dispatchState', a.dispatch_state, 'dispatchOutcome', a.dispatch_outcome);$f$;

-- 4. Guards. The message guard covers BOTH insert and update of a voice row (the photo guard returns early for a row without photos).
create function private.agreement_voice_message_guard_v1() returns trigger language plpgsql security definer set search_path = pg_catalog as $f$
declare a private.agreement_voice_uploads_v1;
begin
  -- The account-closure erasure certificate (one locked row, one fixed patch, inside the service-owned SQL transaction) is the only way past this guard.
  if auth.role() = 'service_role' then
    if tg_op in ('UPDATE', 'DELETE') and private.closure_redaction_allowed_v5(tg_relid, tg_op, to_jsonb(old), case when tg_op = 'UPDATE' then to_jsonb(new) else null end) then
      if tg_op = 'DELETE' then return old; end if;
      return new;
    end if;
  end if;
  if tg_op = 'UPDATE' then
    if old.voice_asset_id is distinct from new.voice_asset_id
       or (old.voice_asset_id is not null and (new.id, new.agreement_id, new.agreement_version, new.sender_account_id, new.client_message_id, new.body, new.photo_asset_ids)
           is distinct from (old.id, old.agreement_id, old.agreement_version, old.sender_account_id, old.client_message_id, old.body, old.photo_asset_ids)) then
      raise exception 'MEDIA_MESSAGE_IMMUTABLE' using errcode = '55000';
    end if;
    return new;
  end if;
  if new.voice_asset_id is null then return new; end if;
  if auth.uid() is distinct from new.sender_account_id or new.client_message_id is null or btrim(new.body) <> '' or cardinality(new.photo_asset_ids) <> 0 then
    raise exception 'MEDIA_INPUT_INVALID' using errcode = '22023';
  end if;
  perform private.agreement_voice_context_v1(new.sender_account_id, new.agreement_id, new.agreement_version, true);
  select * into a from private.agreement_voice_uploads_v1 where id = new.voice_asset_id for update;
  if not found or a.account_id <> new.sender_account_id or a.agreement_id <> new.agreement_id or a.agreement_version <> new.agreement_version
     or a.state <> 'READY' or a.attached_message_id is not null then
    raise exception 'MEDIA_NOT_EDITABLE' using errcode = '42501';
  end if;
  return new;
end $f$;
create trigger agreement_voice_message_guard_v1 before insert or update on public.agreement_messages
  for each row execute function private.agreement_voice_message_guard_v1();
create function private.agreement_voice_link_guard_v1() returns trigger language plpgsql security definer set search_path = pg_catalog as $f$
begin
  if new.voice_asset_id is not null and not exists(select 1 from private.agreement_voice_uploads_v1 a
      where a.id = new.voice_asset_id and a.attached_message_id = new.id and a.account_id = new.sender_account_id
        and a.agreement_id = new.agreement_id and a.agreement_version = new.agreement_version and a.state = 'READY') then
    raise exception 'MEDIA_MESSAGE_LINK_INCOMPLETE' using errcode = '55000';
  end if;
  return new;
end $f$;
create constraint trigger agreement_voice_link_guard_v1 after insert on public.agreement_messages
  deferrable initially deferred for each row execute function private.agreement_voice_link_guard_v1();
create function private.agreement_voice_asset_guard_v1() returns trigger language plpgsql security definer set search_path = pg_catalog as $f$
begin
  -- The account-closure erasure certificate (one locked row, one fixed patch, inside the service-owned SQL transaction) is the only way past this guard.
  if auth.role() = 'service_role' then
    if tg_op in ('UPDATE', 'DELETE') and private.closure_redaction_allowed_v5(tg_relid, tg_op, to_jsonb(old), case when tg_op = 'UPDATE' then to_jsonb(new) else null end) then
      if tg_op = 'DELETE' then return old; end if;
      return new;
    end if;
  end if;
  perform pg_advisory_xact_lock(private.media_evidence_key_v5(old.account_id));
  if tg_op = 'DELETE' then raise exception 'MEDIA_ASSET_IMMUTABLE' using errcode = '55000'; end if;
  if (new.id, new.account_id, new.agreement_id, new.agreement_version, new.client_request_id, new.attempt_id, new.input_sha256, new.input_bytes, new.input_type, new.admitted_at, new.created_at)
     is distinct from (old.id, old.account_id, old.agreement_id, old.agreement_version, old.client_request_id, old.attempt_id, old.input_sha256, old.input_bytes, old.input_type, old.admitted_at, old.created_at)
     or (old.storage_path is not null and (new.storage_path, new.validated_sha256, new.byte_size, new.duration_ms) is distinct from (old.storage_path, old.validated_sha256, old.byte_size, old.duration_ms))
     or (old.attached_message_id is not null and (new.attached_message_id, new.state) is distinct from (old.attached_message_id, old.state))
     or (old.cancelled_at is not null and (new.cancelled_at, new.state) is distinct from (old.cancelled_at, old.state))
     or (old.dispatch_state = 'SETTLED' and (new.dispatch_state, new.dispatch_outcome) is distinct from (old.dispatch_state, old.dispatch_outcome))
     or (old.dispatch_state = 'DISPATCHING' and new.dispatch_state = 'NOT_DISPATCHED')
     or (old.state = 'FAILED' and new.state not in ('FAILED','CANCELLED'))
     or (old.state = 'READY' and new.state not in ('READY','CANCELLED'))
     or (old.state = 'STAGED' and new.state = 'PROCESSING') then
    raise exception 'MEDIA_ASSET_IMMUTABLE' using errcode = '55000';
  end if;
  if new.attached_message_id is not null and not exists(select 1 from public.agreement_messages m where m.id = new.attached_message_id
      and m.sender_account_id = new.account_id and m.agreement_id = new.agreement_id and m.agreement_version = new.agreement_version and m.voice_asset_id = new.id) then
    raise exception 'MEDIA_MESSAGE_LINK_INCOMPLETE' using errcode = '55000';
  end if;
  return new;
end $f$;
create trigger agreement_voice_asset_guard_v1 before update or delete on private.agreement_voice_uploads_v1
  for each row execute function private.agreement_voice_asset_guard_v1();
-- An object of this bucket is immutable while the account is open; it can go only under an EXECUTING closure generation with a DISPATCHED exact-object action.
create function private.agreement_voice_storage_guard_v1() returns trigger language plpgsql security definer set search_path = pg_catalog as $f$
declare a private.agreement_voice_uploads_v1; e private.closure_executions_v5;
begin
  if old.bucket_id <> 'agreement-voice' then return case when tg_op = 'DELETE' then old else new end; end if;
  select * into a from private.agreement_voice_uploads_v1 where storage_path = old.name;
  if not found then raise exception 'MEDIA_ASSET_IMMUTABLE' using errcode = '55000'; end if;
  if tg_op = 'UPDATE' then
    if (to_jsonb(new) - array['last_accessed_at']) is distinct from (to_jsonb(old) - array['last_accessed_at']) then
      raise exception 'MEDIA_ASSET_IMMUTABLE' using errcode = '55000';
    end if;
    return new;
  end if;
  perform pg_advisory_xact_lock_shared(private.closure_account_key(a.account_id));
  select x.* into e from private.closure_executions_v5 x join private.closure_actions_v5 c on c.generation = x.generation and c.account_id = x.account_id
    where x.account_id = a.account_id and x.state = 'EXECUTING' and c.kind = 'STORAGE_DELETE' and c.state = 'DISPATCHED' and c.bucket = old.bucket_id and c.object_path = old.name;
  if not found then raise exception 'MEDIA_ASSET_IMMUTABLE' using errcode = '55000'; end if;
  perform private.closure_assert_current_v5(e);
  perform pg_advisory_xact_lock(private.media_evidence_key_v5(a.account_id));
  -- Only an account-wide hold refuses (it is also a hard closure blocker); a hold scoped to one AI conversation never protects a voice object.
  if exists(select 1 from private.retention_holds where account_id = a.account_id and active and conversation_id is null) then
    raise exception 'MEDIA_EVIDENCE_POLICY_NOT_READY' using errcode = '55000';
  end if;
  return old;
end $f$;
create trigger agreement_voice_storage_guard_v1 before update or delete on storage.objects
  for each row execute function private.agreement_voice_storage_guard_v1();

-- 5. Send. The same sender-global message key and lock as every writer; the message, the attachment and the event commit atomically.
create function public.rpc_send_agreement_voice_message_v1(p_expected_user_id uuid, p_agreement_id uuid, p_expected_version integer, p_client_message_id text, p_asset_id uuid)
  returns jsonb language plpgsql security definer set search_path = pg_catalog as $f$
declare u uuid := private.support_auth_v5(p_expected_user_id); ag public.agreements; m public.agreement_messages;
begin
  if p_client_message_id is null or p_client_message_id !~ '^[A-Za-z0-9][A-Za-z0-9_.:-]{7,199}$' or p_expected_version is null or p_expected_version < 1 or p_asset_id is null then
    raise exception 'MEDIA_INPUT_INVALID' using errcode = '22023';
  end if;
  ag := private.agreement_voice_context_v1(u, p_agreement_id, null, false);
  perform private.closure_assert_open(ag.requester_account_id, ag.worker_account_id);
  perform pg_advisory_xact_lock(private.agreement_voice_key_v1(u));
  perform pg_advisory_xact_lock(hashtextextended('uskoci:message:' || u::text || ':' || p_client_message_id, 0));
  select * into ag from public.agreements where id = p_agreement_id for share;
  select * into m from public.agreement_messages where sender_account_id = u and client_message_id = p_client_message_id;
  if found then
    if m.agreement_id <> p_agreement_id or m.agreement_version <> p_expected_version or m.voice_asset_id is distinct from p_asset_id
       or btrim(m.body) <> '' or cardinality(m.photo_asset_ids) <> 0 then
      raise exception 'MEDIA_COMMAND_CONFLICT' using errcode = 'PT409';
    end if;
  else
    perform private.agreement_voice_context_v1(u, p_agreement_id, p_expected_version, true);
    insert into public.agreement_messages(agreement_id, agreement_version, sender_account_id, client_message_id, body, voice_asset_id)
      values (p_agreement_id, p_expected_version, u, p_client_message_id, '', p_asset_id) returning * into m;
    update private.agreement_voice_uploads_v1 set attached_message_id = m.id where id = p_asset_id;
    perform private.emit_event(case when u = ag.requester_account_id then ag.worker_account_id else ag.requester_account_id end,
      case when u = ag.requester_account_id then 'WORKER' else 'REQUESTER' end, 'MESSAGE_RECEIVED', 'AGREEMENT', ag.id, p_expected_version,
      'Nova poruka', 'Imate novu poruku u Dogovoru.', 'agreement_message:' || m.id::text, 'NORMAL', jsonb_build_object('message_id', m.id));
  end if;
  perform private.support_auth_v5(u);
  return jsonb_build_object('messageId', m.id, 'agreementId', m.agreement_id, 'agreementVersion', m.agreement_version,
    'clientMessageId', m.client_message_id, 'voiceAssetId', m.voice_asset_id);
end $f$;

-- 6. Playback authorization (service role). The Edge function fetches the bytes with the service key after this answer; no URL is ever produced.
create function public.rpc_agreement_voice_read_service_v1(p_account_id uuid, p_session_id uuid, p_agreement_id uuid, p_asset_id uuid, p_message_id uuid)
  returns jsonb language plpgsql security definer set search_path = pg_catalog as $f$
declare a private.agreement_voice_uploads_v1;
begin
  if auth.role() is distinct from 'service_role' then raise exception 'SERVICE_ROLE_REQUIRED' using errcode = '42501'; end if;
  if not private.push_session_valid(p_account_id, p_session_id) then raise exception 'AUTH_REQUIRED' using errcode = '28000'; end if;
  perform private.agreement_voice_context_v1(p_account_id, p_agreement_id, null, false);
  select * into a from private.agreement_voice_uploads_v1 where id = p_asset_id and agreement_id = p_agreement_id and state = 'READY';
  if not found or (p_message_id is null and (a.account_id <> p_account_id or a.attached_message_id is not null))
     or (p_message_id is not null and not exists(select 1 from public.agreement_messages m where m.id = p_message_id and m.agreement_id = p_agreement_id
         and m.agreement_version = a.agreement_version and a.attached_message_id = m.id and m.voice_asset_id = a.id)) then
    raise exception 'MEDIA_NOT_FOUND' using errcode = '42501';
  end if;
  return jsonb_build_object('assetId', a.id, 'agreementId', a.agreement_id, 'messageId', p_message_id, 'bucket', 'agreement-voice', 'path', a.storage_path,
    'sha256', a.validated_sha256, 'contentType', 'audio/mp4', 'byteSize', a.byte_size, 'durationMs', a.duration_ms, 'authoritative', true);
end $f$;

-- 7. The upload protocol (service role only). Only a positive exact settlement bypasses the session and closure gates, and it can never attach a message.
create function public.rpc_agreement_voice_upload_service_v1(p_account_id uuid, p_session_id uuid, p_operation text, p_agreement_id uuid, p_version integer, p_key uuid, p_input jsonb)
  returns jsonb language plpgsql security definer set search_path = pg_catalog as $f$
declare a private.agreement_voice_uploads_v1; ag public.agreements; v jsonb := coalesce(p_input, '{}'); acquired boolean := false; items jsonb;
begin
  if auth.role() is distinct from 'service_role' then raise exception 'SERVICE_ROLE_REQUIRED' using errcode = '42501'; end if;
  if p_account_id is null or p_agreement_id is null or jsonb_typeof(v) <> 'object' or p_operation is null
     or p_operation not in ('CLAIM','READ','CANCEL','LIST','STAGE','DISPATCH','SETTLE','FAIL') then
    raise exception 'MEDIA_INPUT_INVALID' using errcode = '22023';
  end if;
  if p_operation <> 'SETTLE' and not private.push_session_valid(p_account_id, p_session_id) then raise exception 'AUTH_REQUIRED' using errcode = '28000'; end if;
  if p_operation = 'LIST' then
    if v <> '{}' then raise exception 'MEDIA_INPUT_INVALID' using errcode = '22023'; end if;
    perform private.agreement_voice_context_v1(p_account_id, p_agreement_id, null, false);
    select coalesce(jsonb_agg(private.agreement_voice_document_v1(x) order by x.created_at desc), '[]') into items
      from (select * from private.agreement_voice_uploads_v1 where account_id = p_account_id and agreement_id = p_agreement_id
              and state not in ('FAILED','CANCELLED') and attached_message_id is null order by created_at desc limit 20) x;
    return jsonb_build_object('accountId', p_account_id, 'agreementId', p_agreement_id, 'uploads', items, 'authoritative', true);
  end if;
  if p_key is null or p_version is null or p_version < 1 then raise exception 'MEDIA_INPUT_INVALID' using errcode = '22023'; end if;
  if p_operation in ('CLAIM','STAGE','DISPATCH') then
    ag := private.agreement_voice_context_v1(p_account_id, p_agreement_id, p_version, true);
  elsif p_operation <> 'SETTLE' then
    perform private.agreement_voice_context_v1(p_account_id, p_agreement_id, null, false);
  end if;
  perform pg_advisory_xact_lock(private.agreement_voice_key_v1(p_account_id));
  select * into a from private.agreement_voice_uploads_v1 where account_id = p_account_id and client_request_id = p_key for update;
  if found and (a.agreement_id <> p_agreement_id or a.agreement_version <> p_version) then raise exception 'MEDIA_COMMAND_CONFLICT' using errcode = 'PT409'; end if;
  if p_operation in ('READ','CANCEL','DISPATCH','FAIL') and v <> '{}' then raise exception 'MEDIA_INPUT_INVALID' using errcode = '22023'; end if;
  if p_operation = 'READ' then
    if a.id is null then
      return jsonb_build_object('receipt', jsonb_build_object('accountId', p_account_id, 'agreementId', p_agreement_id, 'agreementVersion', p_version, 'clientRequestId', p_key,
        'assetId', null, 'state', 'ABSENT', 'attachedMessageId', null, 'voice', null, 'authoritative', true));
    end if;
  elsif p_operation = 'CANCEL' then
    if a.id is null then
      insert into private.agreement_voice_uploads_v1(account_id, agreement_id, agreement_version, client_request_id, state, cancelled_at)
        values (p_account_id, p_agreement_id, p_version, p_key, 'CANCELLED', clock_timestamp()) returning * into a;
    elsif a.attached_message_id is null and a.state <> 'CANCELLED' then
      update private.agreement_voice_uploads_v1 set state = 'CANCELLED', cancelled_at = clock_timestamp() where id = a.id returning * into a;
    end if;
  elsif p_operation = 'CLAIM' then
    if v - array['sha256','byteSize','contentType'] <> '{}' or not (v ?& array['sha256','byteSize','contentType'])
       or jsonb_typeof(v->'sha256') <> 'string' or coalesce(v->>'sha256', '') !~ '^[a-f0-9]{64}$'
       or jsonb_typeof(v->'byteSize') <> 'number' or (v->>'byteSize') !~ '^[1-9][0-9]{0,7}$' or (v->>'byteSize')::integer > 4194304
       or jsonb_typeof(v->'contentType') <> 'string' or v->>'contentType' <> 'audio/mp4' then
      raise exception 'MEDIA_INPUT_INVALID' using errcode = '22023';
    end if;
    if a.id is not null then
      if a.state <> 'CANCELLED' and (a.input_sha256 <> v->>'sha256' or a.input_bytes <> (v->>'byteSize')::integer or a.input_type <> v->>'contentType') then
        raise exception 'MEDIA_COMMAND_CONFLICT' using errcode = 'PT409';
      end if;
    else
      if (select count(*) from private.agreement_voice_uploads_v1 where account_id = p_account_id and admitted_at > clock_timestamp() - interval '24 hours') >= 60
         or (select count(*) from private.agreement_voice_uploads_v1 where account_id = p_account_id and admitted_at > clock_timestamp() - interval '1 minute') >= 6 then
        raise exception 'MEDIA_RATE_LIMITED' using errcode = '54000';
      end if;
      insert into private.agreement_voice_uploads_v1(account_id, agreement_id, agreement_version, client_request_id, state, input_sha256, input_bytes, input_type, admitted_at)
        values (p_account_id, p_agreement_id, p_version, p_key, 'PROCESSING', v->>'sha256', (v->>'byteSize')::integer, v->>'contentType', clock_timestamp()) returning * into a;
      acquired := true;
    end if;
  elsif a.id is null then raise exception 'MEDIA_NOT_FOUND' using errcode = '42501';
  elsif p_operation = 'STAGE' then
    -- No transformation is made in V1: the validated bytes ARE the input bytes, so the staged hash and size must equal the claimed ones.
    if v - array['attemptId','sha256','byteSize','durationMs'] <> '{}' or not (v ?& array['attemptId','sha256','byteSize','durationMs'])
       or jsonb_typeof(v->'attemptId') <> 'string' or v->>'attemptId' is distinct from a.attempt_id::text
       or jsonb_typeof(v->'sha256') <> 'string' or coalesce(v->>'sha256', '') !~ '^[a-f0-9]{64}$'
       or exists(select 1 from unnest(array['byteSize','durationMs']) k where jsonb_typeof(v->k) <> 'number' or (v->>k) !~ '^[1-9][0-9]{0,7}$')
       or (v->>'byteSize')::integer > 4194304 or (v->>'durationMs')::integer not between 300 and 300000
       or (a.input_sha256 is not null and (v->>'sha256' is distinct from a.input_sha256 or (v->>'byteSize')::integer is distinct from a.input_bytes)) then
      raise exception 'MEDIA_INPUT_INVALID' using errcode = '22023';
    end if;
    if a.state = 'PROCESSING' then
      update private.agreement_voice_uploads_v1 set state = 'STAGED', validated_sha256 = v->>'sha256',
        storage_path = p_account_id::text || '/agreement-voice-v1/' || a.id::text || '/' || (v->>'sha256') || '.m4a',
        byte_size = (v->>'byteSize')::integer, duration_ms = (v->>'durationMs')::integer where id = a.id returning * into a;
    elsif a.state <> 'CANCELLED' and (a.validated_sha256 is distinct from v->>'sha256' or a.byte_size is distinct from (v->>'byteSize')::integer
        or a.duration_ms is distinct from (v->>'durationMs')::integer) then
      raise exception 'MEDIA_COMMAND_CONFLICT' using errcode = 'PT409';
    end if;
  elsif p_operation = 'DISPATCH' then
    if a.state = 'STAGED' and a.dispatch_state = 'NOT_DISPATCHED' then
      update private.agreement_voice_uploads_v1 set dispatch_state = 'DISPATCHING' where id = a.id returning * into a; acquired := true;
    end if;
  elsif p_operation = 'SETTLE' then
    if v - array['sha256','outcome'] <> '{}' or not (v ?& array['sha256','outcome']) or jsonb_typeof(v->'sha256') <> 'string'
       or v->>'sha256' is distinct from a.validated_sha256 or v->>'outcome' not in ('STORED','REJECTED') or jsonb_typeof(v->'outcome') <> 'string'
       or a.dispatch_state = 'NOT_DISPATCHED' then
      raise exception 'MEDIA_INPUT_INVALID' using errcode = '22023';
    end if;
    if a.dispatch_state = 'SETTLED' and a.dispatch_outcome <> v->>'outcome' then raise exception 'MEDIA_COMMAND_CONFLICT' using errcode = 'PT409'; end if;
    update private.agreement_voice_uploads_v1 set dispatch_state = 'SETTLED', dispatch_outcome = v->>'outcome',
      state = case when state = 'CANCELLED' then state when v->>'outcome' = 'STORED' then 'READY' else 'FAILED' end where id = a.id returning * into a;
  elsif p_operation = 'FAIL' then
    if a.state = 'PROCESSING' then update private.agreement_voice_uploads_v1 set state = 'FAILED' where id = a.id returning * into a; end if;
  end if;
  return private.agreement_voice_transfer_v1(a) || jsonb_build_object('acquired', acquired);
end $f$;

-- 8. Versioned history reads. V2 adds kind VOICE and a voice object; V1 keeps serving builds that only know TEXT and PHOTO.
create function public.rpc_read_agreement_messages_page_v2(p_expected_user_id uuid, p_agreement_id uuid, p_limit integer default 50,
  p_before_created_at timestamptz default null, p_before_id uuid default null)
returns jsonb language plpgsql security definer set search_path = pg_catalog as $page$
declare
  u uuid := private.support_auth_v5(p_expected_user_id); ag public.agreements;
  selected jsonb; page_rows jsonb; photo_rows jsonb; messages jsonb;
  ids uuid[]; older jsonb := null; has_older boolean;
begin
  ag := private.agreement_voice_context_v1(u, p_agreement_id, null, false);
  if p_limit is null or p_limit not between 1 and 50
     or (p_before_created_at is null) <> (p_before_id is null)
     or (p_before_created_at is not null and not isfinite(p_before_created_at)) then
    raise exception 'CHAT_CURSOR_INVALID' using errcode = '22023';
  end if;
  if p_before_id is not null and not exists(select 1 from public.agreement_messages m
      where m.agreement_id = p_agreement_id and m.id = p_before_id and m.created_at = p_before_created_at) then
    raise exception 'CHAT_CURSOR_INVALID' using errcode = '22023';
  end if;
  select coalesce(jsonb_agg(jsonb_build_object(
      'messageId', m.id, 'agreementVersion', m.agreement_version, 'senderAccountId', m.sender_account_id,
      'clientMessageId', m.client_message_id, 'body', m.body, 'createdAt', m.created_at,
      'kind', case when m.voice_asset_id is not null then 'VOICE' when cardinality(m.photo_asset_ids) > 0 then 'PHOTO' else 'TEXT' end,
      'mine', m.sender_account_id = u,
      'voice', (select jsonb_build_object('assetId', a.id, 'durationMs', a.duration_ms, 'byteSize', a.byte_size, 'contentType', 'audio/mp4')
                from private.agreement_voice_uploads_v1 a where a.id = m.voice_asset_id and a.attached_message_id = m.id
                  and a.agreement_id = m.agreement_id and a.agreement_version = m.agreement_version and a.state = 'READY')
    ) order by m.created_at desc, m.id desc), '[]'::jsonb)
  into selected from (select x.* from public.agreement_messages x
    where x.agreement_id = p_agreement_id and (p_before_id is null or (x.created_at, x.id) < (p_before_created_at, p_before_id))
    order by x.created_at desc, x.id desc limit p_limit + 1) m;
  has_older := jsonb_array_length(selected) > p_limit;
  select coalesce(jsonb_agg(value order by ord desc), '[]'::jsonb), array_agg((value->>'messageId')::uuid order by ord desc)
    into page_rows, ids from jsonb_array_elements(selected) with ordinality r(value, ord) where ord <= p_limit;
  if cardinality(ids) > 0 then
    photo_rows := public.rpc_read_agreement_photo_messages_v5(u, p_agreement_id, ids)->'messages';
    select jsonb_agg(r.value || jsonb_build_object('photos', p.value->'photos') order by r.ord)
      into messages from jsonb_array_elements(page_rows) with ordinality r(value, ord)
      join jsonb_array_elements(photo_rows) p(value) on p.value->>'messageId' = r.value->>'messageId'
        and p.value->>'agreementVersion' = r.value->>'agreementVersion'
        and p.value->'clientMessageId' = r.value->'clientMessageId' and p.value->>'body' = r.value->>'body';
    if messages is null or jsonb_array_length(messages) <> cardinality(ids)
       or exists(select 1 from jsonb_array_elements(messages) x where x->>'kind' = 'VOICE' and jsonb_typeof(x->'voice') <> 'object') then
      raise exception 'CHAT_MESSAGE_PROJECTION_CHANGED' using errcode = '55000';
    end if;
    if has_older then older := jsonb_build_object('createdAt', page_rows->0->'createdAt', 'messageId', page_rows->0->'messageId'); end if;
  else messages := '[]'::jsonb; end if;
  perform private.support_auth_v5(u);
  return jsonb_build_object('schema', 'AGREEMENT_MESSAGES_PAGE_V2', 'accountId', u, 'agreementId', p_agreement_id,
    'messages', messages, 'olderCursor', older, 'asOf', statement_timestamp(), 'authoritative', true);
end
$page$;

create function public.rpc_read_agreement_message_window_v2(p_expected_user_id uuid, p_agreement_id uuid, p_target_message_id uuid,
  p_before_count integer default 24, p_after_count integer default 25)
returns jsonb language plpgsql security definer set search_path = pg_catalog as $window$
declare
  u uuid := private.support_auth_v5(p_expected_user_id); ag public.agreements;
  target_at timestamptz; page_rows jsonb; photo_rows jsonb; messages jsonb; ids uuid[];
  has_before boolean; has_after boolean; before_cursor jsonb := null; after_cursor jsonb := null;
begin
  ag := private.agreement_voice_context_v1(u, p_agreement_id, null, false);
  if p_before_count is null or p_after_count is null or p_before_count not between 0 and 49 or p_after_count not between 0 and 49
     or p_before_count + p_after_count > 49 then
    raise exception 'CHAT_WINDOW_INVALID' using errcode = '22023';
  end if;
  select m.created_at into target_at from public.agreement_messages m where m.id = p_target_message_id and m.agreement_id = p_agreement_id;
  if not found then raise exception 'CHAT_MESSAGE_NOT_AVAILABLE' using errcode = '42501'; end if;
  with before_rows as materialized (
    select m.* from public.agreement_messages m where m.agreement_id = p_agreement_id and (m.created_at, m.id) < (target_at, p_target_message_id)
    order by m.created_at desc, m.id desc limit p_before_count + 1
  ), after_rows as materialized (
    select m.* from public.agreement_messages m where m.agreement_id = p_agreement_id and (m.created_at, m.id) > (target_at, p_target_message_id)
    order by m.created_at, m.id limit p_after_count + 1
  ), window_rows as (
    (select * from before_rows order by created_at desc, id desc limit p_before_count)
    union all
    (select m.* from public.agreement_messages m where m.id = p_target_message_id and m.agreement_id = p_agreement_id and m.created_at = target_at)
    union all
    (select * from after_rows order by created_at, id limit p_after_count)
  )
  select coalesce(jsonb_agg(jsonb_build_object(
      'messageId', m.id, 'agreementVersion', m.agreement_version, 'senderAccountId', m.sender_account_id,
      'clientMessageId', m.client_message_id, 'body', m.body, 'createdAt', m.created_at,
      'kind', case when m.voice_asset_id is not null then 'VOICE' when cardinality(m.photo_asset_ids) > 0 then 'PHOTO' else 'TEXT' end,
      'mine', m.sender_account_id = u,
      'voice', (select jsonb_build_object('assetId', a.id, 'durationMs', a.duration_ms, 'byteSize', a.byte_size, 'contentType', 'audio/mp4')
                from private.agreement_voice_uploads_v1 a where a.id = m.voice_asset_id and a.attached_message_id = m.id
                  and a.agreement_id = m.agreement_id and a.agreement_version = m.agreement_version and a.state = 'READY')
    ) order by m.created_at, m.id), '[]'::jsonb),
    array_agg(m.id order by m.created_at, m.id),
    (select count(*) > p_before_count from before_rows), (select count(*) > p_after_count from after_rows)
    into page_rows, ids, has_before, has_after from window_rows m;
  if cardinality(ids) is null or cardinality(ids) > 50 or not p_target_message_id = any(ids) then
    raise exception 'CHAT_MESSAGE_NOT_AVAILABLE' using errcode = '42501';
  end if;
  photo_rows := public.rpc_read_agreement_photo_messages_v5(u, p_agreement_id, ids)->'messages';
  select jsonb_agg(r.value || jsonb_build_object('photos', p.value->'photos') order by r.ord)
    into messages from jsonb_array_elements(page_rows) with ordinality r(value, ord)
    join jsonb_array_elements(photo_rows) p(value) on p.value->>'messageId' = r.value->>'messageId'
      and p.value->>'agreementVersion' = r.value->>'agreementVersion'
      and p.value->'clientMessageId' = r.value->'clientMessageId' and p.value->>'body' = r.value->>'body';
  if messages is null or jsonb_array_length(messages) <> cardinality(ids)
     or exists(select 1 from jsonb_array_elements(messages) x where x->>'kind' = 'VOICE' and jsonb_typeof(x->'voice') <> 'object') then
    raise exception 'CHAT_MESSAGE_PROJECTION_CHANGED' using errcode = '55000';
  end if;
  if has_before then before_cursor := jsonb_build_object('createdAt', page_rows->0->'createdAt', 'messageId', page_rows->0->'messageId'); end if;
  if has_after then after_cursor := jsonb_build_object('createdAt', page_rows->-1->'createdAt', 'messageId', page_rows->-1->'messageId'); end if;
  perform private.support_auth_v5(u);
  return jsonb_build_object('schema', 'AGREEMENT_MESSAGE_WINDOW_V2', 'accountId', u, 'agreementId', p_agreement_id,
    'targetMessageId', p_target_message_id, 'messages', messages, 'beforeCursor', before_cursor, 'afterCursor', after_cursor,
    'asOf', statement_timestamp(), 'authoritative', true);
end
$window$;

-- The V1 answer for builds that only know TEXT and PHOTO: a voice row goes out as TEXT with a fixed notice, so such a build never fails the page
-- (hiding the row would leave gaps in its paging and acknowledgements). Key sets, cursors and schema names are exactly the V1 contract.
create function private.agreement_messages_v1_view(v jsonb, schema_name text) returns jsonb language sql immutable set search_path = pg_catalog as $f$
  select (v - 'messages') || jsonb_build_object('schema', schema_name, 'messages', (
    select coalesce(jsonb_agg(case when m->>'kind' = 'VOICE'
        then (m - 'voice') || jsonb_build_object('kind', 'TEXT', 'body', 'Glasovna poruka. Ažuriraj aplikaciju da je poslušaš.')
        else m - 'voice' end order by o), '[]'::jsonb)
    from jsonb_array_elements(v->'messages') with ordinality t(m, o)));$f$;
create or replace function public.rpc_read_agreement_messages_page_v1(p_expected_user_id uuid, p_agreement_id uuid, p_limit integer default 50,
  p_before_created_at timestamptz default null, p_before_id uuid default null)
returns jsonb language plpgsql security definer set search_path = pg_catalog as $page$
begin
  return private.agreement_messages_v1_view(public.rpc_read_agreement_messages_page_v2(p_expected_user_id, p_agreement_id, p_limit, p_before_created_at, p_before_id),
    'AGREEMENT_MESSAGES_PAGE_V1');
end
$page$;
create or replace function public.rpc_read_agreement_message_window_v1(p_expected_user_id uuid, p_agreement_id uuid, p_target_message_id uuid,
  p_before_count integer default 24, p_after_count integer default 25)
returns jsonb language plpgsql security definer set search_path = pg_catalog as $window$
begin
  return private.agreement_messages_v1_view(public.rpc_read_agreement_message_window_v2(p_expected_user_id, p_agreement_id, p_target_message_id, p_before_count, p_after_count),
    'AGREEMENT_MESSAGE_WINDOW_V1');
end
$window$;

do $acl$
declare f record;
begin
  for f in select p.oid::regprocedure signature, p.proname, n.nspname from pg_proc p join pg_namespace n on n.oid = p.pronamespace
      where (n.nspname = 'private' and p.proname in ('agreement_voice_key_v1','agreement_voice_context_v1','agreement_voice_document_v1','agreement_voice_transfer_v1',
          'agreement_voice_message_guard_v1','agreement_voice_link_guard_v1','agreement_voice_asset_guard_v1','agreement_voice_storage_guard_v1','agreement_messages_v1_view'))
         or (n.nspname = 'public' and p.proname in ('rpc_send_agreement_voice_message_v1','rpc_agreement_voice_upload_service_v1','rpc_agreement_voice_read_service_v1',
          'rpc_read_agreement_messages_page_v2','rpc_read_agreement_message_window_v2')) loop
    execute format('revoke all on function %s from public, anon, authenticated, service_role', f.signature);
    if f.nspname = 'public' then
      execute format('grant execute on function %s to %I', f.signature,
        case when f.proname in ('rpc_agreement_voice_upload_service_v1','rpc_agreement_voice_read_service_v1') then 'service_role' else 'authenticated' end);
    end if;
  end loop;
end
$acl$;

do $post$
declare f record; s text;
begin
  if not exists(select 1 from pg_class where oid = 'private.agreement_voice_uploads_v1'::regclass and relrowsecurity and relforcerowsecurity)
     or has_table_privilege('anon', 'private.agreement_voice_uploads_v1', 'SELECT,INSERT,UPDATE,DELETE')
     or has_table_privilege('authenticated', 'private.agreement_voice_uploads_v1', 'SELECT,INSERT,UPDATE,DELETE')
     or has_table_privilege('service_role', 'private.agreement_voice_uploads_v1', 'SELECT,INSERT,UPDATE,DELETE') then
    raise exception 'VOICE_B1A_TABLE_AUTHORITY_MISMATCH' using errcode = '55000';
  end if;
  if not exists(select 1 from storage.buckets where id = 'agreement-voice' and public = false and file_size_limit = 4194304 and allowed_mime_types = array['audio/mp4'])
     or not exists(select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'agreement_voice_no_client_v1' and permissive = 'RESTRICTIVE') then
    raise exception 'VOICE_B1A_BUCKET_MISMATCH' using errcode = '55000';
  end if;
  for f in select * from (values
    ('public.rpc_send_agreement_voice_message_v1(uuid,uuid,integer,text,uuid)', false, true),
    ('public.rpc_agreement_voice_upload_service_v1(uuid,uuid,text,uuid,integer,uuid,jsonb)', true, false),
    ('public.rpc_agreement_voice_read_service_v1(uuid,uuid,uuid,uuid,uuid)', true, false),
    ('public.rpc_read_agreement_messages_page_v2(uuid,uuid,integer,timestamptz,uuid)', false, true),
    ('public.rpc_read_agreement_message_window_v2(uuid,uuid,uuid,integer,integer)', false, true),
    ('public.rpc_read_agreement_messages_page_v1(uuid,uuid,integer,timestamptz,uuid)', false, true),
    ('public.rpc_read_agreement_message_window_v1(uuid,uuid,uuid,integer,integer)', false, true)
  ) p(signature, service_only, authenticated_only) loop
    if not exists(select 1 from pg_proc where oid = to_regprocedure(f.signature) and prosecdef and proconfig = array['search_path=pg_catalog'])
       or has_function_privilege('anon', f.signature, 'EXECUTE') or has_function_privilege('public', f.signature, 'EXECUTE')
       or has_function_privilege('service_role', f.signature, 'EXECUTE') is distinct from f.service_only
       or has_function_privilege('authenticated', f.signature, 'EXECUTE') is distinct from f.authenticated_only then
      raise exception 'VOICE_B1A_FUNCTION_AUTHORITY_MISMATCH: %', f.signature using errcode = '55000';
    end if;
  end loop;
  if not exists(select 1 from pg_constraint where conrelid = 'public.agreement_messages'::regclass and conname = 'agreement_messages_body_media_check' and convalidated)
     or exists(select 1 from pg_constraint where conrelid = 'public.agreement_messages'::regclass and conname = 'agreement_messages_body_photo_check') then
    raise exception 'VOICE_B1A_MESSAGE_CONSTRAINT_MISMATCH' using errcode = '55000';
  end if;
  -- The schema digest covers every table, constraint and trigger: the certificate is UNCERTIFIED now until B1-b re-binds it. Recorded, not asserted.
  s := private.closure_source_digest_v5();
  if s is null then raise exception 'VOICE_B1A_DIGEST_UNAVAILABLE' using errcode = '55000'; end if;
end
$post$;
notify pgrst, 'reload schema';
$voice_b1a_install$;
  execute $voice_b1b_install$
set local lock_timeout = '5s';
set local statement_timeout = '60s';
set local search_path = pg_catalog;

create temporary table voice_b1b_before(digest text, ready boolean) on commit drop;
do $pre$
declare pin record; actual text; bad text[] := '{}';
begin
  if to_regprocedure('private.agreement_voice_surface_v1()') is not null then
    raise exception 'VOICE_B1B_ALREADY_APPLIED' using errcode = '55000';
  end if;
  if to_regclass('private.agreement_voice_uploads_v1') is null
     or not exists(select 1 from pg_attribute where attrelid = 'public.agreement_messages'::regclass and attname = 'voice_asset_id' and not attisdropped)
     or to_regprocedure('public.rpc_send_agreement_voice_message_v1(uuid,uuid,integer,text,uuid)') is null
     or to_regprocedure('private.agreement_voice_storage_guard_v1()') is null
     or not exists(select 1 from storage.buckets where id = 'agreement-voice') then
    raise exception 'VOICE_B1B_B1A_MISSING' using errcode = '55000';
  end if;
  if exists(select 1 from private.closure_executions_v5 where state = 'EXECUTING') then
    raise exception 'VOICE_B1B_CLOSURE_IN_FLIGHT' using errcode = '55000';
  end if;
  -- Each predecessor body is pinned (every mismatch is listed at once). The two functions that the B24 part 2 package rewrote (a conflict code only, at other sites than the
  -- anchors below) also accept their pre-B24 body, so the disposable chain, which does not replay B24, runs the very same bytes; the DEV application pins the DEV body exactly.
  for pin in select * from (values
    ('private.closure_redaction_relations_v5()', 'c6d687219096c03371560cabb961cb0e', null::text),
    ('private.closure_redaction_scope_v5(text)', '3197a4c47582823d4474027bc49b4f84', null),
    ('private.closure_redaction_patch_v5(text,jsonb,uuid,uuid)', '0779e304e719774679d8ffb2d7c67fd9', null),
    ('private.closure_blockers_v5(uuid)', 'dc78d910fde458c18e25c732888fa93a', null),
    ('public.rpc_start_account_closure_execution(uuid,uuid,integer,uuid,text)', '4e24973f86127de890d4cb77ab1b6e14', 'c26b69083508cdaf08fb216845914921'),
    ('private.support_reference_v5(uuid,jsonb)', '907b383f500a91d3cf436448b1146295', 'cdc5890d7481b454f4eb5b63e5c0d5a8'),
    ('private.data_export_snapshot(uuid,uuid,jsonb,timestamptz)', 'b3c4b64a4c3afc98bd7a9aa12314bea5', null),
    ('private.data_export_dataset_catalog()', 'c3d3a109d8e765ae1ad78910c320248d', null),
    ('private.data_export_policy_binding()', '2dbe3d1f343c37c5b3d722c97d9bcb70', null),
    ('private.closure_source_digest_v5()', 'd67d37e2ebc5d9f85448693c0772f663', null),
    ('private.closure_erasure_program_digest_v5()', '3ec8d244730415d3a047312366672375', null)
  ) p(signature, body_md5, alternative_md5) loop
    -- A missing function must never equal an absent alternative: NULL is not distinct from NULL.
    actual := coalesce((select md5(replace(prosrc, E'\r\n', E'\n')) from pg_proc where oid = to_regprocedure(pin.signature)), 'MISSING');
    if actual is distinct from pin.body_md5 and actual is distinct from pin.alternative_md5 then
      bad := array_append(bad, pin.signature || '=' || actual);
    end if;
  end loop;
  if cardinality(bad) > 0 then
    raise exception 'VOICE_B1B_PREDECESSOR_DRIFT: %', array_to_string(bad, ' ') using errcode = '55000';
  end if;
  if (select array_agg(pg_get_constraintdef(oid)) from pg_constraint where conrelid = 'private.closure_actions_v5'::regclass and conname = 'closure_action_shape146')
     is distinct from array[$c$CHECK ((((kind = 'STORAGE_DELETE'::text) AND (bucket = ANY (ARRAY['profile-media'::text, 'data-export-artifacts'::text])) AND (object_path IS NOT NULL)) OR ((kind = ANY (ARRAY['RELATIONAL_REDACT'::text, 'AUTH_IDENTITY_ERASE'::text])) AND (bucket IS NULL) AND (object_path IS NULL))))$c$]::text[] then
    raise exception 'VOICE_B1B_PREDECESSOR_DRIFT: closure_action_shape146' using errcode = '55000';
  end if;
  if (select relations from private.closure_dataset_catalog_v5 where data_class = 'MEDIA_OBJECTS')
     is distinct from array['private.owned_media_assets','private.agreement_media_snapshots_v5','private.media_evidence_refs_v5','private.media_evidence_gaps_v5','private.agreement_photo_uploads_v5']::text[] then
    raise exception 'VOICE_B1B_PREDECESSOR_DRIFT: MEDIA_OBJECTS catalog' using errcode = '55000';
  end if;
  insert into voice_b1b_before values (private.closure_source_digest_v5(), private.retention_ai_source_ready());
end
$pre$;

-- 1. The erasure program: ordered relation, exact owner scope, DELETE plan for the upload table, and the own-message redaction carries the voice asset.
do $erasure$
declare d text; anchor text;
begin
  d := pg_get_functiondef('private.closure_redaction_relations_v5()'::regprocedure);
  anchor := $a$'private.owned_media_assets','private.agreement_photo_uploads_v5',$a$;
  if length(d) - length(replace(d, anchor, '')) <> length(anchor) then raise exception 'VOICE_B1B_RELATIONS_ANCHOR_DRIFT'; end if;
  execute replace(d, anchor, $a$'private.owned_media_assets','private.agreement_photo_uploads_v5','private.agreement_voice_uploads_v1',$a$);

  d := pg_get_functiondef('private.closure_redaction_scope_v5(text)'::regprocedure);
  anchor := $a$'private.owned_media_assets','private.agreement_photo_uploads_v5',$a$;
  if length(d) - length(replace(d, anchor, '')) <> length(anchor) then raise exception 'VOICE_B1B_SCOPE_ANCHOR_DRIFT'; end if;
  execute replace(d, anchor, $a$'private.owned_media_assets','private.agreement_photo_uploads_v5','private.agreement_voice_uploads_v1',$a$);

  d := pg_get_functiondef('private.closure_redaction_patch_v5(text,jsonb,uuid,uuid)'::regprocedure);
  anchor := $a$if r in('private.owned_media_assets','private.agreement_photo_uploads_v5') then$a$;
  if length(d) - length(replace(d, anchor, '')) <> length(anchor) then raise exception 'VOICE_B1B_PATCH_UPLOAD_ANCHOR_DRIFT'; end if;
  -- A voice upload is never evidence (Support cannot capture one): it goes once its object is gone, and never while a transfer is in flight.
  d := replace(d, anchor, $a$if r='private.agreement_voice_uploads_v1' then
  if t->>'dispatch_state'='DISPATCHING' then raise exception 'ERASURE_PRODUCER_UNSETTLED';end if;
  if exists(select 1 from storage.objects where bucket_id='agreement-voice' and name=t->>'storage_path') then raise exception 'ERASURE_STORAGE_NOT_CLEAN';end if;
  return jsonb_build_object('operation','DELETE','patch','{}'::jsonb);
 end if;
 $a$ || anchor);
  anchor := $a$p:=jsonb_build_object('body','Sadržaj uklonjen pri zatvaranju naloga.','photo_asset_ids','[]'::jsonb);$a$;
  if length(d) - length(replace(d, anchor, '')) <> length(anchor) then raise exception 'VOICE_B1B_PATCH_MESSAGE_ANCHOR_DRIFT'; end if;
  execute replace(d, anchor, $a$p:=jsonb_build_object('body','Sadržaj uklonjen pri zatvaranju naloga.','photo_asset_ids','[]'::jsonb,'voice_asset_id',null);$a$);
end
$erasure$;

-- 2. The blockers and the start planner: the new bucket is an owned bucket, an in-flight voice transfer blocks, every tracked voice object becomes a STORAGE_DELETE action.
do $closure$
declare d text; anchor text;
begin
  d := pg_get_functiondef('private.closure_blockers_v5(uuid)'::regprocedure);
  anchor := $a$bucket_id not in('profile-media','data-export-artifacts')$a$;
  if length(d) - length(replace(d, anchor, '')) <> length(anchor) then raise exception 'VOICE_B1B_BLOCKERS_BUCKET_ANCHOR_DRIFT'; end if;
  d := replace(d, anchor, $a$bucket_id not in('profile-media','data-export-artifacts','agreement-voice')$a$);
  anchor := $a$if exists(select 1 from private.agreement_photo_uploads_v5 where account_id=a and dispatch_state='DISPATCHING') then$a$;
  if length(d) - length(replace(d, anchor, '')) <> length(anchor) then raise exception 'VOICE_B1B_BLOCKERS_PENDING_ANCHOR_DRIFT'; end if;
  execute replace(d, anchor, $a$if exists(select 1 from private.agreement_photo_uploads_v5 where account_id=a and dispatch_state='DISPATCHING')
 or exists(select 1 from private.agreement_voice_uploads_v1 where account_id=a and dispatch_state='DISPATCHING') then$a$);

  d := pg_get_functiondef('public.rpc_start_account_closure_execution(uuid,uuid,integer,uuid,text)'::regprocedure);
  anchor := $a$union select 'data-export-artifacts',object_path from private.data_export_artifacts where account_id=u) x$a$;
  if length(d) - length(replace(d, anchor, '')) <> length(anchor) then raise exception 'VOICE_B1B_START_ANCHOR_DRIFT'; end if;
  execute replace(d, anchor, $a$union select 'agreement-voice',storage_path from private.agreement_voice_uploads_v1 where account_id=u and storage_path is not null
  union select 'data-export-artifacts',object_path from private.data_export_artifacts where account_id=u) x$a$);
end
$closure$;

alter table private.closure_actions_v5 drop constraint closure_action_shape146;
alter table private.closure_actions_v5 add constraint closure_action_shape146 check(
  (kind = 'STORAGE_DELETE' and bucket in ('profile-media', 'data-export-artifacts', 'agreement-voice') and object_path is not null)
  or (kind in ('RELATIONAL_REDACT', 'AUTH_IDENTITY_ERASE') and bucket is null and object_path is null));

-- 3. The retention catalog: the upload table is a media object like the photo one.
update private.closure_dataset_catalog_v5 set relations = relations || array['private.agreement_voice_uploads_v1'] where data_class = 'MEDIA_OBJECTS';

-- 4. The export: one new dataset (metadata only), one new field, projection version 9, 52 datasets. An export contains a field only when the active policy lists it.
do $export$
declare catalog jsonb; d text; anchor text;
begin
  catalog := private.data_export_dataset_catalog();
  if jsonb_array_length(catalog) <> 51 then raise exception 'VOICE_B1B_EXPORT_PREDECESSOR_DRIFT'; end if;
  catalog := (select jsonb_agg(case when e->>'key' = 'ownAgreementMessages' then jsonb_set(e, '{fields}', (e->'fields') || '"voiceAssetId"'::jsonb) else e end order by ord)
    from jsonb_array_elements(catalog) with ordinality t(e, ord));
  catalog := catalog || '[{"key":"ownAgreementVoice","dataClass":"MEDIA_OBJECTS","fields":["id","agreementId","agreementVersion","messageId","state","durationMs","byteSize","createdAt","cancelledAt","bytesIncluded"],"ownershipFilter":"t.account_id=REQUEST_ACCOUNT"}]'::jsonb;
  execute format('create or replace function private.data_export_dataset_catalog() returns jsonb language sql immutable security definer set search_path=pg_catalog as $catalog$ select %L::jsonb $catalog$', catalog::text);

  d := pg_get_functiondef('private.data_export_snapshot(uuid,uuid,jsonb,timestamptz)'::regprocedure);
  anchor := $a$'agreementVersion',t.agreement_version,'assetIds',to_jsonb(t.photo_asset_ids)) as value from public.agreement_messages t$a$;
  if length(d) - length(replace(d, anchor, '')) <> length(anchor) then raise exception 'VOICE_B1B_EXPORT_MESSAGES_ANCHOR_DRIFT'; end if;
  d := replace(d, anchor, $a$'agreementVersion',t.agreement_version,'assetIds',to_jsonb(t.photo_asset_ids),'voiceAssetId',t.voice_asset_id) as value from public.agreement_messages t$a$);
  anchor := $a$from private.agreement_photo_uploads_v5 t where t.account_id=p_account_id
union all
select 'ownErasureSteps'$a$;
  if length(d) - length(replace(d, anchor, '')) <> length(anchor) then raise exception 'VOICE_B1B_EXPORT_ROWS_ANCHOR_DRIFT'; end if;
  d := replace(d, anchor, $a$from private.agreement_photo_uploads_v5 t where t.account_id=p_account_id
union all
select 'ownAgreementVoice',jsonb_build_object('id',t.id,'agreementId',t.agreement_id,'agreementVersion',t.agreement_version,'messageId',t.attached_message_id,'state',t.state,
 'durationMs',t.duration_ms,'byteSize',t.byte_size,'createdAt',t.created_at,'cancelledAt',t.cancelled_at,'bytesIncluded',false) from private.agreement_voice_uploads_v1 t where t.account_id=p_account_id
union all
select 'ownErasureSteps'$a$);
  anchor := $a$'OWN_ACCOUNT_V5_8'$a$;
  if length(d) - length(replace(d, anchor, '')) <> length(anchor) then raise exception 'VOICE_B1B_EXPORT_VERSION_ANCHOR_DRIFT'; end if;
  execute replace(d, anchor, $a$'OWN_ACCOUNT_V5_9'$a$);

  d := pg_get_functiondef('private.data_export_policy_binding()'::regprocedure);
  if length(d) - length(replace(d, $a$'OWN_ACCOUNT_V5_8'$a$, '')) <> length($a$'OWN_ACCOUNT_V5_8'$a$)
     or length(d) - length(replace(d, $a$jsonb_array_length(m->'datasets')<>51$a$, '')) <> length($a$jsonb_array_length(m->'datasets')<>51$a$)
     or length(d) - length(replace(d, $a$in('mediaMetadata','ownedMediaAssets','ownAgreementPhotos','ownSupportEvidence')$a$, '')) <> length($a$in('mediaMetadata','ownedMediaAssets','ownAgreementPhotos','ownSupportEvidence')$a$) then
    raise exception 'VOICE_B1B_EXPORT_BINDING_ANCHOR_DRIFT';
  end if;
  d := replace(d, $a$'OWN_ACCOUNT_V5_8'$a$, $a$'OWN_ACCOUNT_V5_9'$a$);
  d := replace(d, $a$jsonb_array_length(m->'datasets')<>51$a$, $a$jsonb_array_length(m->'datasets')<>52$a$);
  execute replace(d, $a$in('mediaMetadata','ownedMediaAssets','ownAgreementPhotos','ownSupportEvidence')$a$, $a$in('mediaMetadata','ownedMediaAssets','ownAgreementPhotos','ownAgreementVoice','ownSupportEvidence')$a$);
end
$export$;

-- 5. Support: a reported voice message keeps its exact identity and revision, carries a fixed label instead of an empty body, and never audio.
do $support$
declare d text; anchor text;
begin
  d := pg_get_functiondef('private.support_reference_v5(uuid,jsonb)'::regprocedure);
  anchor := $a$content:=jsonb_build_object('agreementId',m.agreement_id,'body',m.body,'createdAt',m.created_at,'mine',m.sender_account_id=a);$a$;
  if length(d) - length(replace(d, anchor, '')) <> length(anchor) then raise exception 'VOICE_B1B_SUPPORT_ANCHOR_DRIFT'; end if;
  execute replace(d, anchor, $a$content:=jsonb_build_object('agreementId',m.agreement_id,'body',case when m.voice_asset_id is not null then 'Glasovna poruka (zvuk nije deo prijave).' else m.body end,'createdAt',m.created_at,'mine',m.sender_account_id=a);$a$);
end
$support$;

-- 6. The certificate surface: the bucket row and the storage policies that keep it private are not covered by the schema or program digests, so one helper binds them.
create function private.agreement_voice_surface_v1() returns text language sql stable security definer set search_path = pg_catalog as $surface$
select encode(extensions.digest(convert_to(jsonb_build_object(
 'bucket',(select jsonb_build_object('id',b.id,'name',b.name,'public',b.public,'fileSizeLimit',b.file_size_limit,'allowedMimeTypes',b.allowed_mime_types)
   from storage.buckets b where b.id='agreement-voice'),
 'policies',(select coalesce(jsonb_agg(jsonb_build_object('name',p.policyname,'permissive',p.permissive,'roles',p.roles,'cmd',p.cmd,'qual',p.qual,'withCheck',p.with_check)
   order by p.policyname),'[]'::jsonb) from pg_policies p where p.schemaname='storage' and p.tablename='objects'
   and (p.permissive='RESTRICTIVE' or coalesce(p.qual,'')||coalesce(p.with_check,'') like '%agreement-voice%')),
 'rowSecurity',(select jsonb_build_array(c.relrowsecurity,c.relforcerowsecurity) from pg_class c where c.oid='storage.objects'::regclass)
 )::text,'UTF8'),'sha256'),'hex')
$surface$;
revoke all on function private.agreement_voice_surface_v1() from public, anon, authenticated, service_role;

do $roster$
declare d text; anchor text; extra text[];
begin
  extra := array['private.agreement_voice_key_v1(uuid)','private.agreement_voice_context_v1(uuid,uuid,integer,boolean)',
    'private.agreement_voice_document_v1(private.agreement_voice_uploads_v1)','private.agreement_voice_transfer_v1(private.agreement_voice_uploads_v1)',
    'private.agreement_voice_message_guard_v1()','private.agreement_voice_link_guard_v1()','private.agreement_voice_asset_guard_v1()','private.agreement_voice_storage_guard_v1()',
    'public.rpc_agreement_voice_upload_service_v1(uuid,uuid,text,uuid,integer,uuid,jsonb)','public.rpc_agreement_voice_read_service_v1(uuid,uuid,uuid,uuid,uuid)',
    'public.rpc_send_agreement_voice_message_v1(uuid,uuid,integer,text,uuid)','private.agreement_voice_surface_v1()'];
  if cardinality(extra) <> 12 or exists(select 1 from unnest(extra) x where to_regprocedure(x) is null) then raise exception 'VOICE_B1B_ROSTER_FUNCTION_MISSING'; end if;

  d := pg_get_functiondef('private.closure_source_digest_v5()'::regprocedure);
  anchor := $a$private.agreement_invalidation_surface_v1()||':'||string_agg($a$;
  if length(d) - length(replace(d, anchor, '')) <> length(anchor) then raise exception 'VOICE_B1B_SOURCE_SURFACE_ANCHOR_DRIFT'; end if;
  d := replace(d, anchor, $a$private.agreement_invalidation_surface_v1()||':'||private.agreement_voice_surface_v1()||':'||string_agg($a$);
  anchor := $a$'private.agreement_invalidation_surface_v1()']) signature$a$;
  if length(d) - length(replace(d, anchor, '')) <> length(anchor) or strpos(d, 'having count(*)=76') = 0 then raise exception 'VOICE_B1B_SOURCE_ROSTER_ANCHOR_DRIFT'; end if;
  d := replace(d, anchor, $a$'private.agreement_invalidation_surface_v1()',$a$ || (select string_agg(quote_literal(x), ',' order by ord) from unnest(extra) with ordinality t(x, ord)) || $a$]) signature$a$);
  execute replace(d, 'having count(*)=76', 'having count(*)=' || (76 + cardinality(extra))::text);

  d := pg_get_functiondef('private.closure_erasure_program_digest_v5()'::regprocedure);
  anchor := $a$,private.closure_source_digest_v5(),private.closure_erasure_program_digest_v5()}'::text[]) x)$a$;
  if length(d) - length(replace(d, anchor, '')) <> length(anchor) then raise exception 'VOICE_B1B_PROGRAM_ROSTER_ANCHOR_DRIFT'; end if;
  execute replace(d, anchor, $a$,private.closure_source_digest_v5(),private.closure_erasure_program_digest_v5(),$a$
    || (select string_agg(case when x like '%,%' then '"' || x || '"' else x end, ',' order by ord) from unnest(extra) with ordinality t(x, ord)) || $a$}'::text[]) x)$a$);
end
$roster$;

do $post$
declare s text; b record;
begin
  select * into b from voice_b1b_before;
  s := private.closure_source_digest_v5();
  if s is null or s = b.digest then raise exception 'VOICE_B1B_DIGEST_DID_NOT_MOVE' using errcode = '55000'; end if;
  if private.retention_ai_source_ready() is distinct from false or private.closure_erasure_binding_v5() is not null then
    raise exception 'VOICE_B1B_UNCERTIFIED_STATE_NOT_CLOSED' using errcode = '55000';
  end if;
  if has_function_privilege('anon', 'private.agreement_voice_surface_v1()', 'EXECUTE') or has_function_privilege('authenticated', 'private.agreement_voice_surface_v1()', 'EXECUTE')
     or has_function_privilege('service_role', 'private.agreement_voice_surface_v1()', 'EXECUTE') then
    raise exception 'VOICE_B1B_AUTHORITY_CHANGED' using errcode = '55000';
  end if;
  if not ('private.agreement_voice_uploads_v1' = any(private.closure_redaction_relations_v5()))
     or private.closure_redaction_scope_v5('private.agreement_voice_uploads_v1') is distinct from 't.account_id=$1'
     or not exists(select 1 from pg_constraint where conrelid = 'private.closure_actions_v5'::regclass and conname = 'closure_action_shape146' and convalidated
        and pg_get_constraintdef(oid) like '%agreement-voice%')
     or jsonb_array_length(private.data_export_dataset_catalog()) <> 52
     or not exists(select 1 from jsonb_array_elements(private.data_export_dataset_catalog()) e where e->>'key' = 'ownAgreementVoice')
     or (select relations from private.closure_dataset_catalog_v5 where data_class = 'MEDIA_OBJECTS') is distinct from
        array['private.owned_media_assets','private.agreement_media_snapshots_v5','private.media_evidence_refs_v5','private.media_evidence_gaps_v5','private.agreement_photo_uploads_v5','private.agreement_voice_uploads_v1']::text[] then
    raise exception 'VOICE_B1B_POSTCONDITION' using errcode = '55000';
  end if;
end
$post$;
$voice_b1b_install$;
  -- END EXACT PROVED INSTALL FRAGMENTS. Their own preconditions proved the predecessor and their postconditions proved the closed, uncertified state.
  new_source:=private.closure_source_digest_v5();
  if new_source is null or new_source=old_source or new_source!~'^[0-9a-f]{64}$' then
    raise exception 'VOICE_B1_APPLICATION_NEW_SOURCE_INVALID' using errcode='55000';end if;
  if private.retention_ai_source_ready() is distinct from false or private.closure_erasure_binding_v5() is not null then
    raise exception 'VOICE_B1_APPLICATION_UNCERTIFIED_STATE_NOT_CLOSED' using errcode='55000';end if;
  update private.closure_source_v5 set sha256=new_source where singleton and sha256=old_source;
  get diagnostics affected=row_count;
  if affected<>1 then raise exception 'VOICE_B1_APPLICATION_SOURCE_ROW_COUNT' using errcode='55000';end if;
  update private.closure_erasure_source_v5 set sha256=new_source where singleton and sha256=old_source;
  get diagnostics affected=row_count;
  if affected<>1 then raise exception 'VOICE_B1_APPLICATION_ERASURE_ROW_COUNT' using errcode='55000';end if;
  execute replace(definition,old_source,new_source);

  -- Delta accounting 1/4: every old function is unchanged, except the readiness constant and the rewritten ones (their body only; owner, ACL, security, configuration and result stay).
  for prior in select * from voice_b1_application_functions loop
    select to_jsonb(p) into actual from pg_proc p where oid=prior.oid;
    if actual is null then raise exception 'VOICE_B1_APPLICATION_FUNCTION_REMOVED: %',prior.signature using errcode='55000';end if;
    if prior.oid='private.retention_ai_source_ready()'::regprocedure then
      if actual is distinct from jsonb_set(prior.metadata,'{prosrc}',to_jsonb(replace(prior.metadata->>'prosrc',old_source,new_source))) then
        raise exception 'VOICE_B1_APPLICATION_READINESS_DELTA' using errcode='55000';end if;
    elsif prior.oid=any(rewritten) then
      if actual-'prosrc' is distinct from prior.metadata-'prosrc' then
        raise exception 'VOICE_B1_APPLICATION_FUNCTION_AUTHORITY_DELTA: %',prior.signature using errcode='55000';end if;
      if actual->>'prosrc' is not distinct from prior.metadata->>'prosrc' then
        raise exception 'VOICE_B1_APPLICATION_REWRITE_MISSING: %',prior.signature using errcode='55000';end if;
    elsif actual is distinct from prior.metadata then
      raise exception 'VOICE_B1_APPLICATION_UNRELATED_FUNCTION_DELTA: %',prior.signature using errcode='55000';
    end if;
  end loop;
  -- Delta accounting 2/4: exactly the reviewed new functions exist, each with its exact body, language, volatility, security, result and ACL.
  select coalesce(array_agg(p.oid order by p.oid),'{}'::oid[]) into fresh from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    where n.nspname in('public','private','rls_private') and not exists(select 1 from voice_b1_application_functions old where old.oid=p.oid);
  if fresh is distinct from (select array_agg(to_regprocedure(x)::oid order by to_regprocedure(x)::oid) from unnest(array[
    'private.agreement_voice_key_v1(uuid)','private.agreement_voice_context_v1(uuid,uuid,integer,boolean)',
    'private.agreement_voice_document_v1(private.agreement_voice_uploads_v1)','private.agreement_voice_transfer_v1(private.agreement_voice_uploads_v1)',
    'private.agreement_voice_message_guard_v1()','private.agreement_voice_link_guard_v1()','private.agreement_voice_asset_guard_v1()','private.agreement_voice_storage_guard_v1()',
    'public.rpc_send_agreement_voice_message_v1(uuid,uuid,integer,text,uuid)','public.rpc_agreement_voice_read_service_v1(uuid,uuid,uuid,uuid,uuid)',
    'public.rpc_agreement_voice_upload_service_v1(uuid,uuid,text,uuid,integer,uuid,jsonb)',
    'public.rpc_read_agreement_messages_page_v2(uuid,uuid,integer,timestamptz,uuid)','public.rpc_read_agreement_message_window_v2(uuid,uuid,uuid,integer,integer)',
    'private.agreement_messages_v1_view(jsonb,text)','private.agreement_voice_surface_v1()']::text[]) x) then
    raise exception 'VOICE_B1_APPLICATION_FUNCTION_ROSTER_DELTA' using errcode='55000';end if;
  for pin in select * from (values
    ('private.agreement_voice_key_v1(uuid)','7fc22c4fa37e737d09917f03c497b84c','sql','i',false,true,'bigint','{postgres=X/postgres}'),
    ('private.agreement_voice_context_v1(uuid,uuid,integer,boolean)','db79bbcb1557e698f96e1973f5f1114d','plpgsql','v',true,false,'public.agreements','{postgres=X/postgres}'),
    ('private.agreement_voice_document_v1(private.agreement_voice_uploads_v1)','e3d28dc212ec03b7686809307125a2b0','sql','s',false,false,'jsonb','{postgres=X/postgres}'),
    ('private.agreement_voice_transfer_v1(private.agreement_voice_uploads_v1)','90adbecaf2f168e5aa2813053ef4ee71','sql','s',false,false,'jsonb','{postgres=X/postgres}'),
    ('private.agreement_voice_message_guard_v1()','f7945764ecc4176f519c6adc051036a4','plpgsql','v',true,false,'trigger','{postgres=X/postgres}'),
    ('private.agreement_voice_link_guard_v1()','70b7d13295f1a9407106d32a7c08fb15','plpgsql','v',true,false,'trigger','{postgres=X/postgres}'),
    ('private.agreement_voice_asset_guard_v1()','7dac0b4c2cad1da11dcd30e1ea35509a','plpgsql','v',true,false,'trigger','{postgres=X/postgres}'),
    ('private.agreement_voice_storage_guard_v1()','f3baf1ab27b347216cdede156ca3f42a','plpgsql','v',true,false,'trigger','{postgres=X/postgres}'),
    ('public.rpc_send_agreement_voice_message_v1(uuid,uuid,integer,text,uuid)','2cb1a99fd913115235a5762bf068f52e','plpgsql','v',true,false,'jsonb','{postgres=X/postgres,authenticated=X/postgres}'),
    ('public.rpc_agreement_voice_read_service_v1(uuid,uuid,uuid,uuid,uuid)','5d82c4a9683513a43f4edc9d8bd08e54','plpgsql','v',true,false,'jsonb','{postgres=X/postgres,service_role=X/postgres}'),
    ('public.rpc_agreement_voice_upload_service_v1(uuid,uuid,text,uuid,integer,uuid,jsonb)','aebb8132f2500415b2daded197e57975','plpgsql','v',true,false,'jsonb','{postgres=X/postgres,service_role=X/postgres}'),
    ('public.rpc_read_agreement_messages_page_v2(uuid,uuid,integer,timestamptz,uuid)','c0ae8862bb86be54834227c10d2aef89','plpgsql','v',true,false,'jsonb','{postgres=X/postgres,authenticated=X/postgres}'),
    ('public.rpc_read_agreement_message_window_v2(uuid,uuid,uuid,integer,integer)','e16aeb18144c44a8baa4aebaf420944c','plpgsql','v',true,false,'jsonb','{postgres=X/postgres,authenticated=X/postgres}'),
    ('private.agreement_messages_v1_view(jsonb,text)','4a2065e1b0c27894f4e2dcc352d7fb59','sql','i',false,false,'jsonb','{postgres=X/postgres}'),
    ('private.agreement_voice_surface_v1()','b697d12234198c95815257d7ce73f147','sql','s',true,false,'text','{postgres=X/postgres}')
  ) p(signature,body_md5,language_name,volatility,definer,strict_function,result_type,acl) loop
    if not exists(select 1 from pg_proc p where p.oid=to_regprocedure(pin.signature)
      and md5(replace(prosrc,E'\r\n',E'\n'))=pin.body_md5 and prosecdef=pin.definer and proisstrict=pin.strict_function
      and proconfig=array['search_path=pg_catalog'] and proowner='postgres'::regrole
      and prolang=(select oid from pg_language where lanname=pin.language_name)
      and provolatile::text=pin.volatility and prokind='f' and prorettype=to_regtype(pin.result_type)
      and proacl::text=pin.acl and not proretset and not proleakproof and proparallel='u'
      and probin is null and prosqlbody is null and protrftypes is null and proallargtypes is null and proargmodes is null) then
      raise exception 'VOICE_B1_APPLICATION_NEW_FUNCTION_DELTA: %',pin.signature using errcode='55000';end if;
  end loop;
  -- Delta accounting 3/4: every table, column, constraint, trigger, policy, index and bucket is unchanged except the reviewed additions and the two replaced constraints.
  execute surface_query into after_surface;
  if after_surface is distinct from before_surface then
    -- Name what differs (the key, how many entries each way and one example of each), so a refused application explains itself.
    select string_agg(k||': +'||(select count(*) from jsonb_array_elements(coalesce(after_surface->k,'[]'::jsonb)) e where not(coalesce(before_surface->k,'[]'::jsonb) @> jsonb_build_array(e)))::text
      ||' -'||(select count(*) from jsonb_array_elements(coalesce(before_surface->k,'[]'::jsonb)) e where not(coalesce(after_surface->k,'[]'::jsonb) @> jsonb_build_array(e)))::text
      ||' added '||coalesce((select left(e::text,240) from jsonb_array_elements(coalesce(after_surface->k,'[]'::jsonb)) e where not(coalesce(before_surface->k,'[]'::jsonb) @> jsonb_build_array(e)) limit 1),'-')
      ||' removed '||coalesce((select left(e::text,240) from jsonb_array_elements(coalesce(before_surface->k,'[]'::jsonb)) e where not(coalesce(after_surface->k,'[]'::jsonb) @> jsonb_build_array(e)) limit 1),'-'),' | ')
      into diff_keys from jsonb_object_keys(before_surface) k where before_surface->k is distinct from after_surface->k;
    raise exception 'VOICE_B1_APPLICATION_UNRELATED_CATALOG_DELTA: %',diff_keys using errcode='55000';
  end if;
  if (select jsonb_agg(to_jsonb(b) order by b.id) from storage.buckets b where b.id is distinct from 'agreement-voice') is distinct from before_buckets
     or not exists(select 1 from storage.buckets where id='agreement-voice' and not public and file_size_limit=4194304 and allowed_mime_types=array['audio/mp4'])
     or (select jsonb_agg(to_jsonb(p) order by policyname) from pg_policies p where schemaname='storage' and tablename='objects' and policyname is distinct from 'agreement_voice_no_client_v1')
       is distinct from before_storage_policies
     or not exists(select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname='agreement_voice_no_client_v1'
       and permissive='RESTRICTIVE' and roles=array['authenticated']::name[] and cmd='ALL' and qual like '%agreement-voice%' and with_check like '%agreement-voice%') then
    raise exception 'VOICE_B1_APPLICATION_STORAGE_DELTA' using errcode='55000';end if;
  if not exists(select 1 from pg_class where oid='private.agreement_voice_uploads_v1'::regclass and relowner='postgres'::regrole and relkind='r' and relpersistence='p'
      and not relispartition and relrowsecurity and relforcerowsecurity and relreplident='d' and reloptions is null and relacl=acldefault('r','postgres'::regrole))
    or exists(select 1 from pg_policies where schemaname='private' and tablename='agreement_voice_uploads_v1')
    or (select count(*) from pg_attribute where attrelid='public.agreement_messages'::regclass and attname='voice_asset_id' and not attisdropped and atttypid='uuid'::regtype and not attnotnull)<>1 then
    raise exception 'VOICE_B1_APPLICATION_NEW_TABLE_DELTA' using errcode='55000';end if;
  for pin in select * from (values
    ('public.agreement_messages','agreement_voice_message_guard_v1','private.agreement_voice_message_guard_v1()',23,false),
    ('public.agreement_messages','agreement_voice_link_guard_v1','private.agreement_voice_link_guard_v1()',5,true),
    ('private.agreement_voice_uploads_v1','agreement_voice_asset_guard_v1','private.agreement_voice_asset_guard_v1()',27,false),
    ('storage.objects','agreement_voice_storage_guard_v1','private.agreement_voice_storage_guard_v1()',27,false)
  ) p(relation,trigger_name,signature,event_type,deferred) loop
    if not exists(select 1 from pg_trigger t where tgrelid=pin.relation::regclass and tgname=pin.trigger_name
      and tgfoid=to_regprocedure(pin.signature) and tgtype=pin.event_type and tgenabled='O' and not tgisinternal
      and tgnargs=0 and octet_length(tgargs)=0 and tgqual is null and (tgconstraint<>0)=pin.deferred
      and tgdeferrable=pin.deferred and tginitdeferred=pin.deferred and tgoldtable is null and tgnewtable is null and tgparentid=0 and tgattr::text='') then
      raise exception 'VOICE_B1_APPLICATION_NEW_TRIGGER_DELTA: %',pin.trigger_name using errcode='55000';end if;
  end loop;
  -- The deferred constraint trigger is also a pg_constraint row: exactly this one, deferrable and initially deferred, local, bound to its own trigger.
  if (select count(*) from pg_constraint x where x.conrelid='public.agreement_messages'::regclass and x.conname='agreement_voice_link_guard_v1' and x.contype='t'
      and x.condeferrable and x.condeferred and x.convalidated and x.conparentid=0 and x.conislocal and x.coninhcount=0 and x.contypid=0 and x.conindid=0 and x.confrelid=0
      and exists(select 1 from pg_trigger t where t.tgconstraint=x.oid and t.tgname='agreement_voice_link_guard_v1' and t.tgrelid=x.conrelid))<>1 then
    raise exception 'VOICE_B1_APPLICATION_NEW_CONSTRAINT_DELTA' using errcode='55000';end if;
  -- Delta accounting 4/4: the retention catalog changed only by the new relation, publications and migration history are untouched, the certificate is bound in its three places and nothing else.
  if (select jsonb_agg(to_jsonb(c) order by data_class) from private.closure_dataset_catalog_v5 c) is distinct from expected_datasets then
    raise exception 'VOICE_B1_APPLICATION_CATALOG_DELTA' using errcode='55000';end if;
  if (select to_jsonb(c) from private.closure_source_v5 c where singleton) is distinct from jsonb_set(source_row,'{sha256}',to_jsonb(new_source))
    or (select to_jsonb(c) from private.closure_erasure_source_v5 c where singleton) is distinct from jsonb_set(erasure_row,'{sha256}',to_jsonb(new_source))
    or pg_get_functiondef('private.retention_ai_source_ready()'::regprocedure) is distinct from replace(definition,old_source,new_source)
    or private.closure_source_digest_v5() is distinct from new_source
    or private.retention_ai_source_ready() is distinct from true
    or private.closure_erasure_binding_v5()->>'sourceSha256' is distinct from new_source then
    raise exception 'VOICE_B1_APPLICATION_CERTIFIED_POSTCONDITION' using errcode='55000';end if;
  if exists(select 1 from private.closure_executions_v5 where state='EXECUTING')
    or has_function_privilege('anon','private.retention_ai_source_ready()','EXECUTE')
    or has_function_privilege('authenticated','private.retention_ai_source_ready()','EXECUTE')
    or has_function_privilege('anon','private.agreement_voice_surface_v1()','EXECUTE')
    or has_function_privilege('authenticated','private.agreement_voice_surface_v1()','EXECUTE')
    or has_function_privilege('service_role','private.agreement_voice_surface_v1()','EXECUTE') then
    raise exception 'VOICE_B1_APPLICATION_FINAL_AUTHORITY_OR_STATE_DRIFT' using errcode='55000';end if;
end
$voice_b1_application$;
