-- D12 written comment with the star rating: DEV application candidate. NOT APPLIED. It needs the owner's explicit "primeni" that NAMES the closure-certificate re-bind (a privacy certification of the erasure program, AGENTS 3.1.4).
-- GENERATED by supabase/proofs/d12/build_d12.py from supabase/proofs/d12/sql/*, d12_pins.json (read-only DEV pins) and d12_preimage.json (read-only DEV pre-image): do not edit by hand (`--check` fails on any difference).
-- predecessor pins: supabase/proofs/d12/d12_pins.json (sha256 c24d4a31d877bce11b4153eb6270af1e7c1728f1100aa37362b9171a48cd40ac, read-only DEV capture); pre-image: supabase/proofs/d12/d12_preimage.json (sha256 f4121cb20d07f4a00f15be776c0d03701eb4d2936ef94e02ea8c3c274d199709, read-only DEV capture of the seven definitions this file rewrites or re-binds); the certified digest it starts from on DEV is 58447d7730e909a0c0e60dd92ef77416af927471bd6f645988448e32c6e3cb46.
-- One atomic DO statement: exact DEV predecessor pins (complete metadata and LF-normalised bodies; owner, ACL, security and configuration of the three composite-typed functions; the exact shape of the immutable star table), the new private table with
-- its triggers, the new functions (the legacy review functions are NOT touched), the exact-once anchor edits of the three certified closure functions and of the three export functions, the one retention-catalog row and the one retention-class
-- description (a catalog TEXT: it names the new free text and sets no period), an isolation probe that proves the digest moved because of THIS change only, the three-place re-bind computed inside the same transaction, and an exact delta accounting
-- (every old function is unchanged except the six edited ones and the readiness constant, exactly the six reviewed new functions exist, every catalog surface is unchanged except the reviewed additions).
-- TRANSPORT: this file is ASCII-only and carries no unicode escape text (every character class is built with chr()), so a connector that resolves escapes cannot change a stored text or a pinned md5. Send it behind the integrity guard that
-- `build_d12.py --wrap` generates: the database then proves that the statement it received is the proved one, byte for byte.
-- Conflicts raise PT409, never the SQLSTATE that PostgREST 14 re-executes without end (registry blocker B24); no new body mentions that SQLSTATE at all.
do $d12_application$
declare
  pin record; prior record; actual jsonb; before_surface jsonb; after_surface jsonb; expected_datasets jsonb; before_default_acls text; star_before text; star_after text;
  old_source text; new_source text; ready_definition text; edit_definition text; source_row jsonb; erasure_row jsonb; affected integer; rewritten oid[]; fresh oid[]; diff_keys text;
  pre_relations text; pre_scope text; pre_patch text; probe_message text; probe_digest text; expected_classes jsonb;
  surface_query text := $surface_query$
    select jsonb_build_object(
      'relations',(select jsonb_agg(jsonb_build_array(c.oid,c.relname,c.relnamespace,c.relowner,c.relkind,c.relacl,
        c.relrowsecurity,c.relforcerowsecurity,c.relreplident,c.relispartition,c.reloptions) order by c.oid)
        from pg_class c join pg_namespace n on n.oid=c.relnamespace
        where n.nspname in('public','private','rls_private') and c.relkind in('r','p') and c.oid is distinct from to_regclass('private.agreement_review_comments_v1')),
      'columns',(select jsonb_agg(to_jsonb(a) order by a.attrelid,a.attnum)
        from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace
        where n.nspname in('public','private','rls_private') and c.relkind in('r','p') and a.attnum>0 and not a.attisdropped and c.oid is distinct from to_regclass('private.agreement_review_comments_v1')),
      'constraints',(select jsonb_agg(to_jsonb(x) order by x.oid)
        from pg_constraint x join pg_class c on c.oid=x.conrelid join pg_namespace n on n.oid=c.relnamespace
        where n.nspname in('public','private','rls_private') and c.oid is distinct from to_regclass('private.agreement_review_comments_v1')),
      'triggers',(select jsonb_agg(to_jsonb(t) order by t.oid)
        from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace
        where (n.nspname in('public','private','rls_private') or c.oid='storage.objects'::regclass) and not t.tgisinternal
          and t.tgname not in('agreement_review_comment_closure_guard_v1','agreement_review_comment_mutation_guard_v1')),
      'policies',(select jsonb_agg(to_jsonb(p) order by schemaname,tablename,policyname) from pg_policies p
        where schemaname in('public','private','rls_private') or (schemaname='storage' and tablename='objects')),
      'indexes',(select jsonb_agg(to_jsonb(i) order by schemaname,indexname) from pg_indexes i
        where schemaname in('public','private','rls_private') and tablename is distinct from 'agreement_review_comments_v1'),
      'buckets',(select jsonb_agg(to_jsonb(b) order by b.id) from storage.buckets b)
    )
  $surface_query$;
begin
  perform set_config('lock_timeout','5s',true);
  perform set_config('statement_timeout','120s',true);
  perform set_config('search_path','pg_catalog',true);
  if current_user<>'postgres' then raise exception 'D12_APPLICATION_OWNER_REQUIRED' using errcode='55000';end if;
  -- Hold closure writes and review writes until this atomic change commits: a check without these locks could admit a closure or a review between the check and the certificate replacement.
  lock table private.closure_executions_v5 in share mode;
  lock table private.closure_source_v5,private.closure_erasure_source_v5,private.closure_dataset_catalog_v5 in share row exclusive mode;
  lock table private.agreement_reviews in share row exclusive mode;
  lock table private.retention_data_classes in share row exclusive mode;
  -- The predecessor shape of the immutable star table, re-checked INSIDE this transaction (a preflight may be hours old): columns, constraints, triggers, ACL, forced RLS, no policy.
  if (select string_agg(attname::text||':'||format_type(atttypid,atttypmod)||':'||attnotnull::text||':'||attidentity::text||':'||attgenerated::text,',' order by attnum)
           from pg_attribute where attrelid='private.agreement_reviews'::regclass and attnum>0 and not attisdropped) is distinct from 'id:uuid:true::,agreement_id:uuid:true::,reviewer_account_id:uuid:true::,target_account_id:uuid:true::,rating:integer:true::,tags:text[]:true::,client_request_id:uuid:true::,input_hash:text:true::,created_at:timestamp with time zone:true::'
      or (select md5(string_agg(conname||':'||replace(pg_get_constraintdef(oid),'REFERENCES public.','REFERENCES '),';' order by conname)) from pg_constraint where conrelid='private.agreement_reviews'::regclass) is distinct from 'fe44059a7fa96aeb732ff3459f6865d1'
      or (select string_agg(tgname,',' order by tgname) from pg_trigger where tgrelid='private.agreement_reviews'::regclass and not tgisinternal) is distinct from 'pre_v3_closure_review,pre_v3_review_immutable'
      or (select relacl::text from pg_class where oid='private.agreement_reviews'::regclass) is distinct from '{postgres=arwdDxtm/postgres}'
      or not (select relrowsecurity and relforcerowsecurity from pg_class where oid='private.agreement_reviews'::regclass)
      or (select count(*) from pg_policy where polrelid='private.agreement_reviews'::regclass)<>0 then
    raise exception 'D12_APPLICATION_STAR_TABLE_DRIFT' using errcode='55000';end if;
  if exists(select 1 from private.closure_executions_v5 where state='EXECUTING') then
    raise exception 'D12_APPLICATION_CLOSURE_IN_FLIGHT' using errcode='55000';end if;
  if (select count(*) from private.closure_source_v5)<>1 or (select count(*) from private.closure_erasure_source_v5)<>1 then
    raise exception 'D12_APPLICATION_CERTIFICATE_CARDINALITY' using errcode='55000';end if;
  if to_regclass('private.agreement_review_comments_v1') is not null
     or exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where (n.nspname,p.proname) in(('private','guard_review_comment_mutation'),('private','review_comment_input_v1'),('public','rpc_submit_agreement_review_v2'),('public','rpc_get_my_agreement_review_v2'),('public','rpc_list_review_comments_v1'),('public','rpc_moderate_review_comment_service_v1')))
     or exists(select 1 from pg_trigger where tgname in('agreement_review_comment_closure_guard_v1','agreement_review_comment_mutation_guard_v1'))
     or exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='private' and c.relname in('agreement_review_comments_v1_author_idx','agreement_review_comments_v1_pkey','agreement_review_comments_v1_target_idx')) then
    raise exception 'D12_APPLICATION_ALREADY_PRESENT' using errcode='55000';end if;
  -- The retention class text this change appends to is exactly the predecessor text (a catalog row, no trigger, not hashed by any certified function).
  if (select description from private.retention_data_classes where code='AGREEMENT_REVIEWS' and required and active) is distinct from 'Immutable bilateral completed-Agreement reviews and their account-level reputation projection (private.agreement_reviews).' then
    raise exception 'D12_APPLICATION_RETENTION_CLASS_PREDECESSOR_DRIFT' using errcode='55000';end if;
  -- Exact DEV predecessor metadata: every function this change rewrites, replaces, calls or leaves untouched on purpose.
  for pin in select * from (values
    ('private.closure_redaction_relations_v5()','30967acfddf4a189e7d97f1230ce286b'),
    ('private.closure_redaction_scope_v5(text)','1d9ea6d4b770cb0da939e87b2218e1eb'),
    ('private.closure_redaction_patch_v5(text,jsonb,uuid,uuid)','6f2f71c85685d1c34f07c6b7eb8efc64'),
    ('private.retention_ai_source_ready()','60d41c1d50dbaedd8cbcd7a580fc21d2'),
    ('private.data_export_dataset_catalog()','206096870b0fd5eae1cb2780db2e6601'),
    ('private.data_export_snapshot(uuid,uuid,jsonb,timestamptz)','3965d2c8b12ff99d3c9dc928912890f1'),
    ('private.data_export_policy_binding()','a9596e2741a92a607cfd4cee0896604a'),
    ('public.rpc_submit_agreement_review(uuid,uuid,jsonb,jsonb,uuid)','a19f46c4668de2563f2edda6bb5b690f'),
    ('public.rpc_get_my_agreement_review(uuid)','ca42148a86a12c6129cd70feec7b54f6'),
    ('public.rpc_get_account_reputation(uuid)','11bbaac433967396787dca48002a3d7c'),
    ('public.rpc_get_public_profile(uuid)','c7de91ef7e30343f6cf6d49754382d82'),
    ('private.account_reputation(uuid)','0f4d25b7c14261835a5495ff40c2bef8'),
    ('private.guard_review_immutable()','60f1016a6f655c3b5f4e23bc1287f92b'),
    ('private.review_tag_catalog()','f7ddc53185277f0afbf0f2ea681dbc17'),
    ('private.review_tags_valid(text[])','8fcf97112d335bd9cf9a6fba921be85f'),
    ('public.rpc_list_my_agreements_page(text,integer,timestamptz,uuid)','891f18c2a10c9ada3bda3fa1b6e9e8ed'),
    ('public.rpc_home_attention()','1081f68fd348e9e1125a8e03786e0cf3'),
    ('private.closure_guard_owned_write()','eda4068416eb9a54691c331cbde691dd'),
    ('private.closure_redaction_allowed_v5(oid,text,jsonb,jsonb)','e4245b6db4ef8b0d4ee8846e684f511a'),
    ('private.closure_blockers_v5(uuid)','272d5ea792598448e86b127f4dc37c3c'),
    ('private.closure_erasure_binding_v5()','5b8021c77f85c119e95a41bbac2da3b1'),
    ('private.closure_source_digest_v5()','7ade1ea4e26aa1f5a7fb8a84553b89d4'),
    ('private.closure_erasure_program_digest_v5()','3b5059bc329407eface02b5b631d709d'),
    ('private.closure_schema_digest_v5_139()','226adf4b6cd896c5fa48fcab19780f35'),
    ('private.closure_assert_open(uuid,uuid)','7b0a4e1be3205b5de509ddfc726e406a'),
    ('private.closure_account_key(uuid)','20307d6e0d35a0c76b8e04fc12ded583'),
    ('private.closure_account_restricted(uuid)','814dfd0286240ae2eec5a2d2a56bbe51'),
    ('public.rpc_start_account_closure_execution(uuid,uuid,integer,uuid,text)','77bb6868db8bfcc02d56137e22c04dab'),
    ('public.rpc_closure_api_guard()','a36eea680eedb95a8d61632b060ca5ff'),
    ('public.rpc_redact_account_closure_step_service(uuid,uuid,uuid,uuid)','5a558704604067ae344261a2e84b6762'),
    ('private.support_reference_v5(uuid,jsonb)','1433a1360c044dc3a6d984af95c89668'),
    ('public.rpc_support_find_context_v5(uuid,text,uuid)','6a6a213a6f0e564905a09b127d889dd2'),
    ('private.audit_marketplace(uuid,text,text,uuid,integer,jsonb)','1f67d6123158625d421938e4b18bc0e0'),
    ('private.emit_event(uuid,text,text,text,uuid,integer,text,text,text,text,jsonb,timestamptz)','f42a9a9adeed0279cd446cae160746c6'),
    ('private.safety_pair_blocked(uuid,uuid)','7d6f3e0e0af60182f612bd0251c8f152'),
    ('private.accounts_same_world(uuid,uuid)','822aa2709088e7e2140c1d96d96a2794'),
    ('private.account_visibility_world(uuid)','7fd9af73365f1dfeae423da03950bd63'),
    ('private.ru4b_public_floor_reason(text)','db1ee32f5be6f43b23ae3522bfc0adce'),
    ('private.data_export_projection_sha_v5()','28fe45d56ec78178809319de4c643e25'),
    ('private.data_export_scalar_v5(jsonb,text)','9caa811e2b0b486d3fd5c888ae76b762'),
    ('private.data_export_array_v5(jsonb,text)','83ec48e5d734a1993abaf7d7682f7c29'),
    ('private.data_export_worker_candidate_v5(jsonb)','c5dc3f98fc276304fd4dbd196fb7e1e5'),
    ('private.data_export_task_facts_v5(jsonb)','9c3b78c23c2d7e7e2fbcc140744bc724'),
    ('public.rpc_submit_safety_report(uuid,uuid,uuid,text,text,text,uuid)','1f8550103d2b71dfa3aecd335525238c')
  ) p(signature,metadata_md5) loop
    if (select md5(((to_jsonb(p)-'oid'-'pronamespace'-'proowner'-'prolang'-'proacl'-'prosrc')
        ||jsonb_build_object('namespace',n.nspname,'owner',pg_get_userbyid(p.proowner),
          'language',l.lanname,'acl',p.proacl::text))::text)
      from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang
      where p.oid=to_regprocedure(pin.signature)) is distinct from pin.metadata_md5 then
      raise exception 'D12_APPLICATION_METADATA_DRIFT: %',pin.signature using errcode='55000';end if;
  end loop;
  -- (The functions with a composite argument or result type are pinned by body only: their metadata carries a per-database type OID and cannot be portable.)
  -- Exact DEV predecessor BODIES (LF-normalised). The readiness body is pinned below after replacing only its one certified literal.
  for pin in select * from (values
    ('private.closure_redaction_relations_v5()','e3ce45840fe907be2baf5d8ad051c74f'),
    ('private.closure_redaction_scope_v5(text)','0cf65a6947305b6c31e6138549016363'),
    ('private.closure_redaction_patch_v5(text,jsonb,uuid,uuid)','b1f6aa501bfbee2bfaa6ee60a22f19ef'),
    ('private.data_export_dataset_catalog()','7fc01c563915f0a168b9eb82d962bd06'),
    ('private.data_export_snapshot(uuid,uuid,jsonb,timestamptz)','b198bff51d2d67a6095ddcd00b7ba2e1'),
    ('private.data_export_policy_binding()','dd63c427109ffff1c940c335b34e0ad6'),
    ('public.rpc_submit_agreement_review(uuid,uuid,jsonb,jsonb,uuid)','ff68b552c4f972e5d58a632672bc359e'),
    ('public.rpc_get_my_agreement_review(uuid)','75a8b78ec8a5e6334f42366b4461c14c'),
    ('public.rpc_get_account_reputation(uuid)','4166221185edf108338898ba04f5e48a'),
    ('public.rpc_get_public_profile(uuid)','9ecc0b69096f1167d02e0bb7b9656bc0'),
    ('private.account_reputation(uuid)','f03e558ff56a31a0b49e394714b628cd'),
    ('private.review_receipt(private.agreement_reviews,boolean)','7058b3cc23f853edaea9cb21cdb865b1'),
    ('private.guard_review_immutable()','f883b4ed1be3dfa5401f98f9bdfe1960'),
    ('private.review_tag_catalog()','2b2ccb8e1c2672d091c3e319e4b1ea49'),
    ('private.review_tags_valid(text[])','69ca0f79f5869c13bcfaa392cc0ac6fa'),
    ('public.rpc_list_my_agreements_page(text,integer,timestamptz,uuid)','5017f90ff8d9e5cd29ead0f88a6b0106'),
    ('public.rpc_home_attention()','1703b04e248759a19cbcc539621ed906'),
    ('private.closure_guard_owned_write()','f13117fd601dcb82de423b78f25acb4f'),
    ('private.closure_redaction_allowed_v5(oid,text,jsonb,jsonb)','7fabcc71502e065e638364fc3d58b761'),
    ('private.closure_blockers_v5(uuid)','cd0c2921bfd52ba2e96769b2a409b9db'),
    ('private.closure_erasure_binding_v5()','d6d7e7f6f108fff45a4df5126949fa04'),
    ('private.closure_source_digest_v5()','9fb4a72f3feef8e4557a96f4c9d7224e'),
    ('private.closure_erasure_program_digest_v5()','229887adb43d52990dc4254176222696'),
    ('private.closure_schema_digest_v5_139()','988b9d3ab9c0dc7341cd30a391184e40'),
    ('private.closure_assert_open(uuid,uuid)','dc9bc4c718593850da4fdb49e612dbd2'),
    ('private.closure_account_key(uuid)','2dde6ad2462255b188e4f03ffe88edcd'),
    ('private.closure_account_restricted(uuid)','f4999250c315e0253374d4611291c7ad'),
    ('private.closure_erasure_assert_current_v5(private.closure_executions_v5)','be536bbccba9600ecc5c34f4a4d747de'),
    ('public.rpc_start_account_closure_execution(uuid,uuid,integer,uuid,text)','3fc04b344892a252956219ce85f4de34'),
    ('public.rpc_closure_api_guard()','09d52badff732c2b22ba7b69adfa4d66'),
    ('public.rpc_redact_account_closure_step_service(uuid,uuid,uuid,uuid)','0fd89c6c870f3496d485f97d8016ba7c'),
    ('private.closure_erasure_refresh_steps_v5(private.closure_executions_v5)','f228322985e8ae90bce17880d1ffd9c4'),
    ('private.support_reference_v5(uuid,jsonb)','94ad410f355654cffccd9de1084571bb'),
    ('public.rpc_support_find_context_v5(uuid,text,uuid)','66b392dcf118e3109e3a12ebd909c159'),
    ('private.audit_marketplace(uuid,text,text,uuid,integer,jsonb)','ef33e1d34afb1507071c47253a13c9b2'),
    ('private.emit_event(uuid,text,text,text,uuid,integer,text,text,text,text,jsonb,timestamptz)','67413effbbb3fa227397d355e0d4edfb'),
    ('private.safety_pair_blocked(uuid,uuid)','698fb21abb0379743bc7ab09d9f946ad'),
    ('private.accounts_same_world(uuid,uuid)','16f541f952d4e1e2dbb4fc87e594d572'),
    ('private.account_visibility_world(uuid)','876cfc16f0ed1c4d32b128e8e18bdcda'),
    ('private.ru4b_public_floor_reason(text)','3462ec034f1f9df9760e4729aa0d2c18'),
    ('private.data_export_projection_sha_v5()','f628ae258c3bae4a1d0fed0cde3dac53'),
    ('private.data_export_scalar_v5(jsonb,text)','e02fe0db0a56b90b74a29c2b81a38357'),
    ('private.data_export_array_v5(jsonb,text)','00933c589c16905b09318c080a2150f6'),
    ('private.data_export_worker_candidate_v5(jsonb)','aa9c5f1b7ab4711cda7cb16905de55a4'),
    ('private.data_export_task_facts_v5(jsonb)','b1552206df3434002e6d294befbca5b6'),
    ('public.rpc_submit_safety_report(uuid,uuid,uuid,text,text,text,uuid)','9249705c01cc3d29d178f1ebd331daeb')
  ) p(signature,body_md5) loop
    if (select md5(replace(prosrc,E'\r\n',E'\n')) from pg_proc where oid=to_regprocedure(pin.signature)) is distinct from pin.body_md5 then
      raise exception 'D12_APPLICATION_BODY_DRIFT: %',pin.signature using errcode='55000';end if;
  end loop;
  -- The three composite-typed functions: owner, ACL, security, configuration, volatility, strictness, language and result (their body is pinned above; their full metadata hash carries a per-database type OID and cannot be portable).
  for pin in select * from (values
    ('private.review_receipt(private.agreement_reviews,boolean)','{postgres=X/postgres}','{search_path=pg_catalog}',false,'s','plpgsql','jsonb',false),
    ('private.closure_erasure_assert_current_v5(private.closure_executions_v5)','{postgres=X/postgres}','{search_path=pg_catalog}',true,'v','plpgsql','void',false),
    ('private.closure_erasure_refresh_steps_v5(private.closure_executions_v5)','{postgres=X/postgres}','{search_path=pg_catalog}',true,'v','plpgsql','void',false)
  ) p(signature,acl,config,definer,volatility,language_name,result_type,strict_function) loop
    if not exists(select 1 from pg_proc p where p.oid=to_regprocedure(pin.signature) and p.proowner='postgres'::regrole and p.proacl::text=pin.acl and coalesce(p.proconfig::text,'')=pin.config and p.prosecdef=pin.definer and p.provolatile::text=pin.volatility
      and p.proisstrict=pin.strict_function and p.prolang=(select oid from pg_language where lanname=pin.language_name) and p.prorettype=to_regtype(pin.result_type) and p.prokind='f') then
      raise exception 'D12_APPLICATION_COMPOSITE_METADATA_DRIFT: %',pin.signature using errcode='55000';end if;
  end loop;
  -- Certificate and readiness: certified in all three places, equal to the live digest, ready, bound.
  select to_jsonb(c),sha256 into source_row,old_source from private.closure_source_v5 c where singleton;
  select to_jsonb(c) into erasure_row from private.closure_erasure_source_v5 c where singleton;
  select pg_get_functiondef(p.oid) into ready_definition from pg_proc p where oid='private.retention_ai_source_ready()'::regprocedure;
  if old_source is null or old_source is distinct from private.closure_source_digest_v5() or old_source is distinct from erasure_row->>'sha256'
     or private.retention_ai_source_ready() is distinct from true or private.closure_erasure_binding_v5()->>'sourceSha256' is distinct from old_source then
    raise exception 'D12_APPLICATION_CLOSURE_PREDECESSOR_NOT_READY' using errcode='55000';end if;
  if not exists(select 1 from pg_proc where oid='private.retention_ai_source_ready()'::regprocedure
      and (length(prosrc)-length(replace(prosrc,old_source,'')))=length(old_source)
      and md5(replace(replace(prosrc,E'\r\n',E'\n'),old_source,'__CERTIFIED_SOURCE__'))='bc85a1a744869abb6441e647b18b2195') then
    raise exception 'D12_APPLICATION_READINESS_PREDECESSOR_DRIFT' using errcode='55000';end if;
  if (length(ready_definition)-length(replace(ready_definition,old_source,'')))<>length(old_source)
     or (select count(*) from regexp_matches(ready_definition,'[0-9a-f]{64}','g'))<>1 then
    raise exception 'D12_APPLICATION_READINESS_LITERAL_DRIFT' using errcode='55000';end if;
  -- The roster, the catalog row and the review table are exactly what the design expects before the change.
  if cardinality(private.closure_redaction_relations_v5())<>75
     or 'private.agreement_reviews'=any(private.closure_redaction_relations_v5())
     or 'private.agreement_review_comments_v1'=any(private.closure_redaction_relations_v5())
     or (select relations from private.closure_dataset_catalog_v5 where data_class='AGREEMENT_REVIEWS') is distinct from array['private.agreement_reviews']::text[]
     or jsonb_array_length(private.data_export_dataset_catalog())<>52
     or private.data_export_projection_sha_v5() is distinct from '70009062e365b92295eba138a63868e84fd712ee270d9e6ea24237507e5eecfa' then
    raise exception 'D12_APPLICATION_ROSTER_OR_CATALOG_PREDECESSOR_DRIFT' using errcode='55000';end if;
  -- What the isolation probe needs: the three certified definitions exactly as they are now.
  pre_relations:=pg_get_functiondef('private.closure_redaction_relations_v5()'::regprocedure);
  pre_scope:=pg_get_functiondef('private.closure_redaction_scope_v5(text)'::regprocedure);
  pre_patch:=pg_get_functiondef('private.closure_redaction_patch_v5(text,jsonb,uuid,uuid)'::regprocedure);
  execute surface_query into before_surface;
  select string_agg(defaclnamespace::regnamespace::text||':'||defaclobjtype::text||':'||defaclacl::text,' | ' order by defaclnamespace::regnamespace::text,defaclobjtype::text) into before_default_acls from pg_default_acl;
  create temporary table d12_application_functions on commit drop as
    select p.oid,p.oid::regprocedure::text signature,to_jsonb(p) metadata
    from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    where n.nspname in('public','private','rls_private');
  select jsonb_agg(case when c.data_class='AGREEMENT_REVIEWS' then
    jsonb_set(to_jsonb(c),'{relations}',to_jsonb(c.relations||array['private.agreement_review_comments_v1']::text[]))
    else to_jsonb(c) end order by data_class) into expected_datasets from private.closure_dataset_catalog_v5 c;
  select md5(coalesce(string_agg(to_jsonb(r)::text,E'\n' order by r.id),'')) into star_before from private.agreement_reviews r;
  select jsonb_agg(case when c.code='AGREEMENT_REVIEWS' then jsonb_set(to_jsonb(c),'{description}',to_jsonb('Immutable bilateral completed-Agreement reviews and their account-level reputation projection (private.agreement_reviews), plus the optional written comment of a review (private.agreement_review_comments_v1): free text of the author, erased when the author account is closed; this description sets no retention period.'::text)) else to_jsonb(c) end order by c.code)
    into expected_classes from private.retention_data_classes c;
  rewritten:=array[to_regprocedure('private.closure_redaction_relations_v5()'),to_regprocedure('private.closure_redaction_scope_v5(text)'),to_regprocedure('private.closure_redaction_patch_v5(text,jsonb,uuid,uuid)'),to_regprocedure('private.data_export_dataset_catalog()'),to_regprocedure('private.data_export_snapshot(uuid,uuid,jsonb,timestamptz)'),to_regprocedure('private.data_export_policy_binding()')]::oid[];
  if cardinality(rewritten)<>6 or array_position(rewritten,null) is not null then raise exception 'D12_APPLICATION_REWRITTEN_ROSTER' using errcode='55000';end if;

  -- 1. The private table: one row per review that carries a comment, keyed by the review (so "at most one comment per review" is the primary key), nothing client-reachable.
  create table private.agreement_review_comments_v1(
    review_id uuid not null,
    author_account_id uuid not null,
    target_account_id uuid not null,
    comment text not null,
    comment_sha256 text not null,
    created_at timestamptz not null default clock_timestamp(),
    hidden_at timestamptz,
    hidden_reason_code text,
    constraint agreement_review_comments_v1_pkey primary key(review_id),
    constraint agreement_review_comments_v1_review_fkey foreign key(review_id) references private.agreement_reviews(id) on delete restrict,
    constraint agreement_review_comments_v1_author_fkey foreign key(author_account_id) references public.app_accounts(id) on delete restrict,
    constraint agreement_review_comments_v1_target_fkey foreign key(target_account_id) references public.app_accounts(id) on delete restrict,
    constraint agreement_review_comments_v1_parties_check check(author_account_id<>target_account_id),
    constraint agreement_review_comments_v1_text_length_check check(char_length(comment) between 1 and 500 and octet_length(comment)<=2000),
    constraint agreement_review_comments_v1_text_trim_check check(comment=btrim(comment,E' \n')),
    constraint agreement_review_comments_v1_text_chars_check check(comment !~ ('[' || chr(1) || '-' || chr(9) || chr(11) || '-' || chr(31) || chr(127) || '-' || chr(159) || chr(1564) || chr(4447) || '-' || chr(4448) || chr(6068) || '-' || chr(6069) || chr(6155) || '-' || chr(6159) || chr(8203) || chr(8206) || '-' || chr(8207) || chr(8232) || '-' || chr(8238) || chr(8288) || '-' || chr(8303) || chr(12644) || chr(65279) || chr(65440) || chr(65520) || '-' || chr(65531) || chr(78896) || '-' || chr(78911) || chr(113824) || '-' || chr(113827) || chr(119155) || '-' || chr(119162) || chr(917504) || '-' || chr(921599) || ']')),
    constraint agreement_review_comments_v1_sha_check check(comment_sha256 ~ '^[0-9a-f]{64}$'),
    constraint agreement_review_comments_v1_hidden_check check((hidden_at is null)=(hidden_reason_code is null) and (hidden_reason_code is null or hidden_reason_code ~ '^[A-Z][A-Z0-9_]{0,63}$'))
  );
  create index agreement_review_comments_v1_target_idx on private.agreement_review_comments_v1(target_account_id,created_at desc,review_id desc) where hidden_at is null;
  create index agreement_review_comments_v1_author_idx on private.agreement_review_comments_v1(author_account_id);
  alter table private.agreement_review_comments_v1 enable row level security;
  alter table private.agreement_review_comments_v1 force row level security;
  revoke all on private.agreement_review_comments_v1 from public,anon,authenticated,service_role;
  comment on table private.agreement_review_comments_v1 is 'Written comment of an immutable completed-Agreement review, one row per review that carries a comment (D12). Never reachable by a client role: read only through rpc_list_review_comments_v1 and the author own receipt. Immutable for every role; erased at the author account closure by the certified erasure program; the moderation function may only hide the text (hidden_at, hidden_reason_code). Stars, count and average live in private.agreement_reviews and never depend on this table.';

  -- 2. The new functions. The legacy review functions are not touched: every installed build keeps its star-only path with no new error name.
  create function private.guard_review_comment_mutation() returns trigger language plpgsql security definer set search_path = pg_catalog as $f$
begin
 -- The comment is part of an immutable review: no author edit, no author delete, for every role. Exactly two paths exist, both service-owned and both narrower than the table.
 if auth.role()='service_role' then
  -- 1. The account-closure erasure certificate (one locked row, one fixed DELETE patch, inside the service-owned SQL transaction): the author's own text goes, the review row stays.
  if tg_op='DELETE' and private.closure_redaction_allowed_v5(tg_relid,tg_op,to_jsonb(old),null) then return old; end if;
  -- 2. The audited moderation function: ONLY the two hide columns, ONLY while its transaction-local marker is on, and nothing else of the row may change.
  if tg_op='UPDATE' and current_setting('uskoci.review_comment_moderation',true) is not distinct from 'on'
   and (to_jsonb(new)-array['hidden_at','hidden_reason_code']) is not distinct from (to_jsonb(old)-array['hidden_at','hidden_reason_code']) then
   return new;
  end if;
 end if;
 raise exception 'REVIEW_COMMENT_IMMUTABLE' using errcode='42501';
end;
$f$;
  create trigger agreement_review_comment_closure_guard_v1 before insert on private.agreement_review_comments_v1
    for each row execute function private.closure_guard_owned_write('ACCOUNT','author_account_id');
  create trigger agreement_review_comment_mutation_guard_v1 before update or delete on private.agreement_review_comments_v1
    for each row execute function private.guard_review_comment_mutation();
  create function private.review_comment_input_v1(p_comment jsonb) returns text language plpgsql stable set search_path = pg_catalog as $f$
declare v text; n text;
begin
 -- Absent: SQL NULL, JSON null, or a string with nothing but white space. Nothing is stored for an absent comment and a later comment can never be added (the review is immutable).
 if p_comment is null or jsonb_typeof(p_comment)='null' then return null; end if;
 if jsonb_typeof(p_comment)<>'string' then raise exception 'REVIEW_COMMENT_INVALID' using errcode='22023'; end if;
 if octet_length(p_comment::text)>8192 then raise exception 'REVIEW_COMMENT_TOO_LONG' using errcode='22023'; end if;
 v:=p_comment#>>'{}';
 -- "No comment": white space (an EXPLICIT class: ASCII white space U+0009..U+000D and U+0020, U+0085 and the Unicode separators; never the locale dependent POSIX class, so U+001C..U+001F are not blank and a lone one is INVALID in every
 -- locale), characters that render as nothing but are tolerated inside a sentence (soft hyphen, combining grapheme joiner, braille blank), the two joiners and ALL sixteen variation selectors ONLY. Every class below is built from chr() pieces:
 -- no escape text, no invisible character in this source. The forbidden class below is every default-ignorable code point of Unicode 17.0 except those allowed-inside groups, plus the controls (see README_D12_CANDIDATE.md, Text rules).
 if btrim(v,E' \n')='' or v ~ ('^[' || chr(9) || '-' || chr(13) || chr(32) || chr(133) || chr(160) || chr(173) || chr(847) || chr(5760) || chr(8192) || '-' || chr(8202) || chr(8204) || '-' || chr(8205) || chr(8232) || '-' || chr(8233) || chr(8239) || chr(8287) || chr(10240) || chr(12288) || chr(65024) || '-' || chr(65039) || ']*$') then return null; end if;
 -- The length is counted in code points of the text as sent; the octet cap is defence in depth (500 code points are at most 2000 octets, so it can never fire first). The server REJECTS, it never normalises (the client compares the echoed text).
 if char_length(v)>500 or octet_length(v)>2000 then raise exception 'REVIEW_COMMENT_TOO_LONG' using errcode='22023'; end if;
 if v<>btrim(v,E' \n') or v ~ ('[' || chr(1) || '-' || chr(9) || chr(11) || '-' || chr(31) || chr(127) || '-' || chr(159) || chr(1564) || chr(4447) || '-' || chr(4448) || chr(6068) || '-' || chr(6069) || chr(6155) || '-' || chr(6159) || chr(8203) || chr(8206) || '-' || chr(8207) || chr(8232) || '-' || chr(8238) || chr(8288) || '-' || chr(8303) || chr(12644) || chr(65279) || chr(65440) || chr(65520) || '-' || chr(65531) || chr(78896) || '-' || chr(78911) || chr(113824) || '-' || chr(113827) || chr(119155) || '-' || chr(119162) || chr(917504) || '-' || chr(921599) || ']') then raise exception 'REVIEW_COMMENT_INVALID' using errcode='22023'; end if;
 -- Deterministic contact floor (no AI, no provider): e-mail, link, @handle and a phone number that starts with 0, 00, + or 381 (8 to 13 digits, not a date shape) are refused with ONE plain code (the live PKG-029c floor). It runs on the text as sent
 -- AND on an NFKC-normalised copy without invisible characters and with Arabic-Indic and Persian digits mapped to ASCII, so full-width digits or '@', a soft hyphen or a zero-width joiner inside a number do not hide it; the STORED text is the original.
 -- It is a screen against careless contact details, NOT privacy protection: a number without its leading 0 or 381, 7-digit runs, digits split by letters or by combining marks, digits of other numeral systems (for example Devanagari),
 -- spelled-out numbers, bare domains, short links and handles without @ pass.
 n:=translate(regexp_replace(normalize(v,NFKC),('[' || chr(173) || chr(847) || chr(8204) || '-' || chr(8205) || chr(10240) || chr(65024) || '-' || chr(65039) || ']'),'','g'),chr(1632) || chr(1633) || chr(1634) || chr(1635) || chr(1636) || chr(1637) || chr(1638) || chr(1639) || chr(1640) || chr(1641) || chr(1776) || chr(1777) || chr(1778) || chr(1779) || chr(1780) || chr(1781) || chr(1782) || chr(1783) || chr(1784) || chr(1785),'01234567890123456789');
 if private.ru4b_public_floor_reason(v) is not null or private.ru4b_public_floor_reason(n) is not null then raise exception 'REVIEW_COMMENT_CONTACT_NOT_PUBLIC' using errcode='22023'; end if;
 return v;
end;
$f$;
  create function public.rpc_submit_agreement_review_v2(p_agreement_id uuid, p_target_account_id uuid, p_rating jsonb, p_tags jsonb, p_client_request_id uuid, p_comment jsonb default null) returns jsonb language plpgsql security definer set search_path = pg_catalog as $f$
declare u uuid:=auth.uid(); a public.agreements; r private.agreement_reviews;
 rating_value numeric; tags_value text[]; h text; target_role text;
 comment_value text; comment_sha text; stored_comment text; stored_sha text;
begin
 -- D12: the legacy review command (same auth, validation order, locks, eligibility, star hash, audit row and REVIEW_RECEIVED event, byte for byte in behaviour) plus ONE optional comment
 -- that is stored in the SAME transaction as the stars and never later. The legacy function stays untouched and keeps serving every installed build.
 if u is null then raise exception 'AUTH_REQUIRED' using errcode='42501'; end if;
 if p_agreement_id is null or p_target_account_id is null or p_target_account_id=u or p_client_request_id is null
 or jsonb_typeof(p_rating) is distinct from 'number' or length(p_rating::text)>30 then
  raise exception 'REVIEW_INPUT_INVALID' using errcode='22023';
 end if;
 rating_value:=(p_rating#>>'{}')::numeric;
 if rating_value not between 1 and 5 or trunc(rating_value)<>rating_value then
  raise exception 'REVIEW_INPUT_INVALID' using errcode='22023';
 end if;
 if jsonb_typeof(p_tags) is distinct from 'array' then raise exception 'REVIEW_TAGS_INVALID' using errcode='22023'; end if;
 if jsonb_array_length(p_tags)>3 or exists(select 1 from jsonb_array_elements(p_tags) t
  where jsonb_typeof(t.value)<>'string' or not (t.value#>>'{}'=any(private.review_tag_catalog()))) then
  raise exception 'REVIEW_TAGS_INVALID' using errcode='22023';
 end if;
 tags_value:=array(select t.value#>>'{}' from jsonb_array_elements(p_tags) t order by (t.value#>>'{}') collate "C");
 if not private.review_tags_valid(tags_value) then raise exception 'REVIEW_TAGS_INVALID' using errcode='22023'; end if;
 -- The star hash keeps the legacy formula exactly (so every stored hash and every replay through either function stays compatible); the comment is bound by its own digest in its own row.
 h:=encode(extensions.digest(jsonb_build_object('agreementId',p_agreement_id,'target',p_target_account_id,
  'rating',rating_value::integer,'tags',to_jsonb(tags_value))::text,'sha256'),'hex');
 comment_value:=private.review_comment_input_v1(p_comment);
 comment_sha:=case when comment_value is null then null else encode(extensions.digest(convert_to(comment_value,'UTF8'),'sha256'),'hex') end;
 -- Same successful command remains an immutable read, even after a later block.
 perform pg_advisory_xact_lock(hashtextextended('uskoci:review-command:'||u::text||':'||p_client_request_id::text,9120));
 select * into r from private.agreement_reviews where reviewer_account_id=u and client_request_id=p_client_request_id;
 if found then
  if r.input_hash<>h then raise exception 'REQUEST_ID_REUSED' using errcode='22023'; end if;
  -- A comment that differs from the stored one (or one added to a stored star-only review) is another command under the same id.
  select c.comment,c.comment_sha256 into stored_comment,stored_sha from private.agreement_review_comments_v1 c where c.review_id=r.id;
  if stored_sha is distinct from comment_sha then raise exception 'REQUEST_ID_REUSED' using errcode='22023'; end if;
  return private.review_receipt(r,true)||jsonb_build_object('comment',stored_comment);
 end if;
 select * into a from public.agreements where id=p_agreement_id and u in(requester_account_id,worker_account_id) for share;
 if not found then raise exception 'REVIEW_NOT_ALLOWED' using errcode='42501'; end if;
 if p_target_account_id<>(case when u=a.requester_account_id then a.worker_account_id else a.requester_account_id end) then
  raise exception 'REVIEW_NOT_ALLOWED' using errcode='42501';
 end if;
 if a.status<>'COMPLETED' or not exists(select 1 from public.agreement_execution where agreement_id=a.id and state='COMPLETED') then
  raise exception 'REVIEW_NOT_COMPLETED' using errcode='55000';
 end if;
 perform pg_advisory_xact_lock(hashtextextended('uskoci:review-agreement:'||a.id::text||':'||u::text,9120));
 if exists(select 1 from private.agreement_reviews where agreement_id=a.id and reviewer_account_id=u) then
  raise exception 'REVIEW_ALREADY_SUBMITTED' using errcode='55000';
 end if;
 -- A block cannot remove the counterpart's completed-work review entitlement (stars and comment alike; a refusal would reveal the block).
 -- P8 suppresses ordinary deliveries, including this event, for blocked pairs. The comment is hidden from readers while the pair is blocked, at read time.
 insert into private.agreement_reviews(agreement_id,reviewer_account_id,target_account_id,rating,tags,client_request_id,input_hash)
 values(a.id,u,p_target_account_id,rating_value::integer,tags_value,p_client_request_id,h) returning * into r;
 if comment_value is not null then
  insert into private.agreement_review_comments_v1(review_id,author_account_id,target_account_id,comment,comment_sha256,created_at)
  values(r.id,r.reviewer_account_id,r.target_account_id,comment_value,comment_sha,r.created_at);
 end if;
 perform private.audit_marketplace(u,'AGREEMENT_REVIEW_SUBMITTED','AGREEMENT',a.id,a.current_version,jsonb_build_object('reviewId',r.id));
 target_role:=case when u=a.requester_account_id then 'WORKER' else 'REQUESTER' end;
 perform private.emit_event(p_target_account_id,target_role,'REVIEW_RECEIVED','AGREEMENT',a.id,a.current_version,
  'Nova ocena','Dobili ste ocenu za zavr'||chr(353)||'en Dogovor.','agreement-review:'||r.id::text,'NORMAL','{}'::jsonb,null);
 return private.review_receipt(r,false)||jsonb_build_object('comment',comment_value);
end;
$f$;
  create function public.rpc_get_my_agreement_review_v2(p_agreement_id uuid) returns jsonb language plpgsql stable security definer set search_path = pg_catalog as $f$
declare u uuid:=auth.uid(); a public.agreements; r private.agreement_reviews; own_review jsonb; own_comment text;
begin
 -- D12: the legacy context (same participant gate, same eligibility incl. the closure restriction, same tag catalog) plus the author's OWN comment inside the review and the comment policy.
 -- The presence of THIS function is the capability a new client tests; an older server answers PGRST202 and the client falls back to the legacy pair.
 if u is null then raise exception 'AUTH_REQUIRED' using errcode='42501'; end if;
 select * into a from public.agreements where id=p_agreement_id and u in(requester_account_id,worker_account_id);
 if not found then raise exception 'REVIEW_NOT_ALLOWED' using errcode='42501'; end if;
 select * into r from private.agreement_reviews where agreement_id=a.id and reviewer_account_id=u;
 if found then
  select c.comment into own_comment from private.agreement_review_comments_v1 c where c.review_id=r.id;
  own_review:=private.review_receipt(r,false)||jsonb_build_object('comment',own_comment);
 end if;
 return jsonb_build_object('accountId',u,'agreementId',a.id,
 'targetAccountId',case when u=a.requester_account_id then a.worker_account_id else a.requester_account_id end,
 'eligible',own_review is null and not private.closure_account_restricted(u) and a.status='COMPLETED' and exists(select 1 from public.agreement_execution where agreement_id=a.id and state='COMPLETED'),
 'review',own_review,'tagCatalog',jsonb_build_object('version','PRE_V3_REVIEW_TAGS_V1','maxTags',3,'tags',to_jsonb(private.review_tag_catalog())),
 'commentPolicy',jsonb_build_object('supported',true,'maxLength',500,'version','REVIEW_COMMENT_V1'),
 'authoritative',true);
end;
$f$;
  create function public.rpc_list_review_comments_v1(p_profile_id uuid, p_limit integer default 20, p_after jsonb default null) returns jsonb language plpgsql stable security definer set search_path = pg_catalog as $f$
declare v_actor uuid:=auth.uid(); v_profile public.app_profiles; v_limit integer; v_after_at timestamptz; v_after_id uuid; v_items jsonb; v_more boolean;
begin
 -- D12: the gated reader of the written comments ABOUT the person whose public profile is open. One paged, account-level list (a review is account-level reputation, both roles pooled);
 -- only reviews that carry a visible comment appear (a star-only review has no text row, but the public count and average still include it, so for a small count the rating of a star-only review can be inferred by subtraction from the
 -- listed ratings: an owner-visible consequence, README_D12_CANDIDATE.md); stars, the count and the average are never changed by anything here.
 -- DESIGN DEFAULT D-DEC-7 (the owner accepted the defaults of the design): ONE account-level list usable from both profile kinds, so the same reviewIds and texts appear under the REQUESTER and the WORKER profile of one person and each item names the role
 -- of its author: an observer who has seen both faces can LINK them by comparing lists. A role-scoped list is a function-only change (add: and the target role of the Agreement equals v_profile.kind) that needs no certificate move; it is NOT implemented here.
 if v_actor is null then raise exception 'AUTH_REQUIRED' using errcode='42501'; end if;
 if p_profile_id is null then raise exception 'PROFILE_ID_REQUIRED' using errcode='22023'; end if;
 v_limit:=least(greatest(coalesce(p_limit,20),1),50);
 if p_after is not null and jsonb_typeof(p_after)<>'null' then
  if jsonb_typeof(p_after)<>'object' or jsonb_typeof(p_after->'createdAt') is distinct from 'string' or jsonb_typeof(p_after->'reviewId') is distinct from 'string' then
   raise exception 'INVALID_PAGE' using errcode='22023';
  end if;
  begin
   v_after_at:=(p_after->>'createdAt')::timestamptz; v_after_id:=(p_after->>'reviewId')::uuid;
  exception when data_exception then raise exception 'INVALID_PAGE' using errcode='22023';
  end;
 end if;
 -- The gate stack of rpc_get_public_profile, in the same order and with the same safe failure: an ACTIVE profile only, closure-restricted viewer or subject, a blocked pair and another world all read as "nothing here".
 select p.* into v_profile from public.app_profiles p where p.id=p_profile_id and p.profile_status='ACTIVE' and p.kind in('REQUESTER','WORKER');
 if not found then return null; end if;
 if private.closure_account_restricted(v_actor) or private.closure_account_restricted(v_profile.account_id) then return null; end if;
 if private.safety_pair_blocked(v_actor,v_profile.account_id) then return null; end if;
 if not private.accounts_same_world(v_actor,v_profile.account_id) then return null; end if;
 -- Read-time gating of every row: a hidden comment, an author under a closure restriction, a pair VIEWER/author that is blocked either way (the viewer-versus-subject pair is gated above), another world, or an author profile that is not ACTIVE is not listed.
 -- DELIBERATELY NO viewer-independent block gate: a block between the author and the reviewed person must NOT remove the comment for third viewers, otherwise either party could censor or re-publish the text for everybody by toggling a block (the author edit/delete path
 -- the owner forbade, through a side door). It still hides the text from the one person who blocked its author, because that person is the VIEWER here. Hiding for everyone is the audited moderation HIDE only.
 -- KNOWN CONSEQUENCE (owner-visible, NOT decided here): the block is symmetric, so when the AUTHOR blocks the reviewed person (or blocked them before writing) that person is the viewer of a blocked pair and no longer sees the comment
 -- about them (nor its agreementId, so they cannot report it from here), is not notified, and every third viewer still sees it; the block costs the author nothing and the only remedy is the audited service-role HIDE. Options: README_D12_CANDIDATE.md.
 -- No write-time refusal exists for any of this (it would reveal a block); the author's profile is the face of the Agreement role in which the review was written. The only place an account id can appear is inside avatarPath, exactly as rpc_get_public_profile returns it.
 select coalesce(jsonb_agg(x.item order by x.created_at desc,x.review_id desc),'[]'::jsonb) into v_items from (
  select c.created_at,c.review_id,
   jsonb_build_object('reviewId',c.review_id,'rating',rv.rating,'comment',c.comment,'createdAt',c.created_at,
    'agreementId',case when v_actor=c.target_account_id then rv.agreement_id else null end,
    'author',jsonb_build_object('profileId',ap.id,'role',ap.kind,'displayName',nullif(btrim(ap.display_name),''),'avatarPath',ap.avatar_path)) as item
  from private.agreement_review_comments_v1 c
  join private.agreement_reviews rv on rv.id=c.review_id
  join public.agreements ag on ag.id=rv.agreement_id
  join public.app_profiles ap on ap.id=case when ag.requester_account_id=c.author_account_id then ag.requester_profile_id else ag.worker_profile_id end
   and ap.account_id=c.author_account_id
  where c.target_account_id=v_profile.account_id and c.hidden_at is null
   and ap.profile_status='ACTIVE' and ap.kind in('REQUESTER','WORKER')
   and not private.closure_account_restricted(c.author_account_id)
   and not private.safety_pair_blocked(v_actor,c.author_account_id)
   and private.accounts_same_world(v_actor,c.author_account_id)
   and (v_after_at is null or (c.created_at,c.review_id)<(v_after_at,v_after_id))
  order by c.created_at desc,c.review_id desc
  limit v_limit+1
 ) x;
 v_more:=jsonb_array_length(v_items)>v_limit;
 if v_more then v_items:=v_items-v_limit; end if;
 return jsonb_build_object('profileId',v_profile.id,'items',v_items,'hasMore',v_more,
  'nextAfter',case when v_more then jsonb_build_object('createdAt',v_items->(v_limit-1)->'createdAt','reviewId',v_items->(v_limit-1)->'reviewId') else null end,
  'authoritative',true);
end;
$f$;
  create function public.rpc_moderate_review_comment_service_v1(p_review_id uuid, p_action text, p_reason_code text, p_client_request_id uuid) returns jsonb language plpgsql security definer set search_path = pg_catalog as $f$
declare c private.agreement_review_comments_v1; v_agreement uuid; v_hide boolean;
begin
 -- D12 moderation (owner decision D-DEC-2): HIDE or RESTORE the TEXT of one comment, by the service role only, by an operator who acts on purpose (the owner, in a controlled test). There is no automatic
 -- trigger, no AI, no notification and no author action. Stars, the count, the average and ratingDue are never touched: only the two hide columns of the comment row change.
 if auth.role() is distinct from 'service_role' then raise exception 'SERVICE_ROLE_REQUIRED' using errcode='42501'; end if;
 if p_review_id is null or p_client_request_id is null or p_action is null or p_action not in('HIDE','RESTORE')
  or (p_action='HIDE' and (p_reason_code is null or p_reason_code !~ '^[A-Z][A-Z0-9_]{0,63}$'))
  or (p_action='RESTORE' and p_reason_code is not null) then
  raise exception 'REVIEW_COMMENT_MODERATION_INVALID' using errcode='22023';
 end if;
 v_hide:=p_action='HIDE';
 select * into c from private.agreement_review_comments_v1 where review_id=p_review_id for update;
 if not found then raise exception 'REVIEW_COMMENT_NOT_FOUND' using errcode='P0002'; end if;
 -- Idempotent by state: repeating the same action changes and writes nothing. HIDE under another reason needs a RESTORE first (a deterministic conflict: PT409, never the SQLSTATE that PostgREST retries without end).
 if v_hide and c.hidden_at is not null then
  if c.hidden_reason_code=p_reason_code then
   return jsonb_build_object('reviewId',c.review_id,'hidden',true,'reasonCode',c.hidden_reason_code,'changed',false,'authoritative',true);
  end if;
  raise exception 'REVIEW_COMMENT_MODERATION_CONFLICT' using errcode='PT409';
 end if;
 if not v_hide and c.hidden_at is null then
  return jsonb_build_object('reviewId',c.review_id,'hidden',false,'reasonCode',null,'changed',false,'authoritative',true);
 end if;
 perform set_config('uskoci.review_comment_moderation','on',true);
 update private.agreement_review_comments_v1
  set hidden_at=case when v_hide then clock_timestamp() else null end,
      hidden_reason_code=case when v_hide then p_reason_code else null end
  where review_id=c.review_id;
 perform set_config('uskoci.review_comment_moderation','off',true);
 select agreement_id into v_agreement from private.agreement_reviews where id=c.review_id;
 -- Audit: ids and the reason code only, never any text. The actor is the service role (no account), so the actor column stays empty.
 perform private.audit_marketplace(null,case when v_hide then 'AGREEMENT_REVIEW_COMMENT_HIDDEN' else 'AGREEMENT_REVIEW_COMMENT_RESTORED' end,'AGREEMENT',v_agreement,null,
  jsonb_build_object('reviewId',c.review_id,'reasonCode',coalesce(p_reason_code,c.hidden_reason_code),'requestId',p_client_request_id));
 return jsonb_build_object('reviewId',c.review_id,'hidden',v_hide,'reasonCode',case when v_hide then p_reason_code else null end,'changed',true,'authoritative',true);
end;
$f$;
  revoke all on function private.guard_review_comment_mutation(),private.review_comment_input_v1(jsonb),public.rpc_submit_agreement_review_v2(uuid,uuid,jsonb,jsonb,uuid,jsonb),public.rpc_get_my_agreement_review_v2(uuid),public.rpc_list_review_comments_v1(uuid,integer,jsonb),public.rpc_moderate_review_comment_service_v1(uuid,text,text,uuid) from public,anon,authenticated,service_role;
  grant execute on function public.rpc_submit_agreement_review_v2(uuid,uuid,jsonb,jsonb,uuid,jsonb),public.rpc_get_my_agreement_review_v2(uuid),public.rpc_list_review_comments_v1(uuid,integer,jsonb) to authenticated;
  grant execute on function public.rpc_moderate_review_comment_service_v1(uuid,text,text,uuid) to service_role;

  -- 3. The certified erasure program and the export: each edit is ONE exact replace on the current definition, the anchor having been pinned to occur exactly once.
  edit_definition:=pg_get_functiondef('private.closure_redaction_relations_v5()'::regprocedure);
  if (length(edit_definition)-length(replace(edit_definition,$a$'public.app_profiles','public.app_accounts'$a$,'')))<>length($a$'public.app_profiles','public.app_accounts'$a$) then
    raise exception 'D12_RELATIONS_ANCHOR_1_DRIFT' using errcode='55000';end if;
  execute replace(edit_definition,$a$'public.app_profiles','public.app_accounts'$a$,$a$'public.app_profiles','public.app_accounts','private.agreement_review_comments_v1'$a$);
  edit_definition:=pg_get_functiondef('private.closure_redaction_scope_v5(text)'::regprocedure);
  if (length(edit_definition)-length(replace(edit_definition,$a$when r in('private.need_edit_commands','private.need_publish_commands','private.remaining_search_close_commands') then 't.requester_account_id=$1'$a$,'')))<>length($a$when r in('private.need_edit_commands','private.need_publish_commands','private.remaining_search_close_commands') then 't.requester_account_id=$1'$a$) then
    raise exception 'D12_SCOPE_ANCHOR_1_DRIFT' using errcode='55000';end if;
  execute replace(edit_definition,$a$when r in('private.need_edit_commands','private.need_publish_commands','private.remaining_search_close_commands') then 't.requester_account_id=$1'$a$,$a$when r='private.agreement_review_comments_v1' then 't.author_account_id=$1' when r in('private.need_edit_commands','private.need_publish_commands','private.remaining_search_close_commands') then 't.requester_account_id=$1'$a$);
  edit_definition:=pg_get_functiondef('private.closure_redaction_patch_v5(text,jsonb,uuid,uuid)'::regprocedure);
  if (length(edit_definition)-length(replace(edit_definition,$a$'private.support_read_markers_v5','private.group_message_visibility_v5') then$a$,'')))<>length($a$'private.support_read_markers_v5','private.group_message_visibility_v5') then$a$) then
    raise exception 'D12_PATCH_ANCHOR_1_DRIFT' using errcode='55000';end if;
  execute replace(edit_definition,$a$'private.support_read_markers_v5','private.group_message_visibility_v5') then$a$,$a$'private.support_read_markers_v5','private.group_message_visibility_v5','private.agreement_review_comments_v1') then$a$);
  edit_definition:=pg_get_functiondef('private.data_export_dataset_catalog()'::regprocedure);
  if (length(edit_definition)-length(replace(edit_definition,$a$"key": "ownAgreementReviews", "fields": ["agreementId", "createdAt", "id", "rating", "tags"]$a$,'')))<>length($a$"key": "ownAgreementReviews", "fields": ["agreementId", "createdAt", "id", "rating", "tags"]$a$) then
    raise exception 'D12_EXPORT_CATALOG_ANCHOR_1_DRIFT' using errcode='55000';end if;
  execute replace(edit_definition,$a$"key": "ownAgreementReviews", "fields": ["agreementId", "createdAt", "id", "rating", "tags"]$a$,$a$"key": "ownAgreementReviews", "fields": ["agreementId", "createdAt", "id", "rating", "tags", "comment"]$a$);
  edit_definition:=pg_get_functiondef('private.data_export_snapshot(uuid,uuid,jsonb,timestamptz)'::regprocedure);
  if (length(edit_definition)-length(replace(edit_definition,$a$'tags',t.tags,'createdAt',t.created_at) as value from private.agreement_reviews t$a$,'')))<>length($a$'tags',t.tags,'createdAt',t.created_at) as value from private.agreement_reviews t$a$) then
    raise exception 'D12_EXPORT_SNAPSHOT_ANCHOR_1_DRIFT' using errcode='55000';end if;
  if (length(edit_definition)-length(replace(edit_definition,$a$'OWN_ACCOUNT_V5_9'$a$,'')))<>length($a$'OWN_ACCOUNT_V5_9'$a$) then
    raise exception 'D12_EXPORT_SNAPSHOT_ANCHOR_2_DRIFT' using errcode='55000';end if;
  execute replace(replace(edit_definition,$a$'tags',t.tags,'createdAt',t.created_at) as value from private.agreement_reviews t$a$,$a$'tags',t.tags,'createdAt',t.created_at,'comment',(select c.comment from private.agreement_review_comments_v1 c where c.review_id=t.id)) as value from private.agreement_reviews t$a$),$a$'OWN_ACCOUNT_V5_9'$a$,$a$'OWN_ACCOUNT_V5_10'$a$);
  edit_definition:=pg_get_functiondef('private.data_export_policy_binding()'::regprocedure);
  if (length(edit_definition)-length(replace(edit_definition,$a$'OWN_ACCOUNT_V5_9'$a$,'')))<>length($a$'OWN_ACCOUNT_V5_9'$a$) then
    raise exception 'D12_EXPORT_BINDING_ANCHOR_1_DRIFT' using errcode='55000';end if;
  execute replace(edit_definition,$a$'OWN_ACCOUNT_V5_9'$a$,$a$'OWN_ACCOUNT_V5_10'$a$);
  update private.closure_dataset_catalog_v5 set relations=relations||array['private.agreement_review_comments_v1']::text[] where data_class='AGREEMENT_REVIEWS' and relations=array['private.agreement_reviews']::text[];
  get diagnostics affected=row_count;
  if affected<>1 then raise exception 'D12_APPLICATION_CATALOG_ROW_COUNT' using errcode='55000';end if;
  -- The class text: the optional free text now lives in the class AGREEMENT_REVIEWS, so its description says so (it states what is implemented and sets no retention period). ONE row, pinned by its old text.
  update private.retention_data_classes set description='Immutable bilateral completed-Agreement reviews and their account-level reputation projection (private.agreement_reviews), plus the optional written comment of a review (private.agreement_review_comments_v1): free text of the author, erased when the author account is closed; this description sets no retention period.' where code='AGREEMENT_REVIEWS' and required and active and description='Immutable bilateral completed-Agreement reviews and their account-level reputation projection (private.agreement_reviews).';
  get diagnostics affected=row_count;
  if affected<>1 then raise exception 'D12_APPLICATION_RETENTION_CLASS_ROW_COUNT' using errcode='55000';end if;

  -- 4. The rewritten bodies, exactly: the md5 (LF-normalised) each body must have after this change. They are computed by the generator from the pinned DEV pre-image and the same anchor replacements,
  -- so on DEV, whose predecessor bodies are pinned above, the exact-once replacements can only produce these bytes.
  for pin in select * from (values
    ('private.closure_redaction_relations_v5()','ba362b6d0045d06e6207fc0a8f0592d4'),
    ('private.closure_redaction_scope_v5(text)','aec26bb057ec0022245a5d8641a47585'),
    ('private.closure_redaction_patch_v5(text,jsonb,uuid,uuid)','3891fe77d38af04e06cfe4c9e4abb96f'),
    ('private.data_export_dataset_catalog()','b19598a0ad6547de9609da121f5d4a3e'),
    ('private.data_export_snapshot(uuid,uuid,jsonb,timestamptz)','a50e4f7203df2a65cff264ee2471c13c'),
    ('private.data_export_policy_binding()','3695d063e7c8fa9f835b5e8cc34b5926')
  ) p(signature,body_md5) loop
    if (select md5(replace(prosrc,E'\r\n',E'\n')) from pg_proc where oid=to_regprocedure(pin.signature)) is distinct from pin.body_md5 then
      raise exception 'D12_APPLICATION_REWRITTEN_BODY_DELTA: %',pin.signature using errcode='55000';end if;
  end loop;
  if private.data_export_projection_sha_v5() is distinct from '53848e48d1a01082fcbd1413e4f9210b43153a9eb75e7af2723aa8c40f32b597' then
    raise exception 'D12_APPLICATION_PROJECTION_SHA_DELTA' using errcode='55000';end if;

  -- 5. The certificate. The digest must have moved, and the certificate is UNCERTIFIED until the exact three-place re-bind below.
  new_source:=private.closure_source_digest_v5();
  if new_source is null or new_source=old_source or new_source!~'^[0-9a-f]{64}$' then
    raise exception 'D12_APPLICATION_NEW_SOURCE_INVALID' using errcode='55000';end if;
  if private.retention_ai_source_ready() is distinct from false or private.closure_erasure_binding_v5() is not null then
    raise exception 'D12_APPLICATION_UNCERTIFIED_STATE_NOT_CLOSED' using errcode='55000';end if;
  -- Isolation probe: undo ONLY the certified-surface change (the three edited certified definitions and the new table with its triggers) inside a nested block that is always rolled back,
  -- and read the digest there. It must be exactly the OLD certified value: the digest moved because of THIS change and nothing else (the new functions and the export edits are outside it).
  begin
    execute pre_relations;
    execute pre_scope;
    execute pre_patch;
    drop table private.agreement_review_comments_v1;
    raise exception 'D12_ISOLATION_PROBE' using errcode='55000',detail=private.closure_source_digest_v5();
  exception when sqlstate '55000' then
    get stacked diagnostics probe_message=message_text,probe_digest=pg_exception_detail;
    if probe_message is distinct from 'D12_ISOLATION_PROBE' then raise; end if;
  end;
  if probe_digest is distinct from old_source then
    raise exception 'D12_APPLICATION_DIGEST_NOT_ISOLATED: probe % old %',probe_digest,old_source using errcode='55000';end if;
  if to_regclass('private.agreement_review_comments_v1') is null or pg_get_functiondef('private.closure_redaction_relations_v5()'::regprocedure) is not distinct from pre_relations then
    raise exception 'D12_APPLICATION_PROBE_NOT_ROLLED_BACK' using errcode='55000';end if;
  update private.closure_source_v5 set sha256=new_source where singleton and sha256=old_source;
  get diagnostics affected=row_count;
  if affected<>1 then raise exception 'D12_APPLICATION_SOURCE_ROW_COUNT' using errcode='55000';end if;
  update private.closure_erasure_source_v5 set sha256=new_source where singleton and sha256=old_source;
  get diagnostics affected=row_count;
  if affected<>1 then raise exception 'D12_APPLICATION_ERASURE_ROW_COUNT' using errcode='55000';end if;
  execute replace(ready_definition,old_source,new_source);

  -- Delta accounting 1/4: every old function is unchanged, except the readiness constant and the rewritten ones (their body only; owner, ACL, security, configuration and result stay).
  for prior in select * from d12_application_functions loop
    select to_jsonb(p) into actual from pg_proc p where oid=prior.oid;
    if actual is null then raise exception 'D12_APPLICATION_FUNCTION_REMOVED: %',prior.signature using errcode='55000';end if;
    if prior.oid='private.retention_ai_source_ready()'::regprocedure then
      if actual is distinct from jsonb_set(prior.metadata,'{prosrc}',to_jsonb(replace(prior.metadata->>'prosrc',old_source,new_source))) then
        raise exception 'D12_APPLICATION_READINESS_DELTA' using errcode='55000';end if;
    elsif prior.oid=any(rewritten) then
      if actual-'prosrc' is distinct from prior.metadata-'prosrc' then
        raise exception 'D12_APPLICATION_FUNCTION_AUTHORITY_DELTA: %',prior.signature using errcode='55000';end if;
      if actual->>'prosrc' is not distinct from prior.metadata->>'prosrc' then
        raise exception 'D12_APPLICATION_REWRITE_MISSING: %',prior.signature using errcode='55000';end if;
    elsif actual is distinct from prior.metadata then
      raise exception 'D12_APPLICATION_UNRELATED_FUNCTION_DELTA: %',prior.signature using errcode='55000';
    end if;
  end loop;
  -- Delta accounting 2/4: exactly the reviewed new functions exist, each with its exact body, language, volatility, security, result and ACL.
  select coalesce(array_agg(p.oid order by p.oid),'{}'::oid[]) into fresh from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    where n.nspname in('public','private','rls_private') and not exists(select 1 from d12_application_functions old where old.oid=p.oid);
  if fresh is distinct from (select array_agg(to_regprocedure(x)::oid order by to_regprocedure(x)::oid) from unnest(array['private.guard_review_comment_mutation()','private.review_comment_input_v1(jsonb)','public.rpc_submit_agreement_review_v2(uuid,uuid,jsonb,jsonb,uuid,jsonb)','public.rpc_get_my_agreement_review_v2(uuid)','public.rpc_list_review_comments_v1(uuid,integer,jsonb)','public.rpc_moderate_review_comment_service_v1(uuid,text,text,uuid)']::text[]) x) then
    raise exception 'D12_APPLICATION_FUNCTION_ROSTER_DELTA' using errcode='55000';end if;
  for pin in select * from (values
    ('private.guard_review_comment_mutation()','5280b99f20c4a7be695d7e16402b3f43','plpgsql','v',true,false,'trigger','{postgres=X/postgres}'),
    ('private.review_comment_input_v1(jsonb)','130692c918a53e26f1d911bbb6482029','plpgsql','s',false,false,'text','{postgres=X/postgres}'),
    ('public.rpc_submit_agreement_review_v2(uuid,uuid,jsonb,jsonb,uuid,jsonb)','75a88570ff847b97a7d71b0854acf171','plpgsql','v',true,false,'jsonb','{postgres=X/postgres,authenticated=X/postgres}'),
    ('public.rpc_get_my_agreement_review_v2(uuid)','60fb54e25317d6c2873321e66588dbeb','plpgsql','s',true,false,'jsonb','{postgres=X/postgres,authenticated=X/postgres}'),
    ('public.rpc_list_review_comments_v1(uuid,integer,jsonb)','0712dcb3bfb25ec782f40c0fe47f17c3','plpgsql','s',true,false,'jsonb','{postgres=X/postgres,authenticated=X/postgres}'),
    ('public.rpc_moderate_review_comment_service_v1(uuid,text,text,uuid)','2de37076287d759515407eecccc92728','plpgsql','v',true,false,'jsonb','{postgres=X/postgres,service_role=X/postgres}')
  ) p(signature,body_md5,language_name,volatility,definer,strict_function,result_type,acl) loop
    if not exists(select 1 from pg_proc p where p.oid=to_regprocedure(pin.signature) and md5(replace(p.prosrc,E'\r\n',E'\n'))=pin.body_md5 and p.prosecdef=pin.definer and p.proisstrict=pin.strict_function
      and p.proconfig=array['search_path=pg_catalog'] and p.proowner='postgres'::regrole
      and p.prolang=(select oid from pg_language where lanname=pin.language_name)
      and p.provolatile::text=pin.volatility and p.prokind='f' and p.prorettype=to_regtype(pin.result_type)
      and p.proacl::text=pin.acl and not p.proretset and not p.proleakproof and p.proparallel='u'
      and p.probin is null and p.prosqlbody is null and p.protrftypes is null and p.proallargtypes is null and p.proargmodes is null) then
      raise exception 'D12_APPLICATION_NEW_FUNCTION_DELTA: %',pin.signature using errcode='55000';end if;
  end loop;
  -- Delta accounting 3/4: every table, column, constraint, trigger, policy, index and bucket is unchanged except the reviewed additions (the new table with everything it owns).
  execute surface_query into after_surface;
  if after_surface is distinct from before_surface then
    -- Name what differs (the key, how many entries each way and one example of each), so a refused application explains itself.
    select string_agg(k||': +'||(select count(*) from jsonb_array_elements(coalesce(after_surface->k,'[]'::jsonb)) e where not(coalesce(before_surface->k,'[]'::jsonb) @> jsonb_build_array(e)))::text
      ||' -'||(select count(*) from jsonb_array_elements(coalesce(before_surface->k,'[]'::jsonb)) e where not(coalesce(after_surface->k,'[]'::jsonb) @> jsonb_build_array(e)))::text
      ||' added '||coalesce((select left(e::text,240) from jsonb_array_elements(coalesce(after_surface->k,'[]'::jsonb)) e where not(coalesce(before_surface->k,'[]'::jsonb) @> jsonb_build_array(e)) limit 1),'-')
      ||' removed '||coalesce((select left(e::text,240) from jsonb_array_elements(coalesce(before_surface->k,'[]'::jsonb)) e where not(coalesce(after_surface->k,'[]'::jsonb) @> jsonb_build_array(e)) limit 1),'-'),' | ')
      into diff_keys from jsonb_object_keys(before_surface) k where before_surface->k is distinct from after_surface->k;
    raise exception 'D12_APPLICATION_UNRELATED_CATALOG_DELTA: %',diff_keys using errcode='55000';
  end if;
  if (select string_agg(defaclnamespace::regnamespace::text||':'||defaclobjtype::text||':'||defaclacl::text,' | ' order by defaclnamespace::regnamespace::text,defaclobjtype::text) from pg_default_acl) is distinct from before_default_acls then
    raise exception 'D12_APPLICATION_DEFAULT_ACL_DELTA' using errcode='55000';end if;
  -- The new table, exactly: owner, flags, ACL, no policy, the columns (with their defaults), every constraint by name and kind, the two triggers, the two indexes.
  if (not exists(select 1 from pg_class where oid=to_regclass('private.agreement_review_comments_v1') and relowner='postgres'::regrole and relkind='r' and relpersistence='p'
      and not relispartition and relrowsecurity and relforcerowsecurity and relreplident='d' and reloptions is null and relacl=acldefault('r','postgres'::regrole))
    or exists(select 1 from pg_policies where schemaname='private' and tablename='agreement_review_comments_v1')
    or (select string_agg(attname::text||':'||format_type(atttypid,atttypmod)||':'||attnotnull::text||':'||attidentity::text||':'||attgenerated::text,',' order by attnum)
        from pg_attribute where attrelid=to_regclass('private.agreement_review_comments_v1') and attnum>0 and not attisdropped) is distinct from 'review_id:uuid:true::,author_account_id:uuid:true::,target_account_id:uuid:true::,comment:text:true::,comment_sha256:text:true::,created_at:timestamp with time zone:true::,hidden_at:timestamp with time zone:false::,hidden_reason_code:text:false::'
    or (select pg_get_expr(d.adbin,d.adrelid) from pg_attrdef d join pg_attribute a on a.attrelid=d.adrelid and a.attnum=d.adnum
        where d.adrelid=to_regclass('private.agreement_review_comments_v1') and a.attname='created_at') is distinct from 'clock_timestamp()'
    or (select string_agg(conname::text||':'||contype::text,',' order by conname) from pg_constraint
        where conrelid=to_regclass('private.agreement_review_comments_v1') and contype<>'n' and convalidated and conislocal and conparentid=0) is distinct from 'agreement_review_comments_v1_author_fkey:f,agreement_review_comments_v1_hidden_check:c,agreement_review_comments_v1_parties_check:c,agreement_review_comments_v1_pkey:p,agreement_review_comments_v1_review_fkey:f,agreement_review_comments_v1_sha_check:c,agreement_review_comments_v1_target_fkey:f,agreement_review_comments_v1_text_chars_check:c,agreement_review_comments_v1_text_length_check:c,agreement_review_comments_v1_text_trim_check:c'
    or (select count(*) from pg_constraint where conrelid=to_regclass('private.agreement_review_comments_v1') and contype='f' and confdeltype='r' and confupdtype='a' and confmatchtype='s'
        and confrelid in('private.agreement_reviews'::regclass,'public.app_accounts'::regclass))<>3
    or (select string_agg(indexname::text,',' order by indexname) from pg_indexes where schemaname='private' and tablename='agreement_review_comments_v1') is distinct from 'agreement_review_comments_v1_author_idx,agreement_review_comments_v1_pkey,agreement_review_comments_v1_target_idx'
    or not exists(select 1 from pg_indexes where schemaname='private' and tablename='agreement_review_comments_v1' and indexname='agreement_review_comments_v1_target_idx'
        and indexdef like '%(target_account_id, created_at DESC, review_id DESC)%' and indexdef like '%hidden_at IS NULL%')
    or not exists(select 1 from pg_indexes where schemaname='private' and tablename='agreement_review_comments_v1' and indexname='agreement_review_comments_v1_author_idx' and indexdef like '%(author_account_id)%')) then
    raise exception 'D12_APPLICATION_NEW_TABLE_DELTA' using errcode='55000';end if;
  if (exists(select 1 from (values
      ('agreement_review_comment_closure_guard_v1','private.closure_guard_owned_write()',7,'4143434f554e5400617574686f725f6163636f756e745f696400'),
      ('agreement_review_comment_mutation_guard_v1','private.guard_review_comment_mutation()',27,'')
    ) q(trigger_name,signature,event_type,argument_hex)
    where not exists(select 1 from pg_trigger t where t.tgrelid=to_regclass('private.agreement_review_comments_v1') and t.tgname=q.trigger_name
      and t.tgfoid=to_regprocedure(q.signature) and t.tgtype=q.event_type and t.tgenabled='O' and not t.tgisinternal
      and encode(t.tgargs,'hex')=q.argument_hex and t.tgqual is null and t.tgconstraint=0
      and not t.tgdeferrable and not t.tginitdeferred and t.tgoldtable is null and t.tgnewtable is null and t.tgparentid=0 and t.tgattr::text=''))
    or (select count(*) from pg_trigger where tgrelid=to_regclass('private.agreement_review_comments_v1') and not tgisinternal)<>2) then
    raise exception 'D12_APPLICATION_NEW_TRIGGER_DELTA' using errcode='55000';end if;
  -- Delta accounting 4/4: the retention catalog changed only by the new relation, the retention classes only by the one description, the star table is untouched, the certificate is bound in its three places and nothing else.
  if (select jsonb_agg(to_jsonb(c) order by data_class) from private.closure_dataset_catalog_v5 c) is distinct from expected_datasets then
    raise exception 'D12_APPLICATION_CATALOG_DELTA' using errcode='55000';end if;
  if (select jsonb_agg(to_jsonb(c) order by c.code) from private.retention_data_classes c) is distinct from expected_classes
     or (select count(*) from private.retention_data_classes where required and active)<>15 then
    raise exception 'D12_APPLICATION_RETENTION_CLASSES_DELTA' using errcode='55000';end if;
  -- The comment text must never be streamed: the new table is in no publication and no FOR ALL TABLES publication exists.
  if exists(select 1 from pg_publication_tables where schemaname='private' and tablename='agreement_review_comments_v1') or exists(select 1 from pg_publication where puballtables) then
    raise exception 'D12_APPLICATION_COMMENT_TABLE_PUBLISHED' using errcode='55000';end if;
  select md5(coalesce(string_agg(to_jsonb(r)::text,E'\n' order by r.id),'')) into star_after from private.agreement_reviews r;
  if star_after is distinct from star_before or exists(select 1 from private.agreement_review_comments_v1) then
    raise exception 'D12_APPLICATION_STAR_OR_COMMENT_DATA_DELTA' using errcode='55000';end if;
  if cardinality(private.closure_redaction_relations_v5())<>76
     or (private.closure_redaction_relations_v5())[76] is distinct from 'private.agreement_review_comments_v1'
     or private.closure_redaction_scope_v5('private.agreement_review_comments_v1') is distinct from 't.author_account_id=$1'
     or private.closure_redaction_patch_v5('private.agreement_review_comments_v1','{}'::jsonb,'00000000-0000-0000-0000-000000000000'::uuid,'00000000-0000-0000-0000-000000000000'::uuid)
        is distinct from jsonb_build_object('operation','DELETE','patch','{}'::jsonb)
     or (select v->'fields' from jsonb_array_elements(private.data_export_dataset_catalog()) v where v->>'key'='ownAgreementReviews')
        is distinct from '["agreementId","createdAt","id","rating","tags","comment"]'::jsonb
     or jsonb_array_length(private.data_export_dataset_catalog())<>52 then
    raise exception 'D12_APPLICATION_CLOSURE_OR_EXPORT_POSTCONDITION' using errcode='55000';end if;
  if (select to_jsonb(c) from private.closure_source_v5 c where singleton) is distinct from jsonb_set(source_row,'{sha256}',to_jsonb(new_source))
    or (select to_jsonb(c) from private.closure_erasure_source_v5 c where singleton) is distinct from jsonb_set(erasure_row,'{sha256}',to_jsonb(new_source))
    or pg_get_functiondef('private.retention_ai_source_ready()'::regprocedure) is distinct from replace(ready_definition,old_source,new_source)
    or private.closure_source_digest_v5() is distinct from new_source
    or private.retention_ai_source_ready() is distinct from true
    or private.closure_erasure_binding_v5()->>'sourceSha256' is distinct from new_source then
    raise exception 'D12_APPLICATION_CERTIFIED_POSTCONDITION' using errcode='55000';end if;
  -- Authority: nothing reachable by anon; the three comment RPCs by authenticated only; the moderation function by the service role only; no client role on the table or on a private function.
  if exists(select 1 from private.closure_executions_v5 where state='EXECUTING')
    or has_function_privilege('anon','private.retention_ai_source_ready()','EXECUTE')
    or has_function_privilege('authenticated','private.retention_ai_source_ready()','EXECUTE')
    or exists(select 1 from unnest(array['private.guard_review_comment_mutation()','private.review_comment_input_v1(jsonb)','public.rpc_submit_agreement_review_v2(uuid,uuid,jsonb,jsonb,uuid,jsonb)','public.rpc_get_my_agreement_review_v2(uuid)','public.rpc_list_review_comments_v1(uuid,integer,jsonb)','public.rpc_moderate_review_comment_service_v1(uuid,text,text,uuid)']::text[]) x where has_function_privilege('anon',x,'EXECUTE'))
    or exists(select 1 from unnest(array['public.rpc_submit_agreement_review_v2(uuid,uuid,jsonb,jsonb,uuid,jsonb)','public.rpc_get_my_agreement_review_v2(uuid)','public.rpc_list_review_comments_v1(uuid,integer,jsonb)']::text[]) x where not has_function_privilege('authenticated',x,'EXECUTE') or has_function_privilege('service_role',x,'EXECUTE'))
    or exists(select 1 from unnest(array['private.guard_review_comment_mutation()','private.review_comment_input_v1(jsonb)']::text[]) x where has_function_privilege('authenticated',x,'EXECUTE') or has_function_privilege('service_role',x,'EXECUTE'))
    or has_function_privilege('authenticated','public.rpc_moderate_review_comment_service_v1(uuid,text,text,uuid)','EXECUTE') or not has_function_privilege('service_role','public.rpc_moderate_review_comment_service_v1(uuid,text,text,uuid)','EXECUTE')
    or exists(select 1 from unnest(array['anon','authenticated','service_role']) r where has_table_privilege(r,'private.agreement_review_comments_v1','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER')) then
    raise exception 'D12_APPLICATION_FINAL_AUTHORITY_OR_STATE_DRIFT' using errcode='55000';end if;
  -- The new functions are visible to PostgREST without waiting for its next schema poll.
  perform pg_notify('pgrst','reload schema');
end
$d12_application$;
