-- EX-04 S1 revert: the exact inverse of ex04a_own_tasks_page.sql. NOT APPLIED. It needs its own explicit "primeni".
-- GENERATED by supabase/proofs/ex04/build_ex04a.py: do not edit by hand (`--check` fails on any difference).
-- It restores the DEV predecessor body of rpc_list_my_needs_page byte for byte (md5 dad1de3234e72d4e2f44be5e920eda61, the PKG-045a text) and drops private.own_task_counts. It refuses unless the
-- reader and the helper are exactly what the application produced. No data is touched.
do $ex04a_revert$
declare
  page_signature constant text := 'public.rpc_list_my_needs_page(text,integer,timestamp with time zone,uuid)';
  helper_signature constant text := 'private.own_task_counts(uuid)';
  new_body constant text := $new_body$
declare
  v_uid uuid := auth.uid();
  v_items jsonb;
begin
  if v_uid is null then raise exception 'AUTH_REQUIRED' using errcode = '28000'; end if;
  if p_limit is null or p_limit < 1 or p_limit > 100 or (p_before_at is null) <> (p_before_id is null) then
    raise exception 'INVALID_PAGE' using errcode = '22023';
  end if;
  if p_scope is null or p_scope not in ('ALL','ACTIVE','DRAFTS','HISTORY','WAITING') then
    raise exception 'INVALID_SCOPE' using errcode = '22023';
  end if;

  if not public.rpc_storage_account_open() then raise exception 'ACCOUNT_NOT_OPEN' using errcode='42501'; end if;

  -- EX-04 S1 (A09). Every item IS the rpc_read_task document that rpc_list_my_tasks returns, so the card, the price basis and the selectable count
  -- cannot drift from the ordinary read; sortAt is the keyset value. The scopes are the client's own sections: Aktivni = PUBLISHED, SELECTION, ACTIVE;
  -- Nacrti = DRAFT; Istorija = COMPLETED, CANCELLED, EXPIRED, ARCHIVED; WAITING = an active task with a place left and a selectable application.
  with page as materialized (
    select n.created_at, n.id
    from public.needs n
    where n.requester_account_id = v_uid
      and (p_before_at is null or (n.created_at, n.id) < (p_before_at, p_before_id))
      and case p_scope
            when 'ALL' then true
            when 'ACTIVE' then n.status in ('PUBLISHED','SELECTION','ACTIVE')
            when 'DRAFTS' then n.status = 'DRAFT'
            when 'HISTORY' then n.status in ('COMPLETED','CANCELLED','EXPIRED','ARCHIVED')
            else n.status in ('PUBLISHED','SELECTION','ACTIVE')
              and greatest(1, n.required_slots) - greatest(0, least(greatest(1, n.required_slots), public.covered_slots(n))) > 0
              and coalesce(public.selectable_application_count(n), 0) > 0
          end
    order by n.created_at desc, n.id desc
    limit p_limit + 1
  )
  select coalesce(jsonb_agg(public.rpc_read_task(p.id) || jsonb_build_object('sortAt', p.created_at) order by p.created_at desc, p.id desc), '[]'::jsonb)
    into v_items from page p;

  return jsonb_build_object(
    'items', case when jsonb_array_length(v_items) > p_limit then v_items - p_limit else v_items end,
    'hasMore', jsonb_array_length(v_items) > p_limit,
    -- The five counts of the tabs ride with the first page; a later page does not pay for them again.
    'counts', case when p_before_at is null then private.own_task_counts(v_uid) end,
    'asOf', statement_timestamp());
end
$new_body$;
  old_body constant text := $old_body$
declare
  v_uid uuid := auth.uid();
  v_items jsonb;
begin
  if v_uid is null then raise exception 'AUTH_REQUIRED' using errcode = '28000'; end if;
  if p_limit is null or p_limit < 1 or p_limit > 100 or (p_before_at is null) <> (p_before_id is null) then
    raise exception 'INVALID_PAGE' using errcode = '22023';
  end if;
  if p_scope is null or p_scope not in ('ALL','ACTIVE','HISTORY') then
    raise exception 'INVALID_SCOPE' using errcode = '22023';
  end if;

  if not public.rpc_storage_account_open() then raise exception 'ACCOUNT_NOT_OPEN' using errcode='42501'; end if;

  select coalesce(jsonb_agg(q.item order by q.created_at desc, q.id desc), '[]'::jsonb) into v_items
  from (
    select n.created_at, n.id, jsonb_build_object(
      'id', n.id, 'sortAt', n.created_at, 'revision', n.revision,
      'title', n.title, 'description', n.description, 'category', n.category, 'status', n.status,
      'urgent', n.urgent, 'scheduleKind', n.schedule_kind, 'startsAt', n.starts_at, 'endsAt', n.ends_at,
      'taskCountryCode', n.task_country_code, 'taskTimezone', n.task_timezone,
      'executionLocationMode', n.execution_location_mode,
      'approximateArea', n.approximate_area, 'approximateCity', n.approximate_city,
      -- covered_slots is the existing computed field public.covered_slots(needs), not a column.
      'requiredSlots', n.required_slots, 'coveredSlots', public.covered_slots(n),
      'requiredSkills', to_jsonb(n.required_skills), 'requiredTools', to_jsonb(n.required_tools),
      'requiredVehicles', to_jsonb(n.required_vehicles), 'requiredLicenses', to_jsonb(n.required_licenses),
      'minimumExperienceYears', n.minimum_experience_years,
      'verifiedIdentityRequired', n.verified_identity_required,
      'mode', n.mode, 'requesterPriceRsd', n.requester_price_rsd,
      'applicationCount', (select count(*) from public.marketplace_responses r where r.need_id = n.id),
      'publicTopology', (select g.public_topology from public.need_geography g where g.need_id = n.id),
      'criticalConditions', (select to_jsonb(d.critical_conditions) from public.need_requirement_details d where d.need_id = n.id)
    ) as item
    from public.needs n
    where n.requester_account_id = v_uid
      and (p_scope = 'ALL' or (p_scope = 'ACTIVE') = (n.status in ('DRAFT','PUBLISHED','SELECTION','ACTIVE')))
      and (p_before_at is null or (n.created_at, n.id) < (p_before_at, p_before_id))
    order by n.created_at desc, n.id desc
    limit p_limit + 1
  ) q;

  return jsonb_build_object(
    'items', case when jsonb_array_length(v_items) > p_limit then v_items - p_limit else v_items end,
    'hasMore', jsonb_array_length(v_items) > p_limit,
    'asOf', statement_timestamp());
end
$old_body$;
  helper_body constant text := $helper_body$
  select jsonb_build_object(
    'total', count(*),
    'active', count(*) filter (where n.status in ('PUBLISHED','SELECTION','ACTIVE')),
    'drafts', count(*) filter (where n.status = 'DRAFT'),
    'history', count(*) filter (where n.status in ('COMPLETED','CANCELLED','EXPIRED','ARCHIVED')),
    'waiting', count(*) filter (where n.status in ('PUBLISHED','SELECTION','ACTIVE')
      and greatest(1, n.required_slots) - greatest(0, least(greatest(1, n.required_slots), public.covered_slots(n))) > 0
      and coalesce(public.selectable_application_count(n), 0) > 0))
  from public.needs n where n.requester_account_id = a
$helper_body$;
  prior record; actual jsonb; digest_before text; page_oid oid; helper_oid oid;
begin
  perform set_config('lock_timeout', '5s', true);
  perform set_config('statement_timeout', '60s', true);
  perform set_config('search_path', 'pg_catalog', true);
  if current_user <> 'postgres' then raise exception 'EX04A_REVERT_OWNER_REQUIRED' using errcode = '55000'; end if;
  page_oid := to_regprocedure(page_signature)::oid; helper_oid := to_regprocedure(helper_signature)::oid;
  if helper_oid is null or (select prosrc from pg_proc where oid = page_oid) is distinct from new_body
     or (select prosrc from pg_proc where oid = helper_oid) is distinct from helper_body then
    raise exception 'EX04A_REVERT_STATE_NOT_THE_APPLIED_ONE' using errcode = '55000';
  end if;
  if private.retention_ai_source_ready() is distinct from true
     or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton) then
    raise exception 'EX04A_REVERT_CLOSURE_NOT_READY' using errcode = '55000';
  end if;
  digest_before := private.closure_source_digest_v5();
  create temporary table ex04a_revert_functions on commit drop as
    select p.oid, p.oid::regprocedure::text signature, to_jsonb(p) metadata
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname in ('public', 'private', 'rls_private') and p.oid <> helper_oid;
  execute format($c$create or replace function public.rpc_list_my_needs_page(p_scope text default 'ALL'::text, p_limit integer default 30, p_before_at timestamp with time zone default null::timestamp with time zone, p_before_id uuid default null::uuid) returns jsonb language plpgsql stable security definer set search_path to 'pg_catalog' as %L$c$, old_body);
  execute 'drop function private.own_task_counts(uuid)';
  if private.closure_source_digest_v5() is distinct from digest_before or private.retention_ai_source_ready() is distinct from true then
    raise exception 'EX04A_REVERT_CLOSURE_MOVED' using errcode = '55000';
  end if;
  for prior in select * from ex04a_revert_functions loop
    select to_jsonb(p) into actual from pg_proc p where p.oid = prior.oid;
    if actual is null then raise exception 'EX04A_REVERT_FUNCTION_REMOVED: %', prior.signature using errcode = '55000'; end if;
    if prior.oid = page_oid then
      if actual - 'prosrc' is distinct from prior.metadata - 'prosrc' or actual ->> 'prosrc' is distinct from old_body then
        raise exception 'EX04A_REVERT_PAGE_MISMATCH' using errcode = '55000';
      end if;
    elsif actual is distinct from prior.metadata then
      raise exception 'EX04A_REVERT_UNRELATED_FUNCTION_DELTA: %', prior.signature using errcode = '55000';
    end if;
  end loop;
  if (select md5(replace(prosrc, E'\r\n', E'\n')) from pg_proc where oid = page_oid) is distinct from 'dad1de3234e72d4e2f44be5e920eda61'
     or to_regprocedure(helper_signature) is not null then
    raise exception 'EX04A_REVERT_POSTCONDITION' using errcode = '55000';
  end if;
end
$ex04a_revert$;
