-- EX-04 S4 (A11 candidates and comparison): the candidate list of a task a keyset page at a time, with the state of a candidate computed for the candidates of one page only. NOT APPLIED to DEV:
-- it needs the owner's explicit "primeni". TWO NEW functions, nothing replaced, no existing function touched.
-- GENERATED by supabase/proofs/ex04/build_ex04d.py: do not edit by hand (`--check` fails on any difference).
-- Canonical basis: LIVE Master Plan card A11 ("straniči duži skup po postojećem ugovoru i sačuvaj selekciju/scroll"; DONE: "... bez lažnog statusa ili neograničenih čitanja"), EX04 plan section 6 (S4).
-- rpc_list_need_candidates_page returns the SAME candidate document as rpc_list_need_candidates, in its order (submission, then id), plus `sortAt` (the keyset value); the first page carries `counts.total`.
-- private.need_candidate_states_v5(uuid, uuid[]) is the PKG-035a state function (the exact DEV body, pinned) restricted to the given responses by ONE anchored edit, so a page pays the per-candidate calendar match and
-- price assertion for its own candidates only. The final selection authority (rpc_select_response) and rpc_list_need_candidates are untouched.
-- One atomic DO statement: exact DEV predecessor pins, the closure certificate checked unchanged, exact delta accounting (two new functions, nothing else changed). No table, column, constraint, trigger,
-- policy, index or data change.
do $ex04d$
declare
  states_signature constant text := 'private.need_candidate_states_v5(uuid,uuid[])';
  page_signature constant text := 'public.rpc_list_need_candidates_page(uuid,integer,timestamp with time zone,uuid)';
  states_body constant text := $states_body$
declare
  n public.needs; c record; remaining integer; s timestamptz; e timestamptz; eligible boolean;
begin
  select * into n from public.needs where id=p_need_id;
  if not found then return; end if;
  remaining:=greatest(n.required_slots-public.fn_need_covered_slots(n.id),0);
  for c in
    select r.id,r.worker_profile_id,r.worker_account_id,r.status,r.current_version,r.covered_slots,
      r.submitted_against_need_revision,v.need_revision as version_revision,v.content_hash,v.price_rsd as version_price,
      v.covered_slots as version_slots, v.proposed_start_at as version_start, v.proposed_end_at as version_end,
      p.account_id as profile_account, p.kind, p.profile_status, p.display_name, p.city, p.skills, p.team_capacity,
      exists(select 1 from public.agreements a where a.selected_response_id=r.id) as has_agreement
    from public.marketplace_responses r
    left join public.marketplace_response_versions v on v.response_id=r.id and v.version=r.current_version
    left join public.app_profiles p on p.id=r.worker_profile_id
    where r.need_id=n.id and r.status<>'DRAFT' and r.id = any(p_response_ids)
  loop
    response_id:=c.id;
    candidate_state:=case
      when c.has_agreement or c.status='SELECTED' then 'SELECTED'
      when c.status='WITHDRAWN' then 'WITHDRAWN'
      when c.status in ('NOT_SELECTED','EXPIRED') then 'CLOSED'
      when n.status not in ('PUBLISHED','SELECTION')
        or (n.response_deadline is not null and n.response_deadline<=statement_timestamp()) then 'CLOSED'
      when c.kind is distinct from 'WORKER' or c.profile_account is distinct from c.worker_account_id
        or c.profile_status is distinct from 'ACTIVE'
        or char_length(btrim(coalesce(c.display_name,'')))<2
        or char_length(btrim(coalesce(c.city,'')))<2
        or cardinality(coalesce(c.skills,'{}'::text[]))<1 or c.team_capacity is null
        or c.version_slots is null or c.version_slots>c.team_capacity
        or c.status in ('STALE','STALE_REVIEW_REQUIRED') or c.current_version is null or c.content_hash is null
        or c.version_revision is distinct from n.revision
        or c.submitted_against_need_revision is distinct from n.revision then 'STALE'
      when remaining<=0 then 'FULL'
      when c.covered_slots>remaining or c.version_slots>remaining then 'OVERFILL'
      when c.status in ('SUBMITTED','DELIVERED','VIEWED','SHORTLISTED') then 'SELECTABLE'
      else 'CLOSED' end;
    if candidate_state='SELECTABLE' then
      s:=coalesce(c.version_start,case when n.schedule_kind='FIXED_WINDOW' then n.starts_at end);
      e:=coalesce(c.version_end,case when n.schedule_kind='FIXED_WINDOW' then n.ends_at end);
      if (c.version_start is null)<>(c.version_end is null)
        or (s is null)<>(e is null)
        or (s is not null and (not isfinite(s) or not isfinite(e) or s>=e))
        or (c.version_start is null and n.schedule_kind='FIXED_WINDOW' and (s is null or e is null)) then
        candidate_state:='STALE';
      else
        eligible:=coalesce((private.match_detail_for_calendar_interval(n.id,c.worker_profile_id,s,e)->>'responseAllowed')::boolean,false);
        if not eligible then candidate_state:='STALE'; end if;
      end if;
      if candidate_state='SELECTABLE' then
        begin
          -- Use the final selection authority, including legacy null/TOTAL/PER_PERSON semantics.
          perform private.assert_application_price_v5(n,c.version_slots,c.version_price);
        exception when sqlstate '22023' or sqlstate 'P0001' then
          if sqlerrm not in ('INVALID_PRICE','FIXED_PRICE_NOT_READY','FIXED_PRICE_MISMATCH',
            'TOTAL_PRICE_REQUIRES_ALL_SLOTS','UNKNOWN_PRICE_BASIS') then raise; end if;
          candidate_state:='STALE';
        end;
      end if;
    end if;
    return next;
  end loop;
end;
$states_body$;
  page_body constant text := $page_body$
declare
  v_actor uuid := auth.uid();
  v_need public.needs;
  v_selected_slots integer := 0;
  v_remaining_slots integer := 0;
  v_items jsonb;
  v_has_more boolean;
  v_total bigint;
begin
  if v_actor is null then
    raise exception using errcode='42501', message='AUTH_REQUIRED';
  end if;
  if p_need_id is null then
    raise exception using errcode='22023', message='NEED_ID_REQUIRED';
  end if;
  if p_limit is null or p_limit < 1 or p_limit > 100 or (p_after_at is null) <> (p_after_id is null) then
    raise exception 'INVALID_PAGE' using errcode = '22023';
  end if;

  select n.* into v_need
  from public.needs n
  where n.id = p_need_id;

  if not found then
    raise exception using errcode='P0002', message='NEED_NOT_FOUND';
  end if;
  if v_need.requester_account_id <> v_actor then
    raise exception using errcode='42501', message='NOT_REQUESTER';
  end if;

  select coalesce(sum(s.covered_slots),0)::integer
  into v_selected_slots
  from public.need_selections s
  where s.need_id = p_need_id
    and s.status = 'SELECTED';

  v_remaining_slots := greatest(coalesce(v_need.required_slots,1) - v_selected_slots, 0);

  -- EX-04 S4 (A11). The same candidate document rpc_list_need_candidates returns, in its order (submission, then id), one keyset page at a time. The keys of the whole set are read
  -- with no function call; the state, the public profile and the evidence are computed for the candidates of THIS page only, so the work of a page does not grow with the task's applications.
  with keys as materialized (
    select r.id as response_id, coalesce(r.submitted_at, r.created_at) as sort_at
    from public.marketplace_responses r
    where r.need_id = p_need_id
      and r.status <> 'DRAFT'
  ), page as materialized (
    select k.response_id, k.sort_at
    from keys k
    where p_after_at is null or (k.sort_at, k.response_id) > (p_after_at, p_after_id)
    order by k.sort_at, k.response_id
    limit p_limit + 1
  ), shown as materialized (
    select pg.response_id, pg.sort_at
    from page pg
    order by pg.sort_at, pg.response_id
    limit p_limit
  ), candidate_rows as (
    select
      r.id as response_id,
      sh.sort_at,
      r.worker_profile_id,
      r.current_version,
      v.need_revision as version_need_revision,
      v.content_hash,
      v.price_rsd,
      v.covered_slots,
      v.proposed_start_at,
      v.proposed_end_at,
      v.scope_note,
      snap.snapshot_schema,
      snap.worker_team_capacity,
      snap.worker_skills,
      snap.worker_tools,
      snap.worker_licenses,
      snap.worker_vehicles
    from shown sh
    join public.marketplace_responses r on r.id = sh.response_id
    left join public.marketplace_response_versions v
      on v.response_id = r.id
     and v.version = r.current_version
    left join private.response_application_snapshots snap
      on snap.response_id = r.id
     and snap.response_version = r.current_version
  ), classified as (
    select
      c.*,
      states.candidate_state
    from candidate_rows c
    join private.need_candidate_states_v5(p_need_id, (select array_agg(sh.response_id) from shown sh)) states on states.response_id = c.response_id
  )
  select
    (select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'responseId', c.response_id,
          'workerProfileId', c.worker_profile_id,
          'needRevision', v_need.revision,
          'responseNeedRevision', c.version_need_revision,
          'version', c.current_version,
          'contentHash', c.content_hash,
          'state', c.candidate_state,
          'canSelect', c.candidate_state = 'SELECTABLE',
          'priceRsd', c.price_rsd,
          'coveredSlots', c.covered_slots,
          'remainingSlots', v_remaining_slots,
          'proposedStartAt', c.proposed_start_at,
          'proposedEndAt', c.proposed_end_at,
          'scopeNote', coalesce(c.scope_note,''),
          'publicProfile', public.rpc_get_public_profile(c.worker_profile_id),
          'applicationEvidence', case
            when c.snapshot_schema is null then jsonb_build_object(
              'schema','LEGACY_UNPROVEN',
              'teamCapacity',null,
              'skills',null,
              'tools',null,
              'licenses',null,
              'vehicles',null
            )
            else jsonb_build_object(
              'schema',c.snapshot_schema,
              'teamCapacity',c.worker_team_capacity,
              'skills',to_jsonb(c.worker_skills),
              'tools',to_jsonb(c.worker_tools),
              'licenses',to_jsonb(c.worker_licenses),
              'vehicles',to_jsonb(c.worker_vehicles)
            )
          end,
          'sortAt', c.sort_at
        )
        order by c.sort_at, c.response_id
      ),
      '[]'::jsonb) from classified c),
    (select count(*) from page) > p_limit,
    -- The total rides with the first page; a later page does not pay for it again.
    case when p_after_at is null then (select count(*) from keys) end
  into v_items, v_has_more, v_total;

  return jsonb_build_object(
    'items', v_items,
    'hasMore', v_has_more,
    'counts', case when p_after_at is null then jsonb_build_object('total', v_total) end,
    'asOf', statement_timestamp());
end
$page_body$;
  pin record; prior record; digest_before text; fresh oid[];
begin
  perform set_config('lock_timeout', '5s', true);
  perform set_config('statement_timeout', '60s', true);
  perform set_config('search_path', 'pg_catalog', true);
  if current_user <> 'postgres' then raise exception 'EX04D_OWNER_REQUIRED' using errcode = '55000'; end if;
  if to_regprocedure(states_signature) is not null or to_regprocedure(page_signature) is not null then raise exception 'EX04D_ALREADY_APPLIED' using errcode = '55000'; end if;
  for pin in select * from (values
    ('public.rpc_list_need_candidates(uuid)','15cb0fd9d891a4ce6d4fdc7ea79abcd1'),
    ('private.need_candidate_states_v5(uuid)','6d65e304f41f3e130228f58874757f0d'),
    ('public.rpc_get_public_profile(uuid)','9ecc0b69096f1167d02e0bb7b9656bc0')
  ) p(signature, body_md5) loop
    if (select md5(replace(prosrc, E'\r\n', E'\n')) from pg_proc where oid = to_regprocedure(pin.signature)) is distinct from pin.body_md5 then
      raise exception 'EX04D_PREDECESSOR_DRIFT: %', pin.signature using errcode = '55000';
    end if;
  end loop;
  if private.retention_ai_source_ready() is distinct from true
     or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton) then
    raise exception 'EX04D_CLOSURE_NOT_READY' using errcode = '55000';
  end if;
  digest_before := private.closure_source_digest_v5();
  create temporary table ex04d_functions on commit drop as
    select p.oid, p.oid::regprocedure::text signature, to_jsonb(p) metadata
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname in ('public', 'private', 'rls_private');

  -- The state function for a set of responses: private, no client privilege of any kind (the ACL of the function it restricts).
  execute format($c$create function private.need_candidate_states_v5(p_need_id uuid, p_response_ids uuid[]) returns table(response_id uuid, candidate_state text) language plpgsql stable security definer set search_path = 'pg_catalog' as %L$c$, states_body);
  execute 'revoke all on function private.need_candidate_states_v5(uuid,uuid[]) from public, anon, authenticated, service_role';
  -- The page reader: authenticated only, like its sibling.
  execute format($c$create function public.rpc_list_need_candidates_page(p_need_id uuid, p_limit integer default 30, p_after_at timestamp with time zone default null::timestamp with time zone, p_after_id uuid default null::uuid) returns jsonb language plpgsql stable security definer set search_path to 'pg_catalog' as %L$c$, page_body);
  execute 'revoke all on function public.rpc_list_need_candidates_page(uuid,integer,timestamp with time zone,uuid) from public, anon, authenticated, service_role';
  execute 'grant execute on function public.rpc_list_need_candidates_page(uuid,integer,timestamp with time zone,uuid) to authenticated';

  -- Delta accounting: the certificate did not move, nothing that existed changed, the two new functions are exactly what was written.
  if private.closure_source_digest_v5() is distinct from digest_before or private.retention_ai_source_ready() is distinct from true then
    raise exception 'EX04D_CLOSURE_MOVED' using errcode = '55000';
  end if;
  for prior in select * from ex04d_functions loop
    if (select to_jsonb(p) from pg_proc p where p.oid = prior.oid) is distinct from prior.metadata then
      raise exception 'EX04D_EXISTING_FUNCTION_DELTA: %', prior.signature using errcode = '55000';
    end if;
  end loop;
  select coalesce(array_agg(p.oid order by p.oid), '{}'::oid[]) into fresh
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname in ('public', 'private', 'rls_private') and not exists(select 1 from ex04d_functions f where f.oid = p.oid);
  if fresh is distinct from (select array_agg(v.oid order by v.oid) from (values (to_regprocedure(states_signature)::oid), (to_regprocedure(page_signature)::oid)) v(oid)) then
    raise exception 'EX04D_FUNCTION_ROSTER_DELTA' using errcode = '55000';
  end if;
  if not exists(select 1 from pg_proc p where p.oid = to_regprocedure(states_signature) and p.prosrc = states_body and p.prosecdef and p.provolatile = 's'
      and p.proconfig = array['search_path=pg_catalog'] and p.proowner = 'postgres'::regrole and p.proacl::text = '{postgres=X/postgres}'
      and p.prokind = 'f' and p.proretset and p.prolang = (select oid from pg_language where lanname = 'plpgsql')) then
    raise exception 'EX04D_STATES_DELTA' using errcode = '55000';
  end if;
  if not exists(select 1 from pg_proc p where p.oid = to_regprocedure(page_signature) and p.prosrc = page_body and p.prosecdef and p.provolatile = 's'
      and p.proconfig = array['search_path=pg_catalog'] and p.proowner = 'postgres'::regrole and p.proacl::text = '{postgres=X/postgres,authenticated=X/postgres}'
      and p.prokind = 'f' and not p.proretset and p.prorettype = 'jsonb'::regtype and pg_get_function_arguments(p.oid) = 'p_need_id uuid, p_limit integer DEFAULT 30, p_after_at timestamp with time zone DEFAULT NULL::timestamp with time zone, p_after_id uuid DEFAULT NULL::uuid') then
    raise exception 'EX04D_PAGE_DELTA' using errcode = '55000';
  end if;
  if has_function_privilege('anon', states_signature, 'EXECUTE') or has_function_privilege('authenticated', states_signature, 'EXECUTE')
     or has_function_privilege('service_role', states_signature, 'EXECUTE')
     or has_function_privilege('anon', page_signature, 'EXECUTE') or has_function_privilege('service_role', page_signature, 'EXECUTE')
     or not has_function_privilege('authenticated', page_signature, 'EXECUTE') then
    raise exception 'EX04D_AUTHORITY_CHANGED' using errcode = '55000';
  end if;
end
$ex04d$;
