-- EX-06 ex06a (flexible-window dispatch fix, S03 finding F1): TWO function bodies completed IN PLACE. NOT APPLIED to DEV: it needs the owner's explicit "primeni".
-- GENERATED by supabase/proofs/ex06/build_ex06a.py: do not edit by hand (`--check` fails on any difference). The file is LF text (.gitattributes): a carriage return in it is refused (EX06A_CRLF_TEXT).
-- Why: a task of schedule_kind TOMORROW_FLEXIBLE or WEEK_FLEXIBLE that is stored WITHOUT a window (the product stores it that way: live DEV 3 of 3, 41 of 41 dispatch rounds empty) is refused for every
-- worker before the worker's availability is read (availability_is_future is false without a window). It now gets a matching window derived from the kind in the task's timezone (the owner's words:
-- "sutra" = the next local calendar day, "ove nedelje" = the remaining part of the local Monday-Sunday week, no invented hour; Europe/Belgrade when the task has no valid zone); the existing flexible rule applies unchanged.
--   1. private.worker_dispatch_time_admitted(uuid,uuid): the derived window (the body is replaced, same signature, owner, ACL, SECURITY DEFINER, STABLE, search_path).
--   2. private.match_detail_without_calendar(uuid,uuid): ONE anchored in-place edit, so that the same task also counts as future availability for the CURRENT_AVAILABILITY_PAUSED test (as W02 does for a
--      stored window); a worker whose live intent is off but who has a real weekly schedule is then admitted by the gate AND the matcher, while live intent alone still invents no availability.
-- Function-only: no table, column, trigger, constraint, policy, ACL or data change; no new function.
-- Certificate-neutral: neither function is in the closure digest list (closure_source_digest_v5, 88 signatures), in the program digest or in any function the digest concatenates, neither is a trigger
-- function; the digest is asserted unchanged and ready before and after.
-- One atomic DO statement: exact DEV predecessor pins (both targets and ten neighbours the change depends on, private.dispatch_next_wave included; the unchanged helpers of the second body, lower_arr, identity_admitted, effective_radius_km and haversine_km, are not pinned), certificate ready and unchanged, exact roster (exactly these two functions change). A conflict, were one
-- raised, would use PT409 (none is).
do $ex06a$
declare
  target_signature constant text := 'private.worker_dispatch_time_admitted(uuid,uuid)';
  detail_signature constant text := 'private.match_detail_without_calendar(uuid,uuid)';
  old_md5 constant text := '5b5f0deef20d76ae4e752fe2a7dcc41f';
  detail_old_md5 constant text := '9180606a038f3606b0906ab4aefdd0c1';
  detail_new_md5 constant text := 'c8aaf3da761242397243fc56262d1aeb';
  new_body constant text := $new_body$
declare n public.needs; p public.app_profiles; tz text; wtz text; at_now timestamptz:=statement_timestamp(); periods tstzmultirange;
  ws timestamptz; we timestamptz; anchor_day date;
begin
  select * into n from public.needs where id=nid;
  if not found then return false; end if;
  select * into p from public.app_profiles where id=pid and kind='WORKER' and profile_status='ACTIVE';
  if not found then return false; end if;
  select timezone into tz from public.worker_match_preferences where worker_profile_id=pid;
  tz:=coalesce(tz,'Europe/Belgrade');
  if not private.availability_timezone_valid(tz) then return false; end if;
  -- EX-06 ex06a (S03 finding F1). A TOMORROW_FLEXIBLE or WEEK_FLEXIBLE task stored WITHOUT a window used to be refused for every worker (availability_is_future is false without one).
  -- It is now matched against the window its own words mean, derived in the task's timezone (Europe/Belgrade when the task has none or an invalid one, never the worker's):
  -- sutra = the local calendar day after the publication day; ove nedelje = the publication day to the end of that local Monday-Sunday week (the existing rule below clips the start to now,
  -- so it is the remaining part of the week). The anchor is published_at (as private.relative_schedule_end_v5 does), so a later wave does not move "tomorrow"; a task without published_at
  -- keeps the refusal. The rule that follows is the existing one: some real available time inside the window, never the whole day or week. A stored window (or one endpoint) and every other
  -- schedule kind are exactly as before.
  ws:=n.starts_at; we:=n.ends_at;
  if n.starts_at is null and n.ends_at is null and n.schedule_kind in ('TOMORROW_FLEXIBLE','WEEK_FLEXIBLE') then
    if n.published_at is null then return false; end if;
    wtz:=case when n.task_timezone is not null and private.availability_timezone_valid(n.task_timezone) then n.task_timezone else 'Europe/Belgrade' end;
    anchor_day:=(n.published_at at time zone wtz)::date;
    if n.schedule_kind='TOMORROW_FLEXIBLE' then
      ws:=(anchor_day+1)::timestamp at time zone wtz; we:=(anchor_day+2)::timestamp at time zone wtz;
    else
      ws:=anchor_day::timestamp at time zone wtz; we:=(anchor_day+(8-extract(isodow from anchor_day)::integer))::timestamp at time zone wtz;
    end if;
  end if;
  if private.availability_is_future(n.schedule_kind,ws,we,at_now) then
    periods:=private.worker_available_periods(pid,greatest(ws,at_now),we,tz);
    if n.schedule_kind='FIXED_WINDOW' then return periods @> tstzrange(ws,we,'[)'); end if;
    -- A flexible search window needs some real available time, not the whole
    -- day/week. It never reserves this window or invents an estimated duration.
    return periods<>'{}'::tstzmultirange;
  end if;
  if n.schedule_kind in ('TOMORROW_FLEXIBLE','WEEK_FLEXIBLE') or
    (n.ends_at is not null and n.ends_at<=at_now) then return false; end if;
  if not p.available_now then return false; end if;
  if exists(select 1 from public.profile_availability_windows w where w.profile_id=pid
    and w.availability_state='UNAVAILABLE' and w.starts_at<=at_now and w.ends_at>at_now)
    or exists(select 1 from private.worker_calendar_events c where c.worker_profile_id=pid
      and c.state='BLOCKING' and c.starts_at<=at_now and c.ends_at>at_now) then return false; end if;
  if n.schedule_kind='FIXED_WINDOW' then return private.schedule_fit(pid,n.starts_at,n.ends_at,tz); end if;
  return true;
end;
$new_body$;
  detail_anchor constant text := $detail_anchor$    and not private.availability_is_future(n.schedule_kind,n.starts_at,n.ends_at,statement_timestamp())
$detail_anchor$;
  detail_replacement constant text := $detail_replacement$    -- EX-06 ex06a: a TOMORROW_FLEXIBLE / WEEK_FLEXIBLE task stored without a window and published is matched against the window private.worker_dispatch_time_admitted derives for it,
    -- so it is future availability here too (W02: live intent off but a real weekly schedule is not paused for a future task). Live intent alone is still no availability.
    and not (private.availability_is_future(n.schedule_kind,n.starts_at,n.ends_at,statement_timestamp())
             or (n.starts_at is null and n.ends_at is null and n.published_at is not null
                 and n.schedule_kind in ('TOMORROW_FLEXIBLE','WEEK_FLEXIBLE')))
$detail_replacement$;
  pin record; tgt record; prior record; actual jsonb; digest_before text; target_oid oid; detail_oid oid; fresh oid[]; def text; expected_detail text;
begin
  perform set_config('lock_timeout', '5s', true);
  perform set_config('statement_timeout', '60s', true);
  perform set_config('search_path', 'pg_catalog', true);
  if current_user <> 'postgres' then raise exception 'EX06A_OWNER_REQUIRED' using errcode = '55000'; end if;
  -- The bytes this statement carries are the bytes the proof ran: a carriage return (a CRLF checkout, a clipboard) is refused, never silently applied.
  if position(E'\r' in new_body) > 0 or position(E'\r' in detail_anchor) > 0 or position(E'\r' in detail_replacement) > 0 then
    raise exception 'EX06A_CRLF_TEXT' using errcode = '55000';
  end if;
  target_oid := to_regprocedure(target_signature)::oid;
  detail_oid := to_regprocedure(detail_signature)::oid;
  if target_oid is null or detail_oid is null then raise exception 'EX06A_TARGET_MISSING' using errcode = '55000'; end if;
  if (select md5(replace(prosrc, E'\r', '')) from pg_proc where oid = target_oid) = md5(replace(new_body, E'\r', ''))
     and (select md5(replace(prosrc, E'\r', '')) from pg_proc where oid = detail_oid) = detail_new_md5 then
    raise exception 'EX06A_ALREADY_APPLIED' using errcode = '55000';
  end if;
  -- The predecessor, exactly: both targets and the neighbours the change depends on (not the unchanged helpers of the second body).
  for pin in select * from (values
    ('private.worker_dispatch_time_admitted(uuid,uuid)', '5b5f0deef20d76ae4e752fe2a7dcc41f'),
    ('private.match_detail_without_calendar(uuid,uuid)', '9180606a038f3606b0906ab4aefdd0c1'),
    ('private.availability_is_future(text,timestamp with time zone,timestamp with time zone,timestamp with time zone)','3a1aee763e9fe3d0f06d6ba04ef21aac'),
    ('private.availability_timezone_valid(text)','013f884ca649cb5246f39eaf9f2e0ec9'),
    ('private.worker_available_periods(uuid,timestamp with time zone,timestamp with time zone,text)','5107af3020a3beb7bb45e6e90e7a203b'),
    ('private.schedule_fit(uuid,timestamp with time zone,timestamp with time zone,text)','e29a7bade1437e3f2067924b5179ddfd'),
    ('private.worker_calendar_conflict(uuid,timestamp with time zone,timestamp with time zone,uuid)','417c9db16bbe70ed9ad652380790900c'),
    ('private.match_detail(uuid,uuid)','38c7894a8cf43a8f32bd5a30bc2cbd09'),
    ('private.match_detail_for_calendar_interval(uuid,uuid,timestamp with time zone,timestamp with time zone)','781956cab666befab216b3ce2334ca1d'),
    ('private.dispatch_cheap_candidate_admitted(uuid,uuid)','0132fae38c75947179b4d389edc1e1f0'),
    ('private.candidate_profile_ids(uuid,integer)','dca4ddc8080a52c8af83c33689c5568e'),
    ('private.dispatch_next_wave(uuid)','1fd8c51ef026ece24471e2f68250ecc5')
  ) p(signature, body_md5) loop
    if (select md5(replace(prosrc, E'\r', '')) from pg_proc where oid = to_regprocedure(pin.signature)) is distinct from pin.body_md5 then
      raise exception 'EX06A_PREDECESSOR_DRIFT: %', pin.signature using errcode = '55000';
    end if;
  end loop;
  for tgt in select * from (values (target_oid, 'boolean'), (detail_oid, 'jsonb')) v(proc_oid, rettype) loop
    if not exists(select 1 from pg_proc p where p.oid = tgt.proc_oid
      and p.prosecdef and p.provolatile = 's' and p.proconfig = array['search_path=pg_catalog'] and p.proowner = 'postgres'::regrole
      and p.proacl::text = '{postgres=X/postgres}' and p.prokind = 'f' and p.prorettype = tgt.rettype::regtype and not p.proretset and p.prolang = (select oid from pg_language where lanname = 'plpgsql')
      and obj_description(p.oid, 'pg_proc') is null) then
      raise exception 'EX06A_TARGET_ATTRIBUTE_DRIFT: %', tgt.proc_oid::regprocedure using errcode = '55000';
    end if;
  end loop;
  if (select count(*) from pg_attribute where attrelid = 'public.needs'::regclass and not attisdropped
        and attname in ('schedule_kind', 'starts_at', 'ends_at', 'published_at', 'task_timezone')) <> 5 then
    raise exception 'EX06A_NEEDS_COLUMNS_DRIFT' using errcode = '55000';
  end if;
  -- Certificate-neutral, by the catalog and not by promise: neither target is a trigger function and no function of the closure digest names either.
  if exists(select 1 from pg_trigger where tgfoid in (target_oid, detail_oid))
     or exists(select 1 from pg_proc p where p.pronamespace = 'private'::regnamespace and p.proname in ('closure_source_digest_v5', 'closure_erasure_program_digest_v5', 'closure_schema_digest_v5_139', 'closure_erasure_binding_v5', 'agreement_invalidation_surface_v1', 'agreement_voice_surface_v1', 'retention_ai_source_ready')
       and (position('worker_dispatch_time_admitted' in p.prosrc) > 0 or position('match_detail_without_calendar' in p.prosrc) > 0)) then
    raise exception 'EX06A_TARGET_IS_CERTIFIED' using errcode = '55000';
  end if;
  if private.retention_ai_source_ready() is distinct from true
     or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton) then
    raise exception 'EX06A_CLOSURE_NOT_READY' using errcode = '55000';
  end if;
  digest_before := private.closure_source_digest_v5();
  create temporary table ex06a_functions on commit drop as
    select p.oid, p.oid::regprocedure::text signature, to_jsonb(p) metadata
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname in ('public', 'private', 'rls_private');

  -- Change 1: the body of the first target, in place (same signature, owner, ACL).
  execute format($c$create or replace function private.worker_dispatch_time_admitted(nid uuid, pid uuid) returns boolean language plpgsql stable security definer set search_path to 'pg_catalog' as %L$c$, new_body);
  -- Change 2: ONE anchored edit of the second target, taken from its own definition (so every attribute stays as it is).
  def := pg_get_functiondef(detail_oid);
  if (length(def) - length(replace(def, detail_anchor, ''))) <> length(detail_anchor) then
    raise exception 'EX06A_DETAIL_ANCHOR_NOT_UNIQUE' using errcode = '55000';
  end if;
  execute replace(def, detail_anchor, detail_replacement);

  -- Delta accounting: the certificate did not move, exactly the two targets changed, nothing is new, nothing is gone.
  if private.closure_source_digest_v5() is distinct from digest_before or private.retention_ai_source_ready() is distinct from true then
    raise exception 'EX06A_CLOSURE_MOVED' using errcode = '55000';
  end if;
  for prior in select * from ex06a_functions loop
    select to_jsonb(p) into actual from pg_proc p where p.oid = prior.oid;
    if actual is null then raise exception 'EX06A_FUNCTION_REMOVED: %', prior.signature using errcode = '55000'; end if;
    if prior.oid = target_oid then
      if actual - 'prosrc' is distinct from prior.metadata - 'prosrc' then
        raise exception 'EX06A_TARGET_ATTRIBUTE_DELTA: %', prior.signature using errcode = '55000';
      end if;
      if actual ->> 'prosrc' is distinct from new_body or md5(replace(prior.metadata ->> 'prosrc', E'\r', '')) is distinct from old_md5 then
        raise exception 'EX06A_TARGET_BODY_MISMATCH: %', prior.signature using errcode = '55000';
      end if;
    elsif prior.oid = detail_oid then
      if actual - 'prosrc' is distinct from prior.metadata - 'prosrc' then
        raise exception 'EX06A_TARGET_ATTRIBUTE_DELTA: %', prior.signature using errcode = '55000';
      end if;
      expected_detail := replace(prior.metadata ->> 'prosrc', detail_anchor, detail_replacement);
      if actual ->> 'prosrc' is distinct from expected_detail or md5(replace(prior.metadata ->> 'prosrc', E'\r', '')) is distinct from detail_old_md5
         or md5(replace(actual ->> 'prosrc', E'\r', '')) is distinct from detail_new_md5 then
        raise exception 'EX06A_TARGET_BODY_MISMATCH: %', prior.signature using errcode = '55000';
      end if;
    elsif actual is distinct from prior.metadata then
      raise exception 'EX06A_UNRELATED_FUNCTION_DELTA: %', prior.signature using errcode = '55000';
    end if;
  end loop;
  select coalesce(array_agg(p.oid order by p.oid), '{}'::oid[]) into fresh
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname in ('public', 'private', 'rls_private') and not exists(select 1 from ex06a_functions f where f.oid = p.oid);
  if fresh is distinct from '{}'::oid[] then
    raise exception 'EX06A_FUNCTION_ROSTER_DELTA' using errcode = '55000';
  end if;
  if has_function_privilege('anon', target_signature, 'EXECUTE') or has_function_privilege('authenticated', target_signature, 'EXECUTE')
     or has_function_privilege('service_role', target_signature, 'EXECUTE')
     or has_function_privilege('anon', detail_signature, 'EXECUTE') or has_function_privilege('authenticated', detail_signature, 'EXECUTE')
     or has_function_privilege('service_role', detail_signature, 'EXECUTE') then
    raise exception 'EX06A_AUTHORITY_CHANGED' using errcode = '55000';
  end if;
end
$ex06a$;
