-- EX-06 ex06b alias registry: DEV application text. NOT APPLIED to DEV: it needs the owner's explicit "PRIMENI EX-06 ex06b".
-- GENERATED by supabase/proofs/ex06/build_ex06b.py: do not edit by hand (`--check` fails on any difference). The file is LF text (.gitattributes): a carriage return in it is refused (EX06B_CRLF_TEXT).
-- S06 of EX-06 (canonical groups, step 1). ONE function body completed IN PLACE and TWELVE data rows; nothing else.
--   1. private.work_kinds_v5(text[]) (PKG-031b, md5 2113eb46ab7ea968b873e76d1de12377): same signature, owner, ACL, SECURITY INVOKER, search_path; SQL IMMUTABLE becomes plpgsql STABLE because it now reads data.
--      The names of the eleven owner-approved kinds stay in the body (a twelfth kind is an owner decision and needs a new body, never a data row).
--   2. private.marketplace_config: NEW keys work_kinds_head (the classification version WK-1) and work_kind:<KIND> for each of the eleven kinds (a JSON array of word stems). Precedent: PKG-051a.
--      The stems are the PKG-031b regular-expression alternatives as literal substrings, so every Latin text classifies exactly as before except the written deltas:
--        Serbian Cyrillic is transliterated to plain Latin letters before matching; MONTAZA_NAMESTAJA += ikee ikei ikeu ikeom; MOLERSKI_RADOVI += ofarb; MONTAZA_NAMESTAJA -= sklapanj (S03 finding F2).
-- Function plus data only: no table, column, constraint, trigger, policy or ACL change, no new function. Certificate-neutral: the function is not in the closure digest list (88 signatures), in the program digest or
-- in any function the digest concatenates, it is not a trigger function, and a data row is not part of any digest; the digest is asserted unchanged and ready before and after.
-- One atomic DO statement: exact DEV predecessor pins (the target and eight neighbours, both callers included), exact target attributes, the exact shape of private.marketplace_config, the twelve keys absent
-- (the insert has no ON CONFLICT: a present key refuses), certificate ready, then the changes, the smoke probes on the live function, and delta accounting (exactly one function changed, nothing new or gone,
-- every pre-existing config row untouched, exactly twelve rows added, no EXECUTE for anon/authenticated/service_role). A conflict, were one raised, would use PT409 (none is).
do $ex06b$
declare
  target_signature constant text := 'private.work_kinds_v5(text[])';
  old_md5 constant text := '2113eb46ab7ea968b873e76d1de12377';
  new_md5 constant text := '78fca96231ddc713cf18990f5a2a34ef';
  old_comment constant text := 'PKG-031b: the hidden kinds of work named by free text (category, skills, exclusions). Used only by matching.';
  new_comment constant text := 'PKG-031b + EX-06 ex06b: the hidden kinds of work named by free text (category, skills, exclusions); the word stems are data rows work_kind:* of private.marketplace_config (classification version in work_kinds_head). Used only by matching.';
  new_body constant text := $new_body$
declare
  closed constant text[] := array['SELIDBE_PREVOZ', 'FIZICKI_POSLOVI', 'MONTAZA_NAMESTAJA', 'SITNE_POPRAVKE', 'MOLERSKI_RADOVI', 'ELEKTRO', 'VODOINSTALATER', 'CISCENJE', 'PRANJE_PEGLANJE', 'BASTA_DVORISTE', 'DOSTAVA'];
  fold_from constant text :=
    chr(269)||chr(263)||chr(353)||chr(273)||chr(382)||chr(268)||chr(262)||chr(352)||
    chr(272)||chr(381)||chr(1040)||chr(1072)||chr(1041)||chr(1073)||chr(1042)||chr(1074)||
    chr(1043)||chr(1075)||chr(1044)||chr(1076)||chr(1026)||chr(1106)||chr(1045)||chr(1077)||
    chr(1046)||chr(1078)||chr(1047)||chr(1079)||chr(1048)||chr(1080)||chr(1032)||chr(1112)||
    chr(1050)||chr(1082)||chr(1051)||chr(1083)||chr(1052)||chr(1084)||chr(1053)||chr(1085)||
    chr(1054)||chr(1086)||chr(1055)||chr(1087)||chr(1056)||chr(1088)||chr(1057)||chr(1089)||
    chr(1058)||chr(1090)||chr(1035)||chr(1115)||chr(1059)||chr(1091)||chr(1060)||chr(1092)||
    chr(1061)||chr(1093)||chr(1062)||chr(1094)||chr(1063)||chr(1095)||chr(1064)||chr(1096);
  fold_to constant text := 'ccsdzccsdzaabbvvggddddeezzzziijjkkllmmnnoopprrssttccuuffhhccccss';
  folded text[];
begin
  -- EX-06 ex06b (S06). The hidden kinds of work (PKG-031b): a closed set of ELEVEN kinds recognised by word stems. The NAMES of the kinds are fixed HERE (a twelfth kind is an owner decision and
  -- needs a new body, never a data row); the STEMS are data: private.marketplace_config rows work_kind:<KIND> (a JSON array of literal lower-case substrings, at least 4 letters) and the
  -- classification version in the row work_kinds_head. Each value is folded first: lower case, Serbian Latin diacritics and the Serbian Cyrillic alphabet to plain Latin letters (the three
  -- Cyrillic digraph letters first), so one Latin stem serves every spelling. A kind is named when a stem occurs inside ONE value (never across two values). Text that names no kind returns
  -- nothing, so an unknown word never matches another unknown word. A registry that is not exactly the head row and the eleven kind rows is refused loudly, never half used; an extra
  -- row work_kind:<anything else> is ignored, so no data row can ever add a kind.
  if p_values is null or cardinality(p_values) = 0 then return '{}'::text[]; end if;
  if not exists(select 1 from private.marketplace_config c
                 where c.key = 'work_kinds_head' and c.value ->> 'schema' = 'WORK_KINDS_HEAD_V1'
                   and c.value -> 'kinds' = to_jsonb(closed) and c.value ->> 'foldVersion' = 'SR_LATIN_CYRILLIC_V1')
     or (select count(*) from private.marketplace_config c
          where starts_with(c.key, 'work_kind:') and substr(c.key, 11) = any(closed)
            and c.value ->> 'schema' = 'WORK_KIND_V1' and c.value ->> 'kind' = substr(c.key, 11)
            and jsonb_typeof(c.value -> 'stems') = 'array') <> cardinality(closed) then
    raise exception 'WORK_KINDS_REGISTRY_INVALID' using errcode = '55000';
  end if;
  select coalesce(array_agg(lower(translate(replace(replace(replace(replace(replace(replace(btrim(v), chr(1033), 'lj'), chr(1113), 'lj'), chr(1034), 'nj'), chr(1114), 'nj'), chr(1039), 'dz'), chr(1119), 'dz'), fold_from, fold_to))), '{}'::text[]) into folded
    from unnest(p_values) v where v is not null;
  return coalesce((
    select array_agg(distinct r.kind order by r.kind)
      from (select substr(c.key, 11) as kind, c.value -> 'stems' as stems
              from private.marketplace_config c
             where starts_with(c.key, 'work_kind:') and substr(c.key, 11) = any(closed)) r
     cross join lateral jsonb_array_elements_text(r.stems) s(stem)
     where length(s.stem) >= 4 and exists(select 1 from unnest(folded) t where strpos(t, s.stem) > 0)
  ), '{}'::text[]);
end;
$new_body$;
  registry_text constant text := $registry$[
  {"key": "work_kinds_head", "value": {"schema": "WORK_KINDS_HEAD_V1", "classificationVersion": "WK-1", "kinds": ["SELIDBE_PREVOZ", "FIZICKI_POSLOVI", "MONTAZA_NAMESTAJA", "SITNE_POPRAVKE", "MOLERSKI_RADOVI", "ELEKTRO", "VODOINSTALATER", "CISCENJE", "PRANJE_PEGLANJE", "BASTA_DVORISTE", "DOSTAVA"], "foldVersion": "SR_LATIN_CYRILLIC_V1", "previous": "PKG-031b hard-coded regular expressions, body md5 2113eb46ab7ea968b873e76d1de12377", "package": "EX-06 ex06b"}},
  {"key": "work_kind:SELIDBE_PREVOZ", "value": {"schema": "WORK_KIND_V1", "kind": "SELIDBE_PREVOZ", "stems": ["selid", "prevoz", "transport", "kombi", "moving", "removal"]}},
  {"key": "work_kind:FIZICKI_POSLOVI", "value": {"schema": "WORK_KIND_V1", "kind": "FIZICKI_POSLOVI", "stems": ["fizick", "nosenj", "nosac", "utovar", "istovar", "iznosenj", "unosenj", "labor", "labour", "loading"]}},
  {"key": "work_kind:MONTAZA_NAMESTAJA", "value": {"schema": "WORK_KIND_V1", "kind": "MONTAZA_NAMESTAJA", "stems": ["montaz", "namestaj", "ikea", "furniture", "assembl", "ikee", "ikei", "ikeu", "ikeom"]}},
  {"key": "work_kind:SITNE_POPRAVKE", "value": {"schema": "WORK_KIND_V1", "kind": "SITNE_POPRAVKE", "stems": ["popravk", "majstor", "handyman", "repair"]}},
  {"key": "work_kind:MOLERSKI_RADOVI", "value": {"schema": "WORK_KIND_V1", "kind": "MOLERSKI_RADOVI", "stems": ["moler", "krecenj", "farbanj", "gletovanj", "painting", "painter", "ofarb"]}},
  {"key": "work_kind:ELEKTRO", "value": {"schema": "WORK_KIND_V1", "kind": "ELEKTRO", "stems": ["elektr", "electr", "struj", "uticnic", "prekidac", "rasvet", "sijalic"]}},
  {"key": "work_kind:VODOINSTALATER", "value": {"schema": "WORK_KIND_V1", "kind": "VODOINSTALATER", "stems": ["vodoinst", "vodovod", "slavin", "odvod", "bojler", "plumb"]}},
  {"key": "work_kind:CISCENJE", "value": {"schema": "WORK_KIND_V1", "kind": "CISCENJE", "stems": ["cisc", "odrzavanj", "clean", "usisav"]}},
  {"key": "work_kind:PRANJE_PEGLANJE", "value": {"schema": "WORK_KIND_V1", "kind": "PRANJE_PEGLANJE", "stems": ["pegl", "pranje vesa", "laundry", "ironing"]}},
  {"key": "work_kind:BASTA_DVORISTE", "value": {"schema": "WORK_KIND_V1", "kind": "BASTA_DVORISTE", "stems": ["bast", "dvorist", "kosenj", "travnjak", "garden", "lawn"]}},
  {"key": "work_kind:DOSTAVA", "value": {"schema": "WORK_KIND_V1", "kind": "DOSTAVA", "stems": ["dostav", "kurir", "delivery", "courier"]}}
]$registry$;
  registry jsonb; pin record; prior record; probe record; actual jsonb;
  digest_before text; config_before text; config_after text; config_acl_before text;
  target_oid oid; fresh oid[]; inserted integer; got text[];
begin
  perform set_config('lock_timeout', '5s', true);
  perform set_config('statement_timeout', '60s', true);
  perform set_config('search_path', 'pg_catalog', true);
  if current_user <> 'postgres' then raise exception 'EX06B_OWNER_REQUIRED' using errcode = '55000'; end if;
  -- The bytes this statement carries are the bytes the proof ran: a carriage return (a CRLF checkout, a clipboard) is refused, never silently applied.
  if position(chr(13) in new_body) > 0 or position(chr(13) in registry_text) > 0 then
    raise exception 'EX06B_CRLF_TEXT' using errcode = '55000';
  end if;
  registry := registry_text::jsonb;
  if jsonb_typeof(registry) <> 'array' or jsonb_array_length(registry) <> 12 or exists(select 1 from jsonb_array_elements(registry) r(item),
           jsonb_array_elements(case when jsonb_typeof(r.item -> 'value' -> 'stems') = 'array' then r.item -> 'value' -> 'stems' else '[]'::jsonb end) e(stem)
         where jsonb_typeof(e.stem) <> 'string' or (e.stem #>> '{}') !~ '^[a-z][a-z ]*[a-z]$' or length(e.stem #>> '{}') < 4) then
    raise exception 'EX06B_REGISTRY_TEXT_INVALID' using errcode = '55000';
  end if;
  target_oid := to_regprocedure(target_signature)::oid;
  if target_oid is null then raise exception 'EX06B_TARGET_MISSING' using errcode = '55000'; end if;
  if (select md5(replace(prosrc, chr(13), '')) from pg_proc where oid = target_oid) = new_md5
     and exists(select 1 from private.marketplace_config c where starts_with(c.key, 'work_kind')) then
    raise exception 'EX06B_ALREADY_APPLIED' using errcode = '55000';
  end if;
  -- The predecessor, exactly: the target and the neighbours the change depends on (both callers of the target among them).
  for pin in select * from (values
    ('private.work_kinds_v5(text[])','2113eb46ab7ea968b873e76d1de12377'),
    ('private.match_detail_without_calendar(uuid,uuid)','c8aaf3da761242397243fc56262d1aeb'),
    ('private.dispatch_cheap_candidate_admitted(uuid,uuid)','0132fae38c75947179b4d389edc1e1f0'),
    ('private.candidate_profile_ids(uuid,integer)','dca4ddc8080a52c8af83c33689c5568e'),
    ('private.dispatch_next_wave(uuid)','1fd8c51ef026ece24471e2f68250ecc5'),
    ('private.match_detail(uuid,uuid)','38c7894a8cf43a8f32bd5a30bc2cbd09'),
    ('private.match_detail_for_calendar_interval(uuid,uuid,timestamp with time zone,timestamp with time zone)','781956cab666befab216b3ce2334ca1d'),
    ('private.worker_dispatch_time_admitted(uuid,uuid)','4f0beb65922d2b3d947d69e68a56a956'),
    ('private.lower_arr(text[])','07f449cf589196cc8ca349b4f5ca460c')
  ) p(signature, body_md5) loop
    if (select md5(replace(prosrc, chr(13), '')) from pg_proc where oid = to_regprocedure(pin.signature)) is distinct from pin.body_md5 then
      raise exception 'EX06B_PREDECESSOR_DRIFT: %', pin.signature using errcode = '55000';
    end if;
  end loop;
  if not exists(select 1 from pg_proc p where p.oid = target_oid
      and not p.prosecdef and p.provolatile = 'i' and p.proparallel = 's' and not p.proisstrict and not p.proleakproof and p.proconfig = array['search_path=pg_catalog']
      and p.proowner = 'postgres'::regrole and p.proacl::text = '{postgres=X/postgres}' and p.prokind = 'f' and p.prorettype = 'text[]'::regtype and not p.proretset
      and p.pronargs = 1 and p.proargnames = array['p_values'] and p.prolang = (select oid from pg_language where lanname = 'sql')
      and obj_description(p.oid, 'pg_proc') = old_comment) then
    raise exception 'EX06B_TARGET_ATTRIBUTE_DRIFT: %', target_signature using errcode = '55000';
  end if;
  -- The config table is exactly the three-column, triggerless, ruleless table the insert assumes, and nobody holds the keys this package writes.
  if (select string_agg(a.attname::text || ':' || format_type(a.atttypid, a.atttypmod) || ':' || a.attnotnull::text, ',' order by a.attnum)
        from pg_attribute a where a.attrelid = 'private.marketplace_config'::regclass and a.attnum > 0 and not a.attisdropped) is distinct from 'key:text:true,value:jsonb:true,updated_at:timestamp with time zone:true'
     or (select count(*) from pg_constraint x where x.conrelid = 'private.marketplace_config'::regclass and x.contype <> 'n') <> 1
     or (select md5(pg_get_constraintdef(x.oid)) from pg_constraint x where x.conrelid = 'private.marketplace_config'::regclass and x.contype = 'p') is distinct from '729d3ed6c85722f863da384d2313331e'
     or exists(select 1 from pg_trigger t where t.tgrelid = 'private.marketplace_config'::regclass and not t.tgisinternal)
     or exists(select 1 from pg_rewrite r where r.ev_class = 'private.marketplace_config'::regclass) then
    raise exception 'EX06B_CONFIG_TABLE_DRIFT' using errcode = '55000';
  end if;
  if exists(select 1 from private.marketplace_config c where starts_with(c.key, 'work_kind')) then
    raise exception 'EX06B_CONFIG_KEY_CONFLICT' using errcode = '55000';
  end if;
  -- Certificate-neutral, by the catalog and not by promise: the target is not a trigger function and no function of the closure digest names it.
  if exists(select 1 from pg_trigger where tgfoid = target_oid)
     or exists(select 1 from pg_proc p where p.pronamespace = 'private'::regnamespace and p.proname in ('closure_source_digest_v5', 'closure_erasure_program_digest_v5', 'closure_schema_digest_v5_139', 'closure_erasure_binding_v5', 'agreement_invalidation_surface_v1', 'agreement_voice_surface_v1', 'retention_ai_source_ready')
       and position('work_kinds_v5' in p.prosrc) > 0) then
    raise exception 'EX06B_TARGET_IS_CERTIFIED' using errcode = '55000';
  end if;
  if private.retention_ai_source_ready() is distinct from true
     or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton) then
    raise exception 'EX06B_CLOSURE_NOT_READY' using errcode = '55000';
  end if;
  digest_before := private.closure_source_digest_v5();
  create temporary table ex06b_functions on commit drop as
    select p.oid, p.oid::regprocedure::text signature, to_jsonb(p) metadata
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname in ('public', 'private', 'rls_private');
  select md5(coalesce(string_agg(c.key || chr(31) || c.value::text || chr(31) || c.updated_at::text, chr(30) order by c.key), '')) into config_before from private.marketplace_config c;
  select c.relacl::text into config_acl_before from pg_class c where c.oid = 'private.marketplace_config'::regclass;

  -- Change 1: the twelve data rows (a plain insert: no ON CONFLICT, a present key refused above and by the primary key).
  insert into private.marketplace_config(key, value)
    select r.item ->> 'key', r.item -> 'value' from jsonb_array_elements(registry) r(item);
  get diagnostics inserted = row_count;
  if inserted <> 12 then raise exception 'EX06B_REGISTRY_INSERT_COUNT: %', inserted using errcode = '55000'; end if;
  -- Change 2: the body of the target, in place (same signature, owner, ACL), and its comment.
  execute format($c$create or replace function private.work_kinds_v5(p_values text[]) returns text[] language plpgsql stable parallel safe set search_path to 'pg_catalog' as %L$c$, new_body);
  execute format('comment on function %s is %L', target_signature, new_comment);

  -- The live function answers as written (the smoke probes: the proof and the postflight repeat them).
  for probe in select * from (values
    (array[(chr(268)||'i'||chr(353)||chr(263)||'enje stana')]::text[], array['CISCENJE']::text[]),
    (array[(chr(1063)||chr(1080)||chr(1096)||chr(1115)||chr(1077)||chr(1114)||chr(1077)||' '||chr(1089)||chr(1090)||chr(1072)||chr(1085)||chr(1072))]::text[], array['CISCENJE']::text[]),
    (array[(chr(1050)||chr(1088)||chr(1077)||chr(1095)||chr(1077)||chr(1114)||chr(1077)), (chr(1060)||chr(1072)||chr(1088)||chr(1073)||chr(1072)||chr(1114)||chr(1077))]::text[], array['MOLERSKI_RADOVI']::text[]),
    (array['Sklapanje maketa']::text[], '{}'::text[]),
    (array[('sklapanje IKEA name'||chr(353)||'taja')]::text[], array['MONTAZA_NAMESTAJA']::text[]),
    (array['ormari iz ikee']::text[], array['MONTAZA_NAMESTAJA']::text[]),
    (array['ikee']::text[], array['MONTAZA_NAMESTAJA']::text[]),
    (array['ofarba sobu']::text[], array['MOLERSKI_RADOVI']::text[]),
    (array['Ciscenje stana', 'Peglanje']::text[], array['CISCENJE', 'PRANJE_PEGLANJE']::text[]),
    (array['transport_selidbe']::text[], array['SELIDBE_PREVOZ']::text[]),
    (array['dresura pasa']::text[], '{}'::text[]),
    (array[('ne'||chr(353)||'to sasvim drugo'), null, '']::text[], '{}'::text[]),
    ('{}'::text[], '{}'::text[]),
    (null::text[], '{}'::text[])
  ) s(probe_input, probe_expected) loop
    got := private.work_kinds_v5(probe.probe_input);
    if got is distinct from probe.probe_expected then
      raise exception 'EX06B_SMOKE_PROBE_FAILED: % gave %', probe.probe_input, got using errcode = '55000';
    end if;
  end loop;

  -- Delta accounting: the certificate did not move, exactly the target changed (body, language, volatility; nothing else), nothing is new, nothing is gone, the data is exactly the twelve rows.
  if private.closure_source_digest_v5() is distinct from digest_before or private.retention_ai_source_ready() is distinct from true then
    raise exception 'EX06B_CLOSURE_MOVED' using errcode = '55000';
  end if;
  for prior in select * from ex06b_functions loop
    select to_jsonb(p) into actual from pg_proc p where p.oid = prior.oid;
    if actual is null then raise exception 'EX06B_FUNCTION_REMOVED: %', prior.signature using errcode = '55000'; end if;
    if prior.oid = target_oid then
      if (actual - 'prosrc' - 'prolang' - 'provolatile') is distinct from (prior.metadata - 'prosrc' - 'prolang' - 'provolatile') then
        raise exception 'EX06B_TARGET_ATTRIBUTE_DELTA: %', prior.signature using errcode = '55000';
      end if;
      if actual ->> 'prosrc' is distinct from new_body or md5(replace(prior.metadata ->> 'prosrc', chr(13), '')) is distinct from old_md5
         or md5(replace(actual ->> 'prosrc', chr(13), '')) is distinct from new_md5 or actual ->> 'provolatile' <> 's'
         or actual ->> 'prolang' is distinct from (select oid::text from pg_language where lanname = 'plpgsql') then
        raise exception 'EX06B_TARGET_BODY_MISMATCH: %', prior.signature using errcode = '55000';
      end if;
    elsif actual is distinct from prior.metadata then
      raise exception 'EX06B_UNRELATED_FUNCTION_DELTA: %', prior.signature using errcode = '55000';
    end if;
  end loop;
  select coalesce(array_agg(p.oid order by p.oid), '{}'::oid[]) into fresh
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where n.nspname in ('public', 'private', 'rls_private') and not exists(select 1 from ex06b_functions f where f.oid = p.oid);
  if fresh is distinct from '{}'::oid[] then
    raise exception 'EX06B_FUNCTION_ROSTER_DELTA' using errcode = '55000';
  end if;
  if not exists(select 1 from pg_proc p where p.oid = target_oid
      and not p.prosecdef and p.provolatile = 's' and p.proparallel = 's' and not p.proisstrict and not p.proleakproof and p.proconfig = array['search_path=pg_catalog']
      and p.proowner = 'postgres'::regrole and p.proacl::text = '{postgres=X/postgres}' and p.prokind = 'f' and p.prorettype = 'text[]'::regtype and not p.proretset
      and p.pronargs = 1 and p.proargnames = array['p_values'] and p.prolang = (select oid from pg_language where lanname = 'plpgsql')
      and obj_description(p.oid, 'pg_proc') = new_comment) then
    raise exception 'EX06B_TARGET_ATTRIBUTE_DELTA: %', target_signature using errcode = '55000';
  end if;
  if (select count(*) from private.marketplace_config c where starts_with(c.key, 'work_kind')) <> 12
     or exists(select 1 from jsonb_array_elements(registry) r(item)
                where not exists(select 1 from private.marketplace_config c where c.key = r.item ->> 'key' and c.value = r.item -> 'value')) then
    raise exception 'EX06B_REGISTRY_MISMATCH' using errcode = '55000';
  end if;
  select md5(coalesce(string_agg(c.key || chr(31) || c.value::text || chr(31) || c.updated_at::text, chr(30) order by c.key), '')) into config_after from private.marketplace_config c where not starts_with(c.key, 'work_kind');
  if config_after is distinct from config_before then
    raise exception 'EX06B_CONFIG_ROWS_CHANGED' using errcode = '55000';
  end if;
  if (select c.relacl::text from pg_class c where c.oid = 'private.marketplace_config'::regclass) is distinct from config_acl_before then
    raise exception 'EX06B_CONFIG_ACL_CHANGED' using errcode = '55000';
  end if;
  if has_function_privilege('anon', target_signature, 'EXECUTE') or has_function_privilege('authenticated', target_signature, 'EXECUTE')
     or has_function_privilege('service_role', target_signature, 'EXECUTE') then
    raise exception 'EX06B_AUTHORITY_CHANGED' using errcode = '55000';
  end if;
end
$ex06b$;
