import React from 'react';
import { StyleSheet } from 'react-native';
import { act, create, type ReactTestRenderer } from 'react-test-renderer';
let mockSession = { user: { id: 'worker' }, accountRevision: 1 };
let mockFocused = true;
let mockState = 'active';
let mockListener: (state: string) => void;
const mockOpen = jest.fn();
jest.mock('../../../store/sesija', () => ({ useSesija: () => mockSession, sesijaSada: () => mockSession }));
jest.mock('expo-router', () => ({ useFocusEffect: (effect: () => void) => require('react').useEffect(
  () => mockFocused ? effect() : undefined, [effect, mockFocused]) }));
jest.mock('react-native', () => {
  const rn = jest.requireActual('react-native');
  return new Proxy(rn, { get(target, key) {
    if (key === 'AppState') return { currentState: mockState, addEventListener: (_: string, fn: typeof mockListener) => { mockListener = fn; return { remove: jest.fn() }; } };
    if (key === 'Linking') return { openURL: (...args: unknown[]) => mockOpen(...args) };
    if (key === 'Modal' || key === 'ScrollView' || key === 'View') return key;
    if (key === 'useWindowDimensions') return () => ({ width: 390, height: 800 });
    return Reflect.get(target, key);
  } });
});
jest.mock('react-native-safe-area-context', () => ({ SafeAreaView: 'SafeAreaView' }));
jest.mock('../../Text', () => ({ T: 'T' }));
jest.mock('../../Press', () => ({ Press: 'Press' }));
jest.mock('../../product/ProductDetails', () => ({ ProductHeader: 'ProductHeader' }));
jest.mock('../../system/motion', () => ({ useReducedMotion: () => true }));
jest.mock('../../v2/V2Action', () => ({ V2Action: 'Action' }));
jest.mock('../LocationOverviewMap', () => ({ LocationOverviewMap: 'Canvas' }));
import { LocationMapPreview } from '../LocationMapPreview';
const points = [{ id: 'start', label: 'Početno mesto', latitude: 45.271234, longitude: 19.831234 },
  { id: 'end', label: 'Završno mesto', latitude: 46, longitude: 20 }];
let tree: ReactTestRenderer;
let scopeKey = 'grant1';
const render = async (coarse = false) => { await act(async () => { tree = create(<LocationMapPreview points={points} scopeKey={scopeKey} coarse={coarse} route />); }); };
const update = async () => { await act(async () => { tree.update(<LocationMapPreview points={points} scopeKey={scopeKey} route />); }); };
const press = async (props: object) => { await act(async () => { tree.root.findByProps(props).props.onPress(); }); };
beforeEach(() => { jest.clearAllMocks(); mockOpen.mockResolvedValue(undefined); mockFocused = true; mockState = 'active';
  mockSession = { user: { id: 'worker' }, accountRevision: 1 }; scopeKey = 'grant1'; });
afterEach(async () => { await act(async () => tree?.unmount()); jest.useRealTimers(); });
describe('task map expansion and explicit navigation', () => {
  it('keeps overview unselected and makes repeated all-points and stop taps explicit camera actions', async () => {
    await render(); await press({ accessibilityLabel: 'Otvori mapu' });
    const canvas = () => tree.root.findByType('Canvas' as React.ElementType);
    const stop = (label: string) => tree.root.findByProps({ accessibilityLabel: `Prikaži na mapi: ${label}` });
    expect(stop('Početno mesto').props.accessibilityState.selected).toBe(false);
    expect(stop('Završno mesto').props.accessibilityState.selected).toBe(false);
    await press({ label: 'Prikaži sve tačke' });
    expect(canvas().props).toMatchObject({ cameraIntent: 1 });
    await press({ label: 'Prikaži sve tačke' });
    expect(canvas().props).toMatchObject({ cameraIntent: 2 });
    await press({ accessibilityLabel: 'Prikaži na mapi: Završno mesto' });
    await press({ accessibilityLabel: 'Prikaži na mapi: Završno mesto' });
    expect(canvas().props).toMatchObject({ selectedId: 'end', cameraIntent: 4 });
    expect(stop('Završno mesto').props.accessibilityState.selected).toBe(true);
    await press({ label: 'Prikaži sve tačke' });
    expect(canvas().props.selectedId).toBeUndefined();
    expect(canvas().props.cameraIntent).toBe(5);
    expect(stop('Početno mesto').props.accessibilityState.selected).toBe(false);
    expect(stop('Završno mesto').props.accessibilityState.selected).toBe(false);
    expect(mockOpen).not.toHaveBeenCalled();
  });
  it('opens the same points, selects a stop, returns without a route push or provider request', async () => {
    await render(); expect(mockOpen).not.toHaveBeenCalled();
    await press({ accessibilityLabel: 'Otvori mapu' });
    expect(tree.root.findByType('Canvas' as React.ElementType).props).toMatchObject({ points, interactive: true });
    await press({ accessibilityLabel: 'Prikaži na mapi: Završno mesto' });
    expect(tree.root.findByType('Canvas' as React.ElementType).props.selectedId).toBe('end');
    await press({ label: 'Navigacija: Završno mesto' });
    expect(mockOpen).toHaveBeenCalledWith('https://www.google.com/maps/dir/?api=1&destination=46%2C20&dir_action=navigate');
    await act(async () => tree.root.findByType('Modal' as React.ElementType).props.onRequestClose());
    expect(tree.root.findByType('Canvas' as React.ElementType).props.interactive).toBe(false);
  });
  it('offers approximate search only for a public point, never exact-route action', async () => {
    await render(true); await press({ accessibilityLabel: 'Otvori mapu' });
    expect(tree.root.findAllByProps({ label: 'Cela putanja u Google mapama' })).toHaveLength(0);
    await press({ label: 'Otvori područje u Google mapama' });
    expect(mockOpen.mock.calls[0][0]).toContain('query=45.27%2C19.83');
  });
  it('gives a single-point expanded map the space above its natural-height actions', async () => {
    await act(async () => { tree = create(<LocationMapPreview points={[points[0]]} scopeKey={scopeKey} coarse />); });
    expect(tree.root.findByType('Canvas' as React.ElementType).props.height).toBe(184);
    await press({ accessibilityLabel: 'Otvori mapu' });
    const canvas = tree.root.findByType('Canvas' as React.ElementType);
    const footer = tree.root.findByProps({ testID: 'location-map-actions' });
    const header = tree.root.findByType('ProductHeader' as React.ElementType);
    expect(canvas.props).toMatchObject({ height: 'fill', interactive: true, coarse: true, points: [points[0]] });
    expect(canvas.parent).toBe(footer.parent);
    expect(header.parent).toBe(canvas.parent?.parent);
    expect(StyleSheet.flatten(canvas.parent!.props.style)).toMatchObject({ flex: 1, minHeight: 0 });
    expect(StyleSheet.flatten(footer.props.style)).toMatchObject({ flexGrow: 0, flexShrink: 1, minHeight: 0, maxHeight: '50%' });
    expect(StyleSheet.flatten(footer.props.contentContainerStyle).flexGrow).toBeUndefined();
    expect(tree.root.findAllByProps({ label: 'Prikaži sve tačke' })).toHaveLength(0);
    await press({ label: 'Otvori područje u Google mapama' });
    expect(mockOpen).toHaveBeenCalledWith('https://www.google.com/maps/search/?api=1&query=45.27%2C19.83');
  });
  it('keeps every long stop and navigation action inside the bounded footer without wrapping the map in a scroller', async () => {
    const stops = Array.from({ length: 12 }, (_, index) => ({ ...points[0], id: `stop-${index}`,
      label: `Mesto ${index + 1}: duga potvrđena oznaka ulaza i mesta preuzimanja`, latitude: 45 + index / 100 }));
    await act(async () => { tree = create(<LocationMapPreview points={stops} scopeKey={scopeKey} route />); });
    await press({ accessibilityLabel: 'Otvori mapu' });
    const footer = tree.root.findByProps({ testID: 'location-map-actions' });
    expect(footer.findAllByProps({ accessibilityRole: 'button' })).toHaveLength(stops.length);
    expect(footer.findAllByType('Canvas' as React.ElementType)).toHaveLength(0);
    expect(footer.findAllByProps({ label: 'Prikaži sve tačke' })).toHaveLength(1);
    await press({ accessibilityLabel: `Prikaži na mapi: ${stops[11].label}` });
    expect(tree.root.findByType('Canvas' as React.ElementType).props.selectedId).toBe('stop-11');
    const navigate = footer.findByProps({ label: `Navigacija: ${stops[11].label}` });
    await act(async () => navigate.props.onPress());
    expect(mockOpen.mock.calls[0][0]).toContain('destination=45.11%2C19.831234');
  });
  it('retires navigation, stop selection and close callbacks between modal visits', async () => {
    await render(); await press({ accessibilityLabel: 'Otvori mapu' });
    const oldNavigate = tree.root.findByProps({ label: 'Navigacija: Početno mesto' }).props.onPress;
    const oldChoose = tree.root.findByProps({ accessibilityLabel: 'Prikaži na mapi: Završno mesto' }).props.onPress;
    const oldClose = tree.root.findByType('Modal' as React.ElementType).props.onRequestClose;
    await act(async () => { oldClose(); oldNavigate(); }); expect(mockOpen).not.toHaveBeenCalled();
    await press({ accessibilityLabel: 'Otvori mapu' });
    await act(async () => { oldNavigate(); oldChoose(); oldClose(); });
    expect(mockOpen).not.toHaveBeenCalled();
    expect(tree.root.findAllByType('Modal' as React.ElementType)).toHaveLength(1);
    expect(tree.root.findByType('Canvas' as React.ElementType).props.selectedId).toBeUndefined();
  });
  it.each(['account', 'scope', 'blur', 'background'] as const)('retires modal and retained navigation on %s', async change => {
    await render(); await press({ accessibilityLabel: 'Otvori mapu' });
    const old = tree.root.findByProps({ label: 'Navigacija: Početno mesto' }).props.onPress;
    if (change === 'account') mockSession = { ...mockSession, accountRevision: 2 };
    if (change === 'scope') scopeKey = 'grant2';
    if (change === 'blur') mockFocused = false;
    if (change === 'background') await act(async () => { mockState = 'background'; mockListener('background'); old(); });
    await update(); await act(async () => old());
    expect(mockOpen).not.toHaveBeenCalled(); expect(tree.root.findAllByType('Modal' as React.ElementType)).toHaveLength(0);
  });
  it('shows a retry after bridge rejection and suppresses duplicate launch while unresolved', async () => {
    await render(); await press({ accessibilityLabel: 'Otvori mapu' });
    let reject!: (error: Error) => void;
    mockOpen.mockImplementationOnce(() => new Promise<void>((_, no) => { reject = no; }));
    const action = tree.root.findByProps({ label: 'Navigacija: Početno mesto' }).props.onPress;
    await act(async () => { action(); action(); }); expect(mockOpen).toHaveBeenCalledTimes(1);
    await act(async () => reject(new Error('unavailable')));
    expect(tree.root.findByProps({ label: 'Navigacija: Početno mesto' }).props.error).toContain('Pokušaj ponovo');
    await press({ label: 'Navigacija: Početno mesto' }); expect(mockOpen).toHaveBeenCalledTimes(2);
  });
  it('checks private authority at the actual expansion and navigation tap without relying on a timer render', async () => {
    let admitted = true;
    const canUse = () => admitted;
    await act(async () => { tree = create(<LocationMapPreview points={points} scopeKey={scopeKey} route canUse={canUse} />); });
    const open = tree.root.findByProps({ accessibilityLabel: 'Otvori mapu' }).props.onPress;
    admitted = false;
    await act(async () => open());
    expect(tree.root.findAllByType('Modal' as React.ElementType)).toHaveLength(0);
    admitted = true;
    await act(async () => open());
    const point = tree.root.findByProps({ label: 'Navigacija: Početno mesto' }).props.onPress;
    const route = tree.root.findByProps({ label: 'Cela putanja u Google mapama' }).props.onPress;
    const choose = tree.root.findByProps({ accessibilityLabel: 'Prikaži na mapi: Završno mesto' }).props.onPress;
    admitted = false;
    await act(async () => { point(); route(); choose(); });
    expect(mockOpen).not.toHaveBeenCalled();
    expect(tree.root.findByType('Canvas' as React.ElementType).props.selectedId).toBeUndefined();
    await act(async () => tree.root.findByType('Modal' as React.ElementType).props.onRequestClose());
    expect(tree.root.findAllByType('Modal' as React.ElementType)).toHaveLength(0);
  });
  it('retires retained actions when the caller replaces its authority without changing geometry', async () => {
    await act(async () => { tree = create(<LocationMapPreview points={points} scopeKey={scopeKey} route canUse={() => true} />); });
    await press({ accessibilityLabel: 'Otvori mapu' });
    const old = tree.root.findByProps({ label: 'Navigacija: Početno mesto' }).props.onPress;
    await act(async () => { tree.update(<LocationMapPreview points={points} scopeKey={scopeKey} route canUse={() => false} />); });
    await act(async () => old());
    expect(mockOpen).not.toHaveBeenCalled();
    expect(tree.root.findAllByType('Modal' as React.ElementType)).toHaveLength(0);
  });
});
