import AsyncStorage from '@react-native-async-storage/async-storage';
jest.mock('@react-native-async-storage/async-storage',()=>{const values=new Map<string,string>();return {getItem:jest.fn(async(key:string)=>values.get(key)??null),setItem:jest.fn(async(key:string,value:string)=>{values.set(key,value);}),removeItem:jest.fn(async(key:string)=>{values.delete(key);}),clear:jest.fn(async()=>{values.clear();})};});
import {closureIntentJournal as journal,type ClosureIntent} from '../closureIntent';
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',K='33333333-3333-4333-8333-333333333333';
const intent:ClosureIntent={kind:'PREPARE',accountId:A,clientRequestId:K,expectedRevision:0};
beforeEach(async()=>{await AsyncStorage.clear();jest.clearAllMocks();});
it('restores opaque owned coordinates from storage without any auto submission',async()=>{await journal.save(intent);expect(await journal.load(A)).toEqual(intent);expect(await journal.load(B)).toBeNull();expect(JSON.parse((await AsyncStorage.getItem('uskoci.closure.intent.v1.'+A))!)).toEqual(intent);});
it('cannot overwrite an unresolved request with a new key',async()=>{await journal.save(intent);await expect(journal.save({...intent,clientRequestId:B})).rejects.toThrow('CLOSURE_UNRESOLVED_INTENT');expect(await journal.load(A)).toEqual(intent);});
it('stale clear cannot remove the new intent',async()=>{await journal.save(intent);await journal.clear(A,B);expect(await journal.load(A)).toEqual(intent);await journal.clear(A,K);expect(await journal.load(A)).toBeNull();});
it('serializes concurrent same-account intents and keeps exactly one',async()=>{const result=await Promise.allSettled([journal.save(intent),journal.save({...intent,clientRequestId:B})]);expect(result.map(r=>r.status)).toEqual(['fulfilled','rejected']);expect(await journal.load(A)).toEqual(intent);});
it('does not replace corrupted persisted state with a new command',async()=>{await AsyncStorage.setItem('uskoci.closure.intent.v1.'+A,'invalid');await expect(journal.load(A)).rejects.toThrow();await expect(journal.save(intent)).rejects.toThrow();});
