-- Chat voice B1 DEV postflight. READ-ONLY: one SELECT, no write, no lock, no function with a side effect. Run it against canonical DEV right after the ONE-statement application (and at any time later).
-- GENERATED by supabase/proofs/chat/build_voice_b1_dev_application.py from the pin tables of voice_b1_dev_application.tail.sql: do not edit by hand (`--check` fails on any difference).
-- Returns ONE row of JSON: how many pins were compared, every part of the applied state that does not hold ("problems": an empty array means the application is exactly in place and the closure certificate is
-- bound, certified and ready) and the live certificate facts. The disposable proof runs this same file on the chain the application produced and requires an empty list.
with
  applied_body_pins(signature, body_md5) as (values
    ('private.closure_redaction_relations_v5()','e3ce45840fe907be2baf5d8ad051c74f'),
    ('private.closure_redaction_scope_v5(text)','0cf65a6947305b6c31e6138549016363'),
    ('private.closure_redaction_patch_v5(text,jsonb,uuid,uuid)','b1f6aa501bfbee2bfaa6ee60a22f19ef'),
    ('private.closure_blockers_v5(uuid)','cd0c2921bfd52ba2e96769b2a409b9db'),
    ('public.rpc_start_account_closure_execution(uuid,uuid,integer,uuid,text)','3fc04b344892a252956219ce85f4de34'),
    ('private.support_reference_v5(uuid,jsonb)','94ad410f355654cffccd9de1084571bb'),
    ('private.data_export_snapshot(uuid,uuid,jsonb,timestamptz)','b198bff51d2d67a6095ddcd00b7ba2e1'),
    ('private.data_export_dataset_catalog()','7fc01c563915f0a168b9eb82d962bd06'),
    ('private.data_export_policy_binding()','dd63c427109ffff1c940c335b34e0ad6'),
    ('private.closure_source_digest_v5()','9fb4a72f3feef8e4557a96f4c9d7224e'),
    ('private.closure_erasure_program_digest_v5()','229887adb43d52990dc4254176222696'),
    ('public.rpc_read_agreement_messages_page_v1(uuid,uuid,integer,timestamptz,uuid)','7e69fba7d5fdeeb57245ecbf69e7a822'),
    ('public.rpc_read_agreement_message_window_v1(uuid,uuid,uuid,integer,integer)','706735a0fcac16e6a98b4063beea057f')
  ),
  voice_function_pins(signature, body_md5, language_name, volatility, definer, strict_function, result_type, acl) as (values
    ('private.agreement_voice_key_v1(uuid)','7fc22c4fa37e737d09917f03c497b84c','sql','i',false,true,'bigint','{postgres=X/postgres}'),
    ('private.agreement_voice_context_v1(uuid,uuid,integer,boolean)','db79bbcb1557e698f96e1973f5f1114d','plpgsql','v',true,false,'public.agreements','{postgres=X/postgres}'),
    ('private.agreement_voice_document_v1(private.agreement_voice_uploads_v1)','e3d28dc212ec03b7686809307125a2b0','sql','s',false,false,'jsonb','{postgres=X/postgres}'),
    ('private.agreement_voice_transfer_v1(private.agreement_voice_uploads_v1)','90adbecaf2f168e5aa2813053ef4ee71','sql','s',false,false,'jsonb','{postgres=X/postgres}'),
    ('private.agreement_voice_message_guard_v1()','f7945764ecc4176f519c6adc051036a4','plpgsql','v',true,false,'trigger','{postgres=X/postgres}'),
    ('private.agreement_voice_link_guard_v1()','70b7d13295f1a9407106d32a7c08fb15','plpgsql','v',true,false,'trigger','{postgres=X/postgres}'),
    ('private.agreement_voice_asset_guard_v1()','7dac0b4c2cad1da11dcd30e1ea35509a','plpgsql','v',true,false,'trigger','{postgres=X/postgres}'),
    ('private.agreement_voice_storage_guard_v1()','f3baf1ab27b347216cdede156ca3f42a','plpgsql','v',true,false,'trigger','{postgres=X/postgres}'),
    ('public.rpc_send_agreement_voice_message_v1(uuid,uuid,integer,text,uuid)','2cb1a99fd913115235a5762bf068f52e','plpgsql','v',true,false,'jsonb','{postgres=X/postgres,authenticated=X/postgres}'),
    ('public.rpc_agreement_voice_read_service_v1(uuid,uuid,uuid,uuid,uuid)','5d82c4a9683513a43f4edc9d8bd08e54','plpgsql','v',true,false,'jsonb','{postgres=X/postgres,service_role=X/postgres}'),
    ('public.rpc_agreement_voice_upload_service_v1(uuid,uuid,text,uuid,integer,uuid,jsonb)','aebb8132f2500415b2daded197e57975','plpgsql','v',true,false,'jsonb','{postgres=X/postgres,service_role=X/postgres}'),
    ('public.rpc_read_agreement_messages_page_v2(uuid,uuid,integer,timestamptz,uuid)','c0ae8862bb86be54834227c10d2aef89','plpgsql','v',true,false,'jsonb','{postgres=X/postgres,authenticated=X/postgres}'),
    ('public.rpc_read_agreement_message_window_v2(uuid,uuid,uuid,integer,integer)','e16aeb18144c44a8baa4aebaf420944c','plpgsql','v',true,false,'jsonb','{postgres=X/postgres,authenticated=X/postgres}'),
    ('private.agreement_messages_v1_view(jsonb,text)','4a2065e1b0c27894f4e2dcc352d7fb59','sql','i',false,false,'jsonb','{postgres=X/postgres}'),
    ('private.agreement_voice_surface_v1()','b697d12234198c95815257d7ce73f147','sql','s',true,false,'text','{postgres=X/postgres}')
  ),
  trigger_pins(relation, trigger_name, signature, event_type, deferred) as (values
    ('public.agreement_messages','agreement_voice_message_guard_v1','private.agreement_voice_message_guard_v1()',23,false),
    ('public.agreement_messages','agreement_voice_link_guard_v1','private.agreement_voice_link_guard_v1()',5,true),
    ('private.agreement_voice_uploads_v1','agreement_voice_asset_guard_v1','private.agreement_voice_asset_guard_v1()',27,false),
    ('storage.objects','agreement_voice_storage_guard_v1','private.agreement_voice_storage_guard_v1()',27,false)
  ),
  cert as (
    select (select count(*) from private.closure_source_v5) as source_rows,
           (select count(*) from private.closure_erasure_source_v5) as erasure_rows,
           (select sha256 from private.closure_source_v5 where singleton) as certified,
           (select sha256 from private.closure_erasure_source_v5 where singleton) as erasure_sha,
           private.closure_source_digest_v5() as live_digest,
           private.retention_ai_source_ready() as ready,
           private.closure_erasure_binding_v5()->>'sourceSha256' as bound
  ),
  problems as (
    select 'APPLIED_BODY_DRIFT' as kind, pin.signature as detail
    from applied_body_pins pin
    where (select md5(replace(prosrc,E'\r\n',E'\n')) from pg_proc where oid=to_regprocedure(pin.signature)) is distinct from pin.body_md5
    union all
    select 'VOICE_FUNCTION_DRIFT', pin.signature
    from voice_function_pins pin
    where not exists(select 1 from pg_proc p where p.oid=to_regprocedure(pin.signature)
      and md5(replace(prosrc,E'\r\n',E'\n'))=pin.body_md5 and prosecdef=pin.definer and proisstrict=pin.strict_function
      and proconfig=array['search_path=pg_catalog'] and proowner='postgres'::regrole
      and prolang=(select oid from pg_language where lanname=pin.language_name)
      and provolatile::text=pin.volatility and prokind='f' and prorettype=to_regtype(pin.result_type)
      and proacl::text=pin.acl and not proretset and not proleakproof and proparallel='u'
      and probin is null and prosqlbody is null and protrftypes is null and proallargtypes is null and proargmodes is null)
    union all
    select 'TRIGGER_DRIFT', pin.trigger_name
    from trigger_pins pin
    where not exists(select 1 from pg_trigger t where tgrelid=pin.relation::regclass and tgname=pin.trigger_name
      and tgfoid=to_regprocedure(pin.signature) and tgtype=pin.event_type and tgenabled='O' and not tgisinternal
      and tgnargs=0 and octet_length(tgargs)=0 and tgqual is null and (tgconstraint<>0)=pin.deferred
      and tgdeferrable=pin.deferred and tginitdeferred=pin.deferred and tgoldtable is null and tgnewtable is null and tgparentid=0 and tgattr::text='')
    union all
    select 'UPLOAD_TABLE_DRIFT', 'private.agreement_voice_uploads_v1'
    where not exists(select 1 from pg_class where oid=to_regclass('private.agreement_voice_uploads_v1') and relowner='postgres'::regrole and relkind='r' and relpersistence='p'
        and not relispartition and relrowsecurity and relforcerowsecurity and relreplident='d' and reloptions is null and relacl=acldefault('r','postgres'::regrole))
      or exists(select 1 from pg_policies where schemaname='private' and tablename='agreement_voice_uploads_v1')
    union all
    select 'MESSAGE_COLUMN_OR_CONSTRAINT_DRIFT', 'public.agreement_messages'
    where (select count(*) from pg_attribute where attrelid='public.agreement_messages'::regclass and attname='voice_asset_id' and not attisdropped and atttypid='uuid'::regtype and not attnotnull)<>1
      or not exists(select 1 from pg_constraint where conrelid='public.agreement_messages'::regclass and conname='agreement_messages_body_media_check' and convalidated)
      or exists(select 1 from pg_constraint where conrelid='public.agreement_messages'::regclass and conname='agreement_messages_body_photo_check')
    union all
    select 'LINK_GUARD_CONSTRAINT_DRIFT', 'agreement_voice_link_guard_v1'
    where (select count(*) from pg_constraint x where x.conrelid='public.agreement_messages'::regclass and x.conname='agreement_voice_link_guard_v1' and x.contype='t'
        and x.condeferrable and x.condeferred and x.convalidated and x.conparentid=0 and x.conislocal and x.coninhcount=0 and x.contypid=0 and x.conindid=0 and x.confrelid=0
        and exists(select 1 from pg_trigger t where t.tgconstraint=x.oid and t.tgname='agreement_voice_link_guard_v1' and t.tgrelid=x.conrelid))<>1
    union all
    select 'CLOSURE_ACTION_SHAPE_DRIFT', 'private.closure_actions_v5'
    where not exists(select 1 from pg_constraint where conrelid='private.closure_actions_v5'::regclass and conname='closure_action_shape146' and convalidated and pg_get_constraintdef(oid) like '%agreement-voice%')
    union all
    select 'BUCKET_OR_STORAGE_POLICY_DRIFT', 'agreement-voice'
    where not exists(select 1 from storage.buckets where id='agreement-voice' and not public and file_size_limit=4194304 and allowed_mime_types=array['audio/mp4'])
      or not exists(select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname='agreement_voice_no_client_v1'
        and permissive='RESTRICTIVE' and roles=array['authenticated']::name[] and cmd='ALL' and qual like '%agreement-voice%' and with_check like '%agreement-voice%')
    union all
    select 'RETENTION_CATALOG_DRIFT', 'MEDIA_OBJECTS'
    where not exists(select 1 from private.closure_dataset_catalog_v5 where data_class='MEDIA_OBJECTS' and relations @> array['private.agreement_voice_uploads_v1']::text[])
    union all
    select 'EXPORT_CATALOG_DRIFT', 'private.data_export_dataset_catalog()'
    where jsonb_array_length(private.data_export_dataset_catalog())<>52
      or not exists(select 1 from jsonb_array_elements(private.data_export_dataset_catalog()) e where e->>'key'='ownAgreementVoice')
    union all
    select 'CERTIFICATE_CARDINALITY', 'closure_source_v5 and closure_erasure_source_v5 must hold exactly one row each'
    from cert where source_rows<>1 or erasure_rows<>1
    union all
    select 'CERTIFICATE_NOT_BOUND', 'the certificate, the live digest, the erasure source row, the readiness and the binding must all agree'
    from cert where certified is null or certified is distinct from live_digest or certified is distinct from erasure_sha or ready is distinct from true or bound is distinct from certified
    union all
    select 'FUNCTION_AUTHORITY_DRIFT', 'private.retention_ai_source_ready() or the voice surface is executable by a client role'
    where has_function_privilege('anon','private.retention_ai_source_ready()','EXECUTE') or has_function_privilege('authenticated','private.retention_ai_source_ready()','EXECUTE')
      or has_function_privilege('anon','private.agreement_voice_surface_v1()','EXECUTE') or has_function_privilege('authenticated','private.agreement_voice_surface_v1()','EXECUTE')
      or has_function_privilege('service_role','private.agreement_voice_surface_v1()','EXECUTE')
    union all
    select 'CLOSURE_IN_FLIGHT', 'a closure execution is EXECUTING'
    where exists(select 1 from private.closure_executions_v5 where state='EXECUTING')
  )
select jsonb_build_object(
  'unit', 'CHAT_VOICE_B1_DEV_POSTFLIGHT',
  'appliedBodyPinsChecked', (select count(*) from applied_body_pins),
  'voiceFunctionPinsChecked', (select count(*) from voice_function_pins),
  'triggerPinsChecked', (select count(*) from trigger_pins),
  'problems', coalesce((select jsonb_agg(jsonb_build_object('kind',kind,'detail',detail) order by kind,detail) from problems), '[]'::jsonb),
  'certifiedSource', (select certified from cert),
  'liveDigest', (select live_digest from cert),
  'ready', (select ready from cert),
  'erasureBindingMatches', (select bound is not distinct from certified from cert),
  'exportDatasets', jsonb_array_length(private.data_export_dataset_catalog()),
  'ledgerRows', (select count(*) from supabase_migrations.schema_migrations),
  'serverVersion', current_setting('server_version'),
  'checkedAt', to_char(clock_timestamp() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
) as postflight;
