-- Chat voice B1 REVERT candidate. NOT APPLIED. It needs the owner's explicit "primeni" for THIS file (a revert of a privacy certification of the erasure program).
-- GENERATED by supabase/proofs/chat/build_voice_b1_revert.py from the pin tables of the DEV application, the read-only pre-image capture and this template: do not edit by hand (`--check` fails on any difference).
-- Provenance: {{PROVENANCE}}
-- One atomic DO statement that returns the canonical DEV database to EXACTLY the state the ONE-statement voice application (chat_voice_b1_dev_application.sql) started from, or changes nothing:
--   * it runs only against the state that application produced (13 rewritten bodies, 15 new functions, the table, the four triggers, the policy, the bucket, the column, the two replaced constraints, the catalog row, all pinned);
--   * it REFUSES while any voice data exists (an upload row, a voice message, an object in the bucket, a closure action on the bucket): removing user data is a separate owner decision, never a side effect;
--   * it restores the 14 pre-image definitions, removes every voice object, restores the two CHECK constraints and the retention catalog row, and re-binds the closure certificate in its three places to the
--     digest it had before the application (a digest the restored catalog must reproduce, pinned below);
--   * then it proves the result: every predecessor pin of the application holds again, nothing else changed (functions, tables, columns, constraints, triggers, policies, indexes, buckets), and the certificate is ready and bound.
do $voice_b1_revert$
declare
  pin record; prior record; actual jsonb; before_surface jsonb; after_surface jsonb; before_buckets jsonb; before_storage_policies jsonb; expected_datasets jsonb;
  applied_source text; restored_source text; affected integer; diff_keys text; definition text; rewritten oid[]; voice_functions oid[]; fresh oid[];
  target_source constant text := '{{CERTIFIED_DIGEST}}';
  media_objects_before constant text[] := {{MEDIA_OBJECTS_BEFORE}};
  surface_query text := $surface_query${{SURFACE_QUERY}}$surface_query$;
begin
  perform set_config('lock_timeout','5s',true);
  perform set_config('statement_timeout','120s',true);
  perform set_config('search_path','pg_catalog',true);
  if current_user<>'postgres' then raise exception 'VOICE_B1_REVERT_OWNER_REQUIRED' using errcode='55000';end if;
  if to_regclass('private.agreement_voice_uploads_v1') is null or to_regprocedure('private.agreement_voice_surface_v1()') is null then
    raise exception 'VOICE_B1_REVERT_NOT_APPLIED' using errcode='55000';end if;
  -- Hold closure writes, voice writes and message writes until this atomic change commits (a fixed order, so a blocked statement times out instead of deadlocking).
  lock table private.closure_executions_v5 in share mode;
  lock table private.closure_source_v5,private.closure_erasure_source_v5,private.closure_dataset_catalog_v5 in share row exclusive mode;
  lock table private.agreement_voice_uploads_v1 in access exclusive mode;
  lock table public.agreement_messages in access exclusive mode;
  if exists(select 1 from private.closure_executions_v5 where state='EXECUTING') then
    raise exception 'VOICE_B1_REVERT_CLOSURE_IN_FLIGHT' using errcode='55000';end if;
  if (select count(*) from private.closure_source_v5)<>1 or (select count(*) from private.closure_erasure_source_v5)<>1 then
    raise exception 'VOICE_B1_REVERT_CERTIFICATE_CARDINALITY' using errcode='55000';end if;
  -- No user data is ever removed by this file.
  if exists(select 1 from private.agreement_voice_uploads_v1) or exists(select 1 from public.agreement_messages where voice_asset_id is not null)
     or exists(select 1 from storage.objects where bucket_id='agreement-voice') or exists(select 1 from private.closure_actions_v5 where bucket='agreement-voice') then
    raise exception 'VOICE_B1_REVERT_VOICE_DATA_PRESENT' using errcode='55000';end if;
  -- The certificate is the one the application bound: certified in all three places, equal to the live digest, ready and bound.
  select sha256 into applied_source from private.closure_source_v5 where singleton;
  if applied_source is null or applied_source is distinct from private.closure_source_digest_v5()
     or applied_source is distinct from (select sha256 from private.closure_erasure_source_v5 where singleton)
     or private.retention_ai_source_ready() is distinct from true or private.closure_erasure_binding_v5()->>'sourceSha256' is distinct from applied_source then
    raise exception 'VOICE_B1_REVERT_APPLIED_STATE_NOT_CERTIFIED' using errcode='55000';end if;
  if applied_source=target_source then raise exception 'VOICE_B1_REVERT_ALREADY_AT_TARGET_DIGEST' using errcode='55000';end if;
  select pg_get_functiondef(p.oid) into definition from pg_proc p where oid='private.retention_ai_source_ready()'::regprocedure;
  if not exists(select 1 from pg_proc where oid='private.retention_ai_source_ready()'::regprocedure
      and (length(prosrc)-length(replace(prosrc,applied_source,'')))=length(applied_source)
      and md5(replace(replace(prosrc,E'\r\n',E'\n'),applied_source,'__CERTIFIED_SOURCE__'))='bc85a1a744869abb6441e647b18b2195')
     or (length(definition)-length(replace(definition,applied_source,'')))<>length(applied_source)
     or (select count(*) from regexp_matches(definition,'[0-9a-f]{64}','g'))<>1 then
    raise exception 'VOICE_B1_REVERT_READINESS_DRIFT' using errcode='55000';end if;
  -- The applied package, exactly: the 13 rewritten bodies (LF-normalised md5) and the 15 new functions.
  for pin in select * from (values
{{APPLIED_BODY_PINS}}
  ) p(signature,body_md5) loop
    if (select md5(replace(prosrc,E'\r\n',E'\n')) from pg_proc where oid=to_regprocedure(pin.signature)) is distinct from pin.body_md5 then
      raise exception 'VOICE_B1_REVERT_APPLIED_BODY_DRIFT: %',pin.signature using errcode='55000';end if;
  end loop;
  for pin in select * from (values
{{VOICE_FUNCTION_PINS}}
  ) p(signature,body_md5) loop
    if (select md5(replace(prosrc,E'\r\n',E'\n')) from pg_proc where oid=to_regprocedure(pin.signature)) is distinct from pin.body_md5 then
      raise exception 'VOICE_B1_REVERT_VOICE_FUNCTION_DRIFT: %',pin.signature using errcode='55000';end if;
  end loop;
  -- The applied structure, exactly.
  for pin in select * from (values
    ('public.agreement_messages','agreement_voice_message_guard_v1'),('public.agreement_messages','agreement_voice_link_guard_v1'),
    ('private.agreement_voice_uploads_v1','agreement_voice_asset_guard_v1'),('storage.objects','agreement_voice_storage_guard_v1')
  ) p(relation,trigger_name) loop
    if not exists(select 1 from pg_trigger t where tgrelid=pin.relation::regclass and tgname=pin.trigger_name and not tgisinternal) then
      raise exception 'VOICE_B1_REVERT_TRIGGER_MISSING: %',pin.trigger_name using errcode='55000';end if;
  end loop;
  if not exists(select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname='agreement_voice_no_client_v1')
     or not exists(select 1 from storage.buckets where id='agreement-voice')
     or (select count(*) from pg_attribute where attrelid='public.agreement_messages'::regclass and attname='voice_asset_id' and not attisdropped)<>1
     or not exists(select 1 from pg_constraint where conrelid='public.agreement_messages'::regclass and conname='agreement_messages_body_media_check')
     or exists(select 1 from pg_constraint where conrelid='public.agreement_messages'::regclass and conname='agreement_messages_body_photo_check')
     or not exists(select 1 from pg_constraint where conrelid='private.closure_actions_v5'::regclass and conname='closure_action_shape146' and pg_get_constraintdef(oid) like '%agreement-voice%')
     or (select relations from private.closure_dataset_catalog_v5 where data_class='MEDIA_OBJECTS') is distinct from media_objects_before||array['private.agreement_voice_uploads_v1']::text[] then
    raise exception 'VOICE_B1_REVERT_APPLIED_STRUCTURE_DRIFT' using errcode='55000';end if;

  -- What this change may touch: captured now, compared at the end.
  execute surface_query into before_surface;
  create temporary table voice_b1_revert_functions on commit drop as
    select p.oid,p.oid::regprocedure::text signature,to_jsonb(p) metadata
    from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    where n.nspname in('public','private','rls_private');
  select jsonb_agg(case when c.data_class='MEDIA_OBJECTS' then jsonb_set(to_jsonb(c),'{relations}',to_jsonb(media_objects_before)) else to_jsonb(c) end order by data_class)
    into expected_datasets from private.closure_dataset_catalog_v5 c;
  select jsonb_agg(to_jsonb(b) order by b.id) into before_buckets from storage.buckets b where b.id is distinct from 'agreement-voice';
  select jsonb_agg(to_jsonb(p) order by policyname) into before_storage_policies from pg_policies p where schemaname='storage' and tablename='objects' and policyname is distinct from 'agreement_voice_no_client_v1';
  rewritten:=array[{{REWRITTEN_ROSTER}}]::oid[];
  if cardinality(rewritten)<>13 or array_position(rewritten,null) is not null then raise exception 'VOICE_B1_REVERT_REWRITTEN_ROSTER' using errcode='55000';end if;
  voice_functions:=array[{{VOICE_FUNCTION_ROSTER}}]::oid[];
  if cardinality(voice_functions)<>15 or array_position(voice_functions,null) is not null then raise exception 'VOICE_B1_REVERT_VOICE_ROSTER' using errcode='55000';end if;

  -- 1. The pre-image definitions (the 13 rewritten functions, then the readiness function with the target digest).
{{RESTORE_FUNCTIONS}}

  -- 2. The retention catalog row loses the voice table before the table goes.
  update private.closure_dataset_catalog_v5 set relations=array_remove(relations,'private.agreement_voice_uploads_v1') where data_class='MEDIA_OBJECTS';
  get diagnostics affected=row_count;
  if affected<>1 then raise exception 'VOICE_B1_REVERT_CATALOG_ROW_COUNT' using errcode='55000';end if;

  -- 3. Triggers and policy first, then the functions (those over the table's row type before the table), then the table, the bucket and the column.
  drop trigger agreement_voice_message_guard_v1 on public.agreement_messages;
  drop trigger agreement_voice_link_guard_v1 on public.agreement_messages;
  drop trigger agreement_voice_asset_guard_v1 on private.agreement_voice_uploads_v1;
  drop trigger agreement_voice_storage_guard_v1 on storage.objects;
  drop policy agreement_voice_no_client_v1 on storage.objects;
  drop function public.rpc_send_agreement_voice_message_v1(uuid,uuid,integer,text,uuid);
  drop function public.rpc_agreement_voice_read_service_v1(uuid,uuid,uuid,uuid,uuid);
  drop function public.rpc_agreement_voice_upload_service_v1(uuid,uuid,text,uuid,integer,uuid,jsonb);
  drop function public.rpc_read_agreement_messages_page_v2(uuid,uuid,integer,timestamptz,uuid);
  drop function public.rpc_read_agreement_message_window_v2(uuid,uuid,uuid,integer,integer);
  drop function private.agreement_messages_v1_view(jsonb,text);
  drop function private.agreement_voice_surface_v1();
  drop function private.agreement_voice_document_v1(private.agreement_voice_uploads_v1);
  drop function private.agreement_voice_transfer_v1(private.agreement_voice_uploads_v1);
  drop function private.agreement_voice_context_v1(uuid,uuid,integer,boolean);
  drop function private.agreement_voice_key_v1(uuid);
  drop function private.agreement_voice_message_guard_v1();
  drop function private.agreement_voice_link_guard_v1();
  drop function private.agreement_voice_asset_guard_v1();
  drop function private.agreement_voice_storage_guard_v1();
  drop table private.agreement_voice_uploads_v1;
  -- Supabase Storage refuses a direct delete on its tables unless this transaction-local setting says so; the bucket is empty (checked above) and removed by identity.
  perform set_config('storage.allow_delete_query','true',true);
  delete from storage.buckets where id='agreement-voice';
  get diagnostics affected=row_count;
  perform set_config('storage.allow_delete_query','false',true);
  if affected<>1 then raise exception 'VOICE_B1_REVERT_BUCKET_ROW_COUNT' using errcode='55000';end if;
  alter table public.agreement_messages drop constraint agreement_messages_body_media_check;
  execute 'alter table public.agreement_messages add constraint agreement_messages_body_photo_check ' || $photo_check${{PHOTO_CHECK_DEF}}$photo_check$;
  alter table public.agreement_messages drop column voice_asset_id;
  alter table private.closure_actions_v5 drop constraint closure_action_shape146;
  execute 'alter table private.closure_actions_v5 add constraint closure_action_shape146 ' || $action_shape${{ACTION_SHAPE_DEF}}$action_shape$;

  -- 4. The certificate: the restored catalog must reproduce the pre-application digest; then the three places are bound to it.
  restored_source:=private.closure_source_digest_v5();
  if restored_source is distinct from target_source then
    raise exception 'VOICE_B1_REVERT_DIGEST_NOT_RESTORED' using errcode='55000';end if;
  update private.closure_source_v5 set sha256=target_source where singleton and sha256=applied_source;
  get diagnostics affected=row_count;
  if affected<>1 then raise exception 'VOICE_B1_REVERT_SOURCE_ROW_COUNT' using errcode='55000';end if;
  update private.closure_erasure_source_v5 set sha256=target_source where singleton and sha256=applied_source;
  get diagnostics affected=row_count;
  if affected<>1 then raise exception 'VOICE_B1_REVERT_ERASURE_ROW_COUNT' using errcode='55000';end if;

  -- Delta accounting 1/3: every function is unchanged except the 13 restored ones (body only) and the readiness constant; the 15 voice functions are gone and nothing new exists.
  for prior in select * from voice_b1_revert_functions loop
    select to_jsonb(p) into actual from pg_proc p where oid=prior.oid;
    if prior.oid=any(voice_functions) then
      if actual is not null then raise exception 'VOICE_B1_REVERT_VOICE_FUNCTION_REMAINS: %',prior.signature using errcode='55000';end if;
    elsif actual is null then raise exception 'VOICE_B1_REVERT_FUNCTION_REMOVED: %',prior.signature using errcode='55000';
    elsif prior.oid='private.retention_ai_source_ready()'::regprocedure then
      if actual is distinct from jsonb_set(prior.metadata,'{prosrc}',to_jsonb(replace(prior.metadata->>'prosrc',applied_source,target_source))) then
        raise exception 'VOICE_B1_REVERT_READINESS_DELTA' using errcode='55000';end if;
    elsif prior.oid=any(rewritten) then
      if actual-'prosrc' is distinct from prior.metadata-'prosrc' then
        raise exception 'VOICE_B1_REVERT_FUNCTION_AUTHORITY_DELTA: %',prior.signature using errcode='55000';end if;
      if actual->>'prosrc' is not distinct from prior.metadata->>'prosrc' then
        raise exception 'VOICE_B1_REVERT_RESTORE_MISSING: %',prior.signature using errcode='55000';end if;
    elsif actual is distinct from prior.metadata then
      raise exception 'VOICE_B1_REVERT_UNRELATED_FUNCTION_DELTA: %',prior.signature using errcode='55000';
    end if;
  end loop;
  select coalesce(array_agg(p.oid order by p.oid),'{}'::oid[]) into fresh from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    where n.nspname in('public','private','rls_private') and not exists(select 1 from voice_b1_revert_functions old where old.oid=p.oid);
  if cardinality(fresh)<>0 then raise exception 'VOICE_B1_REVERT_NEW_FUNCTION_DELTA' using errcode='55000';end if;
  -- The application's own predecessor pins hold again: metadata, then bodies.
  for pin in select * from (values
{{METADATA_PINS}}
  ) p(signature,metadata_md5) loop
    if (select md5(((to_jsonb(p)-'oid'-'pronamespace'-'proowner'-'prolang'-'proacl'-'prosrc')
        ||jsonb_build_object('namespace',n.nspname,'owner',pg_get_userbyid(p.proowner),
          'language',l.lanname,'acl',p.proacl::text))::text)
      from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang
      where p.oid=to_regprocedure(pin.signature)) is distinct from pin.metadata_md5 then
      raise exception 'VOICE_B1_REVERT_METADATA_NOT_RESTORED: %',pin.signature using errcode='55000';end if;
  end loop;
  for pin in select * from (values
{{BODY_PINS}}
  ) p(signature,body_md5) loop
    if (select md5(replace(prosrc,E'\r\n',E'\n')) from pg_proc where oid=to_regprocedure(pin.signature)) is distinct from pin.body_md5 then
      raise exception 'VOICE_B1_REVERT_BODY_NOT_RESTORED: %',pin.signature using errcode='55000';end if;
  end loop;
  if not exists(select 1 from pg_proc where oid='private.retention_ai_source_ready()'::regprocedure
      and (length(prosrc)-length(replace(prosrc,target_source,'')))=length(target_source)
      and md5(replace(replace(prosrc,E'\r\n',E'\n'),target_source,'__CERTIFIED_SOURCE__'))='bc85a1a744869abb6441e647b18b2195') then
    raise exception 'VOICE_B1_REVERT_READINESS_NOT_RESTORED' using errcode='55000';end if;

  -- Delta accounting 2/3: every table, column, constraint, trigger, policy, index and bucket is what it was before the application.
  execute surface_query into after_surface;
  if after_surface is distinct from before_surface then
    select string_agg(k||': +'||(select count(*) from jsonb_array_elements(coalesce(after_surface->k,'[]'::jsonb)) e where not(coalesce(before_surface->k,'[]'::jsonb) @> jsonb_build_array(e)))::text
      ||' -'||(select count(*) from jsonb_array_elements(coalesce(before_surface->k,'[]'::jsonb)) e where not(coalesce(after_surface->k,'[]'::jsonb) @> jsonb_build_array(e)))::text
      ||' added '||coalesce((select left(e::text,240) from jsonb_array_elements(coalesce(after_surface->k,'[]'::jsonb)) e where not(coalesce(before_surface->k,'[]'::jsonb) @> jsonb_build_array(e)) limit 1),'-')
      ||' removed '||coalesce((select left(e::text,240) from jsonb_array_elements(coalesce(before_surface->k,'[]'::jsonb)) e where not(coalesce(after_surface->k,'[]'::jsonb) @> jsonb_build_array(e)) limit 1),'-'),' | ')
      into diff_keys from jsonb_object_keys(before_surface) k where before_surface->k is distinct from after_surface->k;
    raise exception 'VOICE_B1_REVERT_UNRELATED_CATALOG_DELTA: %',diff_keys using errcode='55000';
  end if;
  if (select jsonb_agg(to_jsonb(b) order by b.id) from storage.buckets b) is distinct from before_buckets
     or (select jsonb_agg(to_jsonb(p) order by policyname) from pg_policies p where schemaname='storage' and tablename='objects') is distinct from before_storage_policies then
    raise exception 'VOICE_B1_REVERT_STORAGE_DELTA' using errcode='55000';end if;
  if to_regclass('private.agreement_voice_uploads_v1') is not null
     or exists(select 1 from pg_attribute where attrelid='public.agreement_messages'::regclass and attname='voice_asset_id' and not attisdropped)
     or exists(select 1 from pg_trigger where tgname in('agreement_voice_message_guard_v1','agreement_voice_link_guard_v1','agreement_voice_asset_guard_v1','agreement_voice_storage_guard_v1'))
     or exists(select 1 from pg_constraint where conname in('agreement_messages_body_media_check','agreement_voice_link_guard_v1'))
     or not exists(select 1 from pg_constraint where conrelid='public.agreement_messages'::regclass and conname='agreement_messages_body_photo_check' and convalidated and pg_get_constraintdef(oid)=$photo_check${{PHOTO_CHECK_DEF}}$photo_check$)
     or not exists(select 1 from pg_constraint where conrelid='private.closure_actions_v5'::regclass and conname='closure_action_shape146' and convalidated and pg_get_constraintdef(oid)=$action_shape${{ACTION_SHAPE_DEF}}$action_shape$)
     or exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in('public','private','rls_private') and c.relname like 'agreement\_voice\_%') then
    raise exception 'VOICE_B1_REVERT_NEW_TABLE_DELTA' using errcode='55000';end if;

  -- Delta accounting 3/3: the retention catalog is what it was, the certificate is bound in its three places to the restored digest, nothing else moved.
  if (select jsonb_agg(to_jsonb(c) order by data_class) from private.closure_dataset_catalog_v5 c) is distinct from expected_datasets then
    raise exception 'VOICE_B1_REVERT_CATALOG_DELTA' using errcode='55000';end if;
  if private.closure_source_digest_v5() is distinct from target_source
     or (select sha256 from private.closure_source_v5 where singleton) is distinct from target_source
     or (select sha256 from private.closure_erasure_source_v5 where singleton) is distinct from target_source
     or private.retention_ai_source_ready() is distinct from true
     or private.closure_erasure_binding_v5()->>'sourceSha256' is distinct from target_source then
    raise exception 'VOICE_B1_REVERT_CERTIFIED_POSTCONDITION' using errcode='55000';end if;
  if exists(select 1 from private.closure_executions_v5 where state='EXECUTING')
     or has_function_privilege('anon','private.retention_ai_source_ready()','EXECUTE')
     or has_function_privilege('authenticated','private.retention_ai_source_ready()','EXECUTE') then
    raise exception 'VOICE_B1_REVERT_FINAL_AUTHORITY_OR_STATE_DRIFT' using errcode='55000';end if;
end
$voice_b1_revert$;
