-- D12 written comment DEV postflight. READ-ONLY: one SELECT, no write, no lock, no function with a side effect. Run it against canonical DEV right after the ONE-statement application (and at any time later).
-- GENERATED by supabase/proofs/d12/build_d12.py from the pin tables of the application (d12_pins.json, d12_preimage.json and the new function bodies): do not edit by hand (`--check` fails on any difference).
-- Returns ONE row of JSON: how many pins were compared, every part of the applied state that does not hold ("problems": an empty array means the application is exactly in place and the closure certificate is
-- bound, certified and ready) and the live certificate facts. The disposable proof runs this same file on the chain the application produced and requires an empty list.
with
  metadata_pins(signature, metadata_md5) as (values
    ('private.closure_redaction_relations_v5()','30967acfddf4a189e7d97f1230ce286b'),
    ('private.closure_redaction_scope_v5(text)','1d9ea6d4b770cb0da939e87b2218e1eb'),
    ('private.closure_redaction_patch_v5(text,jsonb,uuid,uuid)','6f2f71c85685d1c34f07c6b7eb8efc64'),
    ('private.retention_ai_source_ready()','60d41c1d50dbaedd8cbcd7a580fc21d2'),
    ('private.data_export_dataset_catalog()','206096870b0fd5eae1cb2780db2e6601'),
    ('private.data_export_snapshot(uuid,uuid,jsonb,timestamptz)','3965d2c8b12ff99d3c9dc928912890f1'),
    ('private.data_export_policy_binding()','a9596e2741a92a607cfd4cee0896604a'),
    ('public.rpc_submit_agreement_review(uuid,uuid,jsonb,jsonb,uuid)','a19f46c4668de2563f2edda6bb5b690f'),
    ('public.rpc_get_my_agreement_review(uuid)','ca42148a86a12c6129cd70feec7b54f6'),
    ('public.rpc_get_account_reputation(uuid)','11bbaac433967396787dca48002a3d7c'),
    ('public.rpc_get_public_profile(uuid)','c7de91ef7e30343f6cf6d49754382d82'),
    ('private.account_reputation(uuid)','0f4d25b7c14261835a5495ff40c2bef8'),
    ('private.guard_review_immutable()','60f1016a6f655c3b5f4e23bc1287f92b'),
    ('private.review_tag_catalog()','f7ddc53185277f0afbf0f2ea681dbc17'),
    ('private.review_tags_valid(text[])','8fcf97112d335bd9cf9a6fba921be85f'),
    ('public.rpc_list_my_agreements_page(text,integer,timestamptz,uuid)','891f18c2a10c9ada3bda3fa1b6e9e8ed'),
    ('public.rpc_home_attention()','1081f68fd348e9e1125a8e03786e0cf3'),
    ('private.closure_guard_owned_write()','eda4068416eb9a54691c331cbde691dd'),
    ('private.closure_redaction_allowed_v5(oid,text,jsonb,jsonb)','e4245b6db4ef8b0d4ee8846e684f511a'),
    ('private.closure_blockers_v5(uuid)','272d5ea792598448e86b127f4dc37c3c'),
    ('private.closure_erasure_binding_v5()','5b8021c77f85c119e95a41bbac2da3b1'),
    ('private.closure_source_digest_v5()','7ade1ea4e26aa1f5a7fb8a84553b89d4'),
    ('private.closure_erasure_program_digest_v5()','3b5059bc329407eface02b5b631d709d'),
    ('private.closure_schema_digest_v5_139()','226adf4b6cd896c5fa48fcab19780f35'),
    ('private.closure_assert_open(uuid,uuid)','7b0a4e1be3205b5de509ddfc726e406a'),
    ('private.closure_account_key(uuid)','20307d6e0d35a0c76b8e04fc12ded583'),
    ('private.closure_account_restricted(uuid)','814dfd0286240ae2eec5a2d2a56bbe51'),
    ('public.rpc_start_account_closure_execution(uuid,uuid,integer,uuid,text)','77bb6868db8bfcc02d56137e22c04dab'),
    ('public.rpc_closure_api_guard()','a36eea680eedb95a8d61632b060ca5ff'),
    ('public.rpc_redact_account_closure_step_service(uuid,uuid,uuid,uuid)','5a558704604067ae344261a2e84b6762'),
    ('private.support_reference_v5(uuid,jsonb)','1433a1360c044dc3a6d984af95c89668'),
    ('public.rpc_support_find_context_v5(uuid,text,uuid)','6a6a213a6f0e564905a09b127d889dd2'),
    ('private.audit_marketplace(uuid,text,text,uuid,integer,jsonb)','1f67d6123158625d421938e4b18bc0e0'),
    ('private.emit_event(uuid,text,text,text,uuid,integer,text,text,text,text,jsonb,timestamptz)','f42a9a9adeed0279cd446cae160746c6'),
    ('private.safety_pair_blocked(uuid,uuid)','7d6f3e0e0af60182f612bd0251c8f152'),
    ('private.accounts_same_world(uuid,uuid)','822aa2709088e7e2140c1d96d96a2794'),
    ('private.account_visibility_world(uuid)','7fd9af73365f1dfeae423da03950bd63'),
    ('private.ru4b_public_floor_reason(text)','db1ee32f5be6f43b23ae3522bfc0adce'),
    ('private.data_export_projection_sha_v5()','28fe45d56ec78178809319de4c643e25'),
    ('private.data_export_scalar_v5(jsonb,text)','9caa811e2b0b486d3fd5c888ae76b762'),
    ('private.data_export_array_v5(jsonb,text)','83ec48e5d734a1993abaf7d7682f7c29'),
    ('private.data_export_worker_candidate_v5(jsonb)','c5dc3f98fc276304fd4dbd196fb7e1e5'),
    ('private.data_export_task_facts_v5(jsonb)','9c3b78c23c2d7e7e2fbcc140744bc724'),
    ('public.rpc_submit_safety_report(uuid,uuid,uuid,text,text,text,uuid)','1f8550103d2b71dfa3aecd335525238c')
  ),
  unchanged_body_pins(signature, body_md5) as (values
    ('public.rpc_submit_agreement_review(uuid,uuid,jsonb,jsonb,uuid)','ff68b552c4f972e5d58a632672bc359e'),
    ('public.rpc_get_my_agreement_review(uuid)','75a8b78ec8a5e6334f42366b4461c14c'),
    ('public.rpc_get_account_reputation(uuid)','4166221185edf108338898ba04f5e48a'),
    ('public.rpc_get_public_profile(uuid)','9ecc0b69096f1167d02e0bb7b9656bc0'),
    ('private.account_reputation(uuid)','f03e558ff56a31a0b49e394714b628cd'),
    ('private.review_receipt(private.agreement_reviews,boolean)','7058b3cc23f853edaea9cb21cdb865b1'),
    ('private.guard_review_immutable()','f883b4ed1be3dfa5401f98f9bdfe1960'),
    ('private.review_tag_catalog()','2b2ccb8e1c2672d091c3e319e4b1ea49'),
    ('private.review_tags_valid(text[])','69ca0f79f5869c13bcfaa392cc0ac6fa'),
    ('public.rpc_list_my_agreements_page(text,integer,timestamptz,uuid)','5017f90ff8d9e5cd29ead0f88a6b0106'),
    ('public.rpc_home_attention()','1703b04e248759a19cbcc539621ed906'),
    ('private.closure_guard_owned_write()','f13117fd601dcb82de423b78f25acb4f'),
    ('private.closure_redaction_allowed_v5(oid,text,jsonb,jsonb)','7fabcc71502e065e638364fc3d58b761'),
    ('private.closure_blockers_v5(uuid)','cd0c2921bfd52ba2e96769b2a409b9db'),
    ('private.closure_erasure_binding_v5()','d6d7e7f6f108fff45a4df5126949fa04'),
    ('private.closure_source_digest_v5()','9fb4a72f3feef8e4557a96f4c9d7224e'),
    ('private.closure_erasure_program_digest_v5()','229887adb43d52990dc4254176222696'),
    ('private.closure_schema_digest_v5_139()','988b9d3ab9c0dc7341cd30a391184e40'),
    ('private.closure_assert_open(uuid,uuid)','dc9bc4c718593850da4fdb49e612dbd2'),
    ('private.closure_account_key(uuid)','2dde6ad2462255b188e4f03ffe88edcd'),
    ('private.closure_account_restricted(uuid)','f4999250c315e0253374d4611291c7ad'),
    ('private.closure_erasure_assert_current_v5(private.closure_executions_v5)','be536bbccba9600ecc5c34f4a4d747de'),
    ('public.rpc_start_account_closure_execution(uuid,uuid,integer,uuid,text)','3fc04b344892a252956219ce85f4de34'),
    ('public.rpc_closure_api_guard()','09d52badff732c2b22ba7b69adfa4d66'),
    ('public.rpc_redact_account_closure_step_service(uuid,uuid,uuid,uuid)','0fd89c6c870f3496d485f97d8016ba7c'),
    ('private.closure_erasure_refresh_steps_v5(private.closure_executions_v5)','f228322985e8ae90bce17880d1ffd9c4'),
    ('private.support_reference_v5(uuid,jsonb)','94ad410f355654cffccd9de1084571bb'),
    ('public.rpc_support_find_context_v5(uuid,text,uuid)','66b392dcf118e3109e3a12ebd909c159'),
    ('private.audit_marketplace(uuid,text,text,uuid,integer,jsonb)','ef33e1d34afb1507071c47253a13c9b2'),
    ('private.emit_event(uuid,text,text,text,uuid,integer,text,text,text,text,jsonb,timestamptz)','67413effbbb3fa227397d355e0d4edfb'),
    ('private.safety_pair_blocked(uuid,uuid)','698fb21abb0379743bc7ab09d9f946ad'),
    ('private.accounts_same_world(uuid,uuid)','16f541f952d4e1e2dbb4fc87e594d572'),
    ('private.account_visibility_world(uuid)','876cfc16f0ed1c4d32b128e8e18bdcda'),
    ('private.ru4b_public_floor_reason(text)','3462ec034f1f9df9760e4729aa0d2c18'),
    ('private.data_export_projection_sha_v5()','f628ae258c3bae4a1d0fed0cde3dac53'),
    ('private.data_export_scalar_v5(jsonb,text)','e02fe0db0a56b90b74a29c2b81a38357'),
    ('private.data_export_array_v5(jsonb,text)','00933c589c16905b09318c080a2150f6'),
    ('private.data_export_worker_candidate_v5(jsonb)','aa9c5f1b7ab4711cda7cb16905de55a4'),
    ('private.data_export_task_facts_v5(jsonb)','b1552206df3434002e6d294befbca5b6'),
    ('public.rpc_submit_safety_report(uuid,uuid,uuid,text,text,text,uuid)','9249705c01cc3d29d178f1ebd331daeb')
  ),
  applied_body_pins(signature, body_md5) as (values
    ('private.closure_redaction_relations_v5()','ba362b6d0045d06e6207fc0a8f0592d4'),
    ('private.closure_redaction_scope_v5(text)','aec26bb057ec0022245a5d8641a47585'),
    ('private.closure_redaction_patch_v5(text,jsonb,uuid,uuid)','3891fe77d38af04e06cfe4c9e4abb96f'),
    ('private.data_export_dataset_catalog()','b19598a0ad6547de9609da121f5d4a3e'),
    ('private.data_export_snapshot(uuid,uuid,jsonb,timestamptz)','a50e4f7203df2a65cff264ee2471c13c'),
    ('private.data_export_policy_binding()','3695d063e7c8fa9f835b5e8cc34b5926')
  ),
  new_function_pins(signature, body_md5, language_name, volatility, definer, strict_function, result_type, acl) as (values
    ('private.guard_review_comment_mutation()','5280b99f20c4a7be695d7e16402b3f43','plpgsql','v',true,false,'trigger','{postgres=X/postgres}'),
    ('private.review_comment_input_v1(jsonb)','130692c918a53e26f1d911bbb6482029','plpgsql','s',false,false,'text','{postgres=X/postgres}'),
    ('public.rpc_submit_agreement_review_v2(uuid,uuid,jsonb,jsonb,uuid,jsonb)','75a88570ff847b97a7d71b0854acf171','plpgsql','v',true,false,'jsonb','{postgres=X/postgres,authenticated=X/postgres}'),
    ('public.rpc_get_my_agreement_review_v2(uuid)','60fb54e25317d6c2873321e66588dbeb','plpgsql','s',true,false,'jsonb','{postgres=X/postgres,authenticated=X/postgres}'),
    ('public.rpc_list_review_comments_v1(uuid,integer,jsonb)','0712dcb3bfb25ec782f40c0fe47f17c3','plpgsql','s',true,false,'jsonb','{postgres=X/postgres,authenticated=X/postgres}'),
    ('public.rpc_moderate_review_comment_service_v1(uuid,text,text,uuid)','2de37076287d759515407eecccc92728','plpgsql','v',true,false,'jsonb','{postgres=X/postgres,service_role=X/postgres}')
  ),
  composite_pins(signature, acl, config, definer, volatility, language_name, result_type, strict_function) as (values
    ('private.review_receipt(private.agreement_reviews,boolean)','{postgres=X/postgres}','{search_path=pg_catalog}',false,'s','plpgsql','jsonb',false),
    ('private.closure_erasure_assert_current_v5(private.closure_executions_v5)','{postgres=X/postgres}','{search_path=pg_catalog}',true,'v','plpgsql','void',false),
    ('private.closure_erasure_refresh_steps_v5(private.closure_executions_v5)','{postgres=X/postgres}','{search_path=pg_catalog}',true,'v','plpgsql','void',false)
  ),
  cert as (
    select (select count(*) from private.closure_source_v5) as source_rows,
           (select count(*) from private.closure_erasure_source_v5) as erasure_rows,
           (select sha256 from private.closure_source_v5 where singleton) as certified,
           (select sha256 from private.closure_erasure_source_v5 where singleton) as erasure_sha,
           private.closure_source_digest_v5() as live_digest,
           private.retention_ai_source_ready() as ready,
           private.closure_erasure_binding_v5()->>'sourceSha256' as bound
  ),
  problems as (
    select 'METADATA_DRIFT' as kind, pin.signature as detail
    from metadata_pins pin
    where (select md5(((to_jsonb(p)-'oid'-'pronamespace'-'proowner'-'prolang'-'proacl'-'prosrc')
        ||jsonb_build_object('namespace',n.nspname,'owner',pg_get_userbyid(p.proowner),'language',l.lanname,'acl',p.proacl::text))::text)
        from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang
        where p.oid=to_regprocedure(pin.signature)) is distinct from pin.metadata_md5
    union all
    select 'UNCHANGED_BODY_DRIFT', pin.signature
    from unchanged_body_pins pin
    where (select md5(replace(prosrc,E'\r\n',E'\n')) from pg_proc where oid=to_regprocedure(pin.signature)) is distinct from pin.body_md5
    union all
    select 'APPLIED_BODY_DRIFT', pin.signature
    from applied_body_pins pin
    where (select md5(replace(prosrc,E'\r\n',E'\n')) from pg_proc where oid=to_regprocedure(pin.signature)) is distinct from pin.body_md5
    union all
    select 'NEW_FUNCTION_DRIFT', pin.signature
    from new_function_pins pin
    where not exists(select 1 from pg_proc p where p.oid=to_regprocedure(pin.signature) and md5(replace(p.prosrc,E'\r\n',E'\n'))=pin.body_md5 and p.prosecdef=pin.definer and p.proisstrict=pin.strict_function
      and p.proconfig=array['search_path=pg_catalog'] and p.proowner='postgres'::regrole
      and p.prolang=(select oid from pg_language where lanname=pin.language_name)
      and p.provolatile::text=pin.volatility and p.prokind='f' and p.prorettype=to_regtype(pin.result_type)
      and p.proacl::text=pin.acl and not p.proretset and not p.proleakproof and p.proparallel='u'
      and p.probin is null and p.prosqlbody is null and p.protrftypes is null and p.proallargtypes is null and p.proargmodes is null)
    union all
    select 'LEGACY_REVIEW_FUNCTION_OVERLOAD', 'rpc_submit_agreement_review or rpc_get_my_agreement_review has a second overload'
    where (select count(*) from pg_proc where pronamespace='public'::regnamespace and proname in('rpc_submit_agreement_review','rpc_get_my_agreement_review'))<>2
    union all
    select 'READINESS_DRIFT', 'private.retention_ai_source_ready() differs from the predecessor by more than its one certified literal'
    where not exists(select 1 from pg_proc p, cert c where p.oid=to_regprocedure('private.retention_ai_source_ready()')
      and (length(p.prosrc)-length(replace(p.prosrc,c.certified,'')))=length(c.certified)
      and md5(replace(replace(p.prosrc,E'\r\n',E'\n'),c.certified,'__CERTIFIED_SOURCE__'))='bc85a1a744869abb6441e647b18b2195')
    union all
    select 'PROJECTION_SHA_DRIFT', 'private.data_export_projection_sha_v5()'
    where private.data_export_projection_sha_v5() is distinct from '53848e48d1a01082fcbd1413e4f9210b43153a9eb75e7af2723aa8c40f32b597'
    union all
    select 'COMMENT_TABLE_DRIFT', 'private.agreement_review_comments_v1'
    where (not exists(select 1 from pg_class where oid=to_regclass('private.agreement_review_comments_v1') and relowner='postgres'::regrole and relkind='r' and relpersistence='p'
      and not relispartition and relrowsecurity and relforcerowsecurity and relreplident='d' and reloptions is null and relacl=acldefault('r','postgres'::regrole))
    or exists(select 1 from pg_policies where schemaname='private' and tablename='agreement_review_comments_v1')
    or (select string_agg(attname::text||':'||format_type(atttypid,atttypmod)||':'||attnotnull::text||':'||attidentity::text||':'||attgenerated::text,',' order by attnum)
        from pg_attribute where attrelid=to_regclass('private.agreement_review_comments_v1') and attnum>0 and not attisdropped) is distinct from 'review_id:uuid:true::,author_account_id:uuid:true::,target_account_id:uuid:true::,comment:text:true::,comment_sha256:text:true::,created_at:timestamp with time zone:true::,hidden_at:timestamp with time zone:false::,hidden_reason_code:text:false::'
    or (select pg_get_expr(d.adbin,d.adrelid) from pg_attrdef d join pg_attribute a on a.attrelid=d.adrelid and a.attnum=d.adnum
        where d.adrelid=to_regclass('private.agreement_review_comments_v1') and a.attname='created_at') is distinct from 'clock_timestamp()'
    or (select string_agg(conname::text||':'||contype::text,',' order by conname) from pg_constraint
        where conrelid=to_regclass('private.agreement_review_comments_v1') and contype<>'n' and convalidated and conislocal and conparentid=0) is distinct from 'agreement_review_comments_v1_author_fkey:f,agreement_review_comments_v1_hidden_check:c,agreement_review_comments_v1_parties_check:c,agreement_review_comments_v1_pkey:p,agreement_review_comments_v1_review_fkey:f,agreement_review_comments_v1_sha_check:c,agreement_review_comments_v1_target_fkey:f,agreement_review_comments_v1_text_chars_check:c,agreement_review_comments_v1_text_length_check:c,agreement_review_comments_v1_text_trim_check:c'
    or (select count(*) from pg_constraint where conrelid=to_regclass('private.agreement_review_comments_v1') and contype='f' and confdeltype='r' and confupdtype='a' and confmatchtype='s'
        and confrelid in('private.agreement_reviews'::regclass,'public.app_accounts'::regclass))<>3
    or (select string_agg(indexname::text,',' order by indexname) from pg_indexes where schemaname='private' and tablename='agreement_review_comments_v1') is distinct from 'agreement_review_comments_v1_author_idx,agreement_review_comments_v1_pkey,agreement_review_comments_v1_target_idx'
    or not exists(select 1 from pg_indexes where schemaname='private' and tablename='agreement_review_comments_v1' and indexname='agreement_review_comments_v1_target_idx'
        and indexdef like '%(target_account_id, created_at DESC, review_id DESC)%' and indexdef like '%hidden_at IS NULL%')
    or not exists(select 1 from pg_indexes where schemaname='private' and tablename='agreement_review_comments_v1' and indexname='agreement_review_comments_v1_author_idx' and indexdef like '%(author_account_id)%'))
    union all
    select 'TRIGGER_DRIFT', 'private.agreement_review_comments_v1 triggers'
    where (exists(select 1 from (values
      ('agreement_review_comment_closure_guard_v1','private.closure_guard_owned_write()',7,'4143434f554e5400617574686f725f6163636f756e745f696400'),
      ('agreement_review_comment_mutation_guard_v1','private.guard_review_comment_mutation()',27,'')
    ) q(trigger_name,signature,event_type,argument_hex)
    where not exists(select 1 from pg_trigger t where t.tgrelid=to_regclass('private.agreement_review_comments_v1') and t.tgname=q.trigger_name
      and t.tgfoid=to_regprocedure(q.signature) and t.tgtype=q.event_type and t.tgenabled='O' and not t.tgisinternal
      and encode(t.tgargs,'hex')=q.argument_hex and t.tgqual is null and t.tgconstraint=0
      and not t.tgdeferrable and not t.tginitdeferred and t.tgoldtable is null and t.tgnewtable is null and t.tgparentid=0 and t.tgattr::text=''))
    or (select count(*) from pg_trigger where tgrelid=to_regclass('private.agreement_review_comments_v1') and not tgisinternal)<>2)
    union all
    select 'ROSTER_DRIFT', 'the redaction roster does not end with the comment table or the scope/patch do not cover it'
    where cardinality(private.closure_redaction_relations_v5())<>76
      or (private.closure_redaction_relations_v5())[76] is distinct from 'private.agreement_review_comments_v1'
      or (private.closure_redaction_relations_v5())[75] is distinct from 'public.app_accounts'
      or 'private.agreement_reviews'=any(private.closure_redaction_relations_v5())
      or private.closure_redaction_scope_v5('private.agreement_review_comments_v1') is distinct from 't.author_account_id=$1'
      or private.closure_redaction_patch_v5('private.agreement_review_comments_v1','{}'::jsonb,'00000000-0000-0000-0000-000000000000'::uuid,'00000000-0000-0000-0000-000000000000'::uuid)
         is distinct from jsonb_build_object('operation','DELETE','patch','{}'::jsonb)
    union all
    select 'RETENTION_CATALOG_DRIFT', 'AGREEMENT_REVIEWS'
    where (select relations from private.closure_dataset_catalog_v5 where data_class='AGREEMENT_REVIEWS') is distinct from array['private.agreement_reviews','private.agreement_review_comments_v1']::text[]
      or (select count(*) from private.retention_data_classes where required and active)<>15
    union all
    select 'EXPORT_CATALOG_DRIFT', 'private.data_export_dataset_catalog()'
    where jsonb_array_length(private.data_export_dataset_catalog())<>52
      or (select v->'fields' from jsonb_array_elements(private.data_export_dataset_catalog()) v where v->>'key'='ownAgreementReviews') is distinct from '["agreementId","createdAt","id","rating","tags","comment"]'::jsonb
      or position('OWN_ACCOUNT_V5_10' in (select prosrc from pg_proc where oid=to_regprocedure('private.data_export_snapshot(uuid,uuid,jsonb,timestamptz)')))=0
      or position('OWN_ACCOUNT_V5_9' in (select prosrc from pg_proc where oid=to_regprocedure('private.data_export_snapshot(uuid,uuid,jsonb,timestamptz)')))<>0
      or position('OWN_ACCOUNT_V5_10' in (select prosrc from pg_proc where oid=to_regprocedure('private.data_export_policy_binding()')))=0
      or position('OWN_ACCOUNT_V5_9' in (select prosrc from pg_proc where oid=to_regprocedure('private.data_export_policy_binding()')))<>0
    union all
    select 'STAR_TABLE_DRIFT', 'private.agreement_reviews is not the unchanged immutable star table'
    where (select string_agg(attname::text||':'||format_type(atttypid,atttypmod)||':'||attnotnull::text||':'||attidentity::text||':'||attgenerated::text,',' order by attnum)
           from pg_attribute where attrelid='private.agreement_reviews'::regclass and attnum>0 and not attisdropped) is distinct from 'id:uuid:true::,agreement_id:uuid:true::,reviewer_account_id:uuid:true::,target_account_id:uuid:true::,rating:integer:true::,tags:text[]:true::,client_request_id:uuid:true::,input_hash:text:true::,created_at:timestamp with time zone:true::'
      or (select md5(string_agg(conname||':'||replace(pg_get_constraintdef(oid),'REFERENCES public.','REFERENCES '),';' order by conname)) from pg_constraint where conrelid='private.agreement_reviews'::regclass) is distinct from 'fe44059a7fa96aeb732ff3459f6865d1'
      or (select string_agg(tgname,',' order by tgname) from pg_trigger where tgrelid='private.agreement_reviews'::regclass and not tgisinternal) is distinct from 'pre_v3_closure_review,pre_v3_review_immutable'
      or (select relacl::text from pg_class where oid='private.agreement_reviews'::regclass) is distinct from '{postgres=arwdDxtm/postgres}'
      or not (select relrowsecurity and relforcerowsecurity from pg_class where oid='private.agreement_reviews'::regclass)
      or (select count(*) from pg_policy where polrelid='private.agreement_reviews'::regclass)<>0
    union all
    select 'COMPOSITE_METADATA_DRIFT', pin.signature
    from composite_pins pin
    where not exists(select 1 from pg_proc p where p.oid=to_regprocedure(pin.signature) and p.proowner='postgres'::regrole and p.proacl::text=pin.acl and coalesce(p.proconfig::text,'')=pin.config and p.prosecdef=pin.definer and p.provolatile::text=pin.volatility
      and p.proisstrict=pin.strict_function and p.prolang=(select oid from pg_language where lanname=pin.language_name) and p.prorettype=to_regtype(pin.result_type) and p.prokind='f')
    union all
    select 'RETENTION_CLASS_DESCRIPTION_DRIFT', 'the description of the retention class AGREEMENT_REVIEWS is not the text this package sets'
    where (select description from private.retention_data_classes where code='AGREEMENT_REVIEWS' and required and active) is distinct from 'Immutable bilateral completed-Agreement reviews and their account-level reputation projection (private.agreement_reviews), plus the optional written comment of a review (private.agreement_review_comments_v1): free text of the author, erased when the author account is closed; this description sets no retention period.'
    union all
    select 'COMMENT_TABLE_PUBLISHED', 'the comment table is in a publication, or a FOR ALL TABLES publication exists: the text could be streamed'
    where exists(select 1 from pg_publication_tables where schemaname='private' and tablename='agreement_review_comments_v1') or exists(select 1 from pg_publication where puballtables)
    union all
    select 'CERTIFICATE_CARDINALITY', 'closure_source_v5 and closure_erasure_source_v5 must hold exactly one row each'
    from cert where source_rows<>1 or erasure_rows<>1
    union all
    select 'CERTIFICATE_NOT_BOUND', 'the certificate, the live digest, the erasure source row, the readiness and the binding must all agree'
    from cert where certified is null or certified is distinct from live_digest or certified is distinct from erasure_sha or ready is distinct from true or bound is distinct from certified
    union all
    select 'CERTIFICATE_NOT_MOVED', 'the certified digest must differ from the pre-D12 DEV value when the chain is DEV (58447d7730e909a0c0e60dd92ef77416af927471bd6f645988448e32c6e3cb46)'
    from cert where certified='58447d7730e909a0c0e60dd92ef77416af927471bd6f645988448e32c6e3cb46'
    union all
    select 'FUNCTION_AUTHORITY_DRIFT', 'a new function is reachable by a role it must not be reachable by, or the table is reachable by a client role'
    where has_function_privilege('anon','private.retention_ai_source_ready()','EXECUTE') or has_function_privilege('authenticated','private.retention_ai_source_ready()','EXECUTE')
      or exists(select 1 from unnest(array['private.guard_review_comment_mutation()','private.review_comment_input_v1(jsonb)','public.rpc_submit_agreement_review_v2(uuid,uuid,jsonb,jsonb,uuid,jsonb)','public.rpc_get_my_agreement_review_v2(uuid)','public.rpc_list_review_comments_v1(uuid,integer,jsonb)','public.rpc_moderate_review_comment_service_v1(uuid,text,text,uuid)']::text[]) x where has_function_privilege('anon',x,'EXECUTE'))
      or exists(select 1 from unnest(array['public.rpc_submit_agreement_review_v2(uuid,uuid,jsonb,jsonb,uuid,jsonb)','public.rpc_get_my_agreement_review_v2(uuid)','public.rpc_list_review_comments_v1(uuid,integer,jsonb)']::text[]) x where not has_function_privilege('authenticated',x,'EXECUTE') or has_function_privilege('service_role',x,'EXECUTE'))
      or exists(select 1 from unnest(array['private.guard_review_comment_mutation()','private.review_comment_input_v1(jsonb)']::text[]) x where has_function_privilege('authenticated',x,'EXECUTE') or has_function_privilege('service_role',x,'EXECUTE'))
      or has_function_privilege('authenticated','public.rpc_moderate_review_comment_service_v1(uuid,text,text,uuid)','EXECUTE') or not has_function_privilege('service_role','public.rpc_moderate_review_comment_service_v1(uuid,text,text,uuid)','EXECUTE')
      or exists(select 1 from unnest(array['anon','authenticated','service_role']) r where has_table_privilege(r,'private.agreement_review_comments_v1','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'))
    union all
    select 'RETRIED_SQLSTATE_IN_A_NEW_BODY', 'a new function mentions the SQLSTATE that PostgREST 14 re-executes without end (a deterministic conflict must be PT409; no new body mentions it at all)'
    where exists(select 1 from unnest(array['private.guard_review_comment_mutation()','private.review_comment_input_v1(jsonb)','public.rpc_submit_agreement_review_v2(uuid,uuid,jsonb,jsonb,uuid,jsonb)','public.rpc_get_my_agreement_review_v2(uuid)','public.rpc_list_review_comments_v1(uuid,integer,jsonb)','public.rpc_moderate_review_comment_service_v1(uuid,text,text,uuid)']::text[]) x join pg_proc p on p.oid=to_regprocedure(x) where position('40001' in p.prosrc)>0)
    union all
    select 'CLOSURE_IN_FLIGHT', 'a closure execution is EXECUTING'
    where exists(select 1 from private.closure_executions_v5 where state='EXECUTING')
  )
select jsonb_build_object(
  'unit', 'D12_DEV_POSTFLIGHT',
  'metadataPinsChecked', (select count(*) from metadata_pins),
  'unchangedBodyPinsChecked', (select count(*) from unchanged_body_pins),
  'appliedBodyPinsChecked', (select count(*) from applied_body_pins),
  'newFunctionPinsChecked', (select count(*) from new_function_pins),
  'problems', coalesce((select jsonb_agg(jsonb_build_object('kind',kind,'detail',detail) order by kind,detail) from problems), '[]'::jsonb),
  'certifiedSource', (select certified from cert),
  'liveDigest', (select live_digest from cert),
  'ready', (select ready from cert),
  'erasureBindingMatches', (select bound is not distinct from certified from cert),
  'redactionRelations', cardinality(private.closure_redaction_relations_v5()),
  'exportDatasets', jsonb_array_length(private.data_export_dataset_catalog()),
  'exportProjectionSha', private.data_export_projection_sha_v5(),
  'exportPolicyBindingIsNull', private.data_export_policy_binding() is null,
  'commentRows', (select count(*) from private.agreement_review_comments_v1),
  'retentionClassDescription', (select description from private.retention_data_classes where code='AGREEMENT_REVIEWS'),
  'closureHistoryNamingTheCommentTable', (select count(*) from private.closure_redaction_steps_v5 where relation_name='private.agreement_review_comments_v1'),
  'reviews', (select count(*) from private.agreement_reviews),
  'reviewIdHashBaseline', (select md5(string_agg(id::text||':'||input_hash,',' order by id)) from private.agreement_reviews),
  'authenticatedHasPrivateSchemaUsage', has_schema_privilege('authenticated','private','USAGE'),
  'ledgerRows', (select count(*) from supabase_migrations.schema_migrations),
  'latestLedgerVersion', (select max(version) from supabase_migrations.schema_migrations),
  'serverVersion', current_setting('server_version'),
  'checkedAt', to_char(clock_timestamp() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
) as postflight;
