import {assert,rows,sql,prove,pass,apply} from './closure_runtime.mjs';
import {migrationSnapshotQuery} from './history_snapshot.mjs';
await prove('PRE_V3_PUBLICATION_OWNER_ACTIVATION','publication-owner-activation-report.json',async report=>{
  await apply(report,'20260912193000_clean_pre_v3_publication_owner_product_activation.sql',123);
  const history=rows(migrationSnapshotQuery());assert.equal(history.length,124);report.historyCount=124;
  const bundles=rows(`select id,policy_id,version,jurisdiction,is_reviewed,is_complete,is_active,review_provenance,reviewed_at,effective_from,activated_at
    from private.publication_policy_bundles where policy_id='RS_PUBLICATION_POLICY_MINIMUM' and jurisdiction='RS' order by version`);
  assert.equal(bundles.length,1);const b=bundles[0];
  assert.equal(b.version,1);assert.equal(b.is_reviewed,true);assert.equal(b.is_complete,true);assert.equal(b.is_active,true);
  assert.equal(b.review_provenance.review_state,'OWNER_PRODUCT_APPROVED_NOT_LEGAL_CERTIFICATION');
  assert.equal(b.review_provenance.legal_certification,false);assert.equal(b.review_provenance.approved_by,'USKOCI_PRODUCT_OWNER');
  assert.ok(b.reviewed_at&&b.effective_from&&b.activated_at);
  assert.equal(sql(`select private.publication_policy_bundle_ready('${b.id}'::uuid,'RS',statement_timestamp())`),'t');
  assert.equal(sql(`select private.current_publication_policy_bundle('RS_PUBLICATION_POLICY_MINIMUM','RS',statement_timestamp())='${b.id}'::uuid`),'t');
  pass(report,'OWNER_PRODUCT_APPROVAL_IS_READY_BUT_EXPLICITLY_NOT_LEGAL_CERTIFICATION');
  const refs=rows(`select rule_id,rule_provenance->>'outcome' outcome from private.publication_policy_rule_refs where bundle_id='${b.id}'::uuid order by rule_id`);
  assert.equal(refs.length,16);const outcome=Object.fromEntries(refs.map(r=>[r.rule_id,r.outcome]));
  assert.equal(outcome['RS-MIN-001'],'ALLOW');
  for(const id of ['RS-MIN-002','RS-MIN-003','RS-MIN-004','RS-MIN-006','RS-MIN-007','RS-MIN-008','RS-MIN-009','RS-MIN-010','RS-MIN-011'])assert.equal(outcome[id],'BLOCK');
  for(const id of ['RS-MIN-005','RS-MIN-012','RS-MIN-013'])assert.equal(outcome[id],'CLARIFY');
  for(const id of ['RS-MIN-014','RS-MIN-016'])assert.equal(outcome[id],'REVIEW');
  assert.equal(outcome['RS-MIN-015'],'NO_OVERRIDE');
  pass(report,'FROZEN_SIXTEEN_RULE_OUTCOMES_PRESERVED_ALLOW_BLOCK_CLARIFY_REVIEW_NO_OVERRIDE');
  assert.equal(sql("select has_table_privilege('anon','private.publication_policy_bundles','SELECT')"),'f');
  assert.equal(sql("select has_table_privilege('authenticated','private.publication_policy_bundles','SELECT')"),'f');
  assert.equal(sql("select has_table_privilege('service_role','private.publication_policy_bundles','SELECT')"),'f');
  assert.equal(sql("select has_function_privilege('authenticated','private.current_publication_policy_bundle(text,text,timestamptz)','EXECUTE')"),'f');
  pass(report,'POLICY_METADATA_AND_PRIVATE_RESOLVER_REMAIN_UNEXPOSED');
  const source=sql("select pg_get_functiondef('public.rpc_record_need_publication_decision_service(uuid,integer,text,text,text,text[],text,text[],text,text,jsonb,jsonb)'::regprocedure)");
  assert.ok(!source.includes('RU3_ALLOW_NOT_ENABLED'),'OBSOLETE_ALLOW_GATE_PRESENT');
  assert.ok(source.includes('publication_policy_bundle_ready'),'DECISION_WRITER_MUST_RECHECK_READY_POLICY');
  pass(report,'DECISION_WRITER_HAS_NO_OBSOLETE_ALLOW_KILL_SWITCH_AND_RECHECKS_POLICY_READINESS');
  assert.deepEqual(rows(migrationSnapshotQuery()),history);
  report.limitations=['This proves product-policy activation and preserved rule outcomes in disposable Auth/Postgres composition.','It does not claim external legal certification.','Real evaluator provider and canonical publish require their own live/runtime proof.'];
});
