-- D12 written comment DEV preflight. READ-ONLY: one SELECT, no write, no lock, no function with a side effect. It can be run against canonical DEV at any time without approval.
-- GENERATED by supabase/proofs/d12/build_d12.py from the pin tables of the application (d12_pins.json, read-only DEV pins): do not edit by hand (`--check` fails on any difference).
-- Returns ONE row of JSON: how many pins were compared, every predecessor gate of the ONE-statement application that does not hold ("problems": an empty array means the application would pass its
-- predecessor gates now) and the live facts it starts from. The application re-checks all of this atomically inside its own transaction; this query only tells earlier whether it would be refused.
with
  metadata_pins(signature, metadata_md5) as (values
{{METADATA_PINS}}
  ),
  body_pins(signature, body_md5) as (values
{{BODY_PINS}}
  ),
  composite_pins(signature, acl, config, definer, volatility, language_name, result_type, strict_function) as (values
{{COMPOSITE_PINS}}
  ),
  ready_function as (
    select p.oid, p.prosrc, pg_get_functiondef(p.oid) as definition
    from pg_proc p where p.oid = to_regprocedure('private.retention_ai_source_ready()')
  ),
  cert as (
    select (select count(*) from private.closure_source_v5) as source_rows,
           (select count(*) from private.closure_erasure_source_v5) as erasure_rows,
           (select sha256 from private.closure_source_v5 where singleton) as old_source,
           (select sha256 from private.closure_erasure_source_v5 where singleton) as erasure_sha,
           private.closure_source_digest_v5() as live_digest,
           private.retention_ai_source_ready() as ready,
           private.closure_erasure_binding_v5()->>'sourceSha256' as bound
  ),
  problems as (
    select 'METADATA_DRIFT' as kind, pin.signature as detail
    from metadata_pins pin
    where (select md5(((to_jsonb(p)-'oid'-'pronamespace'-'proowner'-'prolang'-'proacl'-'prosrc')
        ||jsonb_build_object('namespace',n.nspname,'owner',pg_get_userbyid(p.proowner),'language',l.lanname,'acl',p.proacl::text))::text)
        from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang
        where p.oid=to_regprocedure(pin.signature)) is distinct from pin.metadata_md5
    union all
    select 'BODY_DRIFT', pin.signature
    from body_pins pin
    where (select md5(replace(prosrc,E'\r\n',E'\n')) from pg_proc where oid=to_regprocedure(pin.signature)) is distinct from pin.body_md5
    union all
    select 'COMPOSITE_METADATA_DRIFT', pin.signature
    from composite_pins pin
    where not exists(select 1 from pg_proc p where p.oid=to_regprocedure(pin.signature) and {{COMPOSITE_PREDICATE}})
    union all
    select 'RETENTION_CLASS_DRIFT', 'the description of the retention class {{RETENTION_CLASS_CODE}} is not the predecessor text'
    where (select description from private.retention_data_classes where code='{{RETENTION_CLASS_CODE}}' and required and active) is distinct from {{RETENTION_DESCRIPTION_OLD}}
    union all
    select 'CLOSURE_IN_FLIGHT', 'a closure execution is EXECUTING'
    where exists(select 1 from private.closure_executions_v5 where state='EXECUTING')
    union all
    select 'CERTIFICATE_CARDINALITY', 'closure_source_v5 and closure_erasure_source_v5 must hold exactly one row each'
    from cert where source_rows<>1 or erasure_rows<>1
    union all
    select 'CERTIFICATE_NOT_READY', 'the certificate, the live digest, the erasure source row, the readiness and the binding must all agree'
    from cert where old_source is null or old_source is distinct from live_digest or old_source is distinct from erasure_sha
      or ready is distinct from true or bound is distinct from old_source
    union all
    select 'READINESS_PREDECESSOR_DRIFT', 'retention_ai_source_ready() is not the certified predecessor'
    where not exists(select 1 from ready_function r, cert c
      where (length(r.prosrc)-length(replace(r.prosrc,c.old_source,'')))=length(c.old_source)
        and md5(replace(replace(r.prosrc,E'\r\n',E'\n'),c.old_source,'__CERTIFIED_SOURCE__'))='{{READINESS_PLACEHOLDER_MD5}}')
    union all
    select 'READINESS_LITERAL_DRIFT', 'the readiness definition must carry exactly one certified literal'
    from ready_function r, cert c
    where (length(r.definition)-length(replace(r.definition,c.old_source,'')))<>length(c.old_source)
      or (select count(*) from regexp_matches(r.definition,'[0-9a-f]{64}','g'))<>1
    union all
    select 'D12_ALREADY_PRESENT', 'a D12 object already exists'
    where to_regclass('private.{{TABLE}}') is not null
      or exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where (n.nspname,p.proname) in({{NEW_FUNCTION_NAME_PAIRS}}))
      or exists(select 1 from pg_trigger where tgname in({{TRIGGER_NAME_LIST}}))
      or exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='private' and c.relname in({{INDEX_NAME_LIST}}))
    union all
    select 'ROSTER_OR_CATALOG_DRIFT', 'the redaction roster, the AGREEMENT_REVIEWS catalog row, the export catalog or the export projection is not the expected predecessor'
    where cardinality(private.closure_redaction_relations_v5())<>{{ROSTER_BEFORE}}
      or (private.closure_redaction_relations_v5())[{{ROSTER_BEFORE}}] is distinct from 'public.app_accounts'
      or 'private.agreement_reviews'=any(private.closure_redaction_relations_v5())
      or (select relations from private.closure_dataset_catalog_v5 where data_class='AGREEMENT_REVIEWS') is distinct from array['private.agreement_reviews']::text[]
      or jsonb_array_length(private.data_export_dataset_catalog())<>52
      or (select v->'fields' from jsonb_array_elements(private.data_export_dataset_catalog()) v where v->>'key'='ownAgreementReviews') is distinct from '["agreementId","createdAt","id","rating","tags"]'::jsonb
      or private.data_export_projection_sha_v5() is distinct from '{{PROJECTION_SHA_BEFORE}}'
    union all
    select 'STAR_TABLE_DRIFT', 'private.agreement_reviews is not the expected immutable star table'
    where {{STAR_TABLE_BAD}}
  )
select jsonb_build_object(
  'unit', 'D12_DEV_PREFLIGHT',
  'metadataPinsChecked', (select count(*) from metadata_pins),
  'bodyPinsChecked', (select count(*) from body_pins),
  'problems', coalesce((select jsonb_agg(jsonb_build_object('kind',kind,'detail',detail) order by kind,detail) from problems), '[]'::jsonb),
  'certifiedSource', (select old_source from cert),
  'certifiedSourceIsTheRecordedDevOne', (select old_source is not distinct from '{{CERTIFIED_DIGEST}}' from cert),
  'liveDigest', (select live_digest from cert),
  'ready', (select ready from cert),
  'erasureBindingMatches', (select bound is not distinct from old_source from cert),
  'closureExecutionsExecuting', (select count(*) from private.closure_executions_v5 where state='EXECUTING'),
  'closureExecutionsTotal', (select count(*) from private.closure_executions_v5),
  'redactionRelations', cardinality(private.closure_redaction_relations_v5()),
  'exportDatasets', jsonb_array_length(private.data_export_dataset_catalog()),
  'exportProjectionSha', private.data_export_projection_sha_v5(),
  'requiredRetentionClasses', (select count(*) from private.retention_data_classes where required and active),
  'reviews', (select count(*) from private.agreement_reviews),
  'reviewIdHashBaseline', (select md5(string_agg(id::text||':'||input_hash,',' order by id)) from private.agreement_reviews),
  'ledgerRows', (select count(*) from supabase_migrations.schema_migrations),
  'latestLedgerVersion', (select max(version) from supabase_migrations.schema_migrations),
  'serverVersion', current_setting('server_version'),
  'checkedAt', to_char(clock_timestamp() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
) as preflight;
