-- EX-06 ex06b DEV POSTFLIGHT. READ-ONLY: one SELECT, no write, no lock. Run it against canonical DEV right after the application (and at any time later).
-- GENERATED by supabase/proofs/ex06/build_ex06b.py: do not edit by hand (`--check` fails on any difference).
-- Returns ONE row of JSON. "problems": every part of the applied state that does not hold (an empty array means the application is exactly in place); "informational": a neighbour function whose body is no
-- longer the pinned DEV predecessor (never a problem of this application: a later package may change one). A LATER legitimate edit of the registry rows (an alias added) shows as REGISTRY_ROW_DIFFERS here:
-- this file describes the state right after the application only.
with
  targets(signature, body_md5) as (values ('private.work_kinds_v5(text[])', '78fca96231ddc713cf18990f5a2a34ef')),
  neighbours(signature, body_md5) as (values
    ('private.match_detail_without_calendar(uuid,uuid)','c8aaf3da761242397243fc56262d1aeb'),
    ('private.dispatch_cheap_candidate_admitted(uuid,uuid)','0132fae38c75947179b4d389edc1e1f0'),
    ('private.candidate_profile_ids(uuid,integer)','dca4ddc8080a52c8af83c33689c5568e'),
    ('private.dispatch_next_wave(uuid)','1fd8c51ef026ece24471e2f68250ecc5'),
    ('private.match_detail(uuid,uuid)','38c7894a8cf43a8f32bd5a30bc2cbd09'),
    ('private.match_detail_for_calendar_interval(uuid,uuid,timestamp with time zone,timestamp with time zone)','781956cab666befab216b3ce2334ca1d'),
    ('private.worker_dispatch_time_admitted(uuid,uuid)','4f0beb65922d2b3d947d69e68a56a956'),
    ('private.lower_arr(text[])','07f449cf589196cc8ca349b4f5ca460c')
  ),
  expected_rows(key, value) as (
    select r.item ->> 'key', r.item -> 'value' from jsonb_array_elements($registry$[
  {"key": "work_kinds_head", "value": {"schema": "WORK_KINDS_HEAD_V1", "classificationVersion": "WK-1", "kinds": ["SELIDBE_PREVOZ", "FIZICKI_POSLOVI", "MONTAZA_NAMESTAJA", "SITNE_POPRAVKE", "MOLERSKI_RADOVI", "ELEKTRO", "VODOINSTALATER", "CISCENJE", "PRANJE_PEGLANJE", "BASTA_DVORISTE", "DOSTAVA"], "foldVersion": "SR_LATIN_CYRILLIC_V1", "previous": "PKG-031b hard-coded regular expressions, body md5 2113eb46ab7ea968b873e76d1de12377", "package": "EX-06 ex06b"}},
  {"key": "work_kind:SELIDBE_PREVOZ", "value": {"schema": "WORK_KIND_V1", "kind": "SELIDBE_PREVOZ", "stems": ["selid", "prevoz", "transport", "kombi", "moving", "removal"]}},
  {"key": "work_kind:FIZICKI_POSLOVI", "value": {"schema": "WORK_KIND_V1", "kind": "FIZICKI_POSLOVI", "stems": ["fizick", "nosenj", "nosac", "utovar", "istovar", "iznosenj", "unosenj", "labor", "labour", "loading"]}},
  {"key": "work_kind:MONTAZA_NAMESTAJA", "value": {"schema": "WORK_KIND_V1", "kind": "MONTAZA_NAMESTAJA", "stems": ["montaz", "namestaj", "ikea", "furniture", "assembl", "ikee", "ikei", "ikeu", "ikeom"]}},
  {"key": "work_kind:SITNE_POPRAVKE", "value": {"schema": "WORK_KIND_V1", "kind": "SITNE_POPRAVKE", "stems": ["popravk", "majstor", "handyman", "repair"]}},
  {"key": "work_kind:MOLERSKI_RADOVI", "value": {"schema": "WORK_KIND_V1", "kind": "MOLERSKI_RADOVI", "stems": ["moler", "krecenj", "farbanj", "gletovanj", "painting", "painter", "ofarb"]}},
  {"key": "work_kind:ELEKTRO", "value": {"schema": "WORK_KIND_V1", "kind": "ELEKTRO", "stems": ["elektr", "electr", "struj", "uticnic", "prekidac", "rasvet", "sijalic"]}},
  {"key": "work_kind:VODOINSTALATER", "value": {"schema": "WORK_KIND_V1", "kind": "VODOINSTALATER", "stems": ["vodoinst", "vodovod", "slavin", "odvod", "bojler", "plumb"]}},
  {"key": "work_kind:CISCENJE", "value": {"schema": "WORK_KIND_V1", "kind": "CISCENJE", "stems": ["cisc", "odrzavanj", "clean", "usisav"]}},
  {"key": "work_kind:PRANJE_PEGLANJE", "value": {"schema": "WORK_KIND_V1", "kind": "PRANJE_PEGLANJE", "stems": ["pegl", "pranje vesa", "laundry", "ironing"]}},
  {"key": "work_kind:BASTA_DVORISTE", "value": {"schema": "WORK_KIND_V1", "kind": "BASTA_DVORISTE", "stems": ["bast", "dvorist", "kosenj", "travnjak", "garden", "lawn"]}},
  {"key": "work_kind:DOSTAVA", "value": {"schema": "WORK_KIND_V1", "kind": "DOSTAVA", "stems": ["dostav", "kurir", "delivery", "courier"]}}
]$registry$::jsonb) r(item)
  ),
  registry_valid as (
    select (exists(select 1 from private.marketplace_config c
                    where c.key = 'work_kinds_head' and c.value ->> 'schema' = 'WORK_KINDS_HEAD_V1'
                      and c.value -> 'kinds' = to_jsonb(array['SELIDBE_PREVOZ', 'FIZICKI_POSLOVI', 'MONTAZA_NAMESTAJA', 'SITNE_POPRAVKE', 'MOLERSKI_RADOVI', 'ELEKTRO', 'VODOINSTALATER', 'CISCENJE', 'PRANJE_PEGLANJE', 'BASTA_DVORISTE', 'DOSTAVA']) and c.value ->> 'foldVersion' = 'SR_LATIN_CYRILLIC_V1')
            and (select count(*) from private.marketplace_config c
                  where starts_with(c.key, 'work_kind:') and substr(c.key, 11) = any(array['SELIDBE_PREVOZ', 'FIZICKI_POSLOVI', 'MONTAZA_NAMESTAJA', 'SITNE_POPRAVKE', 'MOLERSKI_RADOVI', 'ELEKTRO', 'VODOINSTALATER', 'CISCENJE', 'PRANJE_PEGLANJE', 'BASTA_DVORISTE', 'DOSTAVA'])
                    and c.value ->> 'schema' = 'WORK_KIND_V1' and c.value ->> 'kind' = substr(c.key, 11)
                    and jsonb_typeof(c.value -> 'stems') = 'array') = cardinality(array['SELIDBE_PREVOZ', 'FIZICKI_POSLOVI', 'MONTAZA_NAMESTAJA', 'SITNE_POPRAVKE', 'MOLERSKI_RADOVI', 'ELEKTRO', 'VODOINSTALATER', 'CISCENJE', 'PRANJE_PEGLANJE', 'BASTA_DVORISTE', 'DOSTAVA'])) as valid
  ),
  smoke(ord, probe_input, probe_expected) as (values
    (1, array[(chr(268)||'i'||chr(353)||chr(263)||'enje stana')]::text[], array['CISCENJE']::text[]),
    (2, array[(chr(1063)||chr(1080)||chr(1096)||chr(1115)||chr(1077)||chr(1114)||chr(1077)||' '||chr(1089)||chr(1090)||chr(1072)||chr(1085)||chr(1072))]::text[], array['CISCENJE']::text[]),
    (3, array[(chr(1050)||chr(1088)||chr(1077)||chr(1095)||chr(1077)||chr(1114)||chr(1077)), (chr(1060)||chr(1072)||chr(1088)||chr(1073)||chr(1072)||chr(1114)||chr(1077))]::text[], array['MOLERSKI_RADOVI']::text[]),
    (4, array['Sklapanje maketa']::text[], '{}'::text[]),
    (5, array[('sklapanje IKEA name'||chr(353)||'taja')]::text[], array['MONTAZA_NAMESTAJA']::text[]),
    (6, array['ormari iz ikee']::text[], array['MONTAZA_NAMESTAJA']::text[]),
    (7, array['ikee']::text[], array['MONTAZA_NAMESTAJA']::text[]),
    (8, array['ofarba sobu']::text[], array['MOLERSKI_RADOVI']::text[]),
    (9, array['Ciscenje stana', 'Peglanje']::text[], array['CISCENJE', 'PRANJE_PEGLANJE']::text[]),
    (10, array['transport_selidbe']::text[], array['SELIDBE_PREVOZ']::text[]),
    (11, array['dresura pasa']::text[], '{}'::text[]),
    (12, array[('ne'||chr(353)||'to sasvim drugo'), null, '']::text[], '{}'::text[]),
    (13, '{}'::text[], '{}'::text[]),
    (14, null::text[], '{}'::text[])
  ),
  smoke_result as (
    select s.ord, s.probe_expected, case when (select valid from registry_valid) then private.work_kinds_v5(s.probe_input) end as got from smoke s
  ),
  problems as (
    select 'BODY_DRIFT' as kind, t.signature as detail
    from targets t
    where (select md5(replace(prosrc, chr(13), '')) from pg_proc where oid = to_regprocedure(t.signature)) is distinct from t.body_md5
    union all
    select 'TARGET_ATTRIBUTES', t.signature
    from targets t
    where not exists(select 1 from pg_proc p where p.oid = to_regprocedure(t.signature)
      and not p.prosecdef and p.provolatile = 's' and p.proparallel = 's' and not p.proisstrict and not p.proleakproof and p.proconfig = array['search_path=pg_catalog']
      and p.proowner = 'postgres'::regrole and p.proacl::text = '{postgres=X/postgres}' and p.prokind = 'f' and p.prorettype = 'text[]'::regtype and not p.proretset
      and p.pronargs = 1 and p.proargnames = array['p_values'] and p.prolang = (select oid from pg_language where lanname = 'plpgsql')
      and obj_description(p.oid, 'pg_proc') = 'PKG-031b + EX-06 ex06b: the hidden kinds of work named by free text (category, skills, exclusions); the word stems are data rows work_kind:* of private.marketplace_config (classification version in work_kinds_head). Used only by matching.')
    union all
    select 'REGISTRY_INVALID', 'the head row and the eleven kind rows are not exactly the valid registry the function reads'
    where not (select valid from registry_valid)
    union all
    select 'REGISTRY_ROW_DIFFERS', e.key
    from expected_rows e
    where not exists(select 1 from private.marketplace_config c where c.key = e.key and c.value = e.value)
    union all
    select 'REGISTRY_EXTRA_ROW', c.key
    from private.marketplace_config c
    where starts_with(c.key, 'work_kind') and not exists(select 1 from expected_rows e where e.key = c.key)
    union all
    select 'STEM_NOT_FOLDED', c.key || ': ' || coalesce(e.stem #>> '{}', 'null')
    from private.marketplace_config c
    cross join lateral jsonb_array_elements(case when jsonb_typeof(c.value -> 'stems') = 'array' then c.value -> 'stems' else '[]'::jsonb end) e(stem)
    where starts_with(c.key, 'work_kind:')
      and (jsonb_typeof(e.stem) <> 'string' or (e.stem #>> '{}') !~ '^[a-z][a-z ]*[a-z]$' or length(e.stem #>> '{}') < 4)
    union all
    select 'SMOKE_PROBE', r.ord::text
    from smoke_result r
    where r.got is distinct from r.probe_expected
    union all
    select 'AUTHORITY', t.signature
    from targets t
    where has_function_privilege('anon', t.signature, 'EXECUTE') or has_function_privilege('authenticated', t.signature, 'EXECUTE')
      or has_function_privilege('service_role', t.signature, 'EXECUTE')
    union all
    select 'CERTIFICATE', 'the closure certificate is not ready and bound'
    where private.retention_ai_source_ready() is distinct from true
      or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
    union all
    select 'CERTIFIED_TARGET', 'the target is a trigger function or named in a function of the closure digest'
    where exists(select 1 from pg_trigger where tgfoid = to_regprocedure('private.work_kinds_v5(text[])'))
      or exists(select 1 from pg_proc p where p.pronamespace = 'private'::regnamespace and p.proname in ('closure_source_digest_v5', 'closure_erasure_program_digest_v5', 'closure_schema_digest_v5_139', 'closure_erasure_binding_v5', 'agreement_invalidation_surface_v1', 'agreement_voice_surface_v1', 'retention_ai_source_ready') and position('work_kinds_v5' in p.prosrc) > 0)
  ),
  informational as (
    select 'NEIGHBOUR_CHANGED' as kind, n.signature as detail
    from neighbours n
    where (select md5(replace(prosrc, chr(13), '')) from pg_proc where oid = to_regprocedure(n.signature)) is distinct from n.body_md5
  )
select jsonb_build_object(
  'unit', 'EX06B_ALIAS_REGISTRY_DEV_POSTFLIGHT',
  'pinsChecked', (select count(*) from targets) + (select count(*) from neighbours),
  'smokeProbes', (select count(*) from smoke),
  'problems', coalesce((select jsonb_agg(jsonb_build_object('kind', kind, 'detail', detail) order by kind, detail) from problems), '[]'::jsonb),
  'informational', coalesce((select jsonb_agg(jsonb_build_object('kind', kind, 'detail', detail) order by kind, detail) from informational), '[]'::jsonb),
  'classificationVersion', (select c.value ->> 'classificationVersion' from private.marketplace_config c where c.key = 'work_kinds_head'),
  'registryRows', (select count(*) from private.marketplace_config c where starts_with(c.key, 'work_kind')),
  'certifiedSource', (select sha256 from private.closure_source_v5 where singleton),
  'ledgerRows', (select count(*) from supabase_migrations.schema_migrations),
  'checkedAt', to_char(clock_timestamp() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
) as postflight;
