-- EX-06 ex06a DEV postflight. READ-ONLY: one SELECT, no write, no lock. Run it against canonical DEV right after the application (and at any time later).
-- GENERATED by supabase/proofs/ex06/build_ex06a.py: do not edit by hand (`--check` fails on any difference).
-- Returns ONE row of JSON. "problems": every part of the applied state that does not hold for the TWO targets and the certificate (an empty array means the application is exactly in place).
-- "informational": a neighbour function whose body is no longer the pinned DEV predecessor (kind NEIGHBOUR_CHANGED): never a problem of this application, a later package may change one legitimately.
with
  targets(signature, body_md5, rettype) as (values
    ('private.worker_dispatch_time_admitted(uuid,uuid)','4f0beb65922d2b3d947d69e68a56a956','boolean'),
    ('private.match_detail_without_calendar(uuid,uuid)','c8aaf3da761242397243fc56262d1aeb','jsonb')
  ),
  neighbours(signature, body_md5) as (values
    ('private.availability_is_future(text,timestamp with time zone,timestamp with time zone,timestamp with time zone)','3a1aee763e9fe3d0f06d6ba04ef21aac'),
    ('private.availability_timezone_valid(text)','013f884ca649cb5246f39eaf9f2e0ec9'),
    ('private.worker_available_periods(uuid,timestamp with time zone,timestamp with time zone,text)','5107af3020a3beb7bb45e6e90e7a203b'),
    ('private.schedule_fit(uuid,timestamp with time zone,timestamp with time zone,text)','e29a7bade1437e3f2067924b5179ddfd'),
    ('private.worker_calendar_conflict(uuid,timestamp with time zone,timestamp with time zone,uuid)','417c9db16bbe70ed9ad652380790900c'),
    ('private.match_detail(uuid,uuid)','38c7894a8cf43a8f32bd5a30bc2cbd09'),
    ('private.match_detail_for_calendar_interval(uuid,uuid,timestamp with time zone,timestamp with time zone)','781956cab666befab216b3ce2334ca1d'),
    ('private.dispatch_cheap_candidate_admitted(uuid,uuid)','0132fae38c75947179b4d389edc1e1f0'),
    ('private.candidate_profile_ids(uuid,integer)','dca4ddc8080a52c8af83c33689c5568e'),
    ('private.dispatch_next_wave(uuid)','1fd8c51ef026ece24471e2f68250ecc5')
  ),
  problems as (
    select 'BODY_DRIFT' as kind, t.signature as detail
    from targets t
    where (select md5(replace(prosrc, E'\r', '')) from pg_proc where oid = to_regprocedure(t.signature)) is distinct from t.body_md5
    union all
    select 'TARGET_ATTRIBUTES', t.signature
    from targets t
    where not exists(select 1 from pg_proc p where p.oid = to_regprocedure(t.signature)
      and p.prosecdef and p.provolatile = 's' and p.proconfig = array['search_path=pg_catalog'] and p.proowner = 'postgres'::regrole
      and p.proacl::text = '{postgres=X/postgres}' and p.prokind = 'f' and p.prorettype = t.rettype::regtype and not p.proretset and p.prolang = (select oid from pg_language where lanname = 'plpgsql')
      and obj_description(p.oid, 'pg_proc') is null)
    union all
    select 'AUTHORITY', t.signature
    from targets t
    where has_function_privilege('anon', t.signature, 'EXECUTE') or has_function_privilege('authenticated', t.signature, 'EXECUTE')
      or has_function_privilege('service_role', t.signature, 'EXECUTE')
    union all
    select 'CERTIFICATE', 'the closure certificate is not ready and bound'
    where private.retention_ai_source_ready() is distinct from true
      or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
    union all
    select 'CERTIFIED_TARGET', 'a target is a trigger function or named in a function of the closure digest'
    where exists(select 1 from pg_trigger where tgfoid in (to_regprocedure('private.worker_dispatch_time_admitted(uuid,uuid)'), to_regprocedure('private.match_detail_without_calendar(uuid,uuid)')))
      or exists(select 1 from pg_proc p where p.pronamespace = 'private'::regnamespace and p.proname in ('closure_source_digest_v5', 'closure_erasure_program_digest_v5', 'closure_schema_digest_v5_139', 'closure_erasure_binding_v5', 'agreement_invalidation_surface_v1', 'agreement_voice_surface_v1', 'retention_ai_source_ready')
        and (position('worker_dispatch_time_admitted' in p.prosrc) > 0 or position('match_detail_without_calendar' in p.prosrc) > 0))
  ),
  informational as (
    select 'NEIGHBOUR_CHANGED' as kind, n.signature as detail
    from neighbours n
    where (select md5(replace(prosrc, E'\r', '')) from pg_proc where oid = to_regprocedure(n.signature)) is distinct from n.body_md5
  )
select jsonb_build_object(
  'unit', 'EX06A_FLEXIBLE_WINDOW_DEV_POSTFLIGHT',
  'pinsChecked', (select count(*) from targets) + (select count(*) from neighbours),
  'problems', coalesce((select jsonb_agg(jsonb_build_object('kind', kind, 'detail', detail) order by kind, detail) from problems), '[]'::jsonb),
  'informational', coalesce((select jsonb_agg(jsonb_build_object('kind', kind, 'detail', detail) order by kind, detail) from informational), '[]'::jsonb),
  'certifiedSource', (select sha256 from private.closure_source_v5 where singleton),
  'ledgerRows', (select count(*) from supabase_migrations.schema_migrations),
  'checkedAt', to_char(clock_timestamp() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
) as postflight;
