-- EX-06 ex06b DEV PREFLIGHT. READ-ONLY: one SELECT, no write, no lock. Run it against canonical DEV right before the application.
-- GENERATED by supabase/proofs/ex06/build_ex06b.py: do not edit by hand (`--check` fails on any difference).
-- Returns ONE row of JSON. "problems": every part of the predecessor state that does not hold (an empty array means the application may run); "facts": what a human reads before saying "primeni".
with
  pins(signature, body_md5) as (values
    ('private.work_kinds_v5(text[])','2113eb46ab7ea968b873e76d1de12377'),
    ('private.match_detail_without_calendar(uuid,uuid)','c8aaf3da761242397243fc56262d1aeb'),
    ('private.dispatch_cheap_candidate_admitted(uuid,uuid)','0132fae38c75947179b4d389edc1e1f0'),
    ('private.candidate_profile_ids(uuid,integer)','dca4ddc8080a52c8af83c33689c5568e'),
    ('private.dispatch_next_wave(uuid)','1fd8c51ef026ece24471e2f68250ecc5'),
    ('private.match_detail(uuid,uuid)','38c7894a8cf43a8f32bd5a30bc2cbd09'),
    ('private.match_detail_for_calendar_interval(uuid,uuid,timestamp with time zone,timestamp with time zone)','781956cab666befab216b3ce2334ca1d'),
    ('private.worker_dispatch_time_admitted(uuid,uuid)','4f0beb65922d2b3d947d69e68a56a956'),
    ('private.lower_arr(text[])','07f449cf589196cc8ca349b4f5ca460c')
  ),
  target as (select p.oid from pg_proc p where p.oid = to_regprocedure('private.work_kinds_v5(text[])')),
  problems as (
    select 'PIN_DRIFT' as kind, p.signature as detail
    from pins p
    where (select md5(replace(prosrc, chr(13), '')) from pg_proc where oid = to_regprocedure(p.signature)) is distinct from p.body_md5
    union all
    select 'TARGET_ATTRIBUTES', 'private.work_kinds_v5(text[])'
    where not exists(select 1 from pg_proc p where p.oid = to_regprocedure('private.work_kinds_v5(text[])')
      and not p.prosecdef and p.provolatile = 'i' and p.proparallel = 's' and not p.proisstrict and not p.proleakproof and p.proconfig = array['search_path=pg_catalog']
      and p.proowner = 'postgres'::regrole and p.proacl::text = '{postgres=X/postgres}' and p.prokind = 'f' and p.prorettype = 'text[]'::regtype and not p.proretset
      and p.pronargs = 1 and p.proargnames = array['p_values'] and p.prolang = (select oid from pg_language where lanname = 'sql')
      and obj_description(p.oid, 'pg_proc') = 'PKG-031b: the hidden kinds of work named by free text (category, skills, exclusions). Used only by matching.')
    union all
    select 'CONFIG_TABLE', 'private.marketplace_config is not the three-column, triggerless, ruleless table with the pinned primary key'
    where (select string_agg(a.attname::text || ':' || format_type(a.atttypid, a.atttypmod) || ':' || a.attnotnull::text, ',' order by a.attnum)
        from pg_attribute a where a.attrelid = 'private.marketplace_config'::regclass and a.attnum > 0 and not a.attisdropped) is distinct from 'key:text:true,value:jsonb:true,updated_at:timestamp with time zone:true'
     or (select count(*) from pg_constraint x where x.conrelid = 'private.marketplace_config'::regclass and x.contype <> 'n') <> 1
     or (select md5(pg_get_constraintdef(x.oid)) from pg_constraint x where x.conrelid = 'private.marketplace_config'::regclass and x.contype = 'p') is distinct from '729d3ed6c85722f863da384d2313331e'
     or exists(select 1 from pg_trigger t where t.tgrelid = 'private.marketplace_config'::regclass and not t.tgisinternal)
     or exists(select 1 from pg_rewrite r where r.ev_class = 'private.marketplace_config'::regclass)
    union all
    select 'CONFIG_KEY_PRESENT', c.key from private.marketplace_config c where starts_with(c.key, 'work_kind')
    union all
    select 'CERTIFICATE', 'the closure certificate is not ready and bound'
    where private.retention_ai_source_ready() is distinct from true
      or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
    union all
    select 'CERTIFIED_TARGET', 'the target is a trigger function or named in a function of the closure digest'
    where exists(select 1 from pg_trigger where tgfoid = to_regprocedure('private.work_kinds_v5(text[])'))
      or exists(select 1 from pg_proc p where p.pronamespace = 'private'::regnamespace and p.proname in ('closure_source_digest_v5', 'closure_erasure_program_digest_v5', 'closure_schema_digest_v5_139', 'closure_erasure_binding_v5', 'agreement_invalidation_surface_v1', 'agreement_voice_surface_v1', 'retention_ai_source_ready') and position('work_kinds_v5' in p.prosrc) > 0)
    union all
    select 'AUTHORITY', 'private.work_kinds_v5(text[])'
    where has_function_privilege('anon', 'private.work_kinds_v5(text[])', 'EXECUTE') or has_function_privilege('authenticated', 'private.work_kinds_v5(text[])', 'EXECUTE')
      or has_function_privilege('service_role', 'private.work_kinds_v5(text[])', 'EXECUTE')
    union all
    select 'CALLERS', 'the functions that name the target are not exactly the two callers: ' || coalesce(string_agg(n.nspname || '.' || p.proname, ', ' order by n.nspname, p.proname), '')
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
    where p.prosrc like '%work_kinds_v5%' and p.oid <> to_regprocedure('private.work_kinds_v5(text[])')
    having coalesce(array_agg(n.nspname || '.' || p.proname order by n.nspname, p.proname), '{}'::text[])
      is distinct from array['private.dispatch_cheap_candidate_admitted', 'private.match_detail_without_calendar']
  )
select jsonb_build_object(
  'unit', 'EX06B_ALIAS_REGISTRY_DEV_PREFLIGHT',
  'pinsChecked', (select count(*) from pins),
  'problems', coalesce((select jsonb_agg(jsonb_build_object('kind', kind, 'detail', detail) order by kind, detail) from problems), '[]'::jsonb),
  'facts', jsonb_build_object(
    'targetBodyMd5', (select md5(replace(prosrc, chr(13), '')) from pg_proc where oid = to_regprocedure('private.work_kinds_v5(text[])')),
    'configRows', (select count(*) from private.marketplace_config),
    'certifiedSource', (select sha256 from private.closure_source_v5 where singleton),
    'liveSource', private.closure_source_digest_v5(),
    'ledgerRows', (select count(*) from supabase_migrations.schema_migrations)),
  'checkedAt', to_char(clock_timestamp() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
) as preflight;
