"""Compare two surface snapshots (pkg023_surface.sql output) and attribute every difference to a ledger text.

usage: python supabase/proofs/pkg023f_closure_recert/surface_diff.py <baseline.txt> <live.txt> <out.md>

An object is attributed to the dev_alpha ledger text whose statement creates or changes it (CREATE FUNCTION,
CREATE TABLE, ADD COLUMN, ADD CONSTRAINT, CREATE TRIGGER, ALTER POLICY, CREATE INDEX; the columns,
constraints and primary-key index of a new table through its CREATE TABLE). "ENVIRONMENT" means no ledger
text does; each such line is explained in
docs/implementation/v5-ai-first/pkg023/CLOSURE_FORENSIC_REVIEW_20260919.md.
"""
import io, json, os, re, sys

baseline, live, out = sys.argv[1:4]
manifest = json.load(io.open('supabase/operations/dev-alpha/ledger/LEDGER_MANIFEST.json', encoding='utf-8'))
ledger = {m['name']: io.open(m['exactTextInRepo'], encoding='utf-8').read() for m in manifest['migrations']}
W, END = '[ \t\r\n]+', '(?![A-Za-z0-9_])'


def read(path):
    return [l for l in io.open(path, encoding='utf-8').read().replace('\r\n', '\n').split('\n') if l]


def key(line):
    kind, rest = line.split(':', 1)
    if kind == 'function':
        return kind + ':' + rest.split('):')[0] + ')'
    return kind + ':' + rest.split(':')[0]


def statement(k, added_tables):
    """The statement that creates or changes the object, as a pattern over a ledger text."""
    kind, rest = k.split(':', 1)
    if kind == 'function':
        name = rest.split('(')[0]
        # Either CREATE [OR REPLACE] FUNCTION, or the patch form pkg015b uses: the definition is selected by
        # proname and re-created through EXECUTE replace(definition, anchor, addition).
        return ('(create' + W + '(or' + W + 'replace' + W + ')?function' + W + re.escape(name) + '[ \t\r\n]*[(])'
                + "|(proname[ ]*=[ ]*'" + re.escape(name.split('.')[-1]) + "';(?:.|\n){0,1200}?execute[ ]+replace[(]def,)")
    parts = rest.split('.')
    table = 'create' + W + 'table' + W + re.escape('.'.join(parts[:2])) + END
    if kind == 'table':
        return table
    if kind in ('column', 'constraint') and 'table:' + '.'.join(parts[:2]) in added_tables:
        return table
    if kind == 'column':
        return 'add' + W + 'column' + W + '(if' + W + 'not' + W + 'exists' + W + ')?' + re.escape(parts[-1]) + END
    if kind == 'constraint':
        return 'add' + W + 'constraint' + W + re.escape(parts[-1]) + END
    if kind == 'trigger':
        return 'create' + W + 'trigger' + W + re.escape(parts[-1]) + END
    if kind == 'policy':
        return '(alter|create)' + W + 'policy' + W + re.escape(parts[-1]) + END
    if kind == 'index':
        owner = re.sub('_(pkey|key)$', '', parts[-1])
        if owner != parts[-1] and 'table:' + parts[0] + '.' + owner in added_tables:
            return 'create' + W + 'table' + W + re.escape(parts[0] + '.' + owner) + END
        return 'create' + W + '(unique' + W + ')?index' + W + re.escape(parts[-1]) + END
    raise ValueError(k)


def attribute(k, added_tables):
    pattern = re.compile(statement(k, added_tables), re.I)
    return [m for m, text in ledger.items() if pattern.search(text)]


a, b = read(baseline), read(live)
A, B = {key(l): l for l in a}, {key(l): l for l in b}
assert len(A) == len(a) and len(B) == len(b), 'a surface key is not unique'
changed = sorted(k for k in A.keys() & B.keys() if A[k] != B[k])
added, removed = sorted(B.keys() - A.keys()), sorted(A.keys() - B.keys())
added_tables = {k for k in added if k.startswith('table:')}
lines = [f'# Surface of `{os.path.basename(live)}` against `{os.path.basename(baseline)}`', '',
         f'baseline {len(a)} objects, live {len(b)} objects: changed {len(changed)}, added {len(added)}, removed {len(removed)}.', '',
         'Generated by `supabase/proofs/pkg023f_closure_recert/surface_diff.py`. Each object is attributed to the dev_alpha',
         'ledger text whose statement creates or changes it; ENVIRONMENT means none does.', '']
environment = []
for title, keys in (('Changed', changed), ('Added', added)):
    lines += [f'## {title}', '']
    for k in keys:
        found = attribute(k, added_tables)
        if not found:
            environment.append(k)
        lines.append(f'- `{k}` <- ' + (', '.join(found) if found else '**ENVIRONMENT**'))
    lines.append('')
lines += ['## Removed', ''] + ([f'- `{k}`' for k in removed] or ['- none']) + ['']
io.open(out, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines))
print('changed', len(changed), 'added', len(added), 'removed', len(removed), 'environment', environment)
