from pathlib import Path
from PIL import Image,ImageDraw,ImageFont
import json,base64,io,html
R=Path(__file__).resolve().parents[1]
cat=json.loads((R/'contracts/SCREEN_CONTRACTS_66.json').read_text())
def image_uri(path):
 b=io.BytesIO();Image.open(path).convert('RGB').save(b,format='WEBP',quality=91,method=4);return 'data:image/webp;base64,'+base64.b64encode(b.getvalue()).decode()
rows=[]
for x in cat:
 rows.append({'key':x['key'],'name':x['name'],'group':x['group'],'note':x['change_note'],'change':x['v2_disposition']!='REVIEWED_RETAINED_SHARED_POLISH','before':image_uri(R/x['before_render']),'after':image_uri(R/x['normal_render'])})
important=[('sweep_r','Meni treba — bez preostalog teksta'),('sweep_w','Ja mogu — suptilan motiv'),('application_live_summary','Prijava — sažetak uz slanje'),('chat_compact','Poruke — kompaktni prihvaćeni uslovi'),('export_requested','Lokalni zahtev za izvoz'),('export_cancelled','Otkazan lokalni zahtev'),('map_pan_zoom','Lokalni pan / zoom'),('map_area_applied','Oblast primenjena na mapu i listu'),('agreement_confirmed','Potvrđeni lokalni Dogovor'),('payment_exact_offer','Tačna ponuda i 0 RSD platformi')]
extra=[{'key':k,'name':n,'image':image_uri(R/f'renders/states/{k}.png')} for k,n in important if (R/f'renders/states/{k}.png').exists()]
template='''<!doctype html><html lang="sr-Latn"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>USKOČI SPOJ V2 — atlas</title><style>
*{box-sizing:border-box}body{margin:0;background:#f3f6f3;color:#143d35;font:15px/1.55 system-ui,sans-serif}header{background:white;border-bottom:1px solid #dae5dd;padding:28px max(20px,calc((100vw - 1320px)/2));position:relative}h1{font-size:clamp(26px,4vw,42px);letter-spacing:-1.3px;line-height:1.12;margin:10px 0}p{max-width:920px;color:#587269}small{font-size:11px;text-transform:uppercase;letter-spacing:2px;color:#2e7a6a;font-weight:800}.tools{display:flex;gap:10px;flex-wrap:wrap;margin:22px 0 0}button,input,select{font:inherit;border:1px solid #cfdfd4;background:white;color:#143d35;border-radius:12px;min-height:44px;padding:10px 15px}button{cursor:pointer}button.active{background:#143d35;color:white;border-color:#143d35}input{min-width:160px;flex:1}button:focus-visible,input:focus-visible{outline:3px solid #ff7908;outline-offset:3px}main{max-width:1360px;margin:auto;padding:24px 20px}.stats{font-size:13px;color:#587269;margin-bottom:22px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:20px}.card{background:white;border:1px solid #dfe8e2;border-radius:21px;padding:16px;min-width:0}.card h2{font-size:17px;line-height:1.25;margin:8px 0}.card p{font-size:12px;min-height:78px}.card img{display:block;width:100%;border-radius:15px;border:1px solid #e1e9e4}.card button{width:100%;margin-top:12px;font-size:13px}.badge{font-size:11px;color:#2e7a6a;background:#eef5f1;padding:4px 8px;border-radius:7px}.both{display:grid;grid-template-columns:1fr 1fr;gap:12px}.both figure{margin:0}.both figcaption{font-size:12px;font-weight:700;margin:8px 0}.both img{width:100%;display:block;border-radius:12px}dialog{max-width:min(900px,96vw);max-height:96dvh;border:0;border-radius:24px;padding:22px;background:#f7faf8;color:#143d35}dialog::backdrop{background:rgba(7,33,23,.72)}dialog .close{float:right}dialog h2{margin:0 60px 10px 0}dialog p{font-size:13px}.empty{padding:60px;text-align:center}footer{max-width:1300px;margin:30px auto;padding:20px;color:#61786b;font-size:12px}.original{margin-top:15px;padding:15px;border-radius:14px;background:#edf5f0;font-size:13px;color:#496d5d}
@media(max-width:1050px){.grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:720px){.grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.card{padding:10px}.card p{min-height:110px}}@media(max-width:440px){.grid{grid-template-columns:1fr}.card{padding:18px}.card p{min-height:0}.card img{max-width:330px;margin:auto}.both{grid-template-columns:1fr}header{padding:22px 18px}}
</style><header><small>USKOČI / SPOJ / 10.09.2026.</small><h1>V2 · Jedan proizvod,<br>jasniji sledeći korak.</h1><p>Stvarni renderi lokalnog HTML-a. Uporedi prethodnu i novu verziju, pogledaj prelaz namere, ponudu, razgovor i lokalne promene stanja. Ovo nije prikaz već povezane native aplikacije.</p><div class="tools"><input id="q" aria-label="Pronađi ekran" placeholder="Pronađi ekran, tok ili grupu…"><button data-tab="all" class="active">Svih 66</button><button data-tab="changed">Veće promene</button><button data-tab="states">Tokovi i stanja</button><select id="version" aria-label="Verzija prikaza"><option value="after">V2 — POSLE</option><option value="before">V1 — PRE</option></select></div><div class="original">Originalni intro i znak su sačuvani. Popravljen je izbor namere. Svaka kolekcija/poruka/ocena u ovim renderima koristi lokalne demo podatke.</div></header><main><div class="stats" id="count"></div><section class="grid" id="grid"></section></main><dialog id="zoom"><button class="close" id="close" aria-label="Zatvori">✕</button><div id="detail"></div></dialog><footer>66 površina nije 66 dovršenih native ruta. Statusi, vezivanje na motor, otvorene odluke i granice testova nalaze se u kompletnom handoff paketu. Renderi su nastali u Chromium-u, ne image generatorom.</footer><script>
const DATA=__DATA__,EXTRA=__EXTRA__;let tab='all';const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){const q=document.querySelector('#q').value.toLowerCase(),version=document.querySelector('#version').value;const rows=(tab==='states'?EXTRA:DATA).filter(r=>(tab!=='changed'||r.change)&&[r.key,r.name,r.group||'',r.note||''].join(' ').toLowerCase().includes(q));document.querySelector('#count').textContent=rows.length+' prikaza · '+(tab==='states'?'lokalni tokovi i stanja':version==='after'?'nova V2 verzija':'prethodna V1 verzija');document.querySelector('#grid').innerHTML=rows.map(r=>`<article class="card"><span class="badge">${esc(r.key)}</span><h2>${esc(r.name)}</h2>${r.note?`<p>${esc(r.note)}</p>`:''}<img loading="lazy" src="${r.image||r[version]}" alt="${esc(r.name)}"><button data-open="${r.key}">${r.image?'Uvećaj':'Uporedi PRE / POSLE'}</button></article>`).join('')||'<div class="empty">Nema prikaza za ovu pretragu.</div>';}
document.querySelector('#q').addEventListener('input',render);document.querySelector('#version').addEventListener('change',render);document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));render()});document.querySelector('#grid').onclick=e=>{const b=e.target.closest('[data-open]');if(!b)return;const r=(tab==='states'?EXTRA:DATA).find(x=>x.key===b.dataset.open);document.querySelector('#detail').innerHTML=`<h2>${esc(r.name)}</h2><p>${esc(r.note||'Lokalni scenario, ne backend dokaz.')}</p>`+(r.image?`<img style="max-width:100%;display:block;margin:auto" src="${r.image}" alt="${esc(r.name)}">`:`<div class="both"><figure><figcaption>PRE — V1</figcaption><img src="${r.before}" alt="Prethodni prikaz"></figure><figure><figcaption>POSLE — V2</figcaption><img src="${r.after}" alt="Novi prikaz"></figure></div>`);document.querySelector('#zoom').showModal();};document.querySelector('#close').onclick=()=>document.querySelector('#zoom').close();document.querySelector('#zoom').onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.close()};render();</script></html>'''
s=template.replace('__DATA__',json.dumps(rows,ensure_ascii=False)).replace('__EXTRA__',json.dumps(extra,ensure_ascii=False))
(R/'ATLAS.html').write_text(s);(R.parent/'USKOCI_SPOJ_V2_ATLAS.html').write_text(s)
# Readable actual screenshot comparisons for the main improvements.
font=ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',18)
for key,title in [('chat','PORUKE: PRE / POSLE'),('apply','PRIJAVA: PRE / POSLE')]:
 i=next(i for i,x in enumerate(cat) if x['key']==key)+1
 out=Image.new('RGB',(820,900),'#f2f6f2');d=ImageDraw.Draw(out);d.text((20,15),title,font=font,fill='#143d35')
 for j,folder in enumerate(['before','after']):out.paste(Image.open(R/f'renders/{folder}/{i:02d}_{key}.png').convert('RGB'),(j*410+10,48))
 out.save(R/f'renders/{key}_PRE_POSLE.png')
# Selection preview, both real frames.
out=Image.new('RGB',(820,900),'#f2f6f2');d=ImageDraw.Draw(out);d.text((20,15),'NOVI PRELAZ · MENI TREBA / JA MOGU',font=font,fill='#143d35')
for j,mode in enumerate(['r','w']):out.paste(Image.open(R/f'renders/states/sweep_{mode}.png').convert('RGB'),(j*410+10,48))
out.save(R/'renders/IZBOR_NAMERE_V2.png');shutil=None
print('Atlas bytes',len(s.encode()),'screens',len(rows),'states',len(extra))
