-- EX-04 S3 DEV postflight. READ-ONLY: one SELECT, no write, no lock. Run it against canonical DEV right after the application (and at any time later).
-- GENERATED by supabase/proofs/ex04/build_ex04c.py: do not edit by hand (`--check` fails on any difference).
-- Returns ONE row of JSON: every part of the applied state that does not hold ("problems": an empty array means the application is exactly in place).
with
  pins(signature, body_md5) as (values
    ('public.rpc_list_my_agreements_page(text,integer,timestamp with time zone,uuid)','5017f90ff8d9e5cd29ead0f88a6b0106'),
    ('public.rpc_home_attention()','1703b04e248759a19cbcc539621ed906'),
    ('public.rpc_get_my_agreement_review(uuid)','75a8b78ec8a5e6334f42366b4461c14c'),
    ('private.closure_account_restricted(uuid)','f4999250c315e0253374d4611291c7ad'),
    ('public.rpc_storage_account_open()','7350621ef256678e209aa6a28c79b58b'),
    ('private.my_application_state(text,integer,integer,text,boolean)','236c6c9c9625e4fb92522c6c3a1bfe03'),
    ('public.covered_slots(public.needs)','cbeb8f2a3da7d08965ef0386cfc437ba'),
    ('public.selectable_application_count(public.needs)','fe53442f8b661d6f33d22a54e2a468a8')
  ),
  problems as (
    select 'BODY_DRIFT' as kind, pin.signature as detail
    from pins pin
    where (select md5(replace(prosrc, E'\r\n', E'\n')) from pg_proc where oid = to_regprocedure(pin.signature)) is distinct from pin.body_md5
    union all
    select 'READER_ATTRIBUTES', signature
    from (values ('public.rpc_list_my_agreements_page(text,integer,timestamp with time zone,uuid)'), ('public.rpc_home_attention()')) r(signature)
    where not exists(select 1 from pg_proc p where p.oid = to_regprocedure(r.signature) and p.prosecdef and p.provolatile = 's'
      and p.proconfig = array['search_path=pg_catalog'] and p.proowner = 'postgres'::regrole and p.proacl::text = '{postgres=X/postgres,authenticated=X/postgres}'
      and p.prorettype = 'jsonb'::regtype and not p.proretset)
    union all
    select 'AUTHORITY', 'anon or service_role can execute a reader, or authenticated cannot'
    where has_function_privilege('anon', 'public.rpc_list_my_agreements_page(text,integer,timestamp with time zone,uuid)', 'EXECUTE') or has_function_privilege('anon', 'public.rpc_home_attention()', 'EXECUTE')
      or has_function_privilege('service_role', 'public.rpc_list_my_agreements_page(text,integer,timestamp with time zone,uuid)', 'EXECUTE') or has_function_privilege('service_role', 'public.rpc_home_attention()', 'EXECUTE')
      or not has_function_privilege('authenticated', 'public.rpc_list_my_agreements_page(text,integer,timestamp with time zone,uuid)', 'EXECUTE') or not has_function_privilege('authenticated', 'public.rpc_home_attention()', 'EXECUTE')
    union all
    select 'HOME_COMMENT_LOST', 'public.rpc_home_attention()'
    where obj_description(to_regprocedure('public.rpc_home_attention()'), 'pg_proc') is null
    union all
    select 'CERTIFICATE', 'the closure certificate is not ready and bound'
    where private.retention_ai_source_ready() is distinct from true
      or private.closure_source_digest_v5() is distinct from (select sha256 from private.closure_source_v5 where singleton)
  )
select jsonb_build_object(
  'unit', 'EX04C_RATING_STATE_DEV_POSTFLIGHT',
  'pinsChecked', (select count(*) from pins),
  'problems', coalesce((select jsonb_agg(jsonb_build_object('kind', kind, 'detail', detail) order by kind, detail) from problems), '[]'::jsonb),
  'certifiedSource', (select sha256 from private.closure_source_v5 where singleton),
  'ledgerRows', (select count(*) from supabase_migrations.schema_migrations),
  'checkedAt', to_char(clock_timestamp() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
) as postflight;
